### ISSUE TITLE
Merge queue: add a way for the build cop to mark a failure as a flake

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/contrib#1020]
... or as due to a reason that shouldn't stop the queue.

**Comment by bgrant0607** [comment]
@lavalamp Please use the kind/velocity-improvement label.

**Comment by bgrant0607** [comment]
There's also an area/mungegithub label.

**Comment by lavalamp** [comment]
@bgrant0607 ah, I didn't realize we had functioning labels in this repo.

**Comment by eparis** [comment]
"functioning"??   I think I'm the only one who actually uses them...

**Comment by alex-mohr** [comment]
FWIW, we had kubemark-500 broken.  We had a revert that with high confidence would fix it.  I'd like a button on http://submit-queue.k8s.io/#/e2e that had "we think we've fixed kubemark-500; treat it as green until it has a run with *start* time after now" semantics.

**Comment by alex-mohr** [comment]
(Impact of it being fixed-but-broken is ~3 hours of me running submit queue manually.)

**Comment by lavalamp** [comment]
It's also about to cost another hour here... I fixed the build but it's going to take an hour for the unit tests to run...

**Comment by lavalamp** [comment]
@eparis What do you think about adding an admin console that's on a different port and only visible if you go through the cluster's proxy or something?

**Comment by eparis** [comment]
That's not unreasonable. Other things I thought of included an API endpoint that submitqueue could read from 'elsewhere' which told us to ignore a test until time X.  Or make that API endpoint 'some file on GCS'.

Although, I'd like to see ALL of the e2e testing stuff spun out into its own binary with its own life. Submit-Queue would just ask about stable/non-stable. And maybe display some stats, (or just have a link to the displays the new tool has).

But that re-arch isn't require here.
