### ISSUE TITLE
Merge queue crashed

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/contrib#1024]
Merge queue just crashed with the following error:

E0520 07:57:15.093393       1 github.go:1155] Can't load commit kubernetes kubernetes bf1f3d37206b0a69c42b8df64c84942c07d5fc3e: GET https://api.github.com/repos/kubernetes/kubernetes/commits/bf1f3d37206b0a69c42b8df64c84942c07d5fc3e: 500  []
E0520 07:57:15.133638       1 github.go:899] Error getting events for issue: GET https://api.github.com/repos/kubernetes/kubernetes/issues/25921/events?page=1&per_page=100: 500  []
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a4572]

goroutine 1 [running]:
panic(0x9910e0, 0xc820014060)
	/usr/local/google/home/dbsmith/.gvm/gos/go1.6/src/runtime/panic.go:464 +0x3e6
k8s.io/contrib/mungegithub/github.(*MungeObject).LabelCreator(0xc82cacea10, 0xc82000be26, 0xc, 0x0, 0x0)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/github/github.go:577 +0x62
k8s.io/contrib/mungegithub/mungers.(*PathLabelMunger).Munge(0xc820112570, 0xc82cacea10)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/mungers/path_label.go:153 +0x5d6
k8s.io/contrib/mungegithub/mungers.MungeIssue(0xc82cacea10, 0x0, 0x0)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/mungers/mungers.go:121 +0x9a
k8s.io/contrib/mungegithub/github.(*Config).ForEachIssueDo(0xc82006db00, 0xb597a0, 0x0, 0x0)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/github/github.go:1551 +0xc56
main.doMungers(0xc82006db00, 0x0, 0x0)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/mungegithub.go:65 +0x20a
main.main.func1(0xc820082e00, 0xc820112750, 0x0, 0x3, 0x0, 0x0)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/mungegithub.go:106 +0x30f
k8s.io/contrib/mungegithub/vendor/github.com/spf13/cobra.(*Command).execute(0xc820082e00, 0xc82000a290, 0x3, 0x3, 0x0, 0x0)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/vendor/github.com/spf13/cobra/command.go:561 +0x62c
k8s.io/contrib/mungegithub/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc820082e00, 0xc820082e00, 0x0, 0x0)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/vendor/github.com/spf13/cobra/command.go:651 +0x55c
k8s.io/contrib/mungegithub/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820082e00, 0x0, 0x0)
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/vendor/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
	/usr/local/google/home/dbsmith/code/k3/src/k8s.io/contrib/mungegithub/mungegithub.go:124 +0x395

@lavalamp @eparis @gmarek

**Comment by gmarek** [comment]
It's probably caused by github being unreachable.

**Comment by gmarek** [comment]
Yup. It's the problem caused by github being unresponsive and the way how merge-queue is written. It's easy to fix this particular problem:
```
func (obj *MungeObject) LabelCreator(label string) string {
	event := obj.labelEvent(label)
	if event == nil {
		return ""
	}
	return *event.Actor.Login
}
```
needs a `|| event.Actor == nil`  in the condition.

The problem is that in very limited number of places we actually handle nils correctly. I vote for leaving this as it is. Merge queue will crash-loop when github is unreachable, but this shouldn't be a big problem.

**Comment by lavalamp** [comment]
Might as well fix it. low-priority though. @apelisse?
