### ISSUE TITLE
Contributor leaderboard

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1029]
Dashboard with contributor stats:
- PRs merged (last week, quarter, all time)
- PRs reviewed (most comments/PR and/or applied LGTM?)
- flaky test issues fixed
- bugs fixed
- help-wanted issues fixed

By individual and by company.

**Comment by ingvagabund** [comment]
Flag distribution? To know how many PRs for ansible, ingress, etc. are still open.

**Comment by bgrant0607** [comment]
Examples of some contributor stats here:
https://apprenda.com/blog/kubernetes-community-update-april-2016/

**Comment by chrisgaun** [comment]
@bgrant0607 I am the one who collects the info in that blog and I'd be happy to help collect more on monthly basis

**Comment by bgrant0607** [comment]
@chrisgaun Thanks! 

A monthly report of the kind you produced in April would be great. 

The idea behind this issue is to provide positive reinforcement of desirable contributor behavior  (e.g., fixing bugs, reviewing PRs, answering stackoverflow questions), provide negative reinforcement of undesirable contributor behavior (e.g., not fixing flaky tests they own -- #24759), and identify candidates for future maintainers. Therefore, for the kinds of metrics I listed in the PR description, a continuously/daily updated dashboard would be ideal. We could run it, along with the submit queue and other dashboards we're building.

**Comment by bgrant0607** [comment]
Other public sources:
http://stackalytics.com/?project_type=kubernetes-group&metric=commits
http://redmonk.com/fryan/2016/03/21/kubernetes-revisited-top-corporate-contributors-over-time/

**Comment by chrisgaun** [comment]
I am talking to JJ and others at Apprenda about building the dashboard. Should have more information soon.

**Comment by bgrant0607** [comment]
Great, @chrisgaun! Thanks!

**Comment by Lukenickerson** [comment]
@bgrant0607 -- Below is an Initial thought on a display for the leaderboard -- is this close to what you were thinking of?

![image](https://cloud.githubusercontent.com/assets/3942453/17110241/028d9be4-526a-11e6-900b-bc8f119d0cad.png)


Thinking about the implementation details of this... Which issues are related to the other dashboards you mentioned? ([1413](https://github.com/kubernetes/contrib/issues/1413), [1302](https://github.com/kubernetes/contrib/issues/1302), and [1372](https://github.com/kubernetes/contrib/issues/1372)?) Have any of them been built yet?

**Comment by bgrant0607** [comment]
@Lukenickerson That looks promising. 

Nice-to-have features:
* Configurable number of contributors to show (10, 25, 50, 100)
* Configurable time period (month, quarter, year, all time)

#1413: Not sure. Ask @rmmh on that issue.
#1302: Not AFAIK. @foxish is working on getting the submit queue to work on multiple repos, but I believe [stats](http://submit-queue.k8s.io/#/info) will be reported per-repo only.
#1372: Also not AFAIK, but ask @david-mcmahon for clarification on that issue.

**Comment by bgrant0607** [comment]
@Lukenickerson I'd probably put the different views (PRs merged, PRs reviewed, etc.) as tabs horizontally, to match the convention used by http://submit-queue.k8s.io/

**Comment by david-mcmahon** [comment]
re #1372, Nothing has been built yet.  I filed this issues in response to a @matchstick request who may have more input if needed.

**Comment by bgrant0607** [comment]
Example of organizational-level metrics:
http://mesos.apache.org/blog/dev-community-status/

**Comment by Lukenickerson** [comment]
Those examples are good for inspiration. 

Where would this live w/r/t code repo and hosting? Would it make sense for this to be part of https://github.com/kubernetes/community or a separate "Community Tracking" project in the kubernetes GitHub space?

**Comment by dims** [comment]
@bgrant0607 @Lukenickerson one more example of org level metrics:
http://stackalytics.com/?project_type=kubernetes-group&release=all&metric=commits

And individual one as well:
http://stackalytics.com/?project_type=kubernetes-group&release=all&metric=commits&user_id=bburns%40google.com

This dashboard was geared towards metrics we track in OpenStack. But may give you ideas...

Another good example is this drill down (In OpenStack Newton Release how were commits and reviews across companies and from a specific company)
http://stackalytics.com/?project_type=tc-approved-release&release=newton&metric=commits&module=nova-group
http://stackalytics.com/?project_type=tc-approved-release&release=newton&metric=commits&module=nova-group&company=mirantis

**Comment by bgrant0607** [comment]
@Lukenickerson We are moving to fine-grained repositories. As discussed in the recent  thread on kubernetes-dev@googlegroups.com, either its own repo or part of a "github-tools" repo would be reasonable.

As for hosting, we run the bot on a Kubernetes cluster. I was thinking we could run this in the same cluster.

**Comment by zen** [comment]
Very simple reporting script that we are using:
https://github.com/gitfred/statkube

**Comment by bgrant0607** [comment]
@Lukenickerson  Do you need further clarifications or help in any way? We're about to add a lot of new automatically assigned reviewers, and I'd like to be able to easily see how many reviews are done by each.

cc @pwittrock @grodrigues3 @philips @hongchaodeng @foxish

**Comment by ryanj** [comment]
I'm planning on spending some time working on this issue as well - currently checking to see if bitergia can set this up for us (short term).

**Comment by ryanj** [comment]
Nice mention here for "most users reviewing code" (2nd over all on GH): https://octoverse.github.com/

**Comment by bgrant0607** [comment]
Thanks, @ryanj. This is urgently needed. We really need visibility into contributor behavior.

**Comment by bgrant0607** [comment]
@philips Who set up the CoreOS bitergia dashboards?

**Comment by bgrant0607** [comment]
cc @apelisse

**Comment by ryanj** [comment]
@bgrant0607: @Phillels has been working on that effort.  I'll send over an email introduction.

**Comment by bgrant0607** [comment]
cc @sarahnovotny

**Comment by bgrant0607** [comment]
CNCF bitergia dashboard: https://cncf.biterg.io/app/kibana#/dashboard/Overview

**Comment by zen** [comment]
Another one, Cauldron dashboard:
https://goo.gl/Ao60nU

Regards,


> On 11 Oct 2016, at 19:14, Brian Grant <notifications@github.com> wrote:
> 
> CNCF bitergia dashboard: https://cncf.biterg.io/app/kibana#/dashboard/Overview
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Tomasz 'Zen' Napierała
tomasz@napierala.org

**Comment by sarahnovotny** [comment]
There's also the work that Apprenda showed at the Community meeting
<https://www.youtube.com/watch?v=_PodBS-KTQI> this week.  All this should
be consolidating under the WG-Contribex.


On Tue, Oct 11, 2016 at 10:28 AM, Tomasz Napierala <notifications@github.com
> wrote:

> Another one, Cauldron dashboard:
> https://goo.gl/Ao60nU
>
> Regards,
>
>

**Comment by bgrant0607** [comment]
More example metrics:
https://opensource.com/business/15/12/top-5-open-source-community-metrics-track

Thanks to @tmrts for pointing it out.

**Comment by cmluciano** [comment]
The stacklytics board was super useful for detecting commits. However, functionality for matching Github review terminology would probably need added.

**Comment by apelisse** [comment]
https://docs.google.com/document/d/14wHc10DOrJCjxuUIKz002kp48WSNQN80CP0IXfOtQT0

**Comment by nikhita** [comment]
Should this be closed? We have https://k8s.devstats.cncf.io/ now.

**Comment by bgrant0607** [comment]
yes, closing
