### ISSUE TITLE
Submit Queue's Bot Stats tab should make it clear when it was last restarted

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/contrib#1037]
@goltermann pointed out to me that the E2E Tests tab shows when the queue was last restarted, but I always forget to look there when I'm trying to figure out the state. The Bot Stats tab under INFO shows a bunch of useful times, and it would be nice if right above "Next Run Loop" it showed "Queue Start Time" or some such heading with the date and time at which the queue was last restarted.

**Comment by eparis** [comment]
fixed
