### ISSUE TITLE
merge bot doesn't read the junit XML files that the unit tests make

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/contrib#1045]
...because they are named differently from the e2e tests.

I don't care if we change the unit test output or change the merge bot. @ixdy opinions?

**Comment by lavalamp** [comment]
Actually I think we should fix the unit test output so it's consistent.

This is preventing the merge queue from filing unit test flakes.

**Comment by ixdy** [comment]
My preference is that mergebot looks for anything named `junit_*.xml`.

I'm also curious how mergebot will handle unit tests, since we run each test there multiple times with slightly different options.

**Comment by lavalamp** [comment]
I don't think merge bot can actually get a directory listing, now that I
think about it. Maybe it can?

**Comment by lavalamp** [comment]
Chatted w/ @freehan-- he's going to figure out how to do a directory listing.

**Comment by lavalamp** [comment]
Hm, it looks like merge bot still isn't filing issues about the unit test suite-- I suspect Jenkins is failing harder than it needs to? Example: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/12970/

@freehan let me know if you have time to figure out what jenkins is doing wrong. :)

**Comment by lavalamp** [comment]
Or maybe it's as easy as merge queue needing to look for junit files inside completely failed builds?

**Comment by freehan** [comment]
Investigating...

**Comment by freehan** [comment]
Okay. It is due to the Junit xml parsing. It could not parse junit xml with multiple testsuites and fail silently. 

Will submit a fix soon.

**Comment by ixdy** [comment]
Per http://llg.cubic.org/docs/junit/, the `<testsuites>` tag can be omitted if there's only a single `<testsuite>`. And it looks like `ginkgo` takes that option.

@spxtr @rmmh do our various test-infra tools handle this correctly?

**Comment by freehan** [comment]
Hope there is no more corner cases. It is very annoying that golang xml parser fail silently. This may mask lots of problem.

**Comment by rmmh** [comment]
Gubernator and the testgrid collector handle either <testsuite> or <testsuites>. Test-history only handles <testsuite>, which makes it skip the unit tests.

**Comment by lavalamp** [comment]
Thanks @freehan!

**Comment by spxtr** [comment]
Actually testgrid handles `<testsuites>` properly, but I still have the test-go tab turned off because it's pretty slow to render and it's tricky to make the tests group properly. Might be worth turning it back on again.
