### ISSUE TITLE
Nginx Ingress Controller - Infinite loop requests

### ISSUE THREAD

**Issue by nottix** [kubernetes/contrib#1047]
Hi @aledbf ,

i'm having this errors on log (also in the latest version):

`127.0.0.1 - [127.0.0.1] - - [24/May/2016:07:44:19 +0000] "GET / HTTP/1.1" 503 23342 "-" "lua-resty-http/0.07 (Lua) ngx_lua/10001" 117 14.774 - - - -
2016/05/24 07:44:19 [info] 23#23: *45353 client 127.0.0.1 closed keepalive connection
127.0.0.1 - [127.0.0.1] - - [24/May/2016:07:44:19 +0000] "GET / HTTP/1.1" 503 23343 "-" "lua-resty-http/0.07 (Lua) ngx_lua/10001" 117 14.774 - - - -
2016/05/24 07:44:19 [info] 23#23: *45351 client 127.0.0.1 closed keepalive connection
127.0.0.1 - [127.0.0.1] - - [24/May/2016:07:44:19 +0000] "GET / HTTP/1.1" 503 23344 "-" "lua-resty-http/0.07 (Lua) ngx_lua/10001" 117 14.775 - - - -
2016/05/24 07:44:19 [info] 23#23: *45349 client 127.0.0.1 closed keepalive connection
127.0.0.1 - [127.0.0.1] - - [24/May/2016:07:44:19 +0000] "GET / HTTP/1.1" 503 23345 "-" "lua-resty-http/0.07 (Lua) ngx_lua/10001" 117 14.775 - - - -`

it is repeating infinitely on our 3 instances.

Thank you.

**Comment by aledbf** [comment]
@nottix please check if the default backend service is working

**Comment by nottix** [comment]
It's the default backend available at https://github.com/aledbf/contrib/tree/nginx-debug-server/Ingress/images/nginx-error-server, it's not working.

Thank you @aledbf

**Comment by aledbf** [comment]
@nottix I suggest you scale the backend to more than one.
If is working, can you close this?

**Comment by nottix** [comment]
thank you
