### ISSUE TITLE
[ansible] Addons/kube-system fail to create on Fedora 23

### ISSUE THREAD

**Issue by thesuperzapper** [kubernetes/contrib#1050]
After pulling the /kubernetes/contrib/ master, and deploying onto my Fedora 23 cluster, I found that all `kube-addons` and the `kube-system` namespace, failed to deploy, effectively leaving the cluster in a useless state. 

After some troubleshooting, I found PR #942 and #797, both of which I applied locally, and then deployed, my cluster now scaffolds without a problem.

Can we get #942 / #797 moving? 
Or at least, can someone verify that the master repo is broken in its current state for new deploys?

**Comment by simonswine** [comment]
It seems both have been merged, @thesuperzapper I think you can close this issue
