### ISSUE TITLE
Submit queue: PRs with "risky-change" label should be merged during business hours.

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/contrib#1068]
Take a flag with a range of times, e.g. --risky-changes-allowed=8am-1pm,11pm-4am (these are California times, but the flag should take UTC times). Then sort PRs with this label into the queue such that they'll get to the top around when the window opens. We can actively manage their position in the queue if the queue is blocked etc.

This is to try and get these things merged when humans are watching the jenkins jobs. We shouldn't merge risky changes at 5pm and go home. The times I put above are roughly mornings for MTV and WAW.

**Comment by lavalamp** [comment]
@roberthbailey this would have been handy yesterday.

**Comment by roberthbailey** [comment]
It would have been more handy if we hadn't manually merged a risk change at 5pm. :)

**Comment by lavalamp** [comment]
Maybe we would have not done that if there was a red "risky-change" label
on the PR :)

**Comment by lavalamp** [comment]
Seems like we haven't really had a need for this. I'll close for now.
