### ISSUE TITLE
cluster-autoscaler: we should write logs to a file and save it in jenkins

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/contrib#1073]
Basically have access similarly to other components like scheduler or apiserver. Now it's hard to debug e2e failures.

**Comment by ingvagabund** [comment]
Would https://github.com/kubernetes/contrib/pull/1100 be sufficient? What OS do you use?

**Comment by fgrzadkowski** [comment]
@ingvagabund I think not, because you explicitly call components and cluster autoscaler is not one of them.

**Comment by fgrzadkowski** [comment]
@mwielgus I think this is done. Please close if it is.

**Comment by mwielgus** [comment]
Yes, @piosz did this.
