### ISSUE TITLE
service-loadbalancer: It does't have a filter,like ingress?

### ISSUE THREAD

**Issue by teijinyer** [kubernetes/contrib#1075]

**Comment by aledbf** [comment]
@YingBurden no. You can specify the flag `--namespace` to restrict the scope of the namespace

**Comment by YingBurden** [comment]
@aledbf ok,In the countainer,I can run the service_loadbalance,but I compiled the service_loadbalancer.go in the local,then copying the service_loadbalance to the countainer,I only got "No such file or directory" when i run my service_loadbalance.
