### ISSUE TITLE
ansible: proxy tests fail on source deploys, missing package deps.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/contrib#1087]
When we install via packages our .specs pull in all the appropriate dependencies that are needed, via the package manager.

When we are doing source deploys this is not the case, and we could potentially be missing a number of dependencies.  (socat) was the one that caused test failures on Conformance. 

/cc @ingvagabund

**Comment by ingvagabund** [comment]
Holds for ``tar`` and ``git`` too.
