### ISSUE TITLE
Cut a new service_loadbalancer image

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#109]
Several useful fixes have gone in/are in flight/will go in soon:
- reaping zombie haproxy
- logging to syslog
- dry run mode talking to localhost kubectl proxy
- using alpine linux 
- url based routing (maybe?)
- liveness probe chk directly in haproxy
- increasing relist period to 10m
- proper flag parsing

Need to test/push a new image to google_containers

**Comment by thockin** [comment]
Beware alpine Linux with DNS - it does not respect search paths.

**Comment by bprashanth** [comment]
@aledbf

**Comment by bprashanth** [comment]
@ric03uec
