### ISSUE TITLE
Detect PRs from new contributors

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1090]
And post useful onboarding information, such as pointers to contributing guidelines, advice about how to get started, how to find similar issues, help-wanted, tec.

**Comment by ingvagabund** [comment]
Who should fall under "new contributors"? Anyone not in ``kubernetes`` organization?

**Comment by bgrant0607** [comment]
@ingvagabund I was thinking 1st PR.

**Comment by foxish** [comment]
Do we want to do first/second PR across the entire organization, or per-repository? It could be done through the API using [this](https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts), and we could figure out when new folks start contributing.
