### ISSUE TITLE
Echoheaders image pull fails on tag not found

### ISSUE THREAD

**Issue by dylangrafmyre** [kubernetes/contrib#1097]
When running `kubectl run echoheaders --image=gcr.io/google_containers/echoserver:1.4 --replicas=1 --port=8080 from
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/README.md

The pod fails to pull the image with  `Tag 1.4 not found` error. 

However, I am able to successfully pull `gcr.io/google_containers/defaultbackend:1.0` for the default-backend deployment.

**Comment by aledbf** [comment]
ping @bprashanth

**Comment by bprashanth** [comment]
gcr.io/google_containers/echoserver:1.4 is now live
