### ISSUE TITLE
Service loadbalancer 404s after first request to http services

### ISSUE THREAD

**Issue by asim** [kubernetes/contrib#110]
reqrep and keep-alive do not play nicely. The first request to a http service works fine but subsequent requests 404 because the request is not parsed. Haproxy merely passes the data through. Using "option http-server-close" fixes this issue. 

Issue noted here a few years back http://permalink.gmane.org/gmane.comp.web.haproxy/7670

**Comment by bprashanth** [comment]
@asim please submit a pr if you have the time, if not I'll verify and report back (I'm pretty sure I've tried curling an http service multiple times, but I don't remember the specifis of reqrep and keep-alive). Perhaps @aledbf has run into this as well?
