### ISSUE TITLE
Nginx Ingress Controller - Support for geoip

### ISSUE THREAD

**Issue by nottix** [kubernetes/contrib#1101]
Hi @aledbf ,

is it possibile to use directives

`geoip_country /usr/share/GeoIP/GeoIP.dat;
vhost_traffic_status_filter_by_set_key $geoip_country_code country::*;`

in the latest version of Nginx ingress controller?

I need it to to calculate traffic for individual country.

Thank you.

**Comment by aledbf** [comment]
@nottix sure. Noted for next version

**Comment by nottix** [comment]
thank you @aledbf, so i'll wait for it :-)

**Comment by nottix** [comment]
Hi @aledbf, i'm trying the latest version 0.7 with GeoIP enabled but i don't see any geo stats on status page, i have to enable some options? Thank you.
