### ISSUE TITLE
Ingress broken - creates new empty Instance-Group

### ISSUE THREAD

**Issue by galan** [kubernetes/contrib#1113]
When I started implementing the Ingress resource in our infrastructure provisioning (2016-05-09) the ingress worked like a charm. Rolling this out to our staging cluster failed yesterday. The ingress successfully creates the L7 HTTP LoadBalancer, creates all entities, but the backend-service did not have any instances configured. Turns out that the Ingress creates a **new Instance Group** called `k8s-ig`, which has no instances associated with it (0) where there should be 4 in our case.

Btw.: The health-check path has changed since then from `/` to `/healthz`, why is that, and how is it possible to reconfigure it?

Tested on gke against cluster version 1.2.1 and 1.2.4.

The Ingress resource:
```
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Ingress",
    "metadata": {
        "name": "de-01",
        "labels": {
            "profile": "staging"
        }
    },
    "spec": {
        "tls": [
            {
                "secretName": "staging-de-01"
            }
        ],
        "backend": {
            "serviceName": "nginx",
            "servicePort": 80
        }
    }
}
```
Image of the empty instance-group, should have 4 nodes (gke-staging-default-506a85c4-group):
![screenshot_2016-06-01_12-44-31](https://cloud.githubusercontent.com/assets/2453957/15708046/95aacfc0-27fc-11e6-8edd-686cf6a99f61.png)

Background: We are using K8s since a year, created the L7 LB entities all by ourself previously. We switched to the Network-LB (which works great), but the Network-LB is unable to provide the client-ip, so we have to switch back to the L7 and the Ingress seems like a good opportunity.

**Comment by bprashanth** [comment]
Can you run kubectl describe ing, or kubectl logs --namespace=kube-system l7-controller-name ?

There was a GCE schema change that required the new instance group. If you're running multiple kube clusters in the same project, with image versions < 0.6.1 you need to allocate a cluster uid of your own: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md#running-multiple-loadbalanced-clusters-in-the-same-gce-project, there's a chance it's not able to add instances to the ig because of this. 

The global-to-project uid is auotmatically allocated in 0.6.3

>Btw.: The health-check path has changed since then from / to /healthz, why is that, and how is it possible to reconfigure it?

/healthz is only for the default backend. All of your services should still be /
you can configure it by going to compute>healthchecks in the pantheon console. 
With the next version (gcr.io/google_containers/glbc:0.7.0) it will scrape the health check url from the readiness probe on your pod endpoints.

**Comment by galan** [comment]
Hi Prashanth,
thanks for getting back on me, output follows shortly after creation):
```
$ kubectl describe ing
Name:			de-01
Namespace:		default
Address:		xxx.xxx.xxx.xxx
Default backend:	nginx:80 (10.36.0.10:80)
TLS:
  staging-de-01 terminates 
Rules:
  Host	Path	Backends
  ----	----	--------
Annotations:
  target-proxy:			k8s-tp-default-de-01
  url-map:			k8s-um-default-de-01
  backends:			{"k8s-be-30237":"Unknown"}
  forwarding-rule:		k8s-fw-default-de-01
  https-forwarding-rule:	k8s-fws-default-de-01
  https-target-proxy:		k8s-tps-default-de-01
  static-ip:			k8s-fw-default-de-01
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason	Message
  ---------	--------	-----	----				-------------	--------	------	-------
  2m		2m		1	{loadbalancer-controller }			Normal		ADD	default/de-01
  1m		1m		1	{loadbalancer-controller }			Normal		CREATE	ip: xxx.xxx.xxx.xxx (same as above)
```
Of course the backend will never become healthy, since there are no nodes to query.

Actually we only have one cluster in our GCE project. Originated in the limitations in the backend-services (3), we decided to put each cluster into an own project. Nowadays you can have up to 30 backend-services, so it should be supported in a release-version of the L7 ingress (the limitations-docu should be updated).

Seems like I have an older version:

    l7-lb-controller-v0.6.0-srt50                                  2/2       Running   0          4d

**Comment by bprashanth** [comment]
can you give me the output of kubectl logs on the l7-lb-controller? (something like: kubectl --namespace=kube-system logs l7-lb-controller-v0.6.0-srt50  -c l7-lb-controller --tail=100 --follow)

**Comment by bprashanth** [comment]
Also, you could always request upto 30 backends but the default is 3, which is what trips people up often (unless something changed recently).

**Comment by galan** [comment]
Sure, I deleted the Ingress, and created a fresh one, here is the output:
```
$ kubectl --namespace=kube-system logs l7-lb-controller-v0.6.0-srt50 -c l7-lb-controller --tail=100 --follow
I0606 07:33:17.480173       1 utils.go:285] Could not find nodeport for backend {ServiceName:nginx ServicePort:{Type:0 IntVal:80 StrVal:}}: Could not find matching nodeport from service.
I0606 07:33:17.480221       1 event.go:211] Event(api.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"de-01", UID:"ef937e3b-2bb8-11e6-94dc-42010af00015", 	APIVersion:"extensions", ResourceVersion:"3364122", FieldPath:""}): type: 'Normal' reason: 'ADD' default/de-01
I0606 07:33:17.705281       1 instances.go:56] Creating instance group k8s-ig
I0606 07:33:22.024072       1 gce.go:1654] Adding port 30237 to instance group k8s-ig with 0 ports
I0606 07:33:22.901913       1 backends.go:116] Creating backend for instance group k8s-ig port 30237 named port &{port30237 30237 []}
I0606 07:33:23.097484       1 healthchecks.go:49] Creating health check k8s-be-30237
I0606 07:33:31.507746       1 loadbalancers.go:128] Creating l7 default-de-01
I0606 07:33:32.283780       1 loadbalancers.go:288] Creating url map k8s-um-default-de-01 for backend k8s-be-30237
I0606 07:33:36.436093       1 loadbalancers.go:304] Creating new http proxy for urlmap k8s-um-default-de-01
I0606 07:33:40.586043       1 loadbalancers.go:397] Creating forwarding rule for proxy [k8s-tp-default-de-01] and ip :80-80
I0606 07:33:44.735414       1 loadbalancers.go:458] Creating static ip k8s-fw-default-de-01
I0606 07:33:48.917516       1 loadbalancers.go:330] Creating new sslCertificates default-de-01 for k8s-ssl-default-de-01
I0606 07:33:53.003353       1 loadbalancers.go:355] Creating new https proxy for urlmap k8s-um-default-de-01
I0606 07:33:57.436092       1 loadbalancers.go:397] Creating forwarding rule for proxy [k8s-tps-default-de-01] and ip xxx.xxx.xxx.xxx:443-443
I0606 07:34:06.379097       1 controller.go:325] Updating loadbalancer default/de-01 with IP xxx.xxx.xxx.xxx
I0606 07:34:06.382901       1 event.go:211] Event(api.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"de-01", UID:"ef937e3b-2bb8-11e6-94dc-42010af00015", APIVersion:"extensions", ResourceVersion:"3364122", FieldPath:""}): type: 'Normal' reason: 'CREATE' ip: xxx.xxx.xxx.xxx
I0606 07:34:06.771371       1 backends.go:212] Deleting instance group k8s-ig
E0606 07:34:07.111357       1 utils.go:92] Requeuing default/de-01, err googleapi: Error 400: The instance_group resource 'k8s-ig' is already being used by 'k8s-be-30237', resourceInUseByAnotherResource
I0606 07:34:07.111408       1 utils.go:285] Could not find nodeport for backend {ServiceName:nginx ServicePort:{Type:0 IntVal:80 StrVal:}}: Could not find matching nodeport from service.
I0606 07:34:13.158152       1 backends.go:212] Deleting instance group k8s-ig
E0606 07:34:13.504396       1 utils.go:92] Requeuing default/de-01, err googleapi: Error 400: The instance_group resource 'k8s-ig' is already being used by 'k8s-be-30237', resourceInUseByAnotherResource
I0606 07:34:13.504445       1 utils.go:285] Could not find nodeport for backend {ServiceName:nginx ServicePort:{Type:0 IntVal:80 StrVal:}}: Could not find matching nodeport from service.
I0606 07:34:19.561356       1 backends.go:212] Deleting instance group k8s-ig
E0606 07:34:19.920335       1 utils.go:92] Requeuing default/de-01, err googleapi: Error 400: The instance_group resource 'k8s-ig' is already being used by 'k8s-be-30237', resourceInUseByAnotherResource
I0606 07:34:19.920441       1 utils.go:285] Could not find nodeport for backend {ServiceName:nginx ServicePort:{Type:0 IntVal:80 StrVal:}}: Could not find matching nodeport from service.
I0606 07:34:26.179462       1 backends.go:212] Deleting instance group k8s-ig
E0606 07:34:26.524984       1 utils.go:92] Requeuing default/de-01, err googleapi: Error 400: The instance_group resource 'k8s-ig' is already being used by 'k8s-be-30237', resourceInUseByAnotherResource
I0606 07:34:26.525029       1 utils.go:285] Could not find nodeport for backend {ServiceName:nginx ServicePort:{Type:0 IntVal:80 StrVal:}}: Could not find matching nodeport from service.
I0606 07:34:32.843356       1 backends.go:212] Deleting instance group k8s-ig
E0606 07:34:33.171923       1 utils.go:92] Requeuing default/de-01, err googleapi: Error 400: The instance_group resource 'k8s-ig' is already being used by 'k8s-be-30237', resourceInUseByAnotherResource
I0606 07:34:33.171994       1 utils.go:285] Could not find nodeport for backend {ServiceName:nginx ServicePort:{Type:0 IntVal:80 StrVal:}}: Could not find matching nodeport from service.
... And so on
```

The nginx service:
```
$ kubectl describe svc nginx
Name:			nginx
Namespace:		default
Labels:			application=nginx,profile=staging,ts=1464778920
Selector:		application=nginx,profile=staging
Type:			ClusterIP
IP:			10.39.242.120
Port:			http	80/TCP
Endpoints:		10.36.0.10:80
Port:			healthcheck	8081/TCP
Endpoints:		10.36.0.10:8081
Session Affinity:	None
No events.
```

As I mentioned in the initial question, it did previously worked in our development-cluster. Here is the output of the echoheaders service, we used to test. Obviously it has created some nodeport:
```
$ kubectl describe svc echoheaders
Name:			echoheaders
Namespace:		default
Labels:			run=echoheaders
Selector:		run=echoheaders
Type:			NodePort
IP:			10.95.240.237
Port:			<unset>	8080/TCP
NodePort:		<unset>	31625/TCP
Endpoints:		10.92.0.4:8080
Session Affinity:	None
No events.
```

**Comment by bprashanth** [comment]
You need a nodeport for ingress, guessing 30237 is the nodeport of the default backend, so it's doing as expected for the most part. If you delete the ingress it will delete the default backend and then be able to free up the associated ig. It's currently confused because the ingress requires a default backend, but the ingress has no node ports. 

Can you just kubectl edit the service and changet type:ClusterIP to NodePort?

**Comment by galan** [comment]
Yes, I added a dummy NodePort (32000) to the  service, and exactly that one will be used by the L7, which works as expected. From the previous observations and the behavior of the Ingress I expected that the NodePort is automatically added to the service -- which is not the case.

We added a separate NodePort for the health-check, but it wasn't taken into account, so we use now only one port (32000) and switch inside nginx using the `http_x_forwarded_for` header.

So the answer to the problem was, that the service must be of type NodePort with a dummy-port.

Thank you Prashanth

**Comment by bprashanth** [comment]
Yeah the ingress won't mutate your service, because nodeport is only a requirement for GCE and AWS. An nginx ingress for example goes straight to endpoints.

> We added a separate NodePort for the health-check, but it wasn't taken into account, so we use now only one port (32000) and switch inside nginx using the http_x_forwarded_for header.

You can also switch on the UA with something like:
```
events {}
http {
  server {
    listen 80;
    location / {
      if ($http_user_agent ~ (GoogleHC/1.0) ) {
        return 200;
      }
      return 404;
    }
  }
}
```
0.7.0 will adopt the url of the readiness probe on your endpoints as the health check url, but the port will still be the same.

**Comment by galan** [comment]
Good to know, unfortunatly Google uses different UAs like "GoogleHC/1.0" and "Go 1.1 package http" coming from the HCs, so we will continue with the other approach for now.

**Comment by galan** [comment]
Ok, the "Go 1.1 package http" comes from the k8s liveness probe. Nevermind :)

**Comment by karolyi** [comment]
+1, the NodePort update helped ended my 4-day struggle finding out why the loadbalancer won't forward requests to my backend instance properly.

this should be highlighted for kubernetes, it's not really well documented, and people who come from tutorials will miss this point.

**Comment by metral** [comment]
@karolyi @galan 

> +1, the NodePort update helped ended my 4-day struggle finding out why the loadbalancer won't forward requests to my backend instance properly.

Can either of you please specify the update taken to get this working? I too am having issues making sure my LB is properly routing to my backend svc and I'm hitting a wall. I specify a NodePort is in my svc, and am manually setting a backend to my gke cluster instancegroup rather than the new one, empty one created, but neither of those solutions are working.

Thanks.

**Comment by metral** [comment]
For anyone who was running into this issue, it ultimately ended up being a slew of misconfigurations of the service & ingress on my end, plus my lack of knowledge on how the GLBC operated compared to running my own nginx Ingress Controller.

Ultimately, following https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#tls helped me to get past this issue, and achieve my goal of enabling HTTPS ingress, as well forcing the redirection of HTTP -> HTTPS (note: this requires a separate nginx service to serve as the backend for the GLBC + Ingress configuration).

**Comment by PaoloneM** [comment]
After converting my service to nodeport, I had no success: my backend was recognized but marked as UNHEALTHY. The problem was that my service was responding 404 while getting root path (/) and the ingress was replying me with an error. Adding a dummy router that responds "OK" when GET / fixed the issue. In my opinion, heath check needs should be better documented.
