### ISSUE TITLE
service-loadbalancer/service_loadbalancer.go ，I can‘t go build it

### ISSUE THREAD

**Issue by YingBurden** [kubernetes/contrib#1121]
error：./service_loadbalancer.go:352: undefined: "k8s.io/kubernetes/pkg/util".RateLimiter
I don’t find this interface。
@aledbf

**Comment by bprashanth** [comment]
https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/throttle.go#L25

It has a makefile, `make server`
