### ISSUE TITLE
hack/for-go-proj.sh doesn't work if there is windows package in vendor directory

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/contrib#1122]
`hack/for-go-proj.sh` tries to build and install golang packages recursively with `./...` https://github.com/kubernetes/contrib/blob/master/hack/for-go-proj.sh#L50

For old Godeps directory "_workspace", it works well. But after switching to golang 1.6, all the dependencies in "vendor" directory will be built and installed.

If there are windows packages included in "vendor", for example `engine-api` relies on "github.com/Microsoft/go-winio", `hack/for-go-proj.sh` will fail.

**Comment by eparis** [comment]
My understanding is that is only true if your `vendor` is incomplete or one of the packages in `vendor/` is incorrectly written. I also believe that old versions of godep could create an incomplete `Godep/_workspace` and/or `vendor`.

In any case I believe the golang recommendation is to use `go $CMD $(go list ./... | grep -v /vendor/)`. Which personally I think stinks...

**Comment by Random-Liu** [comment]
@eparis In the windows package, it relies on some function which is not in my go library, such as ["syscall.Overlapped"](https://github.com/Microsoft/go-winio/blob/master/file.go#L45), which I guess is windows environment specific functions.
Normally "_windows.go" files will be ignored in linux environment, so we won't build windows packages. However, now we recursively compile each directory in vendor, and will build windows specific packages on linux environment.
