### ISSUE TITLE
[submit queue] only auto-merge when test jobs pass consistently

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/contrib#113]
#112 refers

We should only merge PR's if Jenkins e2e tests are stable across multiple runs.  If I'm reading the code correctly:

https://github.com/kubernetes/contrib/blob/023e2c05df5899bf9734b0d6d21fad0b0617fb45/submit-queue/e2e.go#L93

it deems a single successful test run per job to constitute a "stable" job.  In theory, a single fluky success could cause all pending PR's to auto-merge, which is bad.

In practise, we have multiple test jobs being checked, so if all of them become flaky, their intermittent successes would all have to line up correctly for PR's to merge (which is statistically unlikely).  But even so, I'd suggest adding a "number of consecutive successes required" config value per job.  Faster, more reliable test jobs (e.g. e2e-gce-parallel, at 20 min and 90%+ reliability) might require, say, 4 consecutive successes, while slower jobs (e.g. scalability, at multiple hours per run), might require fewer.

**Comment by spiffxp** [comment]
/close
we no longer use postsubmit tests to block merges
