### ISSUE TITLE
ingress controllers (full)-chain support?

### ISSUE THREAD

**Issue by MaxDaten** [kubernetes/contrib#1131]
Hi,

we are currently using a Lets Encrypt service to create and renew certificates. Besides #952 makes it currently impossible (?) to update the cert for the ingress controller automatically (maybe an kubectl apply/replace on the ingress is enough to force a reload?), we need to install the full-chain, otherwise android would reject the cert (https://community.letsencrypt.org/t/on-android-6-0-1-the-certificate-is-untrusted/7815). Is there a support for the full-chain? The certificates for the GCE Load-Balancer offers a field to enter the (full)chain.pem.

**Comment by bprashanth** [comment]
> Besides #952 makes it currently impossible (?) to update the cert for the ingress controller automaticall

Automatically yes, you can do so through gcloud still.
Cert updates work in 0.6.3, which is the version of the controller that we ship with the next kube release (you can get it right now by just changing the image version in your RC with kubectl edit and deleting the current pod). 

>  Is there a support for the full-chain? The certificates for the GCE Load-Balancer offers a field to enter the (full)chain.pem.

Can you just concat your certs? https://github.com/kubernetes/kubernetes/issues/24669

**Comment by MaxDaten** [comment]
> Not automatically in verions < 0.6.3, you can do so through gcloud still.
Cert updates work in 0.6.3, which is the version of the controller that we ship with the next kube release 

Thanks for clearing this up. I'm looking forward to it.

> Can you just concat your certs? kubernetes/kubernetes#24669

I will try it next week. Thanks.
