### ISSUE TITLE
Merge-bot is not picking my PR

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/contrib#1154]
I'm seeing the following on my PR:
```
 Submit Queue — Unable to determine is PR is mergeable. Will try again later.
```

This is blocking merge of that PR.

@eparis @lavalamp

**Comment by wojtek-t** [comment]
Oh - the PR is: https://github.com/kubernetes/kubernetes/pull/26874

**Comment by eparis** [comment]
That was fixed by github an hour or two ago. Now there is a new problem I am debugging as we speak...

**Comment by eparis** [comment]
closing, hopefully everything is working well.....
