### ISSUE TITLE
Assign fixes unable to assign to non-collaborators

### ISSUE THREAD

**Issue by eparis** [kubernetes/contrib#1161]
If a person is not a kubernetes collaborator they are not able to be assigned. So the submit-queue prints lots of errors every 10 minutes like:

```
assign-fixes.go:90] Assigning 24568 to screeley44 (previously assigned to <nil>)
github.go:1217] Assigning PR# 24568  to screeley44
github.go:1222] Error assigning issue# 24568 to screeley44: PATCH https://api.github.com/repos/kubernetes/kubernetes/issues/24568: 422 Validation Failed [{Resource:Issue Field:assignee Code:invalid}]

assign-fixes.go:90] Assigning 24877 to paralin (previously assigned to <nil>)
github.go:1217] Assigning PR# 24877  to paralin
github.go:1222] Error assigning issue# 24877 to paralin: PATCH https://api.github.com/repos/kubernetes/kubernetes/issues/24877: 422 Validation Failed [{Resource:Issue Field:assignee Code:invalid}]
```

**Comment by eparis** [comment]
@asalkeld (much like I can't assign you to this issue)

**Comment by asalkeld** [comment]
Groan, that is disappointing :disappointed: 
Do you want me to remove the bot, or is it still useful for collaborators?

**Comment by eparis** [comment]
The UsersWithAccess() github function might be useful here? Actually, we no longer have a need to distinguish read/write, so maybe get rid of that helper and just expose fetchAllCollaborators() and use that?

I'd like it if we posted a comment in an issue stating why we assigned it to the person in question.

If a user cannot be assigned, post a comment in the issue indicating we wanted to assign it to that person. (And from then on you need to check for the comment and not comment a second time)

**Comment by asalkeld** [comment]
@eparis one of the main use-cases I was trying to solve was "I want to be able to search for bugs that no one is working on". I can't find a way to search for issues that don't have PR that reference them, so maybe I could change the bot to simply add a label "state/pr-posted". This would make it easy to do this search like this:
```
is:issue is:open label:kind/bug -label:state/pr-posted no:assignee
```
The second part is which developer is working on it. For this I could do as you suggested:
for contributor:
```
Assigned to @eparis (by mungegithub)
```

For non-contributor:
```
Claimed by @asalkeld (by mungegithub)
```
This means that I could also put the "Claimed by ..." text in myself.

I'll start on this now, let me know if this seems reasonable.

**Comment by asalkeld** [comment]
So on the ML there was a suggestion of "pr-pending" and using a dummy assignee. Is there a bot user that we can use for this purpose?

**Comment by asalkeld** [comment]
I have added the ability to assign issues to a proxy contributor (called "k8s-almost-a-contributor") and removed the labelling. Next is to bikeshed on a better user name, then we need to create this user and add it as a contributor...

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1629

**Comment by duglin** [comment]
@asalkeld said:
> I have added the ability to assign issues to a proxy contributor (called "k8s-almost-a-contributor") and removed the labelling.

is this done via a bot? Meaning, can a non-maintainer add some comment to the issue to indicate they want to work on it?

**Comment by saadi123** [comment]
Hi,

Sorry if the comment is unrelated but I don't know how to assign it to somebody from my main issues window. No name shows up in the assignee field when I try to assign it to someone. 

The issue is this one: https://github.com/saadi123/pomodoro_clock/issues/2

Can someone please help.

Thank you.
