### ISSUE TITLE
Documentation for PetSet zookeeper needed

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/contrib#1183]
Hi @bprashanth, I am looking at your petset demos:
`https://github.com/kubernetes/contrib/tree/master/pets/zookeeper`

I am running 1.3.0-alpha.5 with dns add ons.

I am struggling to get this running. The init container don't seem to run and I get missing `zkServer.sh not found` error messages.

Any hints on how to test this ? what configs to 1.3.0-alpha.5 needs to be made if any ?

thanks

-seb

**Comment by runseb** [comment]
Also what type of volume backends is needed for the pvc to work ?

**Comment by bprashanth** [comment]
What version is you dns? (encoded into the name). There was a bug somewhere after v11. I'm running v14 right now, it should be fixed on that. 

You should actually be able to docker run those containers https://github.com/kubernetes/contrib/blob/master/pets/zookeeper/zookeeper.yaml#L37 invoke their entrypoint/cmd with the given args and see where it's failing: https://github.com/kubernetes/contrib/blob/master/pets/zookeeper/zookeeper.yaml#L39

The main container is just going to run zkServer installed by the init conatiner (https://github.com/kubernetes/contrib/blob/master/pets/zookeeper/zookeeper.yaml#L93). If it's not finding it, maybe the init containers are not even running?

> Also what type of volume backends is needed for the pvc to work ?

any dynamic volumen provisioner https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/experimental/persistent-volume-provisioning/README.md. On GCE there is a default provisioner, if you're running a custom setup, you need to run one.
