### ISSUE TITLE
submit queue: don't re-check mergability on a PR if it hasn't changed

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/contrib#1186]
As pointed out by github support.

I think this should save us 1 token per unchanged & unmergable PR per loop?

**Comment by eparis** [comment]
Couldn't HEAD have changed?

**Comment by lavalamp** [comment]
Yeah, but that should only make things unmergable-- I wouldn't expect it to
make things mergable again, usually.

**Comment by eparis** [comment]
Define 'changed'....   If the PR hasn't changed at all we shouldn't using a token (we'll satisfy the ETAG). If github is telling us it changed we don't have any caching (outside of the proxy) across loops....

I'm not sure what to do here (looking for work for an intern)

**Comment by apelisse** [comment]
Probably irrelevant now: https://github.com/kubernetes/test-infra/issues/1625
