### ISSUE TITLE
Nginx Ingress Controller - Stats by country does not work

### ISSUE THREAD

**Issue by nottix** [kubernetes/contrib#1194]
Hi,

the latest stats by country does not work. When i go to /nginx_status page there aren't any filters by country.

Thank you.

**Comment by pieterlange** [comment]
Did you enable it? (`enable-vts-status` in the configmap)

**Comment by nottix** [comment]
Yes i enabled it @pieterlange

**Comment by aledbf** [comment]
@nottix I'm sorry for the delay. Fix in next version.

**Comment by nottix** [comment]
Thank you
