### ISSUE TITLE
Evaluate Docker's processes and tools

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1219]
https://blog.docker.com/2016/06/open-source-docker-part-2-processes/
- workflow stage labels
- status labels (e.g., failing-ci)
- how to become a maintainer

https://blog.docker.com/2016/06/open-source-docker-tooling-automation/
- chat-driven commands
- post instructions to PRs
- PR triage
- identify affected releases
- metrics
- reports

cc @fejta @pwittrock

**Comment by bgrant0607** [comment]
The dockercon talk:
http://www.slideshare.net/icecrime/dockercon-us-2016-scaling-open-source-operations

Metrics:
icecrime/vossibility-stack

https://github.com/docker/leeroy

@fejta Are you actively looking at this?

**Comment by bgrant0607** [comment]
@jfrazelle has part of vossibility-stack running.

**Comment by jfrazelle** [comment]
I will work on getting it into the main cluster where the bots are and we can open it up to the public for play

**Comment by jfrazelle** [comment]
so I wrote a lot of github.com/docker/leeroy what a lot of people know as "gordontheturtle" and i think a lot of it doesnt apply here mostly because its heavily integrated with jenkins and it seems like the k8s-bot does a lot of labeling already

**Comment by jfrazelle** [comment]
also a lot of the chat driven commands were specific to IRC too (I built those as well) seems like we could easily port them to use the slack API though

**Comment by jfrazelle** [comment]
I really wish there was a way here to build something that would benefit a lot of different projects cc @icecrime to see if they have anything they have been wanting as well so we could maybe collaborate on something that works for all

**Comment by bgrant0607** [comment]
cc @caniszczyk

**Comment by jfrazelle** [comment]
oh and if we are switching to `git commit -s` for the CNCF CLA instead we can use leeroy (gordontheturtle) to check those
