### ISSUE TITLE
Investigate mention-bot

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1250]
https://github.com/facebook/mention-bot

Thanks to caniszczyk for pointing this out.

cc @fejta

**Comment by bgrant0607** [comment]
cc @kubernetes/contributor-experience

**Comment by bgrant0607** [comment]
It looks like this tries to identify potential reviewers by looking at "blame" for lines touched by a PR. I don't think that's exactly what we want, but maybe it would help us understand how to get data to populate OWNERS.

**Comment by apelisse** [comment]
It's also what I understood by looking quickly at the page. This was my first idea before I knew about OWNERS file.

It is kind of similar to https://github.com/git/git/blob/master/contrib/contacts/git-contacts.txt

**Comment by bgrant0607** [comment]
This doesn't quite look like what we want.
