### ISSUE TITLE
Fix Godeps in cluster-autoscaler

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/contrib#1251]
I'm about to put up an embarassing PR to fix https://github.com/kubernetes/kubernetes/issues/27821 that will manually alter the `vendor/` directory, because the `Godeps` are currently in conflict, but we need to get a release out:

```
$ godep go build ./...
# k8s.io/contrib/cluster-autoscaler/utils/gce
utils/gce/gce.go:65: cannot use gce.NewAltTokenSource(cfg.Global.TokenURL, cfg.Global.TokenBody) (type "k8s.io/kubernetes/vendor/golang.org/x/oauth2".TokenSource) as type "k8s.io/contrib/cluster-autoscaler/vendor/golang.org/x/oauth2".TokenSource in assignment:
        "k8s.io/kubernetes/vendor/golang.org/x/oauth2".TokenSource does not implement "k8s.io/contrib/cluster-autoscaler/vendor/golang.org/x/oauth2".TokenSource (wrong type for Token method)
                have Token() (*"k8s.io/kubernetes/vendor/golang.org/x/oauth2".Token, error)
                want Token() (*"k8s.io/contrib/cluster-autoscaler/vendor/golang.org/x/oauth2".Token, error)
# k8s.io/contrib/cluster-autoscaler/simulator
simulator/cluster.go:78: undefined: cmd.GetPodsForDeletionOnNodeDrain
simulator/nodes.go:31: undefined: cmd.GetPodsForDeletionOnNodeDrain
godep: go exit status 2
```

**Comment by eparis** [comment]
Wait, why is kubernetes not being vendored in? Unlike GOPATH (which is what Godep used) using vendor is a much stronger all or nothing. You must vendor everything....

**Comment by zmerlynn** [comment]
@eparis: It *is* being vendored in, AFAICT. That's after I updated the k8s dep.

**Comment by eparis** [comment]
The fact that it says you have a `k8s.io/kubernetes/vendor/golang.org/x/oauth2` says that it is using `$GOPATH/src/k8s.io/kubernetes` instead of `$GOPATH/src/k8s.io/contrib/vendor/k8s.io/kubernetes`.  hmmmm

**Comment by zmerlynn** [comment]
@eparis: The second error is the more obnoxious one, and looks like it'll take a PR to the main repo (unless I'm missing something). It's very possible I just screwed something up, too.

**Comment by eparis** [comment]
"I think you did something wrong to get the first error, I don't get it"

However, yes, it does seem the second error is going to require some change in pkg/kubectl/cmd/drain.go :-(

**Comment by aledbf** [comment]
@zmerlynn https://github.com/kubernetes/kubernetes/pull/26667

**Comment by zmerlynn** [comment]
@eparis: Yeah, I assume I did.
@aledbf: Yup, that's the culprit, thanks.

Regardless, we chose a faster route rather than me pounding my head against Godeps even longer. If someone wants to start on the right way, we can get it in place for v1.3.1, but it doesn't seem high priority.

**Comment by eparis** [comment]
@zmerlynn agreed with path chosen.

**Comment by davidopp** [comment]
cc/ @mml

**Comment by mwielgus** [comment]
Fixed.
