### ISSUE TITLE
submit queue "details" link on PRs no longer works

### ISSUE THREAD

**Issue by ixdy** [kubernetes/contrib#1271]
The submit queue adds a commit status with a details link to something like http://submit-queue.k8s.io/#/queue?prDisplay=27798&historyDisplay=27798.

This no longer seems to be a valid page.

**Comment by eparis** [comment]
@ixdy and it should be:
http://submit-queue.k8s.io/#/prs?prDisplay=27798&historyDisplay=27798
??

**Comment by ixdy** [comment]
It looks like it's actually generating a link to http://submit-queue.k8s.io/#?prDisplay=27798&historyDisplay=27798.

Which then gets redirected to the one I posted.

**Comment by eparis** [comment]
I assumed as much, I'm asking if you think my link is where it should go.

**Comment by ixdy** [comment]
Not sure. That seems to show relevant info for that PR, but it shows nothing for PRs in the queue, apparently.

/#/history shows stuff for PRs in the queue, but nothing for my PR (which isn't LGTM'd yet).
