### ISSUE TITLE
Cluster autoscaler requires all migs to be autoscaled

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1283]
Otherwise it doesn't do any scale up or scale down.

**Comment by fgrzadkowski** [comment]
@mwielgus Please, please, please! Be more verbose in PRs & issues! It'd be very hard for anyone to understand why is it an important bug and what was actually broken. We're working in a large project, with huge community and we should make sure that our people can understand what and why we are doing. This is really important.

**Comment by mwielgus** [comment]
More details were added in the fixing PR approximately 40 min before your comment. https://github.com/kubernetes/contrib/pull/1282#issuecomment-229147889. 
Sorry if you were confused, I did this fix well beyond my office hours and was too distracted by personal issues to think about elaborate description. And one "please" is enough, no need to get emotional.

The issues is quite straightforward and the problem is defined in the title, however I can rephrase it. If one mig in the cluster has autoscaling turned off then CA doesn't work.  The exact explanation would be rather impossible without a reference to the implementation so it will be bette handled in the PR. Please take a look at the comment linked above.

**Comment by mwielgus** [comment]
Fixed in #1282.
