### ISSUE TITLE
PRs in the queue should sort by first LGTM date

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/contrib#1286]
...instead of by PR number. I think this would be fairer to people.

**Comment by lavalamp** [comment]
@eparis sound ok?

**Comment by eparis** [comment]
I've heard this before, and I don't think it's wrong. But I can think of the argument that someone who has spent the last month dealing with lots and lots of reviews but only got LGTM yesterday has already been waiting their turn and shouldn't have to wait behind the one-liner which got LGTM slightly before.

I don't think it makes a big difference if we keep the queue at reasonable depth but would not be apposed to such a change. I show all info which affects queue position today, so its obviously why every PR is where it is. Should we show LGTM time?

**Comment by lavalamp** [comment]
Yeah, that's not a bad point, either. It might not hurt to show the (first)
LGTM time, though.

**Comment by lavalamp** [comment]
@eparis I really think we should change this. It's super demoralizing to see my PR not make any progress in the queue at all.

**Comment by eparis** [comment]
I won't nix such a patch  :)

**Comment by lavalamp** [comment]
Patch sent!
