### ISSUE TITLE
[ansible] Put did_install varible to group_vars//all.yml

### ISSUE THREAD

**Issue by gouyang** [kubernetes/contrib#1287]
I'm running testing on the same environment over and over, it takes lots of time to make sure the packages `kubernetes, docker, etcd, flannel` are latest each time. These packages are already latest so I want to skip checking latest package in the ansible script.

Run the default playbook will install openssl and PyYAML as well, it's not so obvious to user if they install package manually, so intend to not touch them.

**Comment by ingvagabund** [comment]
> I'm running testing on the same environment over and over, it takes lots of time to make sure the packages kubernetes, docker, etcd, flannel are latest each time. These packages are already latest so I want to skip checking latest package in the ansible script.

Is this RHEL or Fedora or other OS? For Fedora, the package can become outdated at any time. But I can imagine a situation when you install particular versions of packages and then let the ansible to finish the configuration. In this case, it makes sense to provide ``skip_installation`` or flag with similar meaning.

Is this affecting only the mentioned packages or are there other?

> Run the default playbook will install openssl and PyYAML as well, it's not so obvious to user if they install package manually, so intend to not touch them.

So you are saying you don't want the packages being updated?

**Comment by gouyang** [comment]
> Is this RHEL or Fedora or other OS? For Fedora, the package can become outdated at any time. But I can imagine a situation when you install particular versions of packages and then let the ansible to finish the configuration. In this case, it makes sense to provide skip_installation or other flag with similar meaning.

It only for RHEL. There is fedora-install.yml for fedora and centos-install.yml for CentOS. I've used `--skip-tag` options before, but `did_install` is just for this purpose.
> 
> Is this affecting only the mentioned packages or are there others?

I will send PR to make changes only for these mentioned packages.

**Comment by gouyang** [comment]
>> Run the default playbook will install openssl and PyYAML as well, it's not so obvious to user if they install package manually, so intend to not touch them.
> 
> So you are saying you don't want the packages being updated?

Not touch them so they behaves the default, they will be updated.

The goal is not to checking the very common packages: kubernetes, docker, etcd, flanneld.
Turn `did_install` to true in group_var is easy to achieve it.

**Comment by ingvagabund** [comment]
What about to put ``etcd_[role_]skip_install``, ``docker_[role_]skip_install``, ``master_[role_]skip_install`` and similar vars into each role. In a sense to skip every package installation. It does not make much sense to skip installation of kubernetes-master but keep updating openssl. The role will install/update each package or not at all.

**Comment by ingvagabund** [comment]
One ``skip_install`` on a global scope will not be enough once the individual goals get separated into its own repositories (or merged with other repos). Let's make each role as much autonomous as possible.

**Comment by gouyang** [comment]
The purpose of using `did_install` is to skip install these packages `docker, flannel, etcd and kubernetes`, which maybe installed manually, eg: I installed them manually because I pull it from brew, they are newer than CDN. So `did_install` is convenient to use in this case. 

But it does not give enough flexibility as you mentioned:
1. It does not cover all the stuff which need to install, like openssl, PyYAML, easy-rsa etc.
2. It does not as much autonomous as possible.

I've used to use tags for each package before, how about add a tag for each packages? Then user can skip what they want by just add option `--skip-tags=docker,etcd,flannel,master,node,openssl,pyyaml,easy-rsa`, try to keep the tags simple because it need to type manually.

**Comment by gouyang** [comment]
> What about to introduce install_package tag for all installation tasks and use --skip-tags=install_packages. This way no new dependencies between roles (and tasks) gets introduced.

I see no difference between this way and `did_install`. 

There is no complaint about the current situation which is checking all packages updates, the issue maybe only raised on a stable testing environment and testing frequently, because the installation part eat time and the packages are actually latest.

I added a comment above the variable in the PR, which let user know what's situation if they want to change the variable to `true`.

> We can refine the tags later if needed to provide use cases like "install kubernetes and etcd manually and have the ansible to install the remaining packages".

How to refine the tags, in my opinion just give them different tags.

**Comment by ingvagabund** [comment]
> > What about to introduce install_package tag for all installation tasks and use --skip-tags=install_packages. This way no new dependencies between roles (and tasks) gets introduced.
> 
> I see no difference between this way and did_install. 

``did_install`` is already use and meant for different use. It is role-scoped variable. It can not be used in a global level.

**Comment by ingvagabund** [comment]
> I added a comment above the variable in the PR, which let user know what's situation if they want to change the variable to true.

Oh, now I see your point. For this use cases, it makes sense.

**Comment by ingvagabund** [comment]
Still, if your commit gets applied and ``did_install`` is set to false, only etcd gets installed. As the etcd installation tasks set ``did_install`` to true, it is then never reset to ``false`` in kubernetes installation tasks and ``kubernetes`` gets never installed.

**Comment by gouyang** [comment]
@ingvagabund Have you tested the PR, I tested it here it works well.

**Comment by gouyang** [comment]
@ingvagabund I'm okay on the issue if your solution is better, may you open a new issue or send a PR for it and I can see how can the problem be solved in another way.

**Comment by ingvagabund** [comment]
@gouyang it works by accident. If you run the playbook with your patch on Fedora on 1-node cluster, it works like this:

1. ``did_install`` is false by default
1. once the master role gets run, ``pkgMgrInstallers/fedora-install.yml`` gets included as there is no check for ``not did_install``
1. so ``kubernetes-master`` gets installed on fedora no matter what ``did_install`` is set to
1. at the end of maste role, task ``Set fact saying we did Fedora package install`` is run, setting ``did_install`` to true.
1. node role is run
1. now, ``did_install`` is set to true
1. again, task ``pkgMgrInstallers/fedora-install.yml`` is run as there is no check for ``did_install``
1. so ``kubernetes-nodes`` is installed no matter what ``did_install`` is set to

The playbook fails with:

```
TASK [node : Enable kubelet] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable kubelet: rc=1 Failed to execute operation: No such file or directory\n"}
```

as ``kubernetes-node`` is not installed.

On Fedora, you end up with both kubernetes-[master|node] installed (although this is due to unpresence of ``not did_install`` condition). However, when you repeat the same on RHEL with 1-node cluster with master and nodes role run on the same node (or when you add the ``not did_install`` to when condition), ``did_install`` is false in ``master`` but true in ``nodes`` role.

I have just reproduced that on Fedora.

If the ``did_install`` is set to true, it never gets set to false, so no mentioned package is installed.

**Comment by gouyang** [comment]
I tested twice on Fedora 24 and once on RHEL, does not see any failures. My steps are:
1. uninstall all kubernetes packages
2. run the script `setup.sh`

**Comment by ingvagabund** [comment]
@gouyang node and master in the same VM?

**Comment by gouyang** [comment]
yes

**Comment by ingvagabund** [comment]
Following effort in this PR [1], all roles are being re-factored and broken down into semantic tasks as install, configure, start (and possible others). Once done, operator can use --skip-tags="install" to skip installation/update of components/dependencies/packages.

[1] https://github.com/kubernetes/contrib/pull/1380

**Comment by gouyang** [comment]
> all roles are being re-factored and broken down into semantic tasks as install, configure, start (and possible others). Once done, operator can use --skip-tags="install" to skip installation/update of components/dependencies/packages.

The approache looks elegant to solve the problem, any further discussion will go to #1380.
Close this.
