### ISSUE TITLE
[ansible] Use already-present certificates

### ISSUE THREAD

**Issue by siddharthist** [kubernetes/contrib#1290]
In [Mantl](https://mantl.io), we already have TLS certificates that we'd like to use for as many purposes as possible (to reduce attack surface, ease frequent rotation, etc). Can we use these Ansible roles with already generated certificates, and skip the generation setup here?

**Comment by ingvagabund** [comment]
@siddharthist there is an effort to broken the roles into more independent parts going on. Are you aware of any other parts of the ansible you would like to skip?

**Comment by siddharthist** [comment]
@ingvagabund Probably the Docker, addons, and possibly contiv roles. Thanks for the quick response! How can I stay updated on the status of the modularization?

**Comment by ingvagabund** [comment]
@stephenrlouie

**Comment by stephenrlouie** [comment]
@siddharthist #982 is the first PR to make this modularization. Unfortunately I've been taken on other projects and haven't had much time to follow through with the rest of the roles. Once etcd gets merged it could serve as a model for the rest.

**Comment by ingvagabund** [comment]
@siddharthist assuming you would provide a source where your certificates are located and with the predefined names, it should be quite straightforward to skip the ``gen_certs.yml`` tasks. I would suggest to define ``kube_cert_source_url`` or similar varible in ``kubernetes`` role if set would cause the ``gen_certs.yml`` being skipped and certificates ``{{ kube_cert_source_url }}/ca.crt``, ``{{ kube_cert_source_url }}/kubecfg.crt`` and other being downloaded (assuming the private keys are reachable through secure medium).

**Comment by siddharthist** [comment]
@ingvagabund Yes, the paths to the already present certificates would have to be provided. Optimally, there would also be an option to point to certs already on disk.

**Comment by ingvagabund** [comment]
@siddharthist any PR for this feature is welcome. I have started refactoring the ``kubernetes`` role [1]. Still, the task responsible for the certificates generating is untouched. I suggest to create a new task (e.g. ``retrieve_certs.yml``) that will replace the current ``gen_certs`` [2].

[1] https://github.com/kubernetes/contrib/pull/1444
[2] https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes/tasks/gen_certs.yml

**Comment by siddharthist** [comment]
We've done this work as part of Mantl, but it made a few environment specific changes as well. Anyone is welcome to use our ASL2 code, of course :)
