### ISSUE TITLE
Ansible: generalization of roles, CI, joined effort

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/contrib#1298]
**Decomposition of roles to elevate modularity**

As pointed by @stephenrlouie, it makes sense to generalize the roles and make them independent of playbooks [2]. To deploy kubernetes on one node cluster, there is no need for flannel. Sometimes, only kubernetes addons are needed.

Related issues:
- share the roles in Ansible galaxy [1]: https://github.com/kubernetes/contrib/issues/1291
- deploy kubernetes with provided certificates (skip certificate generator): https://github.com/kubernetes/contrib/issues/1290
- create top level directories: https://github.com/kubernetes/contrib/pull/967

**Joined effort**

Some roles are already shared via Ansible galaxy:
- etcd role: https://github.com/retr0h/ansible-etcd
- docker role: https://github.com/angstwad/docker.ubuntu, https://github.com/jamesdbloom/ansible-install-docker, https://github.com/marklee77/ansible-role-docker
- flannel role: https://github.com/openshift/openshift-ansible/tree/master/roles/flannel, https://github.com/goblain/ansible-role-flannel, https://github.com/vmware/ansible-flannel
- kubernetes role: https://github.com/hidekuro/ansible-role-kubernetes

Others can be found for sure. It makes sense to collaborate with individual folks and elevate the effort.

**CI**

Run various tests on various parts of playbooks to extend the application to various linux distributions. Testing for regressions is important as well. Naming few:
- smoke tests (testing individual roles on various OSes)
- unit-tests (testing created facts on various versions of ansible on various OSes)
- some sort of dashboard with daily digests of run playbooks on various OSes

Both smoke tests and unit-tests can be run over each PR. Daily digest can be taken from periodic jobs run from master HEAD.

**Other effort**:

Now, sooner or later it is desired to move the entire ansible code under kube-deploy repository:
- https://github.com/kubernetes/contrib/issues/635
- https://github.com/kubernetes/contrib/issues/762

Make the deployment faster:
- https://github.com/kubernetes/contrib/issues/1599

[1] http://docs.ansible.com/ansible/galaxy.html
[2] https://github.com/openstack/openstack-ansible

**Comment by stephenrlouie** [comment]
@danehans

**Comment by jasonbrooks** [comment]
@ingvagabund Any activity on this front? I've been wondering about whether we should look at joining efforts with https://github.com/kubernetes-incubator/kubespray or perhaps with https://github.com/openshift/openshift-ansible
