### ISSUE TITLE
QUIC & HTTP/2 Ingress controller

### ISSUE THREAD

**Issue by wernight** [kubernetes/contrib#1303]
I see there are [various Ingress controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers), even though I don't know how to choose in my Kuberentes Yaml files.

I'd like to suggest having one that enabled QUIC and HTTP/2 like https://devsisters.github.io/goquic/ does. It should also support WebSockets. That would allow easy creation of a network Ingress frontend that would improve speed for many users transparently. The current GoQuic doesn't support virtualhost so that would have to be implemented somehow.

**Comment by aledbf** [comment]
@wernight the [nginx ingress controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) supports http/2, spdy and websockets ootb.
I'm not sure nginx will support `QUIC` in the near future

**Comment by wernight** [comment]
I wasn't referring to just supporting it, but to have it automatically server as HTTP/2 QUIC reverse proxy. Like QoQuic but for all domains (or selected domain of an Ingress). I agree having support for it and then install GoQuic on all endpoints.

Just wondering, how can one use the Nginx Ingress instead of whatever is the default (that doesn't support WebSocket in my test)?

**Comment by aledbf** [comment]
@wernight this was opened today in the nginx trac https://trac.nginx.org/nginx/ticket/1057

**Comment by bprashanth** [comment]
> I see there are various Ingress controller, even though I don't know how to choose in my Kuberentes Yaml files.

Currently, through an annotation like: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md#disabling-glbc, https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#disabling-nginx-ingress-controller
In the future we might have ingress claims: https://github.com/kubernetes/kubernetes/issues/30151

not sure if that's what you meant

**Comment by wernight** [comment]
What I mean is I'd like to use Nginx Ingress Controller (that's pretty easy) and no matter the backend (may be that Ingress connects to the actual services via HTTP and that's fine), it could support QUIC and act as QUIC proxy.

This means that the (very likely slower) connection from clients to Ingress would be QUIC-enabled without any extra work. The connection from Ingress to the various services could also support QUIC and make use of it, but I don't see it being a big gain for most.

**Comment by bprashanth** [comment]
That should be easy once nginx supports quic. You can flip it at various levels: 
1. All ingresses: command line flag to controller
2. Opt in at ingress level: annotation
3. Opt in at host level: field

1 or 2 actually makes the most sense to begin with. Converging to 3 will allow us to enable Quic from ingress to backend, but like you pointed out the more important journey is from client -> ingress. Also 3 is harder because this won't work cross platform.  

I believe caddy supports quic, though I don't think anyones written an ingress controller for it yet.

**Comment by aledbf** [comment]
@metalshark is enabled by default

**Comment by metalshark** [comment]
@aledbf thanks

Must be due to the Azure Load Balancer infront on it.
