### ISSUE TITLE
Make mungegithub work on all our repos

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1304]
cc @kubernetes/contributor-experience

**Comment by foxish** [comment]
A couple of questions I had, @lavalamp/@eparis, if you could answer these, it would help me out.

- How and where from are the [health charts for the past week](http://storage.googleapis.com/kubernetes-test-history/k8s-queue-health.svg) generated? 
- Can we assume that the underlying mechanism by which we run tests and read log files will remain the same for other repositories? In that case, it seems like it should be sufficient to remove from code into YAML files, parameters like the Jenkins bucket-name, to make the submit-queue generic enough for other repositories.

**Comment by lavalamp** [comment]
That's in the test-infra repo, @fejta and I talked about getting that
running in the same pod as the munger.

And yes, I think we should mandate the same test result distribution
technique, just with a different bucket per repo (or maybe different
directory, but I think different bucket would be less confusing).

**Comment by foxish** [comment]
There is a hardcoded "requiredContexts" [here](https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/submit-queue.go#L72), and a parameter we supply from the commandline [here](https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/submit-queue.go#L488). We use the former in some places (such as [this](https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/ok-to-test.go#L71) and [this](https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/stale-green-ci.go#L85)) and the latter in other places. This looks to me like a bug.

**Comment by lavalamp** [comment]
Yeah, those should be exposed as flags.

Also default values to our flags should be moved into the deployment.yaml
file.

**Comment by foxish** [comment]
Okay. Does it also make sense to remove defaults from code completely and just have them in the yaml file? Some places may need some additional error handling code in that case.

**Comment by lavalamp** [comment]
Depending on the default, yes. Definitely anything with a string like
"kubernetes" in it. And yes, I wouldn't be surprised if more error handling
was needed.

**Comment by foxish** [comment]
The first [PR](https://github.com/kubernetes/contrib/pull/1349). The first one which makes the submit-queue accept GCS parameters such as bucket-name and directory from the command-line. I'm unable to add reviewers, could you please add them for me?

**Comment by bgrant0607** [comment]
@foxish Once this is working, it should assign PRs in contrib automatically. :-)

**Comment by foxish** [comment]
Which are the other repositories against which we want to start running mungegithub right away? Do any of them have jenkins-ci tests? I'm trying to define the success criteria for this issue (and have some other repository to run against).

**Comment by lavalamp** [comment]
Let's start with contrib?

It runs a travis presubmit that needs to pass. It doesn't have any jenkins
jobs (yet).

test-infra might be good to have after that (@fejta).

**Comment by eparis** [comment]
contrib   :)

**Comment by lavalamp** [comment]
And I think the success criteria is that you can turn up a complete set of
our tools against a new cluster in an hour, that it's clearly documented
and anyone with the keys can do it, and that it's easy to push an update to
all the deployments.

**Comment by bgrant0607** [comment]
@foxish I'd like to run this on kubernetes.github.io.

cc @kubernetes/docs

**Comment by foxish** [comment]
[This PR](https://github.com/kubernetes/contrib/pull/1375) turns some more hardcoded options into flags. The next steps (based on my discussion with @lavalamp are:

1. Integrate the chart generation from the test-infra repository into the submit queue deployment.yaml so that we can deploy it per submit-queue; some changes may be needed to make the generated html status pages generic.
2. Explore the use of `ConfigMap` and change the deployment mechanism to make deployments easier when there are multiple instances of the submit-queue.
3.  Use Ingress to proxy connections from *.k8s.io to each submit-queue service. 
4. Turn on the mungers incrementally for each of our repositories, starting with contrib and docs.

**Comment by bgrant0607** [comment]
Thanks, @foxish. This is super-important.

**Comment by apelisse** [comment]
@foxish @lavalamp  what's left to be done for this issue to be fixed? I'd enjoy seeing a checklist

**Comment by foxish** [comment]
Things left to do at this point are:
- [ ] Deploying ConfigMaps & configuring Ingress (https://github.com/kubernetes/contrib/pull/1395).
- [ ] Parameterizing queue-health containers and running them as part of the submit-queue deployment (https://github.com/kubernetes/test-infra/issues/306).
- [ ] Update documentation to ensure someone can turn up submit-queue/cherrypick against a new repository. (to add to https://github.com/kubernetes/contrib/pull/1417)

Later as a cleanup task, https://github.com/kubernetes/contrib/issues/1415 could be undertaken, but that's not essential to finishing this issue.

**Comment by foxish** [comment]
https://github.com/kubernetes/contrib/pull/1456 adds configmaps for docs and contrib. We should be able to spin up an instance after this. 
The DNS changes appear to have propagated as well. We can start pointing things to:
http://kubernetes.submit-queue.k8s.io/

**Comment by foxish** [comment]
Closing this. The bot is currently functional on contrib and docs. There is a document describing the steps required to get the bot to function on any new repos.
