### ISSUE TITLE
[nginx-ingress-controller] real_ip_header is duplicate when useProxyProtocol is enabled 

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/contrib#1316]
It seems as though since https://github.com/kubernetes/contrib/commit/a152cc44707b8f214666ba7468ceb6575478333b, if useProxyProtocol is enabled, real_ip_header is set twice causing an error when reloading nginx: 

```
nginx: [emerg] "real_ip_header" directive is duplicate in /etc/nginx/nginx.conf:65
```

This prevents the ingress controller from starting in 0.8 if useProxyProtocol is enabled.

**Comment by mikesplain** [comment]
Thanks @aledbf and @bprashanth for the quick fix!

**Comment by bprashanth** [comment]
The new image is not out yet, I'll post on here when it is

**Comment by bprashanth** [comment]
pushed gcr.io/google_containers/nginx-ingress-controller:0.8.1
