### ISSUE TITLE
k8s-bot: there should be a command to rerun GKE smoke tests only

### ISSUE THREAD

**Issue by gmarek** [kubernetes/contrib#1322]
I wasn't able to find one. cc @eparis @lavalamp

**Comment by lavalamp** [comment]
This is actually a jenkins/test-infra thing, not a merge bot thing. @fejta @ixdy

**Comment by ixdy** [comment]
cc @spxtr

**Comment by fejta** [comment]
Yes please assign to @spxtr (ideally in test-infra repo)

**Comment by spxtr** [comment]
Right now it uses the same command as the GCE test. It's pretty simple to change it, just need to update the regex.

Something like `@k8s-bot gke e2e test this` where the `gke` is optional?

**Comment by fejta** [comment]
sgtm, we have this for node already

**Comment by gmarek** [comment]
Closing in favor of kubernetes/test-infra#269
