### ISSUE TITLE
systemd defaults: remove ServiceAccount from admissions

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/contrib#1325]
As a starting user of kubernetes I would like to use the default account as much as possible and discover concept of admissions later. Currently, when the kubernetes is installed and the ``kube-apiserver`` started, I can not start playing with k8s right away. I have to tune the configuration first.

Let's discuss what are the disadvantages of disabling the ``ServiceAccount`` admission control [1].

[1] https://github.com/kubernetes/contrib/blob/master/init/systemd/environ/apiserver#L23

**Comment by sjenning** [comment]
I think it should be removed from the default list and a comment added saying it can be added back after the controller-manager is configured with a ```--service-account-private-key```.

**Comment by ingvagabund** [comment]
http://stackoverflow.com/questions/33528398/why-dont-i-have-a-default-serviceaccount-on-kubernetes

**Comment by ingvagabund** [comment]
Maybe, it would make more sense to write down an article/tutorial how to setup the service account. Or at least collect a list of already existing articles. With ServiceAccount on a user is forced to google out the issue and learn more about (at least to remove the ServiceAccount from the admissions). However, yes, it is not install and run.

**Comment by sjenning** [comment]
IIRC the minimum procedure for enabling services accounts is:
- create a self-signed apiserver key/cert
- modify the apiserver ``` --service-account-key-file``` and controller-manager ```- -service-account-private-key``` configs to use the apiserver key for service account secret creation and authorization
- restart the apiserver and controller-manager

This is at least a 4 or 5 step process

**Comment by ingvagabund** [comment]
What about to extend the kubernetes rpms with ``deploy.sh`` script that will deploy the kubernetes cluster on the host? It would run a subset of playbooks and take care of all the steps. Something like:

```
$ cat deploy.sh
sudo dnf install ansible kubernetes-ansible -y
cd /usr/share/ansible/scripts; ./deploy-one-node-cluster.sh
```

**Comment by ingvagabund** [comment]
At the same time, it make sense to install kubernetes-addons as well so a user have running DNS and other extensions.

**Comment by ingvagabund** [comment]
With #1689 the kubernetes is deployed on localhost with addons on.
