### ISSUE TITLE
Nginx Ingress Controller - Default Backend when using HTTPS

### ISSUE THREAD

**Issue by cvle** [kubernetes/contrib#1329]
NGINX redirects all HTTP traffic for undefined hosts to the default backend. But when using HTTPS the traffic all goes to the first defined TLS host in the generated `nginx.conf`. 

By default NGINX should direct all traffic regardless of HTTP or HTTPS to the default backend. When using HTTPS NGINX should serve a default self-signed certificate.

What do you think?

**Comment by nballotta** [comment]
Same issue here. I think @aledbf is looking into a solution for that :)
