### ISSUE TITLE
Enable secure connections to etcd from podmaster

### ISSUE THREAD

**Issue by liggitt** [kubernetes/contrib#133]
All components that connect to etcd directly should support a secured etcd deployment. Podmaster only allows passing in the list of servers... it should also take a etcd client config file (like the API server)

https://github.com/kubernetes/contrib/blob/36816275fd53c7a2ef59650c80e2820fe3595584/pod-master/podmaster.go#L140

**Comment by roboll** [comment]
#130 fixes this, but doesn't use the etcd config file, and instead introduces a few new flags, since it looks like apiserver is moving to the new etcd client. ref https://github.com/kubernetes/kubernetes/issues/11962

**Comment by timothysc** [comment]
This should be deprecated in lieu of https://github.com/kubernetes/kubernetes/pull/16830

**Comment by mikedanese** [comment]
I;m going to close this in lieu of #516 since we are deprecating podmaster and their is a workaround documented in #15847

**Comment by glerchundi** [comment]
@mikedanese thanks for pointing this out, really helpful to know which is the direction k8s is taking in this matter.

**Comment by timothysc** [comment]
cleaning, closing this out from previous comments.
