### ISSUE TITLE
[nginx ingress controller] Nginx statistics based on IP:PORT

### ISSUE THREAD

**Issue by micheleorsi** [kubernetes/contrib#1344]
Once we started to collect statistics from the /nginx_status page we noticed that they are based on IP:PORT, instead of name-of-pod.

Which means that when pods come and go (with different pod name but eventually with the same IP:PORT) NGINX "inherits" the history of a previous pod that was using the same IP:PORT (but had different name).

Would it be possible to have nginx statistcs based on name-of-pod instead of IP:PORT?

Thanks

**Comment by aledbf** [comment]
@micheleorsi is possible but requires a change to use of the DNS addon and this introduces a not optional dependency to use the ingress controller.
Let me see if this option could be behind a flag

**Comment by bprashanth** [comment]
Currently there's no way to ensure static ips for kubernets pods. Please reopen if you know a way to get nginx to perform a reverse lookup of ip <-> hostname and we can try to leverage that to map the pod ips to their services using kube-dns, just for the stats page (afaik there's no way, and @aledbf corroborated).
