### ISSUE TITLE
Cluster-autoscaler: correctly support completely empty nodes

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1345]
Make sure that appropriate node info is created also for nodes that have absolutely no pods running on them.

**Comment by seanturner83** [comment]
My workaround to this is to run a daemonset (any will do). That said, it should still be fixed if possible...

**Comment by seanturner83** [comment]
https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/scale_down.go#L94
->
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/schedulercache/util.go

**Comment by mwielgus** [comment]
It seems that everything should be fine now:

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/nodes.go#L79
https://github.com/kubernetes/kubernetes/blob/1dfd64f4378ad9dd974bbfbef8e90127dce6aafe/plugin/pkg/scheduler/schedulercache/util.go#L23

All previously problematic code that required pods to be present on nodes is gone.
