### ISSUE TITLE
Cluster-autoscaler: use full drain logic in scale down.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1352]
Grace period in particular.

cc: @piosz @jszczepkowski @fgrzadkowski

**Comment by fgrzadkowski** [comment]
More context:

Currently we perform checks if we could drain a given node (e.g. all pods are managed by controllers), but in the end we just delete underlying node. As a result node is not drained, rather simply disappears. As a result we do not respect things like grace period or disruption budget (once it's available).

**Comment by mwielgus** [comment]
Full drain is used, including pod disruption budget.
