### ISSUE TITLE
nginx-slim: bake daemon off option into image

### ISSUE THREAD

**Issue by erictune** [kubernetes/contrib#1354]
To use ningx with docker, you need to set `daemon off`.
So, people who run this image end up adding these 5 lines to pod spec:

```
        command:
        - nginx
        args:
        - -g
        - "daemon off;"
```

Would it make sense to add:
`RUN echo "daemon off;" >> /etc/nginx/nginx.conf`
to the Dockerfile so that people don't have to add those lines?

**Comment by erictune** [comment]
@aledbf do you maintain contrib/images/nginx-slim/?

**Comment by aledbf** [comment]
@erictune yes. The CMD already contains [daemon off](https://github.com/kubernetes/contrib/blob/master/images/nginx-slim/Dockerfile#L29) but I can that echo in the Dockerfile

**Comment by erictune** [comment]
Oh.  Maybe that is good enough.

I was looking at this example:
http://kubernetes.io/docs/user-guide/petset/
which has this yaml https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/release-1.3/docs/user-guide/petset.yaml
and was thinking it could be made shorter.

**Comment by aledbf** [comment]
@erictune I just created https://github.com/kubernetes/kubernetes.github.io/pull/827

**Comment by erictune** [comment]
Thanks, @aledbf
