### ISSUE TITLE
kubernetes/Ingress: Getting connection refused error on running nginx-ingress replication controller

### ISSUE THREAD

**Issue by tushar281188** [kubernetes/contrib#1367]
Hi,

I am trying to run ingress controller example but getting "Get https://204.17.5.1:443/apis/extensions/v1beta1/ingresses: dial tcp 204.17.5.1:443: getsockopt: connection refused" error, where "204.17.5.1" is kubernetes service cluster IP. 

I changed port in rc.yaml to 443 but still facing the same error. 

Found nearly similar conversation at "http://stackoverflow.com/questions/34147547/can-not-access-kubernetes-master-apis-via-https-dial-tcp-10-200-0-1443-i-o-tim", but no luck. 

Can someone guide me on this.

Example link that I followed "https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx-alpha"

K8s version : 1.2.5

**Comment by aledbf** [comment]
> https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx-alpha

Please use `https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx` instead of `nginx-alpha`

**Comment by bprashanth** [comment]
Please reopen if not fixed in the nginx ingress controller, and post the nginx.conf generated by the controller (`kubectl exec <nginx pod> -- cat /etc/nginx/nginx.conf`)
