### ISSUE TITLE
Create special test labels that add test-suites as a gatekeeper for merges

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/contrib#137]
We have the gce-e2e suite that acts as a gatekeeper for PR merges.

We should have the ability to add additional suite(s) to act as a gatekeeper for a PR merge.
This can be done by leveraging github labels.

Currently, we are in a mode where many tests are kicked out of gce-e2e suite because of slowness etc..

Having a custom label-driven suite gatekeeper, we can have certain PRs that need a specific test suite to be run, act as a gatekeep for the PR merges.

@quinton-hoole 
@brendandburns 
@ixdy 
@thockin

**Comment by eparis** [comment]
So I like the idea, and might even do thek if there is some agreement, but I have such a huge submit-queue rewrite in progress I'd hope we don't move too quickly on this as the conflict will surely be extremely difficult.

**Comment by ArtfulCoder** [comment]
We had some offline discussions and have agreed that this would be useful.

Feel free to assign this issue to yourself if you can do it.

**Comment by ixdy** [comment]
I don't think the Jenkins pull request plugin supports triggering based on labels (though it'd be a nice feature to have - jenkinsci/ghprb-plugin#210).

We could probably work around this by having the munger comment with a particular string when certain labels are added, and having the Jenkins bot only run certain tests when certain strings exist in the comment, but ugh.

**Comment by KostyaSha** [comment]
It was one of the reasons why i wrote https://github.com/jenkinsci/github-pullrequest-plugin unfortunately i had no time to desribe it detailed. But it works perfect for 1year on my project. If you really interested i can try wrote a doc on weekend.

**Comment by thockin** [comment]
I like this idea

**Comment by KostyaSha** [comment]
Sorry, was too busy. Seems now i have time. I need resolve small issue (provide default values in UI) and then will notify you.

**Comment by eparis** [comment]
let me suggest starting on top of https://github.com/kubernetes/contrib/pull/173   as if you don't we'll have major merge problems

**Comment by bgrant0607** [comment]
A more recent proposal for test ownership was made by @lavalamp
