### ISSUE TITLE
Show details per user on master and branch PR state via dashboard

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/contrib#1372]
Open/closed in both locations and relevant labels cherrypick-*.
cc @matchstick @lavalamp @eparis @bgrant0607 

Moved from https://github.com/kubernetes/kubernetes/issues/27403

**Comment by bgrant0607** [comment]
To clarify:

This is discussing:

http://cherrypick.k8s.io/#/queue.

https://github.com/kubernetes/contrib/tree/master/mungegithub/cherrypick

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1636
