### ISSUE TITLE
[Possible bug] tcpServices binds to new map in newLoadBalancerController

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/contrib#138]
@beeps:  

In `newLoadBalacnerController` lines https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/service_loadbalancer.go#L391-L395 

Seems a little off to me, i.e. line 391...

```
 lbc := loadBalancerController{ 
...
    tcpServices: map[string]int{},
}
```

In the above, shouldn't the loadBalancerController be binding tcpServices to the value of `cfg.tcpServices` ?  The code just below seems to expect that `tcpServices` actually has some data in it... 

```
strings.Split(*tcpServices, ",") {
```
I'm in the process of extracting more info from reading the code.

If I've missed something obvious, apologies in advance :)..

**Comment by bprashanth** [comment]
I haven't looked at the code but i can tell you how to figure it out. Replace https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/service_loadbalancer.go#L522 with:
```go
	if *dry {
		kubeClient = client.NewOrDie(&client.Config{Host: "http://127.0.0.1:8001", Version: "v1"})
	} else if *cluster {
		if kubeClient, err = client.NewInCluster(); err != nil {
			glog.Fatalf("Failed to create client: %v", err)
		}
	} else {
		config, err := clientConfig.ClientConfig()
		if err != nil {
			glog.Fatalf("error connecting to the client: %v", err)
		}
		kubeClient, err = unversioned.New(config)
	}

```
Create a tcp service like: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer#tcp, run kubectl proxy on localhost pointed at your remote cluster, and observe the haproxy config the loadbalancer spits out when you run (on the same machine kubectl proxy is running on):
```
service_loadbalancer --dry --tcp-services=mysql:3306
```

If there's a bug, submit a pr :)
Also feel free to submit the snippet that allows *dry above as a pr if you have time.

**Comment by jayunit100** [comment]
Thanks ! I'll try to mock this out now and update Docs accordingly also.

**Comment by bprashanth** [comment]
I'm pretty sure --tcp-services is WIA btw, I just used mysql in my cluster.

**Comment by jayunit100** [comment]
WIA="working in action"?

**Comment by bprashanth** [comment]
I mean wai

**Comment by jayunit100** [comment]
ah ok, "working as-is" :) .   Will look deeper now while I test it.

**Comment by jayunit100** [comment]
not a bug , looked closer and the tcpServices was in a struct to begin with, got it confused with the string arg inside the struct .
