### ISSUE TITLE
[service-loadbalancer] fixes and improvements

### ISSUE THREAD

**Issue by jcmoraisjr** [kubernetes/contrib#1381]
I've implemented a couple of fixes and improvements on service loadbalancer in order to use it on our company. Have a look at [this compare](https://github.com/kubernetes/contrib/compare/master...jcmoraisjr:features).

Let me know in what commits you are interested and I'll create the PRs.

**Comment by rikatz** [comment]
+1

**Comment by seattle** [comment]
+1

**Comment by jcmoraisjr** [comment]
service-loadbalancer was deprecated on behalf of [haproxy-ingress](https://github.com/jcmoraisjr/haproxy-ingress). Btw the [fork](https://github.com/kubernetes/contrib/compare/master...jcmoraisjr:features) and the [image](https://quay.io/repository/jcmoraisjr/kube-loadbalancer) will stay there. Closing.
