### ISSUE TITLE
[nginx-ingress-controller] Basic auth header is not stripped

### ISSUE THREAD

**Issue by atombender** [kubernetes/contrib#1383]
If you use basic auth in an ingress, then the `Authorization` header is passed along to the proxied upstream, which can result in incorrect behaviour if the upstream doesn't expect one.

For example, [Drone](https://github.com/drone/drone) will ignore its session cookie if the auth header is specified.

The correct behaviour is to strip the header and not pass it to the upstream.

Until this is fixed, I've been trying to find a workaround by injecting a custom Nginx directive, but I can't a way. Is there one?

**Comment by aledbf** [comment]
@atombender use a custom template and add `proxy_set_header Authorization "";` in the location with the basic auth

**Comment by atombender** [comment]
@aledbf Thanks, I just discovered the template. That's just a temporary workaround, of course.

**Comment by aledbf** [comment]
> That's just a temporary workaround, of course.

Yes, tomorrow I will open a PR to remove the `Authorization` header when the auth annotation is used

**Comment by atombender** [comment]
@aledbf: This PR fixed the issue for me.

**Comment by aledbf** [comment]
@atombender awesome. Thanks!
