### ISSUE TITLE
Makefile has MUNGERS and mungegithub/submit-queue/deployment.yaml duplicates the list

### ISSUE THREAD

**Issue by apelisse** [kubernetes/contrib#1388]
In `mungegithub/Makefile` there is a list of all mungers in `MUNGERS`.
The same list is duplicated in `mungegithub/submique-queue/deployment.yaml` making things kind of confusing.

We should probably find a way to DRY.

**Comment by foxish** [comment]
We should just remove the one in the makefile, since we never use the value except in [local_dryrun](https://github.com/kubernetes/contrib/blob/87fc847f310e7b21ea866155c80e83819f1b0664/mungegithub/Makefile#L74), and I don't think we even need that target anymore.

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1634
