### ISSUE TITLE
Finish OWNERS implementation

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1389]
Described here:
https://github.com/kubernetes/contrib/pull/474#issuecomment-226249631

cc @eparis @davidopp @philips @mike-saparov @hongchaodeng @kubernetes/contributor-experience 

@philips Please add your suggestions here.

**Comment by bgrant0607** [comment]
Copying from #474:

Previous workflow:
* a reviewer, who didn't necessarily have write access (and therefore label access), would be assigned
* the reviewer would eventually type "LGTM" into a comment
* the author would (often) squash commits and/or rebase
* the reviewer would then apply the `lgtm` label if they had label access, or would notify someone in kubernetes-maintainers to do that if they did not; the author could self-apply `lgtm` if they had label access

Proposed workflow:
* a reviewer, who isn't necessarily an approver, would be assigned
* the reviewer would eventually type "LGTM" into a comment
* the author would (often) squash commits and/or rebase
* the reviewer would then type `I approve` if they were an approver, or would notify an approver to do that if they were not; the author could self-approve if they were an approver

It's pretty much the same, except that it bypasses github ACLs.

We've already taken direct merge powers away from most people in kubernetes-maintainers.

On approvers vs. reviewers:

We're bottlenecked on review bandwidth. We need to grow the reviewer pool, but we also need to move to multi-phase PR reviews in order to take load off of bottleneck people.

A reviewer just has to be someone who could provide constructive feedback on a PR review -- someone who understands our project's coding conventions, ideally the code of that component, etc. We should be more liberal with inclusion in the reviewers list.

An approver is someone with the authority to determine whether a PR should be merged or not.

We'll want a progression by which we can grow contributors into reviewers and reviewers into approvers.

A PR might have a single primary reviewer but require multiple approvers (e.g., an API approver and a Kubelet approver, for a Node API change), or multiple reviewers (e.g., people familiar with different parts of the repo) and a single approver (e.g., me).

As an example, I want to be removed from the PR auto-assigner, but would like to retain my approval powers -- I should be an escalation point, not on the front lines of reviews. 

We should find a home for this:
https://github.com/coreos/findowner

**Comment by bgrant0607** [comment]
@hongchaodeng @xiang90 Do you have any more questions about this?

**Comment by hongchaodeng** [comment]
@bgrant0607 
No questions from me so far. Will try to get this done by next Monday.

**Comment by hongchaodeng** [comment]
Here's a follow-up to the proposed workflow:

> a reviewer, who isn't necessarily an approver, would be assigned

The [findowner](https://github.com/coreos/findowner/blob/master/main.go) program will generate owners for each package. Do you want me to assign according to the new owner list in the implementation?

> the reviewer would eventually type "LGTM" into a comment

PR (https://github.com/kubernetes/contrib/pull/1428) will enable munger to look for 'LGTM' comment from reviewer and apply an 'lgtm' label.
I will try to implement a notifier to notify relevant approvers.

**Q**: What's the policy for multiple reviewers?

> the reviewer would then type "I approve" if they were an approver, or would notify an approver to do that if they were not; the author could self-approve if they were an approver

PR (https://github.com/kubernetes/contrib/pull/1429) will enable munger to look for approver's "I approve" comment and apply "approved" label.
I will try to modify the submit-queue logic to look for approval label.

**Q1**: What's an approver? How can I know if someone is an approver?
**Q2**: Multiple approvers policy?

**Comment by bgrant0607** [comment]
@hongchaodeng FYI, I filter all email that doesn't mention "bgrant0607", so I didn't notice your update. I'll try to respond later today.

**Comment by bgrant0607** [comment]
@hongchaodeng 

The bot implementation will be in contrib. The updates of OWNERS needs to happen in the kubernetes repo. These can occur relatively independently. As a starting point, current reviewers should be moved to approvers, and we could use `findowner` for lists of reviewer candidates. Due to how old the original reviewers lists are and to how much refactoring we do, I imagine we'll need to iterate on both lists. There is also a list of area owners in https://github.com/kubernetes/kubernetes/wiki . 

Policy on multiple reviewers: Github now supports multiple assignees. For PRs touching multiple directories, rather than assigning reviewers from the nearest common ancestor in the source tree, for scalability, I think we should assign reviewers from the leaves, perhaps randomly selecting 2 from each directory and then choosing the least loaded review-wise (The Power of 2 Choices). In the case of multiple assignees, it would be up to them to coordinate the review of the whole thing, though eventually it would be desirable for the bot to confirm LGTM coverage of all directories touched before applying the lgtm label. I'm open to other policies, and we can also refine it over time. 

For approvers, I think we should assign/notify an approver from the nearest common ancestor but, again, transitive coverage of directories touched should gate application of the `approved` label. So an approver in the root OWNERS file could approve any PR.

**Comment by thockin** [comment]
I know most of the talk about repo-splitting was in the main repo, but...

Any objections to breaking off a new repo for "autobots" and putting all
automation and bots etc there?  In the vein of making the bots more
generic, a whole distinct repo might help.

**Comment by bgrant0607** [comment]
@thockin I agree, but could we please not discuss it on this issue?

**Comment by thockin** [comment]
ACK.  Is there an issue for this topic or should I open one?

**Comment by bgrant0607** [comment]
There is actually a doc:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/owners.md

**Comment by hongchaodeng** [comment]
@kubernetes/contributor-experience 
In order to implement the approval munger, I need to define approver and implement some helper function to "get" approver.
Is there any work around it currently? Let me know if any.

My implementation plan follows the comment:

> For approvers, I think we should assign/notify an approver from the nearest common ancestor but, again, transitive coverage of directories touched should gate application of the approved label. So an approver in the root OWNERS file could approve any PR.

@bgrant0607 One question. What does it mean by "transitive coverage of directories touched should gate application of the approved label."

**Comment by bgrant0607** [comment]
@hongchaodeng A user listed as an approver in an OWNERS file applies to files in that directory and in all subdirectories of that directory, so someone in the root OWNERS file could approve all PRs.

**Comment by resouer** [comment]
Interesting to have this! Tracking!

**Comment by bgrant0607** [comment]
If you need more inspiration, here's a similar product:
https://about.pullapprove.com/features/

FWIW, we have looked at pullapprove, but the functionality is a subset of what we need for our PR workflow in general, and the legal process to get it approved could well drag out for a really long time.

**Comment by foxish** [comment]
@hongchaodeng If we are regenerating updated owners for the main repository, we may be able to leverage the code at https://github.com/foxish/findowner/tree/foxish-edits, which I used to generate owners for contrib. It has a few modifications to the original coreos/findowner code, and some of those changes may be reusable.

**Comment by grodrigues3** [comment]
@hongchaodeng can we get a status update on this?  Do you need any help or input on the implementation?

**Comment by hongchaodeng** [comment]
For the code it's done in https://github.com/coreos/findowner
We are still coordinating. Hopefully will be able to discuss it again on Thur's meeting.

**Comment by hongchaodeng** [comment]
Approver handler impl: https://github.com/kubernetes/contrib/pull/1727

**Comment by apelisse** [comment]
PRs adding reviewers to OWNERS files:
- [ ] https://github.com/kubernetes/kubernetes/pull/36115
- [ ] https://github.com/kubernetes/kubernetes/pull/36116
- [ ] https://github.com/kubernetes/kubernetes/pull/35833
- [ ] https://github.com/kubernetes/kubernetes/pull/35715

More to come ...

**Comment by apelisse** [comment]
PRs that can't be merged before each owners file is merged, and are properly tested in a different repo:
- https://github.com/kubernetes/contrib/pull/2018
- https://github.com/kubernetes/contrib/pull/2002
- https://github.com/kubernetes/contrib/pull/1923

**Comment by philips** [comment]
@apelisse thanks for doing this work. What is your target date for getting them all merged?

**Comment by thockin** [comment]
I think @apelisse is out for a while - does someone need to take this over?

**Comment by philips** [comment]
@thockin How long is he out? We have been working on this since July and I want to get it done done.

**Comment by thockin** [comment]
Long enough that you'll be unhappy.  Can we find an alt owner?

**Comment by grodrigues3** [comment]
I've been working on it as well.  I can follow up with directory owners for getting their updates to their OWNERS files.  And we have a PR out for testing this against contrib that gates on the approved and lgtm label and finds/notifies relevant owners. 

[PR](https://github.com/kubernetes/contrib/pull/2076) is currently waiting for review/lgtm.

**Comment by calebamiles** [comment]
Well after long last all the PRs to the various `OWNERS` files in `kubernetes:kubernetes` have been merged! @bgrant0607 what is the next thing that you'd like tacked with respect to this issue or are we at a point of closing this issue and creating new issues for those next steps? Thanks for all hard work @apelisse and @grodrigues3!

**cc: @philips**

**Comment by grodrigues3** [comment]
I'll send an email out to kubernetes-dev shortly that details the approvers process and the timeline.  In short, we'll start running it on the main repo next week and we'll use contribx mailing list for feedback.

**Comment by philips** [comment]
Thanks for all of the hard work @grodrigues3 @apelisse and @calebamiles. For those that missed it the kubernetes-dev thread is here: https://groups.google.com/forum/#!topic/kubernetes-dev/aCuaL0DZZvI

**Comment by apelisse** [comment]
Thanks @philips. it might be time to close this issue :-)

**Comment by apelisse** [comment]
We are fixing issues and addressing feedback here: https://github.com/kubernetes/test-infra/issues/1678

**Comment by apelisse** [comment]
Closing this issue now.
