### ISSUE TITLE
Mergebot merged a PR that had needs-rebase label

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/contrib#1391]
https://github.com/kubernetes/kubernetes/pull/26298 was merged by mergebot even though it had the needs-rebase label.

cc @k8s-oncall as FYI

cc @lavalamp @eparis

**Comment by lavalamp** [comment]
The PR must not have needed a rebase or it wouldn't have been possible to merge it. Maybe the github API had a hiccup while the merge bot was checking mergability.

**Comment by lavalamp** [comment]
Or maybe something got rolled back that made it mergable again?

**Comment by eparis** [comment]
Agreed, I'm not too worried although this may be a case of https://github.com/kubernetes/contrib/issues/422
