### ISSUE TITLE
Ansible should use configuration and script files from local system 

### ISSUE THREAD

**Issue by jeffbean** [kubernetes/contrib#14]
Right now we use the `get_url` to obtain most of the addon and configuration files from the Github content. 

Example:

``` yaml
- name: Make sure the system services namespace exists
  get_url:
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/saltbase/salt/kube-addons/namespace.yaml
    dest="{{ kube_config_dir }}/addons/"
    force=yes
```

We should have a mechanism to use files from the local system. Since the contrib folder is now outside the main repository this is a little more difficult since we can not assume file locations. It would be nice to have as little logic in the `setup.sh` script as well but might be the best solution? 

I propose we keep the downloading versions of the files and have the option to use local files. We do this with `packageManager` and `localBuild` for the actual kubernetes binaries now. Using this same technique we have the config files.

Logging the bug to track ideas, suggestions and progress.

**Comment by eparis** [comment]
Moving us to contrib also broke 'localBuild'   :-(    /me has always hated git submodules, but I wonder if this is a case where it makes sense (probably not, it never does...)
