### ISSUE TITLE
mungegithub should manage CLA labels

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1405]
Similar to the Google bot.

After we switch to the CNCF CLA.

Example using CNCF CLA (on a cncf repo):
https://github.com/cncf/demo/pull/7

It would probably be easier than running a separate bot.

**Comment by foxish** [comment]
Was blocked by https://github.com/kubernetes/contrib/issues/1834
Contrib and pr-bot now have CLA managed by prow. Will extend it to the entire org this week and send out email.

**Comment by foxish** [comment]
Closing
