### ISSUE TITLE
[Ansible] sudo depreciation warning

### ISSUE THREAD

**Issue by AdrianGPrado** [kubernetes/contrib#1407]
The current playbook uses the ansible module `sudo` which is depreciated and will be removed in future releases. This causes a warning and it will be an error in the future.

    [DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

Instead of sudo use the ansible module [become](http://docs.ansible.com/ansible/become.html#become).

**Comment by ingvagabund** [comment]
@AdrianGPrado can you open a PR for the ``s/sudo/become``?

**Comment by AdrianGPrado** [comment]
@ingvagabund PR open #1408. I have rebased it on top of `master` branch, current HEAD is `33d52f3`.
