### ISSUE TITLE
[Ansible] option to keep easyrsa "context directory"

### ISSUE THREAD

**Issue by imsky** [kubernetes/contrib#1409]
it would be useful to keep the easyrsa directory (https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes/files/make-ca-cert.sh#L74) around on the client side in order to generate additional client certificates.

**Comment by galexrt** [comment]
@imsky The latest changes keep the ca keys for apiserver and etcd, so new certificates can be generated.
