### ISSUE TITLE
[Ansible] FLANNEL_ETCD needs to reference internal master IP

### ISSUE THREAD

**Issue by imsky** [kubernetes/contrib#1410]
i periodically get timeouts when setting up Flannel on AWS since the etcd host is inaccessible.

i use a dev machine, so i reference the external IPs in inventory, however the etcd config advertises on the internal IPs, so Flannel is unable to reach the etcd cluster.

i'm not sure if it is simple to create an automated workaround, but this should be referenced in docs.

**Comment by ingvagabund** [comment]
@imsky what about to use host names (e.g. ``etcd-server``) instead of raw IPs? Depending on your entries in ``/etc/hosts`` under each node you can point ``etcd-server`` to internal IP.
