### ISSUE TITLE
[mungegithub] Modify mungegithub to use config files instead of command-line arguments.

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1415]
The number of command-line arguments is getting large and unwieldy. We should switch to reading config files instead.
It would also let us group these command-line options into logical sub-units which is currently not possible.

**Comment by eparis** [comment]
I've not looked at it, but I know `github.com/spf13/viper` is supposed to help add config files on top of cobra/pflag...

**Comment by foxish** [comment]
@eparis I will take a look at that. Thanks!

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1633
