### ISSUE TITLE
[mungegithub] ping inactive reviewers and reassign

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1422]
Formerly part of issue #869 
- Ping the PR due to lack of inactivity, notifying either the PR author or the assignee, depending on who last touched the PR (keep track of whose court it's in).
- Create a way to postpone the next ping for a fixed amount of time (day, week, month, next release cycle).
- Reassign PRs whose assignees never responded.

Additionally:
- label stale PRs.

**Comment by grodrigues3** [comment]
This is related to #1402.  I think that one already pings due to inactivity and also notifies the "involved Users".   We might be able to add additional granularity to the notifications by checking for keywords like PTAL or paying attention to the last action (e.g new commit)

**Comment by foxish** [comment]
@grodrigues3 Good point. It does seem related and we could repurpose parts of that munger. As part of this issue, it seems like we could tackle https://github.com/kubernetes/kubernetes/issues/30034 as well. We could do the labeling and the pings. The close-stale-pr munger has the duration between pings set to a very large number I think (30 days?). It would make sense to parameterize that and decide on the right duration till the first ping and between successive pings.

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1631
