### ISSUE TITLE
Dynamic weights of backends

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#144]
Create a sidecar container that runs in the same pod as your backend and reports it's qps to a service annotation. The servicelb will lookup these service annotations and update the weights of the backends by writing to the haproxy socket (or  https://github.com/kubernetes/contrib/pull/120). The goal here is to send less traffic to backends that have historically been slow to repond (so not exactly leastconns). I expect this to help with noisy neighbors. 

@aledbf @jayunit100

**Comment by bprashanth** [comment]
Ohh you can probably just wrap this into a sidecar https://github.com/ssasso/lbwwd

**Comment by jayunit100** [comment]
cc @timothysc @rrati probably interesting to us for our scale work.

**Comment by aledbf** [comment]
>  The goal here is to send less traffic to backends that have historically been slow to repond

@bprashanth this sounds interesting but I see one potential problem with something like this.
For instance if some application has just 3 urls, 2 are GET and 1 POST. The GET requests return in less than 1 second and the POST requires at least 5 seconds

*Then:*
- adjusting the weight without "context" (GET vs POST) is not "correct"
- is not possible to get stats per request using the haproxy socket (this requires parsing the haproxy log)
- what's the definition of noisy neighbors? 

Maybe using the stats about the las 1024 can help to change the weight (and it's available in the socket stats)

<img width="208" alt="captura de pantalla 2015-10-06 a las 11 49 43 p m" src="https://cloud.githubusercontent.com/assets/161571/10328003/91bcfc38-6c8d-11e5-908d-d739e7f559f8.png">

**Comment by bprashanth** [comment]
> what's the definition of noisy neighbors?

If you have 2 machines with 3 containers, 2 of which are nginx backends and 1 is something heavy, say a database, and the database machine start hammering cpu, how do I send all requests to the other nginx backend? 

> Maybe using the stats about the las 1024 can help to change the weight (and it's available in the socket stats)

This is actually 2 problems: 
* how do we figure out the load/response time/stats of a given backend?
* how do we tell haproxy about this, so it can adjust the weights?

If we solve (2) we can iterate on 1. I haven't completely understood how haproxy modifies the rr weights yet. From the docs:
```
This is the smoothest and fairest algorithm when the server's
processing time remains equally distributed. This algorithm
is dynamic, which means that server weights may be adjusted
on the fly for slow starts for instance.
```
have you had a chance to play with that?

**Comment by aledbf** [comment]
> how do we figure out the load/response time/stats of a given backend?

Parsing the stats from haproxy (it returns a csv). For example: `curl http://<service-loadbalancer-ip>:1936/;csv` 
http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#9.1
```
 58. qtime [..BS]: the average queue time in ms over the 1024 last requests
 59. ctime [..BS]: the average connect time in ms over the 1024 last requests
 60. rtime [..BS]: the average response time in ms over the 1024 last requests
     (0 for TCP)
 61. ttime [..BS]: the average total session time in ms over the 1024 last
     requests
```

This is grouped by type (frontend or backend), name (service name) and server (ip:port) so checking this is not complex

> how do we tell haproxy about this, so it can adjust the weights?

Using the haproxy socket is possible to dynamically adjust the weight http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#set%20weight
