### ISSUE TITLE
NGINX Ingress Controller - net.core.somaxconn=128

### ISSUE THREAD

**Issue by zllovesuki** [kubernetes/contrib#1457]
The setup works fine (btw thank you community :) ), however the logs is flooded with:
```
W0801 05:21:58.225140       1 utils.go:231] system net.core.somaxconn=128. Using NGINX default (511)
```

Is there any way to tune `net.core.somaxconn` or ignore the log?

**Comment by aledbf** [comment]
@zllovesuki this is the example that shows how is possible to tune net.core.somaxconn https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/sysctl/change-proc-values-rc.yaml

**Comment by zllovesuki** [comment]
@aledbf uh, that is very...."hacky." 

I would assume that there's no other way to change the values other than using a "buddy" container to modify sysctl value?

**Comment by aledbf** [comment]
> uh, that is very...."hacky."

I know :) but until something like https://github.com/kubernetes/kubernetes/pull/26057 is implemented this is the least privileged way to change sysctl settings.

> Is there any way to tune net.core.somaxconn or ignore the log?

In the next version of the ingress controller that warning appears only using `--v=3`.

**Comment by bprashanth** [comment]
> I would assume that there's no other way to change the values other than using a "buddy" container to modify sysctl value?

Of course, run it privileged or with net=host :)
There is no better way IMO

**Comment by zllovesuki** [comment]
@aledbf For now, I commented out the corresponding line in `util.go` and recompile controller.go. Hopefully, there's a flag for verbosity soon.

**Comment by bprashanth** [comment]
Hmm, doesn't `--v=0` work (you'd add it to the args in the nginx controller yaml)? 
I agree we should reduce spammy logs in general.

**Comment by zllovesuki** [comment]
@bprashanth Disclaimer: I'm very new to the Kubernetes project, even newer to Go lang in general. Yes, I was thinking of the flag `--v`, but I was searching for such flag in the source code, and I didn't see this flag, so I assume that such flag would have no effect.

**Comment by bprashanth** [comment]
```
$ ./nginx-ingress-controller --help 2>&1 | grep "log level"
      --v=0: log level for V logs
```

**Comment by bprashanth** [comment]
> Disclaimer: I'm very new to the Kubernetes project, even newer to Go lang in general. 

yeah that's fine :)
It might not work, and that'd be a bug, but give it a shot. Modify the args: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/rc.yaml#L102
with
```
- --default-backend-service=foo
- --v=0
```

**Comment by zllovesuki** [comment]
Nevermind, I found the gem:

https://github.com/kubernetes/contrib/blob/1a677a237150f6617788897a21c7ea93230b0af3/ingress/vendor/github.com/golang/glog/glog.go#L401

So that's why I couldn't find the verbosity flag.

**Comment by xavierholt** [comment]
Is anyone looking at a fix for this?  It's pretty spammy at the moment, and I don't see disabling logging as a viable alternative.

I can see two possible solutions:
 - Run the "buddy script" from [aledbf's example](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/sysctl/change-proc-values-rc.yaml) once before starting nginx.  I assume that it loops to prevent the container from dying, not because these settings might change every ten seconds.  Might be awkward if it requires the container to run in privileged mode, though.
 - Check and (possibly) warn once on startup, but don't warn on [every template rewrite](https://github.com/kubernetes/contrib/blob/52beb66f1e862d5fea3802349c22b8542e1e7fe5/ingress/controllers/nginx/nginx/template.go#L68).

**Comment by aledbf** [comment]
@xavierholt this is being fixed in #1498. It will show only in `--v=3` (or higher)

**Comment by aledbf** [comment]
> Might be awkward if it requires the container to run in privileged mode, though.

Only the sidecar runs in privileged mode, not the nginx container. The reason for this is `sysctl -w`

**Comment by xavierholt** [comment]
Great, thanks!  One last question if you've got a second:  Do you know what the default log level is?

**Comment by aledbf** [comment]
@xavierholt the default is 1

**Comment by xavierholt** [comment]
Thanks so much!
