### ISSUE TITLE
Nginx controller should work with local-up-cluster

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#1459]
It's the best way to get people familiar with ingress, but currently it fails with:
```
I0801 22:40:56.415722       1 main.go:99] Using build: https://github.com/bprashanth/contrib.git - git-b195d9b
F0801 22:41:26.419623       1 main.go:128] unexpected error getting runtime information: timed out waiting for the condition
```

I *think* this is because there is no service account. It should just default to using localhost:8080, i thought the client library did this but i might be wrong. I thought `clientConfig` would default to this if nothing else worked, but obviously I'm wrong or missing an option. Can take a look when i have time to debug, but fyi @aledbf

**Comment by aledbf** [comment]
> It should just default to using localhost:8080, i thought the client library did this but i might be wrong.

I was expecting the same thing but the main contains https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/main.go#L125
which is true by default.

**Comment by bprashanth** [comment]
hmm, setting it to false works? if so it's worth adding a snippet to the readme about this
