### ISSUE TITLE
Error while generating secret json config in /tmp/secret.json

### ISSUE THREAD

**Issue by anuribs** [kubernetes/contrib#1464]
I am trying to create a service loadbalancer using "rc.yaml" file as mentioned in https://github.com/kubernetes/contrib/tree/master/service-loadbalancer whic gets successfully deployed. Further I am trying the nginx https service example mentioned in https://github.com/kubernetes/kubernetes/tree/master/examples/https-nginx. however when I do `make keys secret KEY=/tmp/nginx.key CERT=/tmp/nginx.crt SECRET=/tmp/secret.json` I get the errors:

`make_secret.go:29:2: cannot find package "k8s.io/kubernetes/pkg/api" in any of:
        /usr/lib/go/src/pkg/k8s.io/kubernetes/pkg/api (from $GOROOT)
        /root/go/src/k8s.io/kubernetes/pkg/api (from $GOPATH)
make_secret.go:34:2: cannot find package "k8s.io/kubernetes/pkg/api/install" in any of:
        /usr/lib/go/src/pkg/k8s.io/kubernetes/pkg/api/install (from $GOROOT)
        /root/go/src/k8s.io/kubernetes/pkg/api/install (from $GOPATH)
make_secret.go:30:2: cannot find package "k8s.io/kubernetes/pkg/apimachinery/registered" in any of:
        /usr/lib/go/src/pkg/k8s.io/kubernetes/pkg/apimachinery/registered (from $GOROOT)
        /root/go/src/k8s.io/kubernetes/pkg/apimachinery/registered (from $GOPATH)
make_secret.go:31:2: cannot find package "k8s.io/kubernetes/pkg/runtime" in any of:
        /usr/lib/go/src/pkg/k8s.io/kubernetes/pkg/runtime (from $GOROOT)
        /root/go/src/k8s.io/kubernetes/pkg/runtime (from $GOPATH)
make: *** [secret] Error 1`

I have installed go using binaries and my version is
`go version go1.2.1 linux/amd64`.

Does anyone know how to fix this error? I would appreciate suggestions.

**Comment by aledbf** [comment]
@anuribs you need to follow the [development](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#workflow) workflow
