### ISSUE TITLE
[ansible] Move role flannel before role docker in deploy-cluster.yml

### ISSUE THREAD

**Issue by gouyang** [kubernetes/contrib#1483]
This is a real problem I met during testing.
Steps to reproduce the problem:
- There are two host A and B, inventory file looks like on host A.
  
  ```
  
  [masters]
  host-A
  
  [etcd]
  host-A
  
  [nodes]
  host-A
  host-B
  ```
- Run `setup.sh` on host A, the cluster is up.
- After some time, Host A is down and I can use host B only.
- The inventory on host B looks like

```
[masters]
host-B

[etcd]
host-B

[nodes]
host-B
```
- Make some changes to /etc/sysconfig/docker or /etc/sysconfig/docker-network
- Run `setup.sh` on host B, It failed at 

```
RUNNING HANDLER [docker : docker fix start on btrfs] ***************************
skipping: [dell-per610-004.abc.com]

RUNNING HANDLER [docker : docker start service] ********************************
fatal: [dell-per610-004.abc.com]: FAILED! => {"changed": false, "failed": true, "msg": "A dependency job for docker.service failed. See 'journalctl -xe' for details.\n"}
```

It failed because the docker dependency service flanneld could not be started as the flanneld cannot reach the old etcd server host-A.

If move role flannel before role docker, the configure will be overwritten to host-B and the playbook will not exit.

**Comment by eparis** [comment]
Did you mean to say `will NOT exit` ? Is that a good thing?

**Comment by gouyang** [comment]
> Did you mean to say will NOT exit ? Is that a good thing?

Yes，I mean `will NOT exit`. 
It currently failed on this situation, by moving role flannel before role docker and all steps are PASS, isn't it good?

**Comment by ingvagabund** [comment]
The docker must be started before flannel (otherwise you will not be able to deploy containerized flannel/etcd). 

What does it mean the flannel can not reach the old etcd server host-A? If you loose host-A with etcd, you need to reconfigure flannel to use etcd from host-B. Which in this special scenario can lead to running the flannel role first, then docker. However, in general, docker needs to be run first.

Etcd keeps track of flannel's subnets so it is possible all the subnets get lost and the new etcd has just the initial configuration. Not sure how flannel deals with this situation. I would suspect it will create new subnets. In that case you need to restart the docker daemons on all nodes right after that.

**Comment by gouyang** [comment]
> The docker must be started before flannel (otherwise you will not be able to deploy containerized flannel/etcd).
> 
In this case, seems docker must be started before flannel, but it should not run flannel role as it's containerized. It's not a block to move flannel before docker.

> What does it mean the flannel can not reach the old etcd server host-A? If you loose host-A with etcd, you need to reconfigure flannel to use etcd from host-B. Which in this special scenario can lead to running the flannel role first, then docker. However, in general, docker needs to be run first.
> 

I just describe a real problem I have met, I can reconfigure flannel and get it work.
But isn't it better to let the ansible to do it?

In fact, docker cannot be started if flannel cannot be started. So It seems let flannel run first is more general.

> Etcd keeps track of flannel's subnets so it is possible all the subnets get lost and the new etcd has just the initial configuration. Not sure how flannel deals with this situation. I would suspect it will create new subnets. In that case you need to restart the docker daemons on all nodes right after that.
