### ISSUE TITLE
Do not require release-note labels for test or tools PRs.

### ISSUE THREAD

**Issue by timstclair** [kubernetes/contrib#1488]
Changes to certain files / directories almost never require release-notes. If a PR only touches those files, it should not require the release-note label. Candidate files include:
- `test/**`
- `**/*_test.go`
- `hack/**`
- `examples/**`

**Comment by bgrant0607** [comment]
@grodrigues3 Is this addressed by #1930?

**Comment by grodrigues3** [comment]
No, this is not addressed by that #1930 .  I can open a new PR that adds the "release-note-none" label to PRs that only modify code in those directories.
