### ISSUE TITLE
Blunderbuss should pick owners for top-level directory additions

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1491]
When directory additions are made to the top-level of the repository, blunderbuss does not make assignments, or find owners.
Example: no assignees for #1343, #1189, #892, #841

**Comment by eparis** [comment]
So add an OWNERS at the top level...

**Comment by eparis** [comment]
(just don't put me in the list  :))

**Comment by foxish** [comment]
@eparis We do have a [top-level OWNERS file](https://github.com/kubernetes/contrib/commit/c3e5f67b871c9071a8739eddf69024539182f9a6).

**Comment by eparis** [comment]
son of a...   ok, i'll debug this.

**Comment by eparis** [comment]
please review #1493 to fix this.
