### ISSUE TITLE
nginx-ingress-controller: the server does not allow access to the requested resource

### ISSUE THREAD

**Issue by lendico-dmitry-dzifuta** [kubernetes/contrib#1504]
I'm trying to run nginx-ingress-controller from rc-default.yaml. Doing it asis causes the following error:
`I0810 15:56:28.267295       1 main.go:99] Using build: https://github.com/bprashanth/contrib.git - git-b195d9b F0810 15:56:28.353709       1 main.go:128] unexpected error getting runtime information: the server does not allow access to the requested resource (get nodes xxx)`

Environment is kubernetes cluster. Default service account has necessary permissions, so API should be accessible.

 Any ideas why this happens?

**Comment by aledbf** [comment]
@lendico-dmitry-dzifuta please use `--v=100` to check the response from the api server

**Comment by lendico-dmitry-dzifuta** [comment]
@aledbf my investigation showed the following - api server was rejecting (with forbidden) GET request to node resource. I'm using ABAC authorisation mode with the following line for the service account:
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "system:serviceaccount:dev:default",         "namespace": "dev",           "resource": "*",          "apiGroup": "*"}}

Change of the namespace dev --> * resolved the issue. Would be helpful to know the reason of this behaviour. Plus this violates namespace isolation. It would be also useful to have more logging in case of rejection - right now it's just forbidden statement, which is not helpful.

I probably should move the issue to different repo now.

**Comment by aledbf** [comment]
@lendico-dmitry-dzifuta please open an issue in the main kubernetes repo

**Comment by bprashanth** [comment]
@lendico-dmitry-dzifuta this doesn't sound related to ingress per se, please open an issue on https://github.com/kubernetes/kubernetes/issues/new so the right team gets notified
