### ISSUE TITLE
[mungegithub] Set up an E2E test for the bot

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1516]
With the right use of fakes and mocks, we should be able to setup a comprehensive e2e test for the bot, so that we can make changes more confidently. This should go hand in hand with the canary style of deployment, and a standard deployment plan for the submit-queue.

**Comment by foxish** [comment]
We should probably move to the dedicated kubernetes/pr-bot repository first, before we do this.

**Comment by apelisse** [comment]
Yes, we could improve that, it would be very sweet.

**Comment by foxish** [comment]
This is really hard and I question whether it is worth doing considering how reliant it is on github's API.
