### ISSUE TITLE
Some presubmit test jobs are taking more than 30 minutes

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/contrib#1522]
The difference between taking 38 minutes and 28 minutes is more than 15 merges per day.

**Comment by lavalamp** [comment]
@ixdy @spxtr

**Comment by spxtr** [comment]
`kubernetes-pull-build-test-e2e-gce` looks like it's averaging 35-40 minutes. `kubernetes-pull-test-unit-integration` is 30-35 minutes. `kubernetes-pull-verify-all` is about 30 minutes, and `node-pull-build-e2e-test` is about 20 minutes.

**Comment by philips** [comment]
For others reading this issue and not familiar the tests @spxtr is talking about live here: https://github.com/kubernetes/test-infra/search?utf8=%E2%9C%93&q=kubernetes-pull-build-test-e2e-gce

**Comment by spxtr** [comment]
I added a handful of `n1-standard-16`s to the fleet of PR builders. If they're more than a few minutes faster on average then we can consider switching the rest over.

**Comment by spxtr** [comment]
Unfortunately, the E2E tests won't get much faster with a faster machine.

**Comment by ixdy** [comment]
For fun, I took at which e2e tests were taking the longest.

There are a few Dynamic provisioning tests taking ~4m. Which led me to this [lovely hack](https://github.com/kubernetes/kubernetes/blob/bb5d562f37ab029d2b562e23bd23e906ee099a45/test/e2e/volume_provisioning.go#L81-L95), in which we sleep for 3m.

I'm guessing there are lots of nasty sleeps like this lurking in our tests.

**Comment by lavalamp** [comment]
e2e tests run in parallel, right? Could we add a node to the cluster they
start up?

**Comment by ixdy** [comment]
We run up to [25 tests in parallel right now](https://github.com/kubernetes/kubernetes/blob/548780f05a7c7e60c0024cc8e7484b87b47b77c3/hack/ginkgo-e2e.sh#L36-L40). There are around 25-30 e2e tests in PR Jenkins which take a minute or longer.

**Comment by ixdy** [comment]
On the "slow e2e tests" front, I just learned about this neat view in testgrid: https://k8s-testgrid.appspot.com/google-gce#gce&width=5&graph-metrics=test-duration-minutes

Things I immediately notice:
* `[k8s.io] V1Job should fail a job` is very spiky, ranging between 1-11m on passing builds
* `[k8s.io] Job should fail a job` is similarly bad
* `[k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner should create and delete persistent volumes` alternates between 3m and 12m
* `[k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner Alpha should create and delete alpha persistent volumes` was recently introduced and suffers from the same problem as the previous test

**Comment by ixdy** [comment]
@jsafrane @soltysh anything we can do about these slow tests?

**Comment by nikhiljindal** [comment]
cc @saad-ali for the dynamic provisioner tests

**Comment by saad-ali** [comment]
I'm fine with moving the Dynamic provisioning tests to the slow suite. We already have the `Pod disk` tests their because attach/detach can take multiple minutes to complete. CC @jsafrane

**Comment by soltysh** [comment]
@ixdy sorry, I was on PTO for the last two weeks, I'll see what can be done with the job ones.

**Comment by spxtr** [comment]
Even with the slowest tests removed we're still too slow. We tried bumping up Jenkins agents to n1-standard-16 but that didn't improve speeds by more than a minute or two since most of it is waiting for stuff to happen in another cluster.

We can try adding another node to the e2e cluster, or increasing past 25 gingkgo threads.

**Comment by lavalamp** [comment]
Why not both? 25 sounds like a number chosen for roundness and not for
optimality :)

**Comment by spxtr** [comment]
We lowered it from 30 to 25 in #25548 because some tests were flaking due to resource contention. Bumping both the number of cluster nodes and ginkgo threads should be safe.

**Comment by soltysh** [comment]
The jobs reaching 11mins problem is caused by the controller implementation. Currently when nothing is changing a job nor a pod a job controls there's no `syncJob` invocation which checks `.spec.ActiveDeadlineSeconds`. In that case only `FullControllerResyncPeriod` (which is set to 10 mins) causes the `syncJob` method being called. This explains why the tests is reaching 11 mins easily and I can easily reproduce this problem locally. 
Not sure how to approach the problem, though :disappointed: . So any suggestions are more than welcome.

**Comment by soltysh** [comment]
Jobs are fixed in https://github.com/kubernetes/kubernetes/pull/31973.

**Comment by spxtr** [comment]
I computed the average time in the last 24h of each job in minutes on passing runs only. This is pretty absurd. Oftentimes these are taking well over an hour.
```
48 pull-kubernetes-e2e-gce
35 pull-kubernetes-e2e-gke
33 pull-kubernetes-e2e-gke-gci
10 ci-kubernetes-bazel
39 pull-kubernetes-kubemark-e2e-gce
41 pull-kubernetes-verify
49 pull-kubernetes-e2e-gce-gci
42 pull-kubernetes-e2e-kops-aws
47 pull-kubernetes-e2e-gce-cri
31 pull-kubernetes-node-e2e
37 pull-kubernetes-cross
31 pull-kubernetes-node-e2e-cri
11 pull-kubernetes-bazel
47 pull-kubernetes-e2e-gce-etcd3
40 pull-kubernetes-unit
```

**Comment by fejta** [comment]
Batch solved this problem
