### ISSUE TITLE
Merge bot is merging even when Critial builds are yellow

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/contrib#153]
As an example:

PR https://github.com/kubernetes/kubernetes/pull/15014
was merged at 00:51 PST

at the same time "kubernetes-e2e-gce" was yellow

cc @lavalamp @eparis @brendandburns

**Comment by lavalamp** [comment]
We think the problem is that it doesn't double-check before merging.

**Comment by eparis** [comment]
Easy enough to fix, I guess the time between when it checks the google internal e2e and when it actually gets tested could be quite long...

**Comment by wojtek-t** [comment]
Yup - I've checked and this is exactly this case.
And yes - it's usually ~30minutes.

**Comment by eparis** [comment]
Fixed by #155

**Comment by roberthbailey** [comment]
Fixed by #155
