### ISSUE TITLE
Is --default-backend-service really required for Nginx Ingress Controller?

### ISSUE THREAD

**Issue by tyranron** [kubernetes/contrib#1535]
Why `--default-backend-service` flag for `nginx-ingress-controller` is required?
Couldn't we just serve nginx static 404 page by default if no default backend is provided?
Idea to deploy and expose one more service in cluster just for simple 404 page is pretty strange. Do I miss something?

**Comment by aledbf** [comment]
> Couldn't we just serve nginx static 404 page by default if no default backend is provided?

Yes, is possible to do that but the goal is to be compatible with the [GCE controller](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce) where is not possible to expose an internal static resource. 

Besides that using a service to expose the default error page allows custom content without the need to use a custom nginx controller image.

**Comment by tyranron** [comment]
My point is to leave flag `--default-backend-service`, but make it optional.

If we specify `--default-backend-service` everything works like just now, and we have all those benefits and compatibilities.

If we do not specify this flag, just serves default static 404 page.

So... Both the wolves have eaten much and the sheep have not been touched!

If this is OK, I'll made a pull request to implement.

**Comment by aledbf** [comment]
@tyranron honestly I prefer to keep the flag.

@bprashanth  ping

**Comment by bprashanth** [comment]
We should keep the flag, I don't mind defaulting it to something implementation specific if user doesn't supply it. We should make the defaults of a given implementation:     

1. cross platform friendly so people who switch over aren't surprised
2. more natural to people who already use that implementation, so ingress on-boarding isn't a burden

**Comment by tyranron** [comment]
@bprashanth I think I am starting to understand your goals, but still not very well.
To switch over implementation, user should explicitly specify manifest of ingress controller to be switched on, so he exactly knows what he is providing (no surprises). GCE and Nginx ingress controllers manifests have different image names, executable command name...so having slightly different flags and their behaviour is really so bad in this case? Why should we abstract exactly on flags? Is there ingress controller pod abstraction not enough?

The first thing coming in mind to satisfy 1 and 2 is just to serve exactly the same static page that is exposed by `default-backend-service`.

P.S. Sorry for making noise. I'm just trying to understand underneath ideology.

**Comment by bprashanth** [comment]
> .so having slightly different flags and their behaviour is really so bad in this case? Why should we abstract exactly on flags? Is there ingress controller pod abstraction not enough?

We should abstract on behavior, not flags. In this case the flag influences user facing behavior, which would be bad in the case where an admin has deployed 2 ingress controllers with default flag values, and the user is just going to create one ingress with `ingress.class=nginx`, test it, then graduate it to production by flipping the annotation to `ingress.class=aws/gce`. The behavior of what's returned on a particular url shouldn't change.

**Comment by tyranron** [comment]
@bprashanth @aledbf 
Ok. Sorry for late reply.

What about providing some "magic" value of `--default-backend-service` arg and not making it default?
For example: `--default-backend-service=:static`.

**Comment by tyranron** [comment]
@bprashanth @aledbf any suggestions?

**Comment by opstacloud** [comment]
Sincerely, I have agree with @tyranron.

**Comment by tyranron** [comment]
@aledbf ping

Should we move this issue to new repo?

**Comment by tyranron** [comment]
@KristianWindsor you may. It's [optional](https://kubernetes.github.io/ingress-nginx/user-guide/cli-arguments/) since 0.20.0.

**Comment by chencheng696** [comment]
i have the issue when create pod nginx-ingress-controller, the "kubectl logs " shows :  "F0401 08:46:56.430858       8 main.go:72] Please specify --default-backend-service"  

actually, i have deoloy the default-backend-service  

anyone knows how to debug it ? thanks so much

**Comment by tyranron** [comment]
@chencheng696 check if correct version of Docker image is used, or check carefully other flags and settings in ConfigMap whether they require default backend service mandatory.
