### ISSUE TITLE
Potential race: lgtm_handler and lgtm_after_commit

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1546]
Before deploying https://github.com/kubernetes/contrib/pull/1539, I want to ensure that we have no races with the bot fighting against itself and exhausting quota.

It appears that it could happen in the following situation:
* Someone comments `/lgtm`.
* The bot adds the `lgtm` label.
* The author pushes new commits.

What happens:
* The lgtm_handler munger continues to see the comment and tries to apply the label. 
* The lgtm_after_commit munger tries to remove the lgtm label.

cc @eparis @apelisse @lavalamp

**Comment by foxish** [comment]
One potential solution is to use the `do-not-merge` label instead of removing LGTM, which was the way this problem was solved in case of the release notes race https://github.com/kubernetes/contrib/pull/1518. I don't know if that is the best way to solve it though.

**Comment by hongchaodeng** [comment]
Hi @foxish 
Is each munger running concurrently?

**Comment by lavalamp** [comment]
Not concurrently, one after the other, but in an arbitrary order.

**Comment by foxish** [comment]
I think we could get out of removing labels with the bot, and just stick to adding labels. That would let us write mungers without having to worry about other mungers. @lavalamp Would that make sense?

**Comment by lavalamp** [comment]
I don't think that helps in this case-- if you switch to adding "do not
merge" then you'll need to give humans a way to remove "do not merge" via
email and you'll have the same problem.

You could: add an "OK, applying LGTM" message, and ignore "/lgtm" comments
that are followed by a comment like that.

more controversially, you could just edit the message when you take action,
e.g. "/lgtm" -> "!lgtm" or something like that.

**Comment by foxish** [comment]
@lavalamp Ah, the argument makes sense. Here is an alternative that might work as well:
We make the lgtm-after-commit munger comment on the PR with:

```
/lgtm cancel # reason(s)
```

That way, when the lgtm-handler runs, it sees that lgtm was removed.

**Comment by lavalamp** [comment]
That SGTM. (It should also directly remove the label, to avoid the label
sticking around for an extra loop)

**Comment by hongchaodeng** [comment]
> The lgtm_handler munger continues to see the comment and tries to apply the label.

This isn't true. lgtm_handler munger won't see any comment before latest commit.

**Comment by foxish** [comment]
@hongchaodeng The code is using [LastModifiedTime(...)](https://github.com/kubernetes/contrib/blob/aaec42bbee650c5714faa47b70d63be450cd884d/mungegithub/github/github.go#L573), which is looking at the time the commit itself was made, which could be older than the last push made to the PR.

**Comment by eparis** [comment]
I don't think the order is 'arbitrary'. I thought mungers run in the order specified on the command line. But this isn't particularly important.

**Comment by eparis** [comment]
agree we need a `/lgtm cancel` or something like that.

I'm also fine with the bot editing the original `/lgtm` comment to indicate it has been dealt with....

**Comment by lavalamp** [comment]
We shouldn't make a certain order required, that's bound to bite some poor
human in the future.
