### ISSUE TITLE
retest-not-required-docs-only should count images as docs

### ISSUE THREAD

**Issue by timstclair** [kubernetes/contrib#1566]
E.g. the label was removed from [this PR](https://github.com/kubernetes/kubernetes/pull/30840) since it includes several png's referenced in the docs.

**Comment by apelisse** [comment]
Yes, as you understood, you can't fight with "retest-not-required-docs-only". This label is meant to be automatic, and you should use retest-not-required for manual intervention (though I'll probably improve that in the near future).

I'll add the png extension to the list of ignored files. Any other extensions in mind?

**Comment by timstclair** [comment]
Also in our docs directory: `.svg`, `.dia`, `.yaml` (questionable about whether this should be tested)

**Comment by eparis** [comment]
Don't .yaml files typically all get loaded/validated in a test? Or does that only happen in examples?

Agreed on .svg and .dia

**Comment by eparis** [comment]
re-openning, the PV got .png, but we can leave this issue open for .svg and .dia
