### ISSUE TITLE
"tests pending" checks are buggy

### ISSUE THREAD

**Issue by ixdy** [kubernetes/contrib#1583]
Two separate issues that I've noticed the munger getting confused by:
- tests were broken at some point a few days ago. [I request a re-test of just that particular build](https://github.com/kubernetes/kubernetes/pull/30551#issuecomment-241163328), and then the munger [thinks tests have been pending for over 24h](https://github.com/kubernetes/kubernetes/pull/30551#issuecomment-241164346).
- someone LGTM's a PR before all tests have finished running for the first time. The munger will comment "
  pr builder appears to be missing, activating due to 'lgtm' label." and retest, which may cause some builds to needlessly rerun.

cc @lavalamp @eparis @apelisse

**Comment by apelisse** [comment]
cc @foxish

**Comment by ixdy** [comment]
I think both of these issues still exist, but mungegithub is getting deprecated, so :shrug:

/close
