### ISSUE TITLE
Security and API access

### ISSUE THREAD

**Issue by wernight** [kubernetes/contrib#1603]
One part I didn't fully understand after using a Nginx Ingress Controller, is what part of the Kubernetes API is actually exposed without authentication from within the cluster.

From http://kubernetes.io/docs/user-guide/accessing-the-cluster/#programmatic-access-to-the-api is looks like a token is always required.

However the Nginx Ingress Controller is visibly capable of at least reading the list of Ingress rules set up, and probably also secrets, and that without token. How is that possible?

**Comment by aledbf** [comment]
@wernight please check https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/main.go#L92 and this comment that describes the rules https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L1183

**Comment by wernight** [comment]
Thanks I saw it uses the Go API. Isn't it equivalent to the REST API? My main worry is that without having given any authentication, just running some process, that process had access to my TLS private key.

**Comment by aledbf** [comment]
> I don't understand how Nginx Ingress doesn't get it.

If you follow the method `factory.go#L1183` one of the steps is 
```
The env vars KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT are set, and the file /var/run/secrets/kubernetes.io/serviceaccount/token
```

the file contains the required token to access the api server (if you have service accounts enabled that file exists in all the pods)

>  Isn't it equivalent to the REST API?

If you change the log level `--v=5` you will see the bearer token being sent in each request.

**Comment by wernight** [comment]
Wow! Thanks
