### ISSUE TITLE
Nginx Ingress Controller performance

### ISSUE THREAD

**Issue by asifhj** [kubernetes/contrib#1604]
Hey Guys -

Observed significant difference in performance when we access the service from nginx-ingress-controller.

Accessing service via NodePort is faster than accessing via nginx-ingress-controller

nginx-ingress-controller:0.8.2

Kubernetes version

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

Ubuntu 14.04

Any pointer to look into ?

**Comment by aledbf** [comment]
@asifhj can you provide more information about your cluster and how you are testing the controller? (like #1482)

**Comment by asifhj** [comment]
@aledbf  I am hitting nginx-ingress-controller through which it send pass the request to kubernetes service. My setup kubernetes setup is not cloud. I tried 
[I tried this link too to change the proc values. I did't help](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/sysctl/change-proc-values-rc.yaml)

**Comment by aledbf** [comment]
> I tried this link too to change the proc values. It did't help

@asifhj if you are not running in the cloud the performance of the ingress controller can be affected by the configuration of the nodes (distribution version, updated, kernel version, docker/rkt version, sysctl tuning, fs, etc.).
(most of this things are outside the scope of the ingress controller)

Please post more information about the performance you see in the nginx ingress controller using tools like `wrk` or `vegeta` from inside (another pod) and outside the cluster

**Comment by bprashanth** [comment]
Please report with the requested information and I'll reopen
