### ISSUE TITLE
Bot To Handle Approvers AND Reviewers In Owners File

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/contrib#1605]
Here's the proposed workflow as described by @bgrant0607  

Proposed workflow:
a reviewer, who isn't necessarily an approver, would be assigned
the reviewer would eventually type "LGTM" into a comment
the author would (often) squash commits and/or rebase
the reviewer would then type I approve if they were an approver, or would notify an approver to do that if they were not; the author could self-approve if they were an approver

I believe @hongchaodeng is working on tooling to automatically generate an owners file with two components, an Reviewers List and an Owners List. 

We will need to implement our own ACLs using the bot to verify that only approvers can make the final "approvals".

@apelisse @foxish let me know if this sounds reasonable, and if so, I'll start working on it.

**Comment by bgrant0607** [comment]
@grodrigues3 

`/lgtm` now

reviewers aka assignees

owners aka approvers

see also #1429

cc @hongchaodeng @philips @apelisse @foxish

**Comment by bgrant0607** [comment]
and the existing issue is #1389

**Comment by hongchaodeng** [comment]
I do have the reviews list generated. It appends to existing OWNERS or creates new OWNERS with a separate section called "reviewers":
```
diff --git a/build/OWNERS b/build/OWNERS
index acc600a..e10e94b 100644
--- a/build/OWNERS
+++ b/build/OWNERS
@@ -3,3 +3,9 @@ assignees:
   - ixdy
   - lavalamp
   - zmerlynn
+
+reviewers:
+ - thockin
+ - mikedanese
+ - luxas
+ - andyzheng0831
```
Even though the program is ready and file is generated, I'm not sure about the current state yet.. Maybe I should also merge the "assignees" and "reviewers".

The other point I'm confused is about approver. Can someone help create approver list? Once we have that we can continue on #1429 to implement the approval system.

**Comment by grodrigues3** [comment]
@hongchaodeng yes, reviewers and assignees are same thing and therefore can be merged.   Similarly, Owners and Approvers are the same thing.   Reviewers should be a pretty broad pool of people who have some minimum level of familiarity with the code (e.g have touched a related file).   The approvers list may be harder to generate automatically, but perhaps we can figure out how to generate that at the community meeting tomorrow.

**Comment by calebamiles** [comment]
Just to sync up here while I'm updating  https://github.com/kubernetes/kubernetes/pull/31567. Are we OK with promoting the current list of GitHub handles in the existing `OWNERS` files to fall under an `approvers` key. New potential reviewers identified by the tooling that @hongchaodeng has been working on will listed under a `reviewers` key. My understanding of the discussion from the [contrib-x meeting on 25 August](https://docs.google.com/a/google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit?usp=sharing) was that we are going to address automatic promotion of `reviewers` to `approvers` in a separate track of work. Does that all sound correct to you @grodrigues3, @bgrant0607, @apelisse and @hongchaodeng?

**Comment by grodrigues3** [comment]
yeah, sounds right to me.  we can address automatic promotion of reviewers into approvers later.  and we can initially use the existing owners as approvers.
