### ISSUE TITLE
munger: add "what is it doing right now" to dashboard

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/contrib#163]
I'm getting a lot of questions about what the merge bot is doing. I think if we could make that inner goroutine publish a status, that would help a lot.

@eparis any time to make this happen? :)

**Comment by eparis** [comment]
Is there a way to make 'glog' write to a ring buffer we could put on the web page?

Or an I going to have to write a glog wrapper of some sort?

**Comment by wojtek-t** [comment]
In the previous version there were logs like this:
"Considering PR xxxxx for merging"
Even having sth like that will be helpful.

Although for me it seems that there are moments that it can potentially be able to merge (it reports e2e tests are green and there are PRs that could potentially be merge) and is not doing anything.

**Comment by lavalamp** [comment]
I think the necessary info isn't written to glog right now anyway...

I did my own message ring buffer for the previous version :)

**Comment by eparis** [comment]
Right now, I think it's locked because k8s-bot locked, and we never time out if k8s-bot isn't doing it's job.  So only k8s-bot is running, it's going to need kicked   :-(

**Comment by lavalamp** [comment]
Other things to add would be a notification when it runs out of quota, and also when it isn't able to get mergability info.

**Comment by eparis** [comment]
I added this 'history' which tells us what it's doing on the web site.  Closing.

**Comment by lavalamp** [comment]
Yeah, thanks for that!
