### ISSUE TITLE
Document the Commands that the Bot Accepts

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/contrib#1643]
We need a comprehensive list of the commands that humans can use to communicate with the bot.  (e.g /lgtm /lgtm-cancel etc...)

**Comment by eparis** [comment]
does it belong somewhere under: http://kubernetes.submit-queue.k8s.io/#/info (I vote yes)

however that get awkward if we start using a similar syntax to trigger k8s-bot instead of k8s-merge-robot...
