### ISSUE TITLE
Nginx Ingress LivenessProbe fails

### ISSUE THREAD

**Issue by pdoreau** [kubernetes/contrib#1652]
Hello. I'm trying the [nginx ingress http example](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#http).

The livenessProbe fails : 
`Liveness probe failed: Get http://...:10254/healthz: dial tcp ....:10254: getsockopt: connection refused`

Using nmap on the pod I can't see any usage of this port (nmap).

**Comment by aledbf** [comment]
@pdoreau please check you are using the image version `0.8.3`

**Comment by pdoreau** [comment]
@aledbf I wasn't because I just copied the [the example (0.8.2)](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/default/rc-default.yaml#L19)
It's looks fine with 0.8.3
Is the 0.8.3 version stable ? Should the examples be updated ?

**Comment by aledbf** [comment]
> Is the 0.8.3 version stable ?

Yes, is the latest version.

> Should the examples be updated ?

Already being done in #1653


Apologies for the inconsistency in the examples.

**Comment by pdoreau** [comment]
No prob thanks for the fast answers
