### ISSUE TITLE
[ansible] kube-dns container absent and kibana-logging CrashLoopBackOff

### ISSUE THREAD

**Issue by jnorment-q2** [kubernetes/contrib#1671]
Traced this to here:

contrib/ansible/roles/kubernetes-addons/templates/dns/skydns-rc.yaml.j2

When attempting to create the rc from the file, I got these two errors:

error validating "skydns-rc.yaml": error validating data: [found invalid field successThreshold for v1.Probe, found invalid field failureThreshold for v1.Probe]; if you choose to ignore these errors, turn validation off with --validate=false

I think this resulted in the silent failure of the kube-dns RC, but the success of the kube-dns svc.

After deployment, the behavior observed was that every service resolved to the same ( random? ) IP. ( And that there was no container for kube-dns running. )

**Comment by ingvagabund** [comment]
Hi @jnorment-q2 what version of kubernetes are you running on?

**Comment by jnorment-q2** [comment]
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ec7364b6e3b155e78086018aa644057edbe196e5", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ec7364b6e3b155e78086018aa644057edbe196e5", GitTreeState:"clean"}

( This is the version for atomic host ):
● centos-atomic-host:centos-atomic-host/7/x86_64/standard
       Version: 7.20160818 (2016-08-18 14:28:07)

**Comment by ingvagabund** [comment]
That looks very similar to https://github.com/kubernetes/contrib/issues/886#issuecomment-216741889. Can you update to newer version of kubernetes?

**Comment by jnorment-q2** [comment]
I'm not sure that it does. Commenting out those lines fixed the issue for me, whereas it did not fix the issue for the OP in that thread.

Also, I'm already running the minor version of kubernetes that was recommended in that thread.

... and it is not an option to upgrade to a newer version of kubernetes with Atomic Host.
