### ISSUE TITLE
K8S removes LGTM label without a reason

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1673]
See: https://github.com/kubernetes/contrib/pull/1670

**Comment by lavalamp** [comment]
Bot seems to not compare time between a `/lgtm cancel` and a manual label application? @hongchaodeng or @apelisse can one of you take a look?

**Comment by apelisse** [comment]
I'll take a look at it.

**Comment by apelisse** [comment]
Yeah, it doesn't check when the lgtm label was added. It will just remove it as long as the last comment is /lgtm cancel. The easy work-around if it happens to you is to do /lgtm ...

Can you have a look @hongchaodeng ?

**Comment by foxish** [comment]
We fixed this. Closing.
