### ISSUE TITLE
[nginx-ingress-controller] Rate limiting requests to a specific path/requestor ip

### ISSUE THREAD

**Issue by mumoshu** [kubernetes/contrib#1677]
Normally we use something like `limit_req` and `limit_req_zone` for Nginx to rate limit requests to specific path for an requestor ip, so that we can rate limit access to specific path e.g. `/api` not to fire up or web servers until they scale out.

Is there any recommended way to deal with an use-case like this with today's nginx-ingress-controller?

**Comment by aledbf** [comment]
@mumoshu please check https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md#rate-limiting

**Comment by mumoshu** [comment]
@aledbf Ah, I was too dumb to notice that it is already documented. Thanks a lot for your great work 🙇

**Comment by jackzampolin** [comment]
the link is dead, long live the link: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#rate-limiting

**Comment by SharpEdgeMarshall** [comment]
Link is dead again:
https://github.com/kubernetes/ingress-nginx/blob/master/configuration.md#rate-limiting

**Comment by taylorshaulis** [comment]
Link is dead again:
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/annotations.md#rate-limiting

**Comment by LucasR93** [comment]
Again:
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#rate-limiting

**Comment by aledbf** [comment]
Or use the new docs site https://kubernetes.github.io/ingress-nginx/
