### ISSUE TITLE
starting etcd service fails

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [kubernetes/contrib#1682]
In `contrib/ansible`, using `deploy-cluster.sh` to setup a cluster of 3 Ubuntu 16.04.1 servers (virtual machines provisioned on hyper-v), the playbook fails at role `etcd`, at `etcd-start.yml`, at task `Enable etcd`.

The error message returned by ansible is:
```
fatal: [docker1]: FAILED! => {"changed": false, "failed": true, \
"msg": "Error when trying to enable etcd: rc=1 Failed to execute operation: No such file or directory\n"}
```

If any more info is required, pls let me know.

**Comment by valentin-krasontovitsch** [comment]
This is connected to Ubuntu 16.4 using systemd instead of init, I suppose. A workaround that made the playbook proceed was to use the `Debian` task in `etcd-configure.yml`, to be precise:

- In `roles/etcd/tasks/etcd-configure.yml`, 
- in task `Write etcd systemd unit file for Debian` 
- with condition `when: ansible_distribution == "Debian"`, 
- change the condition to `when: ansible_distribution == "Debian" or ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16" )`

probably can skip the `Create upstart script` task in `etcd-install-github-release.yml` for Ubuntu >= 15, and should rename the tasks accordingly.

... but etcd was still not recognized as a service O_o playbook passes, but running `service etcd start` on the machine returns the error message `etcd: unrecognized service`

Going to install with apt-get instead, version 2.2.5 is in repos, and use the config provided by ansible and see where that gets me.

**Comment by ingvagabund** [comment]
Thanks @valentin-krasontovitsch for looking into it

**Comment by ingvagabund** [comment]
With vagrant and xenial box (Ubuntu 16.04 LTS) [1] I hit the same error.

[1] https://atlas.hashicorp.com/yk0/boxes/ubuntu-xenial

**Comment by ingvagabund** [comment]
I got to the point of running ``systemctl start etcd`` working (deploying etcd.service file). Just, the service failed to start.

**Comment by ingvagabund** [comment]
Ok, got it running. Once need to create ``etcd`` user and ``/var/lib/etcd`` directory (as is specified in ``etcd.service`` and ``etcd.conf`` files). After that, etcd service is started.

**Comment by valentin-krasontovitsch** [comment]
Totally checks out, thanks, @ingvagabund! Ran it like you with Vagrant, worked fine, until the playbook tries to download `kubernetes-master`, as hinted at in #1697... does that need a new issue?

**Comment by ingvagabund** [comment]
Already working on kubernetes-master. Almost done.

**Comment by ingvagabund** [comment]
here https://github.com/kubernetes/contrib/pull/1700

**Comment by valentin-krasontovitsch** [comment]
ok, cool : )
