### ISSUE TITLE
Credentials for gcr.io container image repository

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [kubernetes/contrib#1691]
Trying to deploy k8s using the ansible setups in contrib/ansible, I have gotten quite far, only to notice that the proxy settings ain't working for docker (might make own issue), and that I can't pull any images from `gcr.io/google_containers/` - apparently one always need to login / authenticate oneself? If so, is this mentioned anywhere in the docs of kubernets/contrib?

For context, I'm deploying on Ubuntu 16.4.1 virtual machines running on top of hyper-v, and sitting behind a proxy.

**Comment by ingvagabund** [comment]
No need to authenticate. If you install fresh docker on Ubuntu (without ansible), do you hit the same problem?

**Comment by valentin-krasontovitsch** [comment]
Hm, clean install of unbuntu 16.4.1 and docker, setup proxy, and voila, it worked O_o
Going to go back and investigate more...

**Comment by valentin-krasontovitsch** [comment]
hm yeah the machines I originally ran into trouble with are gone now, alas, but I tried it out on another one, and it just works. Seems to just have been a problem with docker and proxy settings. Never mind, and thanks for the pointer, @ingvagabund!

**Comment by ingvagabund** [comment]
Happy the problem is gone, thanks for testing the playbooks on Ubuntu.
