### ISSUE TITLE
kube-apiserver service cannot open port below 1024 on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by kovvik** [kubernetes/contrib#1697]
On Ubuntu with systemd, the kube-apiserver service started by the kube user. But this user cannot open port below 1024:

 kube-apiserver[8482]: E0906 13:19:29.895480    8482 genericapiserver.go:716] Unable to listen for secure (listen tcp 0.0.0.0:443: bind: permission denied); will try again.

My workaround is to set capability on kube-apiserver binary:
`setcap 'cap_net_bind_service=+ep'  /opt/kubernetes/1.2.4/kube-apiserver`

(You cannot set capability on symlinks, so it must not be set directly on /usr/bin/kubeapiserver)

**Comment by ingvagabund** [comment]
This is intended as one can not trust binaries downloaded from non distribution rpms. You change the port to ``6443`` in this case.

I assume there is no kubernetes-* package built for Ubuntu, right? Downloading the binaries from kubernetes github repository is the only way?

**Comment by kovvik** [comment]
Yes, you are right, there are no packages for Ubuntu. I configured it to use github repo, and use 6443 port, and now it works. (after creating the etcd user and /var/lib/etcd folder with correct permissions, as mentioned here: #1682 )

**Comment by ingvagabund** [comment]
The ``443 -> 6443`` issue is described in contrib README [1]. As the default installation for kubernetes is via package manager, the port is set to ``443`` by default. Of course, one could set the port to ``6443`` by default if the ``kubernetes_source_type`` is set to ``github-release``. This affects Ubuntu and CoreOS so far (and any other distro if the source is set) . On the other hand the playbook is usually run as a part of CI or one needs to configure the global vars first.

[1] https://github.com/kubernetes/contrib/tree/master/ansible#kubernetes-source-type

**Comment by pahaz** [comment]
I also have the same issues on 16.04. 
In my opinion, we can change this behavior 
 https://github.com/kubernetes/contrib/blob/master/ansible/roles/master/tasks/apiserver-configure.yml#L9-L11 

We just need to change the 

`when: kube_source_type != "github-release" and not is_atomic and not is_coreos and not ansible_distribution == 'Ubuntu' and not ansible_distribution_major_version|int < 15`

to something like

`when: not is_atomic and not is_coreos`

But I'm not sure. Is it break some distributives or not.

@ingvagabund what do you think about this?

**Comment by pahaz** [comment]
But probably it's also wrong because the `/usr/bin/kube-apiserver` [here](https://github.com/kubernetes/contrib/blob/master/ansible/roles/master/tasks/apiserver-configure.yml#L10) may be a symlink.

It will be better to add capabilities [here](https://github.com/kubernetes/contrib/blob/master/ansible/roles/master/tasks/download_bins.yml#L29) after downloading Kubernetes binaries.

Like this:
```

- name: Add cap_net_bind_service to Kubernetes binaries
  capabilities: path={{ kube_current_release_directory }}/{{ item }} capability=cap_net_bind_service=ep state=present
  with_items:
    - "{{ kube_binaries | default([]) }}"

```
