### ISSUE TITLE
[Ansible] flannel package

### ISSUE THREAD

**Issue by elerion** [kubernetes/contrib#1703]
Hello,

I try to deploy kubernetes cluster with 1 master and 3 nodes.
All my server are on Fedora 24 4.5.7-300.

I have this error :

```
TASK [flannel : Force to use github-release when packages are not available] ***
FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname in groups['masters'] + groups['nodes']' failed. The error was: error while evaluating conditional (inventory_hostname in groups['masters'] + groups['nodes']): 'dict object' has no attribute 'nodes'\n\nThe error appears to have been in '/home/elerion/Ansible/contrib/ansible/roles/flannel/tasks/main.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Flannel\n  ^ here\n"}
```
Have you any idea ?

**Comment by ingvagabund** [comment]
Hi @elerion ,

looking at the error: ``'dict object' has no attribute 'nodes'``, looks like there is no ``[nodes]`` group in your inventory file. Can you paste the file?

At the same time you can check out inventory in the example [1] and compare it.

[1] https://github.com/kubernetes/contrib/tree/master/ansible#configure-inventory

**Comment by elerion** [comment]
@ingvagabund sorry I haven't see this detail 

thank's
