### ISSUE TITLE
Fail to build nginx controller

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#1706]
Hi,

Several weeks ago I success to build the nginx controller at k8s.io/contrib/ingress/controllers/nginx. Today I use git pull to update the source code and try to build again. This time I fail. The output is as follow:

make controller
rm -f nginx-ingress-controller
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags \
        "-s -w -X main.version=git-316e640 -X main.gitRepo=https://github.com/kubernetes/contrib.git" \
        -o nginx-ingress-controller
\# k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/certificates
../../vendor/k8s.io/kubernetes/pkg/util/certificates/csr.go:96: undefined: elliptic.P224

Thanks

**Comment by aledbf** [comment]
You need Go 1.6

**Comment by ingvagabund** [comment]
What distribution did you run the build?

**Comment by tjliupeng** [comment]
@aledbf , My go version is go1.6.3 linux/amd64.
@ingvagabund , what do you mean the distribution? Linux? My OS is CentOS Linux release 7.2.1511 (Core).

**Comment by aledbf** [comment]
@tjliupeng please check https://bugzilla.redhat.com/show_bug.cgi?id=1038683
(installing Go from https://golang.org/dl solves this issue )

**Comment by tjliupeng** [comment]
@aledbf , that works. I install go 1.7.1 and the build succeed. Thank you very much.
