### ISSUE TITLE
Remove "All rights reserved" from all the headers

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/contrib#1707]
It looks like it is applicable for contrib as well [1]. Any thoughts?

[1] https://github.com/kubernetes/kubernetes/pull/26755

**Comment by ingvagabund** [comment]
cc @thockin @zmerlynn @brendanburns @david-mcmahon

**Comment by thockin** [comment]
Yes, we should be consistent.  It has no legal significance and less words
is more better.

**Comment by ingvagabund** [comment]
This will do the trick: ``for file in $(./hack/verify-boilerplate.sh | cut -d":" -f2); do sed -i "s/ All rights reserved\././" $file; done``
