### ISSUE TITLE
[service-loadbalancer] Routed services

### ISSUE THREAD

**Issue by Philmod** [kubernetes/contrib#1709]
Hey!

Why does the service-loadbalancer automatically open routes for heapster, kube-dns:53, kubernetes-dashboard, kubernetes:443, and one for my redis service I created?
![openroutes](https://dl.dropboxusercontent.com/u/45971143/service-loadbalancer.png)

I clearly don't want to open these. Is there a way to avoid it and specify the services I want to route through service-loadbalancer?

Thanks,
Philmod

**Comment by aledbf** [comment]
> Is there a way to avoid it and specify the services I want to route through service-loadbalancer?

No. The existing implementation exports all the services. 
You can use `--namespace` to limit services in one namespace

**Comment by Philmod** [comment]
Ok, thanks.
