### ISSUE TITLE
What cause starting nginx controll failure? 

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#1715]
I build ingress nginx controller and fail to start it. env: kubernetes 1.3.2, docker 1.11.2. CentOS 7.2.1

The output of kubectl describe is:
 7m    7m      1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Created         Created container with docker id e1d3670bad8c
  7m    7m      1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Started         Started container with docker id e1d3670bad8c
  7m    7m      1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Killing         Killing container with docker id e1d3670bad8c: pod "nginx-ingress-controller-du1gp_default(ac3b025c-75a8-11e6-9cd1-00505697649c)" container "nginx-ingress-lb" is unhealthy, it will be killed and re-created.
  2m    2m      1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Created         Created container with docker id 6e71d8c77211
  2m    2m      1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Started         Started container with docker id 6e71d8c77211
  1m    1m      1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Started         (events with common reason combined)
  1m    1m      1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Created         (events with common reason combined)
  17m   1m      10      {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Pulled          Container image "nginx-ingress:0.8.3" already present on machine
  1m    1m      1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Killing         Killing container with docker id 6e71d8c77211: pod "nginx-ingress-controller-du1gp_default(ac3b025c-75a8-11e6-9cd1-00505697649c)" container "nginx-ingress-lb" is unhealthy, it will be killed and re-created.
  16m   40s     12      {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Warning Unhealthy       Liveness probe failed: Get http://172.77.63.3:10249/healthz: dial tcp 172.77.63.3:10249: getsockopt: connection refused
  37s   37s     1       {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Normal  Killing         (events with common reason combined)
  7m    8s      27      {kubelet 16.186.74.94}                                          Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "nginx-ingress-lb" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=nginx-ingress-lb pod=nginx-ingress-controller-du1gp_default(ac3b025c-75a8-11e6-9cd1-00505697649c)"

  12m   8s      47      {kubelet 16.186.74.94}  spec.containers{nginx-ingress-lb}       Warning BackOff Back-off restarting failed docker container

The output of kubectl logs is:
2016/09/08 09:52:38 [debug] 22#22: epoll add event: fd:16 op:1 ev:00002001
2016/09/08 09:52:38 [debug] 23#23: epoll add event: fd:17 op:1 ev:00002001
2016/09/08 09:52:38 [debug] 24#24: epoll add event: fd:18 op:1 ev:00002001
2016/09/08 09:52:38 [debug] 22#22: epoll add event: fd:14 op:1 ev:00002001
2016/09/08 09:52:38 [debug] 22#22: epoll add event: fd:15 op:1 ev:00002001
2016/09/08 09:52:38 [debug] 22#22: epoll add event: fd:20 op:1 ev:00002001
2016/09/08 09:52:38 [debug] 25#25: epoll add event: fd:19 op:1 ev:00002001
2016/09/08 09:52:47 [debug] 24#24: epoll add event: fd:14 op:1 ev:00002001
2016/09/08 09:52:47 [debug] 22#22: epoll del event: fd:14 op:2 ev:00000000

**Comment by micheleorsi** [comment]
How is your deployment file?
Which version are you building?
 
Logs saying that kubernetes is killing the pod due to liveness probe failure, so probably the initialDelaySeconds of livenessProbe is too small or the /healthz is really down for too much time!

**Comment by aledbf** [comment]
@tjliupeng please update the healthz port to 10254

**Comment by Yancey1989** [comment]
Hi @tjliupeng, I have the same problem, and i wanner how can i determine the right port, because the early version of nginx-ingress-controller, the health port is 10249.

**Comment by tjliupeng** [comment]
@aledbf , why should I update the port to 10254? In nginx-ingress.yaml, the livenessProbe setting is:

```
name: nginx-ingress-lb
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10249
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
```

**Comment by tjliupeng** [comment]
Oh, I just check the code, in main.go:
`healthPort = 10254`
