### ISSUE TITLE
[nginx ingress controller] possibility to specify nginx properties different for each ingress

### ISSUE THREAD

**Issue by micheleorsi** [kubernetes/contrib#1717]
Hello,
the problem we are facing is that adding more and more different applications (one for each namespace) in our kubernetes cluster brings different needs in terms of configuration (timeouts for example).

I am already aware of the --watch-namespace property and I followed this discussion #847, but I think that probably a solution like this (https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization#using-annotations) would have a couple of benefits:
- the external load balancer (F5 for example) doesn't have to change in order to redirect proper traffic to the proper ingress controller marked with --watch-namespace
- the level of isolation of different namespaces for different applications is strictly linked to different needs (and that's fine in my opinion, without the need of a service loadbalancer)

Probably an intermediate solution could be to just specify a personalized nginx.tmpl.

Thanks

**Comment by aledbf** [comment]
Right. I will that annotations for each setting in the next release.

**Comment by micheleorsi** [comment]
Hello @aledbf, we really need this feature in short time so we decided to develop on our own and then open a PR here .. 
Have you got some suggestions before starting? 
Thanks

**Comment by aledbf** [comment]
@micheleorsi apologies for the delay with this. I'm waiting for https://github.com/kubernetes/contrib/pull/1847 to be merged. That PR simplifies the parsing of annotations. The new annotation for custom proxy timeouts should be similar to [this one]( https://github.com/aledbf/contrib/blob/c181263a70daca465d6c944793db7bfb00b59c08/ingress/controllers/nginx/pkg/ingress/annotations/healthcheck/main.go)

**Comment by micheleorsi** [comment]
@aledbf no problem at all: you and your team are doing an amazing job following so many open issues and PRs ..
I don't know if you can answer, but do you roughly know when this #1847 will be merged? Because I actually see, it would be way easier to implement with it!

**Comment by aledbf** [comment]
@micheleorsi I hope today or tomorrow (but it depends on @bprashanth :) )

**Comment by micheleorsi** [comment]
Actually we are now taking the path of specify properties at _path_ level inside every ingress. Hope this is useful also for you, so that as soon as that PR is merged I can proceed with this new feature!

**Comment by micheleorsi** [comment]
added in the new version outside kubernetes/contrib (look into PR comments for more details)
