### ISSUE TITLE
Nginx Ingress Controller frequently giving HTTP 503

### ISSUE THREAD

**Issue by wernight** [kubernetes/contrib#1718]
For unknown reasons to me, the [Nginx Ingress Controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) is frequently (that is something like every other day with 1-2 deployments a day of Kubernetes Service updates) returning HTTP error 503 for some of the Ingress rules (which point to running working Pods).

Note: Running also [`kube-lego`](https://github.com/jetstack/kube-lego).

Below are logs of Nginx Ingress Controller:

```
$ kubectl logs nginx-ingress
10.10.10.10 - [10.10.10.10, 10.10.10.10] - - [08/Sep/2016:11:17:26 +0000] "GET / HTTP/1.1" 503 615 "-" "agent here" 592 0.000 - - - -
10.10.10.10 - [10.10.10.10] - - [08/Sep/2016:11:17:26 +0000] "GET / HTTP/2.0" 503 730 "-" "agent here" 18 0.001 127.0.0.1:8181 615 0.001 503
10.10.10.10 - [10.10.10.10, 10.10.10.10] - - [08/Sep/2016:11:17:26 +0000] "GET /favicon.ico HTTP/1.1" 503 615 "https://foo.example.com/" "agent here" 510 0.000 - - - -
10.10.10.10 - [10.10.10.10] - - [08/Sep/2016:11:17:26 +0000] "GET /favicon.ico HTTP/2.0" 503 730 "https://foo.example.com/" "agent here" 24 0.001 127.0.0.1:8181 615 0.001 503
```

Looking at `/etc/nginx/nginx.conf` of that nginx-ingress:

```
$ kubectl exec nginx-ingress-controller grep -A 5 foo /etc/nginx/nginx.conf
upstream foo-frontend-80 {
    least_conn;
    server 20.20.0.37:80 max_fails=0 fail_timeout=0;

}
```

And checking that service actual IP of the Pod (because it's bypassing the service visibly):

```
$ kubectl --namespace=foo describe po frontend | grep IP:
IP:             20.20.0.37
```

IP matches, so visibly the reload failed, and doing this fixes it:

```
$ curl -I https://foo.example.com/
HTTP/1.1 503 Service is no longer available

$ kubectl exec nginx-ingress-controller -- nginx -s reload

$ curl -I https://foo.example.com/
HTTP/1.1 200 OK
```

So it looks like there are cases where the reload didn't pick up changes for some reason, or didn't happen, or some concurrency.

**Comment by wernight** [comment]
I don't know where the `glog.Info("change in configuration detected. Reloading...")` goes as it might be useful to diagnose.

**Comment by wernight** [comment]
Ok found one `requeuing foo/frontend, err error reloading nginx: exit status 1`, nothing more. Didn't repeatably fail.

**Comment by wernight** [comment]
Another note, I'm running it on another cluster with less Ingress rules and didn't notice that issue there. So it'd quite likely related to how many updates happen.

**Comment by aledbf** [comment]
How many ingress rules you are using?
Please increase the verbose level to 2 --v=2 in order to see what it
changes in the nginx.conf

**Comment by aledbf** [comment]
Do you experience the same issue with a backend different to gitlab?

**Comment by wernight** [comment]
Yes all backends, randomly one of them.

9 Ingresses, 98 rules in total (that is hosts).

**Comment by MDrollette** [comment]
I'm noticing similar behavior. It usually occurs if I update/replace a Service. I'll get random 503's until I update something in an Ingress which seems to reload nginx and everything starts working again.

I'm happy to debug things further, but I'm not sure what info would be useful.

**Comment by wernight** [comment]
Two ideas of possible fixed supposing it's some concurrency issue:

- Pass of nginx reload through a [denounce](http://reactivex.io/documentation/operators/debounce.html) function
 - Call nginx reload again something lile 3 sec after the last nginx reload (may be also through a denounce
 - Check that if it fails it really retries (probably good)
 - Perform some self monitoring and reload if it sees something wrong (probably really good)

**Comment by aledbf** [comment]
@wernight thanks for the ideas you are proposing. Most of the points are already present:
- rate limiting for reloads
- reload only when necessary (diff of nginx.conf)
- avoid multiple reloads
Please check [here](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx/command.go#L60)

**Comment by aledbf** [comment]
> I'm noticing similar behavior. It usually occurs if I update/replace a Service

@wernight @MDrollette 
Your service is scaled to more than 1? 
The service has a `livenessProbe` and/or `readinessProbe`? 
What version of the controller are you using?

**Comment by MDrollette** [comment]
I've noticed this twice since updating to v0.8.3. Both times it was after updating a Service that only had 1 pod. Both services have a readinessProbe but no livenessProbe.

**Comment by aledbf** [comment]
> Both times it was after updating a Service that only had 1 pod. Both services have a readinessProbe but no livenessProbe.

ok, the default configuration in nginx is to rely in the probes. If you are not using a `livenessProbe` then you need to adjust the configuration. Please check https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md#custom-nginx-upstream-checks

> Both times it was after updating a Service that only had 1 pod

How are you deploying the update? Deployments?
(You need to start the new version of the pod before removing the old one to avoid 503 errors)

**Comment by MDrollette** [comment]
Thanks, I'll look into the health checks in more detail to see if that can prevent winding up in this broken state.

Yes, I'm using Deployments. Although in this case I didn't deploy any new pods, I just changed some properties on the Service.

And just to clarify, I would expect _temporary_ 503's if I update resources in the wrong order. But my concern in this case is that if the Ingress, Service, and Pod resources are all correct (and no health checks are failing) then I would expect the nginx controller to reconcile itself _eventually_ - following the declarative nature of Kubernetes. But it seems like it can wind up in a permanently broken state if resources are updated in the wrong order.

**Comment by aledbf** [comment]
>  I just changed some properties on the Service. 

Can you mention what was changed in the service?

>  then I would expect the nginx controller to reconcile itself eventually - following the declarative nature of Kubernetes.

It does but if for instance the initial test of readinessProbe requires 60 seconds the you kill the previous pod before that there's no way to avoid errors. The controller doesn't know the state of the pod, just represents the current state in the api server

**Comment by wernight** [comment]
Also using 0.8.3, also applying just few changes to Pods like updating the images (almost exclusively), also having liveness/readiness probes for almost all Pods including those giving 503 but those probes didn't pick up any issues (as Pods were running fine). Some Services are scaled to more than 1, but that doesn't seem to influence this bug as I had issues with those 1 and those with multiple Pods behind a service.

@aledbf I guess you're the rate limiting is only delaying the next reload to have never more than X/second and never actually skipping some. Then it looks like the main thing left to do is self-checking.

**Comment by aledbf** [comment]
> I guess you're the rate limiting is only delaying the next reload to have never more than X/second and never actually skipping some

Exactly

>  Then it looks like the main thing left to do is self-checking.

Do you mean to avoid this

> Ok found one requeuing foo/frontend, err error reloading nginx: exit status 1, nothing more. Didn't repeatably fail.

Can you search the log to see the reason for the error 1?

**Comment by wernight** [comment]
I do mean that Nginx Ingress Controller checking if Nginx is working as intended sounds like a rather good thing. May during the `/healthz` request it could do that.

The logs are no more reporting an error so cannot check the context.

**Comment by aledbf** [comment]
> I do mean that Nginx Ingress Controller checking if Nginx is working as intended 

Just in case nginx never stops working during a reload. Only if the configuration is valid nginx starts new workers and kill the old ones when the current connections are closed.

Do you have memory limits applies to the ingress pod?

**Comment by wernight** [comment]
I have some, I can check but it should be rather high for Nginx like 100 MB

**Comment by wernight** [comment]
Checked and yes it's using 100 MB almost at times. Looks like it's really using a lot more than single Nginx instances. Increased, may be it'll fix that. Good call!

Still it doesn't stay at nearly 100 MB most of the time, so I wonder why I've to manually reload Nginx when theoretically Nginx Ingress Controller could detect those issues and do that reload automatically. Why I'd have more self-checks is because the Ingress Controller is may be the most important piece on the network as it may captures all network packets.

**Comment by aledbf** [comment]
@wernight the amount of memory required is the sum of:
- ~70MB in the master nginx process
- ~65MB * number of worker threads (default is equals to the number of cpus)
- ~50MB for the go binary (the ingress controller)

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0   57996  49748      4 S   0.0  0.1 556:19.50 nginx-ingr+
   17 root      20   0  129552  68692   7012 S   0.0  0.1   0:51.39 nginx
31850 nobody    20   0  391828  65512   3572 S   0.0  0.1   0:04.39 nginx
31851 nobody    20   0  391828  65512   3572 S   0.0  0.1   0:03.65 nginx
31852 nobody    20   0  391828  65512   3572 S   0.0  0.1   0:03.75 nginx
31853 nobody    20   0  391828  65512   3572 S   0.0  0.1   0:03.29 nginx
31854 nobody    20   0  391828  65512   3572 S   0.0  0.1   0:03.60 nginx
31855 nobody    20   0  391828  65512   3572 S   0.0  0.1   0:02.75 nginx
31856 nobody    20   0  391828  65512   3572 S   0.0  0.1   0:03.88 nginx
31857 nobody    20   0  391828  65512   3572 S   0.0  0.1   0:03.18 nginx
32114 root      20   0   18308   3380   2828 S   0.0  0.0   0:00.05 bash
32120 root      20   0   36652   3136   2696 R   0.0  0.0   0:00.01 top
```

**Comment by aledbf** [comment]
@wernight the number of worker thread can be set using the directive `worker-processes`
(https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md)

**Comment by aledbf** [comment]
> Why I'd have more self-checks is because the Ingress Controller is may be the most important piece on the network

Agree. That's why I'm asking all this question in order to be able to reproduce the behavior you see

**Comment by lymichaels** [comment]
I'm seeing the same issue with the ingress controllers occasionally 502/503ing. I usually 'fix' this by just deleting the ingress controller sending those errors. This happened on v0.8.1 as well as v0.8.3. I still have the ingress controller pods that are causing issues up (for both versions). Let me know what I can do to help debug this issue.

This is what I see when i run a ps, which shows a lot of zombie nginx processes.

root@nginx-ingress-lb-jtids:/# ps auxww

USER      | PID |%CPU| %MEM  |  VSZ |  RSS |TTY   |   STAT| START |  TIME| COMMAND
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ----
root     |    1  |0.1|  0.2  |49352 |36772 |?       | Ssl | 17:51   |0:14| /nginx-ingress-controller --default-backend-service=kube-system/default-http-backend --nginx-configmap=kube-system/nginx-ingress-conf
nobody  |  5343|  0.0 | 0.0    |  0   |  0 |?     |   Z   | 19:08  | 0:00 |[nginx] \<defunct\>
nobody   | 5344|  0.0 | 0.0    |  0   |  0| ?     |   Z  |  19:08 |  0:00 |[nginx] \<defunct\>
nobody   | 5345|  0.0 | 0.0    |  0   |  0| ?     |   Z   | 19:08 |  0:00 |[nginx] \<defunct\>
nobody   | 5346|  0.0 | 0.0    |  0   |  0 |?     |   Z   | 19:08  | 0:00 |[nginx] \<defunc\t>
nobody   | 5478|  0.0 | 0.0    |  0   |  0 |?     |   Z   | 19:09  | 0:00 |[nginx] \<defunct\>
nobody   | 5479|  0.0 | 0.0    |  0   |  0 |?    |    Z   | 19:09  | 0:00 |[nginx] \<defunct\>
nobody   | 5480|  0.0 | 0.0    |  0   |  0 |?   |     Z   | 19:09  | 0:00| [nginx] \<defunct\>
nobody   | 5481|  0.0 | 0.0     | 0  |   0 |? |       Z   | 19:09  | 0:00 |[nginx] \<defunct\>
nobody   | 5613|  0.0 | 0.3 |373200 |57624| ?|        Sl  | 19:10 |  0:00 |nginx: worker process
nobody   | 5614|  0.0 | 0.3 |373200| 56296| ? |       Sl  | 19:10  | 0:01 |nginx: worker process
nobody   | 5615|  0.0 | 0.3 |373200 |57532| ?   |     Sl |  19:10  | 0:00 |nginx: worker process
nobody   | 5616|  0.0 | 0.0     | 0    | 0 |?    |    Z  |  19:10 |  0:00| [nginx] \<defunct\>
nobody   | 5748|  0.0 | 0.3 |373200 |57624| ?   |     Sl  | 19:10|   0:02 |nginx: worker process
nobody   | 5749|  0.0 | 0.3 |373200 |57624| ?  |      Sl  | 19:10 |  0:03 |nginx: worker process
root      |5750  |0.0 | 0.0  |    0    | 0 |?  |      Z |   19:10 |  0:00| [nginx] \<defunct\>
nobody |   5751|  0.0|  0.0   |   0   |  0 |?      |  Z   | 19:10  | 0:00| [nginx] \<defunct\>
root      |6431  |2.5  |0.0|  18248 | 3112 |? |       Ss  | 20:32 |  0:00 |/bin/bash
root      |6440 | 0.0|  0.0 | 34428 | 2872 |? |       R+ |  20:32 |  0:00| ps auxww

**Comment by whereisaaron** [comment]
With both 0.8.1 and 0.8.3 when 'apply'ing updates to a Deployment the nginx controller sometimes does not reconfigure for the new Pod IP addresses. When I check the nginx.conf it still has the old IP address for the Pods the Deployment deleted. The Service referred to in the Ingress does update and has the new Pod IPs. The controller never recovers and currently the quick fix is to delete the nginx controller Pods; on restart they get the correct IP address for the Pods. It happens for maybe 1 in 10 updates to a Deployment.

Currently I typically 'apply' an update to the Ingress, Service and Deployment, even though only the Deployment has actually changed. I am assuming 'apply'ing an identical config is a null operation for resources created with 'apply'? Or could this be causing nginx to fail to reconfigure?

**Comment by SleepyBrett** [comment]
We see this where the config is out of date but generally the ingress is throwing an error like:

    [ingress-controller-xnx9m] | E1119 20:55:56.556156 1 command.go:87] failed to execute nginx -s reload: 2016/11/19 20:55:56 [notice] 18988#18988: signal process started
    [ingress-controller-xnx9m] | 2016/11/19 20:55:56 [alert] 18988#18988: kill(18, 1) failed (3: No   such process)
    [ingress-controller-xnx9m] | nginx: [alert] kill(18, 1) failed (3: No such process)

When we exec into the pod we notice that there is still a live nginx worker but the nginx master is down.

Of course because the controller and nginx are both running in the pod and the controller is on pid 1 and considers itself healthy the pod gets wedged in this bad state. 

Perhaps the controller can check that /var/run/nginx.pid is actually pointing to a live master continuously?

**Comment by jeremi** [comment]
We are facing the same issue as @SleepyBrett . When this happen, the PID stored in `/run/nginx.pid` is pointing to a PID that do not run anymore.

**Comment by SleepyBrett** [comment]
@jeremi I eventually made changes to the controller code that cause it to crash if the underlying nginx master crashes. It causes the ingress pod to restart, but it comes back in a healthy state.

It's a quick hack but you can find it here:
https://github.com/Nordstrom/kubernetes-contrib/tree/dieonreloaderror

**Comment by jeremi** [comment]
thanks @SleepyBrett so logging to the Fatal level force the pod to be restarted ? Is it a kubernetes feature ?

**Comment by aledbf** [comment]
> logging to the Fatal level force the pod to be restarted ? Is it a kubernetes feature ?

No, Fatalf terminates the process after printing the log with exit code 255
https://godoc.org/github.com/golang/glog#Fatalf

**Comment by Malet** [comment]
I'm also having this issue when `kubectl apply`'ing to the service, deployment, and ingress. The logs are littered with `failed to execute nginx -s reload` `signal process started`.

**Comment by Malet** [comment]
I was running this with a resource constraint of 200MB of memory, removing this constraint I haven't seen this error re-occur.

This doesn't seem to be the result of an OOM kill, in that case the go ingress controller process receiving the signal would kill the entire container. It seems like the nginx process must be crashing as a result of the constrained memory, but without exceeding the resource limit. 😕

**Comment by domino14** [comment]
I see this with no resource constraint. Just `ab -n 3000 -c 25 https://myurl.com`  and then I load a new image into one of my deployments and I get constant 503s for several seconds. Also, even without the new image, I get fairly frequent "SSL Handshake Error"s. Neither of these issues happens with the nginxinc ingress controller.

**Comment by Jaesang** [comment]
We have same issue like this. We use nginx-ingress-controller:0.9.0-beta.8, Does nginx controller still have this problem?

**Comment by Malet** [comment]
I've been using `gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.11` for a few weeks with no issues with a memory limit of 400MB on kubernetes (actual use is around 130MB for several hundred ingress rules)

**Comment by tanner-bruce** [comment]
@aledbf @Malet we are seeing similar issues on 0.9.0-beta.11. nginx-controller pods have no resource limits or requests, as we run two of them on two dedicated nodes a DS, so they are free to do as they wish.

Our current belief is:

1. liveness check on the pods was always returning 301 because curl didn't have `-L` specified [why this doesn't fail is another question]
2. nginx controller checks the upstreams liveness probe to see if it's ok
3. kubectl apply on a `service` type causes nginx-controller to reload upstreams
4. bad liveness check makes it think the upstream is unavailable
5. why it only happens periodically, ___?

**Comment by Jaesang** [comment]
In my environment, I solve this issue to decrease worker process in nginx.conf.
my server has 58 core so 58 nginx worker processes has running(worker_processes option is auto)
ingress pod have OOM error repeatedly,  It's same when I change ingress image to latest.

when I decrease worker process from auto to 8, 503 error doesn't appear anymore, It doesn't look like image problem.
