### ISSUE TITLE
[Ansible] deployement with contiv

### ISSUE THREAD

**Issue by eksavoy** [kubernetes/contrib#1732]
Hi,

I try to create a new kube cluster with ansible and contiv (Network) But I have an error :
`FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable openvswitch: rc=1 Failed to execute operation: No such file or directory\n"}`

Have you got an idea to solve this problem ?
Thank's

**Comment by ingvagabund** [comment]
What OS is in question? It looks like the service file is not present.

**Comment by elerion** [comment]
I use fedora 24

**Comment by ingvagabund** [comment]
The task fails since `openvswitch` is not installed on Fedora. It is installed on CentOS only.

Is the contiv the only network plugin you can use? I don't know the historical context but the default network plugin for Fedora was and is flannel.
