### ISSUE TITLE
GCE missing l7 ingress controller?

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes/contrib#1733]
Right now if you deploy or upgrade a GCE cluster to 1.3.6, the l7 ingress controller that is mentioned in http://kubernetes.io/docs/user-guide/ingress/#prerequisites is not present, but instead you get:

```
$ kubectl get pods --namespace=kube-system -l k8s-app=glbc
NAME                            READY     STATUS    RESTARTS   AGE
l7-default-backend-v1.0-bym3n   1/1       Running   0          3d
```

This is not mentioned anywhere in the [GCE release notes](https://cloud.google.com/container-engine/release-notes). Is this an unintentional bug in GCE or are the docs out of date and the ingress controller is held elsewhere?

**Comment by bacongobbler** [comment]
Looking at the differences closer, it seems like only the [glbc image](https://github.com/kubernetes/contrib/blob/186beffac4ca5083dfd14215fbb7b85eba404e8f/ingress/controllers/gce/rc.yaml#L64-L82) is missing by default. When I dump l7-default-backend-v1.0 on a fresh cluster, I see the following: https://gist.github.com/bacongobbler/5464eec6e8d5e799945528f5e0b4a362

Is the glbc now managed by GCE or something?

**Comment by thockin** [comment]
Exactly.

**Comment by bacongobbler** [comment]
Thanks @thockin, shall I update the docs to reflect the changes? :)

**Comment by thockin** [comment]
Aweome!

@bprashanth

**Comment by bprashanth** [comment]
sorry for the confusion, this happened in 1.3.0 itself (see Highlights section of https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md/#highlights). 

This line is inaccurate
```
On GCE/GKE there should be a L7 cluster addon, deployed into the kube-system namespace:
```

Please send a pr that upates it to reflect that the L7 controller runs on the master.
