### ISSUE TITLE
Check multiple commands on multiple URLs in Exechealthz

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/contrib#1735]
Refer kubernetes/kubernetes#30633.

Would it be possible to support checking multiple commands on multiple URLs in one Exechealthz process? I am going to run two Exechealthz processes within one pod but consider it would be better if Exechealthz supports this intuitively.

@luxas

**Comment by thockin** [comment]
It sounds viable, but it might be complex to specify that as a flag.  Do
you want to sketch it out, or even try to make a PR?

**Comment by MrHohn** [comment]
@thockin Sure, let me give it a try.
