### ISSUE TITLE
[ansible] Update flanneld config file

### ISSUE THREAD

**Issue by gouyang** [kubernetes/contrib#1769]
On RHEL, the flannel-0.5.5-1 is using environment vairables

```
ExecStart=/usr/bin/flanneld -etcd-endpoints=${FLANNEL_ETCD_ENDPOINTS} -etcd-prefix=${FLANNEL_ETCD_PREFIX}
```

On Fedora 24, flannel-0.5.5-6.fc24.x86_64 is still using 

```
ExecStart=/usr/bin/flanneld -etcd-endpoints=${FLANNEL_ETCD} -etcd-prefix=${FLANNEL_ETCD_KEY}
```

Should update `contrib/ansible/roles/flannel/templates/flanneld.j2` accordingly, no rush.

**Comment by ingvagabund** [comment]
``flanneld.service`` as well.  Plus, add if fedora > VERSION based on when the updated flannel gets into stable repository.
