### ISSUE TITLE
Add upgrade tests as non-blocking tests in submit-queue

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/contrib#1777]
...so that the bot will create issues for flaky upgrade tests.

Do we need all these tests?
- https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade
- https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade
- https://k8s-testgrid.appspot.com/google-kubectl-skew (except the tests for 1.2-1.3 compatibility)

If we need all of these tests, we'll need a script to populate the configMap key: https://github.com/kubernetes/contrib/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L19

@pwittrock @bprashanth @lavalamp @foxish

**Comment by foxish** [comment]
These tests are now part of the non-blocking jobs list. Closing.
