### ISSUE TITLE
[ansible] add variable to configure KUBELET_ARGS in kubelet.j2 template of node role

### ISSUE THREAD

**Issue by pschiffe** [kubernetes/contrib#1788]
Currently it's not possible to provide custom options for `KUBELET_ARGS` in `/etc/kubernetes/kubelet` file. So for example, if I want my pods to run with host network (`KUBELET_ARGS="--host-network-sources=*"`), I have to manually edit `/etc/kubernetes/kubelet` file on every node.

**Comment by ingvagabund** [comment]
Fixed by #1859
