### ISSUE TITLE
[nginx-ingress-controller] Ingress address counts don't match ingress-controller replica count

### ISSUE THREAD

**Issue by metral** [kubernetes/contrib#1799]
I'm running into an anomaly where the Ingress resource for my nginx-ingress-controller has a count of addresses for a host that **do not** actively match the number of replicas of the nginx-ingress-controller itself.

I'm running nginx-ingress-controller v0.8.3 in a Deployment with no hostPort, but instead a NodePort-typed Service fronting the Deployment, and the Ingress resource references this Service for a single host on a single path, in its rules.

This nginx-ingress-controller + Ingress + NodePort Service setup was chosen based on docs read, and mainly done to allow each namespace to run its own nginx-ingress-controller. Each controller is configured in its own namespace, with its own default backend as well, and a `--watch-namespace=$(POD_NAMESPACE)` to only watch for Ingresses in the namespace it operates in.

By default, the ingress-controller Deployment only has 1 replica.

The nginx-ingress-controller is working and I have external access to my app, but in a spurt of curiosity, I scaled the ingress-controller Deployment from 1 replica to 4 (I have 3 Nodes in my cluster), and the address count reported by the ingress resource shows that I have 3 addresses for the Ingress host (one for each of the 3 Nodes). It seemed logical to only have 3 addresses for the Ingress after scaling up as I only had 3 Nodes in the cluster. I also figured that by using a NodePort-typed Service, iptables was already handling the forwarding of the packets for the 4th replica, wherever it ended up living in the set of 3 Nodes, given that I can't physically have a 4th address.

But when I scaled the Deployment back down to 1 replica, the ingress resource address count changed to 2 addresses, instead of 1.

So questions:
1. In this setup, how many addresses _should_ the Ingress resource be reporting? Is it supposed to match the number of replicas of the ingress-controller itself?
   - Better said, how come when I scale down to 1 replica, down from 4, do I have any number of addresses other than a single one being reported by the Ingress? Is this logically incorrect?
2. Given that the ingress-controller's Service is a NodePort type, which opens the same random port on **ALL** nodes, shouldn't the addresses listed for the ingress **always** be the address for each Node, or is there something strange going on that I haven't caught onto given the nature of the nginx-ingress-controller's role?
   - I primarily ask this because even in cases where only one single address is reported for the Ingress, the host:NodePort for **all** Nodes still works in an external curl command to the app, proxying to the app just fine, no matter the Node IP used - the Service used for the Ingress is a NodePort Service after all, so this should be the case, regardless. Is it possible that something to do with the logic of which addresses the Ingress reports to satisfy the host, is off?

Thanks!

/cc @aledbf @bprashanth

**Comment by aledbf** [comment]
> and the address count reported by the ingress resource shows that I have 3 addresses for the Ingress host (one for each of the 3 Nodes)

This is correct

> Is this logically incorrect?

No. If you scale from 4 to 1 there should be only one IP in the Ingress (after a couple of seconds)
Can you reproduce this multiple times (scaling up/down)?

> In this setup, how many addresses should the Ingress resource be reporting?

The maximum number of different IP addresses is the number of nodes in the cluster

**Comment by aledbf** [comment]
@metral where are you running your cluster?

**Comment by metral** [comment]
> No. If you scale from 4 to 1 there should be only one IP in the Ingress (after a couple of seconds)
Can you reproduce this multiple times (scaling up/down)?

Yes, I'm able to reproduce this issue multiple times, so it might be a bug because the additional IP's aren't going away after scaling down. Even after hours have passed.

That being said, given that the Service for this ingress-controller is of type NodePort, shouldn't the Ingress **always** be reporting all 3 addresses, and not one, despite only having 1 replica of the ingress-controller?

> where are you running your cluster?

This is a private cluster I stood up myself running v1.3.5 on CoreOS 1010.5.0

**Comment by aledbf** [comment]
> shouldn't the Ingress always be reporting all 3 addresses, and not one, despite only having 1 replica of the ingress-controller?

Yes but when you scale down the number of replicas there's an update to the Ingress (to remove the IP) and this could be issue (simultaneous updates)

**Comment by metral** [comment]
> Yes but when you scale down the number of replicas there's an update to the Ingress (to remove the IP) and this could be issue (simultaneous updates)

Given this, shouldn't it then be the case that upon initial deployment with only 1 replica that the NodePort Service *always* reports back 3 addresses to the Ingress since each port can in fact receive traffic on the random port for the Ingress?

I ask because the Ingress only ever reports 1 address on creation of the 1 replica Deployment.

**Comment by metral** [comment]
Is it safe to say that even though Ingress seems to be working on all 3 of my Nodes, that the reason only 1 is actually being reported is a bug in nginx-ingress-controller? If so, I'd be interested in helping out.
