### ISSUE TITLE
ingress: controller doesn't reread template when it was modified inside the pod

### ISSUE THREAD

**Issue by kayrus** [kubernetes/contrib#1805]
I use this example https://github.com/kubernetes/contrib/blob/6bc22addcdf29c531ebd1fa449aa8de2d840e242/ingress/controllers/nginx/examples/custom-template/custom-template.yaml#L52..L55
And when I update configmap with the new template I don't see any changes or related logs inside the ingress pod. I suppose it is related to inotify, but I'm not sure.

**Comment by aledbf** [comment]
@kayrus this is fixed in master but not released https://github.com/kubernetes/contrib/pull/1498

**Comment by kayrus** [comment]
@aledbf significant change. is there a way to beta-test the image without compiling it on my side?

**Comment by aledbf** [comment]
@kayrus yes. Please use `aledbf/nginx-third-party:0.40` (contains most of this [list](https://github.com/aledbf/contrib/blob/release-ingress-controller-0.9/ingress/controllers/nginx/Changelog.md#09))

**Comment by kayrus** [comment]
@aledbf could you let me know when new nginx controller release is expected? or how can I force current 0.8.3 release reread template file when it was changed?

**Comment by aledbf** [comment]
> or how can I force current 0.8.3 release reread template file when it was changed?

that's not possible in 0.8.3

> could you let me know when new nginx controller release is expected?

I don't know. There are 4 pending PRs (#1847 is the most important one) before the next release
