### ISSUE TITLE
[nginx-ingress-controller] Feature request: enable session stickiness per-ingress

### ISSUE THREAD

**Issue by emmanuel** [kubernetes/contrib#1807]
We are currently using the ingress-global session stickiness, but have apps with different needs and would like to be able to utilize stickiness on specific ingresses. Based on the other annotation-based configurations that are available per-ingress, it looks like this is not a huge change, since the capability to configure upstreams per-ingress is already present. WDYT?

**Comment by aledbf** [comment]
@emmanuel already in the [TODO List](https://github.com/aledbf/contrib/blob/release-ingress-controller-0.9/ingress/controllers/nginx/Changelog.md) :)

**Comment by emmanuel** [comment]
Wahoo! Thanks @aledbf. Man, you are fast!

**Comment by Jno21** [comment]
Hello, could we have an update on this feature ? :)

Thanks !

**Comment by aledbf** [comment]
@emmanuel @Jno21 please check new release [here](https://github.com/kubernetes/ingress/releases/tag/nginx-0.9.0-beta.2) where the feature was introduced.
