### ISSUE TITLE
[peer-finder] Allow dns domain to be configured 

### ISSUE THREAD

**Issue by cristi-** [kubernetes/contrib#1814]
Hello,

 We are using peer finder for zookeeper auto discovery. However since we are using a custom dns domain with kube-dns, peer-finder is not working.

This is the parameter that's causing the issue:
https://github.com/kubernetes/contrib/blob/master/pets/peer-finder/peer-finder.go#L35

Thanks!

**Comment by cristifalcas** [comment]
:+1:

**Comment by SchwarzM** [comment]
Hi,

proposed a pull req for this #2013 

cya
SchwarzM

**Comment by SchwarzM** [comment]
This should be fixed with the merge of #2013.
