### ISSUE TITLE
nginx   examples/default/rc-default.yaml has healthz errors 

### ISSUE THREAD

**Issue by wstrange** [kubernetes/contrib#1818]
I am finding the latest rc-default config does not work anymore. The container is being restarted because it is failing the liveness / readiness probes. See errors below.

If I comment out those checks, it works fine.

This is minikube  /  k8s 1.4.0 

- [30/Sep/2016:20:56:16 +0000] "GET /ingress-controller-healthz HTTP/1.1" 404 21 "-" "Go-http-client/1.1" 139 0.001 172.17.0.4:8080 21 0.001 404
172.17.0.1 - [172.17.0.1] - - [30/Sep/2016:20:56:26 +0000] "GET /ingress-controller-healthz HTTP/1.1" 404 21 "-" "Go-http-client/1.1" 139 0.000 172.17.0.4:8080 21 0.000 404
172.17.0.1 - [172.17.0.1] - - [30/Sep/2016:20:56:26 +0000] "GET /ingress-controller-healthz HTTP/1.1" 404 21 "-" "Go-http-client/1.1" 139 0.000 172.17.0.4:8080 21 0.000 404
I0930 20:56:27.108540       1 main.go:187] Received SIGTERM, shutting down

**Comment by aledbf** [comment]
@wstrange please change the URL to /healthz and the port to 10254.
The new release (wip) changed both and allow the user to set URL

**Comment by wstrange** [comment]
That did the trick - thanks!

Do you want me to close out this issue?

**Comment by aledbf** [comment]
@wstrange please :)
