### ISSUE TITLE
No Package matching 'etcd' found available

### ISSUE THREAD

**Issue by perezje** [kubernetes/contrib#1822]
I have a small AWS cluster of 3 EC2 redhat 7.2 instances. I'm trying to deploy kubernetes using this ansible playbook. It connected and install k8s master and nodes fine but fails to install etcd with following error...
TASK [etcd : Install etcd via package manager] *********************************
fatal: [52.38.167.59]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'etcd' found available, installed or updated", "rc": 0, "results": []}

Any help/advice would be appreciated.

**Comment by ingvagabund** [comment]
Most likely repository where the etcd is provided is not available. You can install the etcd from github or subscribe to proper RHEL channels.
