### ISSUE TITLE
[nginx-ingress-controller] metrics on reload

### ISSUE THREAD

**Issue by micheleorsi** [kubernetes/contrib#1826]
Hello,
we are adding more and more services/ingresses/pods to our bare metal cluster. 
Since the reload operation is _heavy_ and affects the balancing of our requests we would like to keep track of this event.

I developed a simple endpoint with [expvar](https://golang.org/pkg/expvar/) library to expose such information. 

Are you interested in this feature? If you want I can submit a merge request and discuss about it. 

Thanks

**Comment by aledbf** [comment]
@micheleorsi sure, please share information about the endpoint (gist or a comment)

**Comment by micheleorsi** [comment]
As you prefer @aledbf!

In [nginx/command.go](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx/command.go) I added 

```

import (
        ...

	"expvar"
)
```

```

var (
	reload = expvar.NewInt("reload")

)

```

.. and ..

```
if changed {
	reload.Add(1)

```

.. then I registered the [endpoint ](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/main.go#L164)
```
mux.Handle("/debug/vars", http.DefaultServeMux)
```

Let me know if you like it, so I can submit a merge request!

**Comment by aledbf** [comment]
@micheleorsi please open a PR

**Comment by micheleorsi** [comment]
added in the new version outside kubernetes/contrib (look into PR comments for more details)
