### ISSUE TITLE
[nginx-ingress-controller] wrong balancing of requests for 20-30 seconds after configuration reload

### ISSUE THREAD

**Issue by micheleorsi** [kubernetes/contrib#1827]
Hello,
we are in a situation where we have hundreds of pods and dozens of nginx ingress controllers for high-availability.

We noticed that when the readiness of a pod changes (and the configuration of _failureThreshold_ and _successThreshold_ is a low number) the sort applied in the [following lines](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/controller.go#L806) creates a huge problem in balancing requests.
A single nginx serves **more traffic** to the **first servers (in lexicographic order)** for a slice of 20-30 seconds. After that everything becomes normal. 
The real problem arises when you have dozens of nginx (in our case 20) because everyone of them forwards more requests to the first (lexicographic order) IPs that causes crashes on the application on those IPs, since they cannot sustain such high traffic.
This event triggers a probe failing (readiness or liveness) that triggers another reload on all of the nginx, creating **a self-sustaining spiral** that brings down the whole cluster.

Internally we modified this nginx ingress controller to reshuffle IPs before configuration reload. And it's almost a week that works like a charm.
Are you interested in such improvements? Probably it's more related to nginx itself that doesn't internally reshuffle IPs, but for us it was way simpler to modify this project instead of the whole nginx one.
If you want I can submit a merge request and discuss about it.

Thanks!

**Comment by aledbf** [comment]
> the sort applied in the following lines creates a huge problem in balancing requests.

the sort is required to avoid unnecessary reloads

> Are you interested in such improvements?

yes but I think this change should be behind a flag

**Comment by micheleorsi** [comment]
@aledbf .. so in the end this is the only one left meaningful .. right? 
We have already implemented this feature in our internal branch. Where should I create the PR?

Thanks!

**Comment by aledbf** [comment]
Please open the PR in this repository.
