### ISSUE TITLE
The CLA nag munger alerting the PR author and not the commit authors

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1832]
It is simple enough to check the individual commits and their status, (at the cost of a few extra API calls).
e.g. https://github.com/kubernetes/contrib/pull/1276#issuecomment-250811324

However, when we have a large number of distinct authors, perhaps it would still make sense to ping the PR author (on a cherrypick PR for example).
This issue is to discuss whether it makes sense to always ping everyone who doesn't have a CLA among all commits in a PR.

**Comment by apelisse** [comment]
I would keep it simple, ping the author, and let him deal with his commits. The one pushing is more or less responsible for what is embedded in the PR IMO.

**Comment by foxish** [comment]
I agree with that. I think the cases are very few for now, and we can take care of it if it becomes more rampant.

**Comment by foxish** [comment]
We no longer have the nagging implemented. Moving to close this since this functionality has moved to prow.
