### ISSUE TITLE
CLA munger in each repository

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1834]
Currently, the model we operate under is one instance of the mungegithub bot per repository (test-infra, contrib, kubernetes).
However, with the CNCF CLA, message posting and applying CLA labels are tied to the bot. We would need to have one instance per repository running, which doesn't seem scalable (or efficient) as we have so many different repositories. 

The alternatives include:
- Separating the CLA functionality into a separate single instance of mungegithub which which can easily run on a list of repos.
- Adding the label functionality at the CNCF end.

I think the first option is reasonable. As I understand, the latter is not preferable since we want to have control of how/who we notify. 
cc @kubernetes/contributor-experience @apelisse @grodrigues3

**Comment by apelisse** [comment]
As discussed, I'll take care of that (if time allows)

**Comment by foxish** [comment]
@apelisse If you put out a WIP PR, I can help with this as well, in order to speed it up.

**Comment by apelisse** [comment]
As discussed in https://github.com/kubernetes/test-infra/issues/930, this will eventually be implemented in `prow` (please join the discussion if you have an opinion :-).

**Comment by foxish** [comment]
@apelisse Is prow ready for moving the CLA functionality into it?

**Comment by apelisse** [comment]
@foxish No, we'll just shove it in there anyway :-/

**Comment by spxtr** [comment]
I'll try to have a nice framework in place in the next couple days, then we can put it there without much hassle.

**Comment by foxish** [comment]
Thanks @spxtr
