### ISSUE TITLE
GLBC ingress controller troubleshooting information is out of date, and unclear after v1.3 changes

### ISSUE THREAD

**Issue by miend** [kubernetes/contrib#1839]
The troubleshooting section of [the readme for the GLBC ingress controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#troubleshooting) states that one should look at the controller pod's logs for troubleshooting information. According to the information in #1733, as of v1.3, the L7 controller runs on master, not as a regular pod. Google, of course, does not allow access to master on GKE clusters.

First, this means that the GLBC ingress controller documentation should be updated to reflect its current status. And secondly, how am I recommended to get logs from the ingress controller to troubleshoot potential issues with it if I cannot access it? Or is there some other method now recommended for troubleshooting it? I'm currently receiving a 502 bad gateway error when trying to access services/pods via ingress which are, as far as I can tell, conforming exactly to the standards set in documentation. I thought getting these logs would help me rule out any issues on the controller's end, but I've found I can't get to it at all.

**Comment by bprashanth** [comment]
we should be surfacing more through the events: https://github.com/kubernetes/contrib/issues/1369, but in the meanwhile, can you run `kubectl describe` on the ingress? can you give me the ingress/service etc for a repro? your service needs to be type=NodePort and you need to serve a health check on / or a readiness probe eg: 
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#health-checks
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/examples/health_checks/README.md
