### ISSUE TITLE
Submit Queue should print timezones by dates.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/contrib#1858]
Without it I have no idea what I'm looking at. cc @kubernetes/test-infra-maintainers @eparis

**Comment by eparis** [comment]
All dates are given to your browser with timezone information and your browser is converting those to your local TZ. I'll see if any of those helpers can show a tz, but everything you see in the submit queue should be based on the time on your local host.

**Comment by gmarek** [comment]
Thanks for the info, but I'd rather have a TZ info, as across the system we have PST, UTC, and local (CET for me). Sometimes it's hard to understand what is what.

**Comment by ixdy** [comment]
cc @apelisse @lavalamp

**Comment by lavalamp** [comment]
...and the timezone should ALWAYS BE UTC, everywhere.

**Comment by apelisse** [comment]
I don't have a strong opinion either way (UTC or not). But I agree that it should show the TZ used (one can only guess that it's local tz)
