### ISSUE TITLE
AnsibleUndefinedVariable for networking when running deploy-cluster.sh

### ISSUE THREAD

**Issue by rrati** [kubernetes/contrib#1864]
Attempting to run the deploy-cluster.sh script like this:

cd scripts
INVENTORY=../inventory.kube ./deploy-cluster.sh 

Results in an error:
fatal: [192.10.0.4] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'networking' is undefined", 'failed': True}

**Comment by ingvagabund** [comment]
@pschiffe
