### ISSUE TITLE
[nginx-ingress-lb] Need to have one nginx-ingress-controller per host

### ISSUE THREAD

**Issue by alfirin** [kubernetes/contrib#1873]
I created a new kubernetes v1.4.1 with two minion hosts.

Then I created the `default-http-backend` and one RC `nginx-ingress-controller` following [the contrib example](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) as follow:

```
$ kubectl create -f examples/default-backend.yaml
$ kubectl expose rc default-http-backend --port=80 --target-port=8080 --name=default-http-backend
$ kubectl create -f examples/default/rc-default.yaml
```

Everything is ok for the first host:
```
curl http://<MINION_HOST_1>/healthz
ok%
```
However, for the second host I have an error:
```
curl http://<MINION_HOST_2>/healthz
curl: (7) Failed to connect to <MINION_HOST_2> port 80: Connection refused
```

In order to make this work for the two hosts, I have to scale the `nginx-ingress-controller` to 2 (one per host).

How could I make this work without doing this manual scale / without having one nginx-ingress-controller per host?

Because I have an auto-scaling group for my hosts and I will have more hosts added dynamically and I don't want to scale by hand the `nginx-ingress-controller`.

Thanks a lot for your help.

**Comment by abudargo** [comment]
how about using daemonset instead of rc? http://kubernetes.io/docs/admin/daemons/

**Comment by aledbf** [comment]
@alfirin please check the [daemonset example](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/daemonset)

**Comment by alfirin** [comment]
@abudargo @aledbf Thanks a lot guys for your fast answer.

It worked like a charm.
However I add to put `apiVersion: extensions/v1beta1`.

We will be soon in production with kubernetes or Mesos/Marathon and we would love to know when this feature will be released (not in beta anymore)?

Thanks

**Comment by aledbf** [comment]
> However I add to put apiVersion: extensions/v1beta1.

Please open an issue in the main [kubernetes repo](https://github.com/kubernetes/kubernetes/issues) asking for the promotion of Daemonsets to stable

**Comment by alfirin** [comment]
Ok then I filled a new issue: https://github.com/kubernetes/kubernetes/issues/34616
