### ISSUE TITLE
Proposal: remove nginx ingress controller from contrib

### ISSUE THREAD

**Issue by aledbf** [kubernetes/contrib#1882]
Hi everyone,

I would like to propose moving the nginx ingress controller located in https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx.

I'm not sure if this qualifies for the incubation process or just split it out straight into a repo.
This Ingress controller has been maintained for more than 10 months, with active support in the contrib issues and slack.
(I don't have metrics to indicate the numbers of users)

This will help to:
- remove code from contrib
- give more visibility in the organization (so people can actually find it)
- pick up a few more contributors (hopefully)

_Releases:_

```
gcr.io/google_containers/nginx-ingress-controller    0.8.3    3f8119a98476    7 weeks ago
gcr.io/google_containers/nginx-ingress-controller    0.8.2    485ae35fc9f4    11 weeks ago
gcr.io/google_containers/nginx-ingress-controller    0.8.1    d272ea9a1e92    3 months ago
gcr.io/google_containers/nginx-ingress-controller    0.8      0496d9e01ef6    3 months ago
gcr.io/google_containers/nginx-ingress-controller    0.7      98e6b4e68a67    4 months ago
gcr.io/google_containers/nginx-ingress-controller    0.62     9972dee1b956    4 months ago
gcr.io/google_containers/nginx-ingress-controller    0.61     edeb93850b71    5 months ago
gcr.io/google_containers/nginx-ingress-controller    0.6      8cbcaaf34045    5 months ago
gcr.io/google_containers/nginx-ingress-controller    0.5      1ae65a65a987    6 months ago
gcr.io/google_containers/nginx-ingress-controller    0.4      7ca49d81084b    6 months ago
gcr.io/google_containers/nginx-third-party           0.4      6ece3bb745ea    6 months ago
gcr.io/google_containers/nginx-third-party           0.3      b33a4ba965e7    7 months ago
aledbf/nginx-third-party                             0.2      97561252656d    8 months ago
aledbf/nginx-third-party                             0.1      3fb253ced003    8 months ago
aledbf/nginx-third-party                             0.0      1fcb6571e70d    10 months ago
```

Please let me know your thoughts.

Thanks,
Alejandro

**Comment by justinsb** [comment]
I think this is a great idea (cc @bprashanth ).

The nginx ingress controller is critical to making ingress work on non-GCE platforms (in particular AWS).  Personally I consider it a core part of k8s, given that ingress is in-core.  I would be in favor of grandfathering this in to a kubernetes non-incubator repo, given that we would probably otherwise put it into the incubator and graduate it with the 1.5 release.

**Comment by bgrant0607** [comment]
There is already an issue for this: #1441. See also #762.

**Comment by bgrant0607** [comment]
It doesn't need to be incubated.

**Comment by bgrant0607** [comment]
The home is now https://github.com/kubernetes/ingress-nginx, but there are still examples here that should be moved/removed.

**Comment by bgrant0607** [comment]
cc @bowei

**Comment by aledbf** [comment]
@bgrant0607 the examples were left here because of the existing links in the kubernetes.io doc site. 
It should be safe to remove the examples now.
