### ISSUE TITLE
Incompatible health check path in `ingress/controllers/nginx` image/ examples

### ISSUE THREAD

**Issue by alpe** [kubernetes/contrib#1885]
With https://github.com/kubernetes/contrib/pull/1749 a new healthcheck path was introduced and the path in all the example yamls updated. Unfortunately the examples still point to the old image`gcr.io/google_containers/nginx-ingress-controller:0.8.3` which does not include the updated `nginx.tmpl`. 
This results in a restart loop as the new `/ingress-controller-healthz` path is served by the 404 default backend now.

**Comment by lukesmith** [comment]
I was stumped by this yesterday when setting up the nginx-ingress-controller for the first time. I found the answer in #1872. For now I've changed the path back to `/healthz` and it's working. Hoping 0.9 will be pushed soon

**Comment by bprashanth** [comment]
I'll report when we have a 0.9, closing for now
