### ISSUE TITLE
Cluster Autoscaler should delete nodes that fail to register with the api server

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/contrib#1886]
In the rare occasion that workers fail to register with the api server, the cluster autoscaler gets "stuck":
`W1018 14:50:46.022562       1 cluster_autoscaler.go:191] Cluster is not ready for autoscaling: wrong number of nodes for node group: k8s-worker expected: 3 actual: 2`
until there's manual intervention. 

It would be awesome if the cluster autoscaler could detect new nodes in the cloud provider that haven't been registered for a long period of time (10 mins?) and terminate them to let the cloud provider create a new instance. 

Alternatively you can add your own health checks to your nodes but the implementation would be cleaner if the cluster autoscaler was responsible for that logic. If this is a common issue and a feature that the cluster autoscaler should have, I can get a PR open for it.

**Comment by andrewsykim** [comment]
@mwielgus

**Comment by pbitty** [comment]
@osxi @iterion What do you do in your environment for this situation?

**Comment by osxi** [comment]
@pbitty To my knowledge, this hasn't happened to us (yet). 

I do notice that message/behavior when nodes are still booting up and are in the process of becoming ready on the cluster.

When does that happen to you? I would agree that nodes should probably terminate if they don't come up on the cluster, especially after a reasonable amount of time like 10 minutes maybe. That behavior might also be better off in the ASG's launch configuration but that's just a guess.

**Comment by andrewsykim** [comment]
@osxi it could happen for a variety of reasons, docker daemon crashes, failing to pull important binaries, etc. But those sorts of failures should be expected here and there and should be accounted for. At one point we had an dedicated ELB using the kubelet on each worker as a health check, so if the kubelet failed to start we would have ELB terminate the node, but thats extra expenses that we probably don't need.

**Comment by andrewsykim** [comment]
@mwielgus your thoughts?

**Comment by mwielgus** [comment]
Sorry for the delay. I must have missed this issue.

Fixing cluster and nodes is beyond the scope of cluster autoscaler. You may want to take a look at:
https://github.com/kubernetes/node-problem-detector

**Comment by andrewsykim** [comment]
What if nodes fail to start the kubelet, then the node problem detector would never start.

**Comment by andrewsykim** [comment]
Also I don't believe the node problem detector will clean up nodes that are marked unhealthy.

**Comment by andrewsykim** [comment]
Should be fixed by https://github.com/kubernetes/contrib/issues/2228

**Comment by mwielgus** [comment]
Fixed with the completed unready nodes efforts. The node will be removed only if a removal is allowed (within min/max boundaries).
