### ISSUE TITLE
Incorrect PR Size label

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/contrib#1892]
In PR https://github.com/kubernetes/kubernetes/pull/33944 the bot correctly applied the ` size/XXL` label to the PR that touches 72 files and adds 6936 lines.

It later removed that label and replaced it with `size/XS` <-- Buggy behavior

**Comment by saad-ali** [comment]
Another example where the bot seems to be fighting itself: PR https://github.com/kubernetes/kubernetes/pull/28599

**Comment by foxish** [comment]
@eparis any idea why this might happen? A github api glitch?

**Comment by eparis** [comment]
The sizer is supposed to ignore all changes in `vendor`    so it should be possible for a HUGE PR that only changes `vendor` to be XS.

But it is obviously broken...   Somehow the amount of changes in `vendor` are being mis-counted...

**Comment by eparis** [comment]
Seems definitely like a github API bug...

I'm looking specifically at kubernetes/kubernetes#28599.

If I look at the api
https://api.github.com/repos/kubernetes/kubernetes/pulls/28599

I'll see that is says:
```
  "additions": 18570,
  "deletions": 239,
```

But if I look at it via git:
```
git diff --stat $(git merge-base upstream/pr/28599 upstream/master)..upstream/pr/28599

[snip]
 167 files changed, 62513 insertions(+), 41876 deletions(-)
```

So the github api says there are only 18k insertions but there are really 65k insetions! When we then remove the additions/deletions from ignores paths (in this case that includes at least vendor and more importantly changes to `pkg/api/types.generated.go` and `pkg/api/v1/types.generated.go` which BOTH have > 20k additions and deletions) we end up with a negative size.

`Additions: -39003 Subtractions: -40594`

No idea why the github api just lies about the # of Additions and Deletions.

**Comment by eparis** [comment]
e-mail sent to github support

**Comment by foxish** [comment]
@eparis Thanks for figuring it out. I wonder it is a recent change on their end that caused this.

**Comment by eparis** [comment]
```
Hi Eric,

If you check https://github.com/kubernetes/kubernetes/pull/28599/files you'll see that the UI shows the same thing (so it's not a problem in the API) and offers an explanation about why the numbers are like that:

"Sorry, we could not display the entire diff because it was too big."

And for that file pkg/api/types.generated.go specifically you'll see:

"20,953 additions, 20,281 deletions not shown because the diff is too large. Please use a local Git client to view these changes."

You're hitting some documented limits in displaying and counting diffs:

https://help.github.com/articles/what-are-the-limits-for-viewing-content-and-diffs-in-my-repository

It's something we'd like to improve in the future, but I can't promise an ETA.

Cheers,
Ivan
```

**Comment by eparis** [comment]
Maybe we should calculate the size summing the file.Additions instead of using the pr.Additions and then subtracting out the file.Additions we wish to ignore?
