### ISSUE TITLE
Mungegithub loop takes more than 10 minutes

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1894]
https://github.com/kubernetes/kubernetes/pull/34980#issuecomment-254890383

There is a delay of around 19 minutes between the `/lgtm` comment and the application of the label. 
Clearly looping over the issues serially is taking much too long. Maybe we should take a look at the way the mungers are structured, find ones that can execute in parallel and allow for parallel execution to cut down on the time it takes per loop.

/cc @kubernetes/contributor-experience @apelisse @grodrigues3 @lavalamp

**Comment by foxish** [comment]
Maybe we should have monitoring for this as well in velodrome.

**Comment by spxtr** [comment]
We should move this functionality into one of our push-based systems such as prow or gubernator.

**Comment by spxtr** [comment]
Take a look at https://github.com/kubernetes/test-infra/pull/887. This will get us instant responses and I think the last commit (https://github.com/kubernetes/test-infra/pull/887/commits/c7d6daec17e344f579e14a6c38bfdf74157f8537) is quite simple.

**Comment by foxish** [comment]
Closing this since it is moved to prow.
