### ISSUE TITLE
[vagrant openstack] 'run_provisioner': Catched Error: Catched Error: uninitialized constant 

### ISSUE THREAD

**Issue by rawlingsj** [kubernetes/contrib#190]
Vagrant Installed Version: 1.7.4

Running ansible vagrant with the openstack provider I hit the error below after doing vagrant up.  A quick google suggested a workaround but not sure if thats acceptable.  I'll submit a pr just in case it is.

```
/Users/jamesrawlings/.vagrant.d/gems/gems/vagrant-openstack-provider-0.7.0/lib/vagrant-openstack-provider/action/provision.rb:34:in `run_provisioner': Catched Error: Catched Error: uninitialized constant VagrantPlugins::Shell::Provisioner (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'	
```

Workaround came from..
https://github.com/ggiamarchi/vagrant-openstack-provider/issues/240#issuecomment-144511022

**Comment by eparis** [comment]
closing because https://github.com/ggiamarchi/vagrant-openstack-provider/issues/240 indicates it was fixed
