### ISSUE TITLE
Bot-name should be parameterizable

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1901]
Context: https://github.com/kubernetes/contrib/pull/1897#issuecomment-255005200
Intel is running their own instance of the mergebot under a different name and the CLA-ping is not recognized by the matchers because we assume that they must be made by `k8s-merge-bot`. We should ideally be able to pass in the name of the bot as a commandline argument.

cc @kubernetes/contributor-experience @lavalamp @grodrigues3

**Comment by eparis** [comment]
There are actually multiple 'bots' used throughout the mungers. Not sure what that parameterization will look like, but I always hated the fact they were all hard coded...

**Comment by bgrant0607** [comment]
mungegithub is gone
