### ISSUE TITLE
"Exec format error" when running customized service_loadbalancer 

### ISSUE THREAD

**Issue by chamilad** [kubernetes/contrib#1902]
I tried doing some minor changes to the `service_loadbalancer.go` file and building it in a custom Docker image to be run. However when done so, the RC goes in to CrashLoopBack and `kubectl logs <pod>` shows the only the following error.

```
Exec format error
```

I used both Go 1.7 and 1.6 versions to build the customizations and also tried specifying the target architecture as `GOARCH=386` and `GOARCH=amd64` in the Makefile, without success.

**Comment by davetropeano** [comment]
@chamilad I had the same issues. In my case it was dumb-init not being downloaded properly.

**Comment by chamilad** [comment]
@davetropeano Yes, it seems the `curl` command in the Dockerfile isn't been run properly. After downloading it separately and including through an `ADD` I was able to resolve this. Sorry for not updating this issue earlier.
