### ISSUE TITLE
Cluster-autoscaler: Unschedulable (and unready) nodes are blocking CA

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/contrib#1913]
When debugging customer issue we've seen the following scenario:
1. Customer drained 2 nodes to force CA to remove them
2. CA started reporting that cluster is not ready for autoscaling as number of expected and current nodes does not exist. This was caused by listing only ready, schedulable nodes. See [code](https://github.com/kubernetes/contrib/blob/d519cddaa0b85d37cc912fa6cf2c0592c2b8cf74/cluster-autoscaler/utils/kubernetes/listers.go#L98-L116)
3. CA couldn't do anything.

@davidopp @roberthbailey @mwielgus @piosz @jszczepkowski

**Comment by roberthbailey** [comment]
To get the CA back into service, the two options appear to be:

1. uncordon the two drained nodes
1. manually remove the two drained nodes from the MIG

Both of these options require a user to deeply understand the CA behavior and manually repair the controller.

**Comment by mwielgus** [comment]
Fixed in https://github.com/kubernetes/contrib/pull/1935.
