### ISSUE TITLE
Fix The Approval Handler

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/contrib#1917]
In the `hasApprove` function there is a bug in the for loop

```
for { 
fileOwners := h.features.Repos.LeafAssignees(p)
        if fileOwners.Len() == 0 {
            glog.Warningf("Couldn't find an owner for path (%s)", p)
            continue
        }
...

p = path.Join(p, paths[i])

}
```

The continue statement never allows the handler to look deeper in the tree after it runs into the `fileOwners.Len() == 0`.  The continue statement means the path never gets appended to.

**Comment by foxish** [comment]
cc @hongchaodeng

**Comment by grodrigues3** [comment]
fixed awhile back with new implementation
