### ISSUE TITLE
nginx ingress controller compilation error

### ISSUE THREAD

**Issue by karolyi** [kubernetes/contrib#1920]
Hey,

I want to compile the nginx ingress controller in a google cloud shell.

Running `go get .`, I get the following error:

```
laszlo_karolyi@free-tier-test:~/kubernetes-contrib/ingress/controllers/nginx$ go get -v .
Fetching https://k8s.io/kubernetes/pkg/controller/framework?go-get=1
Parsing meta tags from https://k8s.io/kubernetes/pkg/controller/framework?go-get=1 (status code 200)
get "k8s.io/kubernetes/pkg/controller/framework": found meta tag main.metaImport{Prefix:"k8s.io/kubernetes", VCS:"git", RepoRoot:"https://github.com/kubernetes/kubernetes"} at https://k8s.io/kubernetes/pkg/controller/framework?go-get=1
get "k8s.io/kubernetes/pkg/controller/framework": verifying non-authoritative meta tag
Fetching https://k8s.io/kubernetes?go-get=1
Parsing meta tags from https://k8s.io/kubernetes?go-get=1 (status code 200)
k8s.io/kubernetes (download)
package k8s.io/kubernetes/pkg/controller/framework: cannot find package "k8s.io/kubernetes/pkg/controller/framework" in any of:
        /usr/local/go/src/k8s.io/kubernetes/pkg/controller/framework (from $GOROOT)
        /home/laszlo_karolyi/gopath/src/k8s.io/kubernetes/pkg/controller/framework (from $GOPATH)
        /google/gopath/src/k8s.io/kubernetes/pkg/controller/framework
```

**Comment by aledbf** [comment]
> go get -v .

The project uses godep. You don't need to run `go get` (the vendor directory is in the parent)

**Comment by karolyi** [comment]
sorry I'm not a go professional.

after simply executing `make controller` (as stated in the readme), I get this:

```
laszlo_karolyi@free-tier-test:~/kubernetes-contrib/ingress/controllers/nginx$ make controller
rm -f nginx-ingress-controller
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags \
        "-s -w -X main.version=git-f7d84e9 -X main.gitRepo=https://github.com/kubernetes/contrib.git" \
        -o nginx-ingress-controller
controller.go:37:2: cannot find package "k8s.io/kubernetes/pkg/controller/framework" in any of:
        /usr/local/go/src/k8s.io/kubernetes/pkg/controller/framework (from $GOROOT)
        /home/laszlo_karolyi/gopath/src/k8s.io/kubernetes/pkg/controller/framework (from $GOPATH)
        /google/gopath/src/k8s.io/kubernetes/pkg/controller/framework
Makefile:14: recipe for target 'controller' failed
make: *** [controller] Error 1
```

is there any extra step I have to make?

**Comment by aledbf** [comment]
@karolyi you need to follow the [Getting the Code](https://github.com/kubernetes/contrib#getting-the-code) steps to compile.

(from the errors you are using `~/kubernetes-contrib/ingress` which is no a valid path)

**Comment by aledbf** [comment]
> sorry I'm not a go professional.

Sorry to ask but why are you trying to compile the ingress controller and not just use the image from `gcr.io`?

**Comment by karolyi** [comment]
I'm a newcomer to k8s and in progress of building a cloud solution based on google cloud. The problem is, Google's loadbalancer doesn't handle SNI, and moreover, I just recently stumbled upon on that gcr.io image. Nevertheless, I'd like to have my own with the latest dependencies/libraries compiled. Since there was no latest tag as far as I could see, I decided to compile it for myself.

Might be very well I'm wrong here, of course. Kubernetes is a bit overwhelming for me at first, the learning curve is kinda hard.

**Comment by aledbf** [comment]
> Since there was no latest tag as far as I could see, I decided to compile it for myself.

Just as an comment: `latest` is not a version :)
That's the reason why there's a changelog that shows the releases and the examples always use the latest version.

**Comment by karolyi** [comment]
I beg to differ here, the jenkins docker images have a latest tag :)

I'll be of course tracking this controller, but I like to build and understand things from the ground up, hence my approach.

**Comment by aledbf** [comment]
> I beg to differ here, the jenkins docker images have a latest tag :)

Yes, you are right but if you start using `Kubernetes` to deploy applications using [deployments](http://kubernetes.io/docs/user-guide/deployments/) if you tag images with `latest` you cannot  [rollback](http://kubernetes.io/docs/user-guide/deployments/#rolling-back-to-a-previous-revision) (without re-publishing the old image). Again that's just a comment.

**Comment by karolyi** [comment]
I managed to compile it, thx... closing this ticket.

**Comment by fabianromerorcc** [comment]
@karolyi Hi! how did you resolve that missing package? Cheers.

**Comment by karolyi** [comment]
@fabianromerorcc I followed the getting the code guide step by step, as mentioned before.

**Comment by roffe** [comment]
*BUMP* How did you solve it @karolyi 

running in to the same issues here.

And as to WHY i'm trying to compile it myself:

I want to compile my own ingress controller that listens on a different class so i can have mutiple nginx controllers.

Since these values are hardcoded in the source. a compilation is required once source is modified.
