### ISSUE TITLE
Cluster-autoscaler: add a way to specify which node pool to expand

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1921]
Right now if there are two node pools that expanding which would make a pod schedulable a random one is chosen. This may result creating a 32core+ssd node for a single pod.

**Comment by mumoshu** [comment]
Hi @mwielgus, thanks for developing clusterr-autoscaler!
I'm the primary maintainer of https://github.com/coreos/kube-aws and interested in using or even implementing this feature but how would you like to specify node pool?

Adding something like `--precedence ondemand>spot --precedence smaller>larger` to cluster autoscaler's command-line arg to set preference to ASGs with on-demand instances and/or smaller instances when there're multiple candidates would suffice?

**Comment by mumoshu** [comment]
IMHO I believe this is related to #2066.
If you'd like to keep minimum/base-line capacity with on-demand instances while spreading some loads to cheaper but unreliable instances(from a spot fleet) for performance reason, you'd also like to specify which asg or spot fleet to expand.

**Comment by thebigjc** [comment]
There is the idea of how well the pods that need to be scheduled fit. 

Real world problem I have:
- Some of my pods have moderate CPU / light RAM needs, so we have a node group of c3.2xlarge nodes. 
- Some pods have higher RAM needs, so we have a node group of r3.2xlarge nodes for those. 

Ideally, when needing to schedule the first group of nodes, the cluster-autoscaler would pick the c3.2xlarge nodes, and when needing to schedule the second, it would scale the second. 

An idea of 'fit' for the pods, or 'waste' on the node would satisfy this solution. In the first case, if you were to schedule the pods on the c3 nodes, you would have less wasted RAM than if the r3 were chosen.

Does this seem like a reasonable strategy to adopt?

**Comment by mumoshu** [comment]
@thebigjc Sounds great!
Just my one cent but If there're 2 or more "fitted" node pools, selecting one randomly would be good.

**Comment by thebigjc** [comment]
@mumoshu I agree if there is a tie we should still be random. I have a draft that I'll send as a PR today!

**Comment by thebigjc** [comment]
Should we close this?
