### ISSUE TITLE
Add "/dibs" to available bot commands

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/contrib#1927]
Allow potential reviewers to comment "/dibs" on PRs that they would like assigned to them.   Also allow "/nack" from reviewers who have been assigned that want the PR to be assigned to someone else. 

cc
@bgrant0607 @apelisse @foxish

**Comment by grodrigues3** [comment]
@bgrant0607 regarding /dibs, I was thinking about this exclusively for PRs.  As in, this is NOT going to be a way for people to get issues assigned to them.  Does that make sense to you?

**Comment by eparis** [comment]
`/dibs` feels very informal. Maybe `/assign`, which could be extended to `/assign bgrant0607` for me to assign an issue to someone else? But first implementation would just be `/assign` and it would assign to yourself.

Why wouldn't we want this on issues? If people want to be assigned to issues?

**Comment by eparis** [comment]
What does `/dibs` do with existing assignees?

**Comment by grodrigues3** [comment]
@eparis great questions.  We would want this for issues if people want to self assign (or in the future, potentially assign other people).  I don't have strong opinions for `dibs` vs `assign.`  I will say that [docker](https://github.com/docker/leeroy/search?utf8=%E2%9C%93&q=dibs) uses `dibs` and it's easy to remember.

I don't think it should do anything to existing assignees for the time being.  The PR won't be blocked on their lgtm (since there's another reviewer), so it only hurts in the sense that an assignee may still get notifications for the PR.

**Comment by eparis** [comment]
`assign`/`unassign` seems easier to me, especially to remember the negative. But that's just bike shedding. I'd be just as happy with `dibs`.

I will /nack `/nack` though because NAK is just a common phrase for 'I absolutely do not approve this patch'. We need some other negative version of the command...

**Comment by grodrigues3** [comment]
renaming `/nack` SGTM

**Comment by grodrigues3** [comment]
also, I think we're currently blocking on go-github implementing unassign functionality.

https://github.com/google/go-github/issues/459

**Comment by bgrant0607** [comment]
@eparis @grodrigues3 

How about `/reassign` instead of nack? That would permit adding `/reassign @eparis` later. Yes, `/dibs` came from docker.

PRs are higher priority, but we should implement dibs/reassign for issues, also. That's come up pretty often.

**Comment by apelisse** [comment]
`/reassign` as a much stronger meaning than `/nack`. It will avoid lots of confusion. If we start using `nack`, we might end-up using it in many different situation and create a huge mess.
