### ISSUE TITLE
Have the bot automatically apply release-note-* labels

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/contrib#1929]
We would like to require that PR authors correctly fill out the release note section in the PR template.  That means, if the PR requires no release note, they enter `NONE` in the release block section.  

And if the PR requires a release note, the block is filled in with text that adequately describes the bugfix/feature.  I also think we should remove the functionality that automatically adds the PR title as the release note entirely; this will ensure that if a release note is included, it was **intentional**.

The current problem is that a human being is still required to add one of the `release-note-*` labels manually.  Instead, I propose that the bot read the body of the PR and automatically remove the `release-note-needed` label, and add one of `release-note`, `release-note-none`, or `release-note-action-required` 

Does this make sense to everyone?

cc

@apelisse @foxish @bgrant0607 @david-mcmahon @eparis @roberthbailey

**Comment by david-mcmahon** [comment]
The current release note procedure comes from several iterations and lots of fine tuning.
We actually [discussed this method to drive everything from the template](https://github.com/kubernetes/kubernetes/pull/24431#issuecomment-211616486) in the original PR but at the time it was too much to ask the user and the PR-title method was familiar.

The current procedure is fairly streamlined:

1. Open a new PR
1. Set your state
    * Add a release note title OR
    * Update the PR template OR
    * Clear the PR template
1. Get on with your life

This makes for a fairly friction-free contributor experience.

If we want to rely solely on the PR template body only we'll have to deal somehow with a few new states.

1. Open a new PR
1. Set your state
    * Title is always ignored
    * template is cleared - what do we do?
    * template is there, but there's no text to indicate `NONE` or some release note
    * template is there, filled in, but the free-form label indicators within the template are incomplete or incorrect. 

Going this direction means we'll likely have a lot more back and forth from the munger within the PR conversation.  If that's acceptable and there are clear benefits over the current method, then it is something worth considering.

**Comment by grodrigues3** [comment]
Thanks for the quick response.  #1908 responses indicate that a blocker for reviewers (and the reason lots of people want maintainers privilege) is adding the `release-note` label, or the `release-note-none` label.  People would like to remove the `release-note-needed` label so PRs can move forward.  

Commenting `/lgtm` already allows people to lgtm files without explicitly adding labels

As far as what happens if the release-note block is removed entirely from the template, or if someone does not fill it out correctly, it looks like [the bot explains what to do]  
(https://github.com/kubernetes/kubernetes/pull/32730)  

Can you think of other ways to get the release-note-* labels added without doing it this way?

cc
@bgrant0607

**Comment by david-mcmahon** [comment]
Why not allow /release-note-* and last one wins?

**Comment by bgrant0607** [comment]
@david-mcmahon Filling out the template correctly seems like it should be enough, without a separate command.

**Comment by bgrant0607** [comment]
@grodrigues3 Was this addressed by #1930?

**Comment by grodrigues3** [comment]
Yes, it was.  I'll close the issue.
