### ISSUE TITLE
[vagrant openstack] docker not running before task opencontrail | Build docker container

### ISSUE THREAD

**Issue by rawlingsj** [kubernetes/contrib#193]
During the vagrant up I get an error as docker isn't running in the image during the **opencontrail | Build docker container** task, I've worked around it by adding `service: name=docker state=started` to https://github.com/kubernetes/contrib/blob/master/ansible/roles/docker/tasks/main.yml#L49 but I'm pretty sure my lack of understanding here means that's not the right answer.

Using fedora 22 cloud base image from https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-22-20150521.x86_64.qcow2

```
TASK: [opencontrail | Build docker container] *********************************
skipping: [kube-node-1]
skipping: [kube-node-2]
failed: [kube-master] => {"changed": true, "cmd": ["docker", "build", "-t", "opencontrail/kmod_fedora22-4.0.4-301.fc22.x86_64", "fedora22-4.0.4-301.fc22.x86_64"], "delta": "0:00:00.023080", "end": "2015-10-20 18:01:26.362457", "rc": 1, "start": "2015-10-20 18:01:26.339377", "warnings": []}
stderr: Post http:///var/run/docker.sock/v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=opencontrail%2Fkmod_fedora22-4.0.4-301.fc22.x86_64&ulimits=null: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

**Comment by pedro-r-marques** [comment]
@rawlingsj I believe that PR #256 should have fixed this issue. The docker play is starting the docker daemon as an handler; and handlers run after the play is complete. That was probably not happening when "docker" was invoked as a dependency of the opencontrail play but by separating docker as its own play, i believe that this should be addressed.
