### ISSUE TITLE
[Nginx Ingress Controller] errors during deployments

### ISSUE THREAD

**Issue by wincus** [kubernetes/contrib#1933]
When a k8s deployment takes place some pods are terminated by the scheduler using whatever deployment strategy is defined. As the nginx controller pulls the k8s state in time intervals, a  small time window takes place where the pod is not longer running ( has been terminated ) but it is still present as backend in the nginx controller configuration file.

This has as consequence that the client might get an error from the service that is being deployed if his request is routed to the terminated pod. 

We have been able to lower down the amount of errors a client gets during deployments setting the `upstream-fail-timeout` and `upstream-max-fails` annotations to the ingress object.
Unfortunately this has two problems:
1. as stated here [1] nginx will do "Passive" health checks, meaning that we can't reduce the amount of errors to `0` during deployments.
2. We can't use a fast rolling update strategy for deployments ( aka `maxSure:100%` ) cause we could have a nginx configuration with no valid backends during n seconds if all the old pods are terminated before the nginx controller updates its configuration.

Is there a best practice / known way to avoid the errors described above? 

[1] http://nginx.org/en/docs/http/load_balancing.html#nginx_load_balancing_health_checks

**Comment by aledbf** [comment]
>  As the nginx controller pulls the k8s state in time intervals

the controller watches for changes in the endpoints (time intervals). 
The real problem here is that nginx does not exposes an API so in order to apply a change a reload is needed. [Here's how is done](http://nginx.org/en/docs/control.html#reconfiguration). (you should not see a disruption)

> Is there a best practice / known way to avoid the errors described above?

Please check the new pods are available (using a readinessProbe and livenessProbe) before the removal of the old ones. Also check the `terminationGracePeriodSeconds` is not 0 (in order to allow finish the current connections)

**Comment by aledbf** [comment]
@wincus please check [this article](https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/) (omit the node.js content)

**Comment by wincus** [comment]
hey @aledbf thanks for your response .... really appreciate! That article clarifies a lot the problem.

> Please check the new pods are available (using a readinessProbe and livenessProbe) before the removal of the old ones

Even when new pods are ready to accept requests and k8s services have been updated, we have seen that the nginx controller still sends traffic to old pods until its configuration is refreshed. Seems like there is a longer delay for the nginx controller to catch up the state compared with internal k8s service state.

In the [the article](https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/) you posted is mentioned that:

> App waits (failureThreshold * periodSecond) before it starts to shut down - to make sure that the Service is getting notified via readinessProbe fail

Which I think is the key point to consider. We can make the app to wait n seconds after has gotten the SIGTERM signal to give time to nginx to update its configuration and remove backends that are in terminating mode.

So my question is:  how often you think the nginx controller will pull the state + reload the conf? Is this the value that defines that time period https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/main.go#L70?

Thanks!

**Comment by aledbf** [comment]
> Is this the value that defines that time period 

you can see how it works [here](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/controller.go#L252) and [here](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/controller.go#L164) .
Basically we watch the multiple resources and a function is invoked depending if the event is adding, updating or removing a resource. 
This approach allows to have a local store and process just the delta improving the response time and avoiding unnecessary queries to the api-server. If you add the flag `--v=3` you can see when an event triggers an update.

The period of time you see is how often you want a full resync.

**Comment by wincus** [comment]
thanks for the info @aledbf .... we were able to deploy without errors by taking ideas from the article you shared. Specifically we now trap the SIGTERM signal k8s sends and trigger a graceful shutdown.

Thanks Again!
