### ISSUE TITLE
Ingress whitelist doesn't seem to be working

### ISSUE THREAD

**Issue by ericuldall** [kubernetes/contrib#1941]
I'm trying to restrict my ingress to a certain IP using the following doc (https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/whitelist) and it doesn't seem to be working. 

I'm running in a gke 1.4 cluster.

Here's my ingress yaml:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/backends: '{"k8s-be-30148--d986a7842f3541a8":"HEALTHY","k8s-be-30419--d986a7842f3541a8":"HEALTHY","k8s-be-31619--d986a7842f3541a8":"HEALTHY"}'
    ingress.kubernetes.io/forwarding-rule: k8s-fw-default-site-ingress--d986a7842f3541a8
    ingress.kubernetes.io/target-proxy: k8s-tp-default-site-ingress--d986a7842f3541a8
    ingress.kubernetes.io/url-map: k8s-um-default-site-ingress--d986a7842f3541a8
    ingress.kubernetes.io/whitelist-source-range: 1.2.3.4/32
  creationTimestamp: 2016-10-26T19:20:14Z
  generation: 3
  name: [REDACTED]
  namespace: default
  resourceVersion: "76990"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/[REDACTED]
  uid: [REDACTED]
spec:
  rules:
  - host: a.site.com
    http:
      paths:
      - backend:
          serviceName: a
          servicePort: 80
  - host: b.site.com
    http:
      paths:
      - backend:
          serviceName: b
          servicePort: 80
status:
  loadBalancer:
    ingress:
    - ip: [REDACTED]
```

The ingress is routing traffic to the correct hosts, but the whitelist does not seem to take affect.
Does the whitelist even apply to hosts?

**Comment by aledbf** [comment]
@ericuldall please check if the nginx log is receiving the correct IPs (externals) and not from your local cluster.

**Comment by ericuldall** [comment]
Where do I find the nginx log?

**Comment by ericuldall** [comment]
I'm seeing the proper ip in the GCL Load Balancer access log.

**Comment by aledbf** [comment]
You need to check the nginx ingress controller logs.

**Comment by ericuldall** [comment]
Is this the info? There is nothing explicitly labeled as nginx, that I can see.
```
httpRequest: {
  requestMethod: "GET"    
  requestUrl: "http://a.site.com/"    
  requestSize: "1017"    
  status: 200    
  responseSize: "1825"    
  userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"    
  remoteIp: "[MY IP]"    
  serverIp: "[INTERNAL IP]"    
 }
```

**Comment by aledbf** [comment]
@ericuldall use `kubectl logs <nginx ingress pod>`
You should see something like:
```
200.75.12.234 - 10.0.0.49 - - [27/Oct/2016:19:52:04 +0000] "GET /logout-timeout HTTP/2.0" 302 315 "https://my-site.com/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0" 350 0.027 10.3.0.219:80 56 0.027 302
```
The first field is the client IP

**Comment by ericuldall** [comment]
There is no nginx pod. The Ingress is an L7 Load Balancer resource in Google Cloud

**Comment by ericuldall** [comment]
And I now see that this example I was using is an nginx example. So i'm guessing the annotation does not work in the default GKE setup. Or should it?

**Comment by aledbf** [comment]
> So i'm guessing the annotation does not work in the default GKE setup. Or should it?

Right. The annotation only works in the nginx ingress controller.

**Comment by ericuldall** [comment]
Okay. TY. Sorry for the mistaken interpretation of that doc.

**Comment by krish7919** [comment]
@aledbf : Will ingress rules work for a TCP stream? Or a heavily configured nginx running as a deployment inside kubernetes but which wants to see the real 'source' IPs?

**Comment by aledbf** [comment]
@krish7919 what are you trying to do?

**Comment by krish7919** [comment]
@aledbf I was trying to whitelist TCP clients based on the source IP in nginx.
Which I did because of [this in Azure](https://kubernetes.io/docs/tutorials/services/source-ip/), but wanted a cloud agnostic way to do it. Will ingress work here?
