### ISSUE TITLE
[Nginx ingress controller] TCP/UDP upstreams need to be sorted

### ISSUE THREAD

**Issue by pesho** [kubernetes/contrib#1947]
cc @aledbf 

I needed to expose an FTP service (don't ask :scream_cat:). FTP is a horrible protocol which requires exposing multiple ports for "passive mode" to work. I managed quickly to achieve that using the Nginx ingress controller's support for exposing TCP services, using a ConfigMap like this:

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-conf-tcp
  namespace: kube-system
data:
  21: "mynamespace/upload:21"
  2100: "mynamespace/upload:2100"
  2101: "mynamespace/upload:2101"
  2102: "mynamespace/upload:2102"
  2103: "mynamespace/upload:2103"
  2104: "mynamespace/upload:2104"
  2105: "mynamespace/upload:2105"
  2106: "mynamespace/upload:2106"
  2107: "mynamespace/upload:2107"
  2108: "mynamespace/upload:2108"
  2109: "mynamespace/upload:2109"
  2110: "mynamespace/upload:2110"
  2111: "mynamespace/upload:2111"
  2112: "mynamespace/upload:2112"
  2113: "mynamespace/upload:2113"
  2114: "mynamespace/upload:2114"
  2115: "mynamespace/upload:2115"
  2116: "mynamespace/upload:2116"
  2117: "mynamespace/upload:2117"
  2118: "mynamespace/upload:2118"
  2119: "mynamespace/upload:2119"
```

(the `mynamespace/upload` service exposes the same ports, of course)

A couple of hours later I started receiving alerts that the service is down, and investigation showed that Nginx was constantly reloading (every sync interval), which eventually lead to memory exhaustion due to the many old processes. Upon examining the generated `nginx.conf` within pods, it turned out that the order of TCP servers/upstreams is random and changes on each sync, which leads to Nginx reloading every time.

I think that TCP and UDP upstreams need to be sorted in order to have deterministic result, as is already done with HTTP ingress resources.

P.S. A mildly related question: Early versions of the Nginx ingress controller had support for updating the endpoints without reloading, using Lua scripts. Why was this approach abandoned? Looks like it was dropped in #570, but no rationale was given for the reason.

**Comment by aledbf** [comment]
> Upon examining the generated nginx.conf within pods, it turned out that the order of TCP servers/upstreams is random and changes on each sync, which leads to Nginx reloading every time.

Right. This is being done in http/s upstreams [here](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/controller.go#L823)
I will add the same logic to tcp and udp services.


> Why was this approach abandoned?

Just because it was like magic :) meaning there was only 1 server, no upstreams, etc and you needed to know lua. The idea behind the change was to simplify the code and lower the entry barrier to new contributors.
