### ISSUE TITLE
[Nginx ingress controller] Additional SSL options

### ISSUE THREAD

**Issue by pesho** [kubernetes/contrib#1949]
A couple of suggestions for additional SSL options:
- An option to enable OCSP stapling. Should be as easy as adding the [ssl_stapling](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling) directive. I also think it should be on by default, as it has no significant drawbacks and can speed up the first connection.
- An option to specify the [secret key](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_ticket_key) used to encrypt the TLS session tickets. This is desirable when running multiple instances of the load balancer. The option should accept a file path, which could be provided using a Secret volume mount.

Of course, both of these could be achieved using a custom Nginx template.

**Comment by eXeDK** [comment]
What is the status on this? Especially the OCSP stapling features I think would be nice.

**Comment by ccatlett2000** [comment]
I fully support adding these options
Could enabling it by default cause backwards compatibility problems?

**Comment by ccatlett2000** [comment]
Should this be opened elsewhere?
