### ISSUE TITLE
[ansible] github-release option failing due to flannel timeouts

### ISSUE THREAD

**Issue by wattsteve** [kubernetes/contrib#1960]
I have 4 nodes. 1 Master and 3 Workers. I am running Fedora 24 on all of them and have run dnf -y update on all of them as well. I ran the same experiment earlier today with the packageManager option and everything worked and I had a working Kube 1.2.2 cluster. However, I want a Kube 1.4 cluster, so I used the github-release option on an identical setup but new cluster and it fails with the exception below:

TASK [flannel : Start flannel] *************************************************
changed: [leader.kube]
fatal: [node-2.kube]: FAILED! => {"changed": false, "failed": true, "msg": "Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [node-1.kube]: FAILED! => {"changed": false, "failed": true, "msg": "Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [node-3.kube]: FAILED! => {"changed": false, "failed": true, "msg": "Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}

**Comment by ingvagabund** [comment]
@wattsteve can you ssh to any of the machines, run ``systemctl start flannel`` manually and get output of ``systemctl status flannel`` (if there are some logs). Or run the flannel binary itself and get its error output?

**Comment by ingvagabund** [comment]
Reproduced it with Vagrant. The problem is flanneld service calls ``/usr/bin/flanneld -etcd-endpoints=${FLANNEL_ETCD} -etcd-prefix=${FLANNEL_ETCD_KEY} $FLANNEL_OPTIONS`` where ``FLANNEL_ETCD`` is set to ``http://kube-master-1:2379``. Looking into ``/etc/hosts`` there is no entry for ``kube-master-1``. I am curious how much ansible 2.2 changes from 2.1 since with the 2.1 this does not happen. Investigating further.

**Comment by ingvagabund** [comment]
Ok, with ansible 2.1 the etcd looks like this:
```
127.0.0.1 kube-node-1 kube-node-1  localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

192.168.121.87 kube-master-1
192.168.121.105 kube-node-1
192.168.121.2 kube-node-2
```

With ansible 2.1, the last three lines with cluster member ips are gone.

**Comment by ingvagabund** [comment]
Hmm, 2.1:
```
TASK [Build hosts file] ********************************************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{groups['all']}}').
This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{groups['all']}}').
This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{groups['all']}}').
This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
changed: [kube-master-1] => (item=kube-master-1)
changed: [kube-node-1] => (item=kube-master-1)
changed: [kube-node-2] => (item=kube-master-1)
changed: [kube-master-1] => (item=kube-node-1)
changed: [kube-node-2] => (item=kube-node-1)
changed: [kube-node-1] => (item=kube-node-1)
changed: [kube-master-1] => (item=kube-node-2)
changed: [kube-node-1] => (item=kube-node-2)
changed: [kube-node-2] => (item=kube-node-2)
```

2.2:
```
TASK [Build hosts file] ********************************************************
skipping: [kube-node-1] => (item=groups['all']) 
skipping: [kube-master-1] => (item=groups['all']) 
skipping: [kube-node-2] => (item=groups['all']) 
```

So far to ignoring warnings. @wattsteve what is content of ``/etc/hosts`` inside of ``node-[1-3].kube``?
