### ISSUE TITLE
[Nginx ingress controller] file open limit

### ISSUE THREAD

**Issue by dgoujard** [kubernetes/contrib#1966]
Hi,

I created a cluster with kubeadm on ubuntu 16.04.1 lts (really awesome tool), all pods works great except the nginx ingress controller.
I got this error : 
` [alert] 5#5: setrlimit(RLIMIT_NOFILE, 131072) failed (1: Operation not permitted)`

On a clean ubuntu image with docker i can reproduce this issue with this config : 

```
worker_processes 1;

pid /run/nginx.pid;

worker_rlimit_nofile 131072;

pcre_jit on;

events {
    multi_accept        on;
    worker_connections  16384;
    use                 epoll; 
}

http {
    real_ip_header      X-Forwarded-For;
    set_real_ip_from    0.0.0.0/0;

    real_ip_recursive   on;
    sendfile            on;
    aio                 threads;
    tcp_nopush          on;
    tcp_nodelay         on;

    log_subrequest      on;

    reset_timedout_connection on;

    keepalive_timeout 75s;

    types_hash_max_size 2048;
    server_names_hash_max_size 512;
    server_names_hash_bucket_size 64;

    include /etc/nginx/mime.types;
    default_type text/html;

    client_max_body_size "1m";

    error_log  /var/log/nginx/error.log notice;

    # Map a response error watching the header Content-Type
    map $http_accept $httpAccept {
        default          html;
        application/json json;
        application/xml  xml;
        text/plain       text;
    }

    map $httpAccept $httpReturnType {
        default          text/html;
        json             application/json;
        xml              application/xml;
        text             text/plain;
    }

    server_name_in_redirect off;
    port_in_redirect off;


    # default server for services without endpoints
    server {
        listen 8181;
        set $proxy_upstream_name "-";

        location / {
            return 503;
        }
    }
}
```

`docker run -v /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf:ro gcr.io/google_containers/nginx-slim:0.9`

It's a limit with default ubuntu settings on file open. I didn't find how to bypass this limitation, i tried this : 
```
cat /etc/security/limits.d/nofile.conf
* soft nofile 10000
* hard nofile 1000000
```

How can i get this image running correctly ? i think i will not be this onlyone this the issue, it affect all ubuntu user with nginx-slim image (so Nginx ingress controller)

**Comment by aledbf** [comment]
@dgoujard you need to change this in `systemd` (`docker.service`)
adding something like:
```
[Service]
LimitNOFILE=1048576
LimitNPROC=1048576
```

**Comment by dgoujard** [comment]
@aledbf Thank you for the reply but it didn't works, i edited` /lib/systemd/system/docker.service` and restarted systemctl and docker but i get the same error
```
systemctl daemon-reload
/etc/init.d/docker restart
[ ok ] Restarting docker (via systemctl): docker.service.
```

In the default docker.service the value are already unlimited : 
```
LimitNOFILE=infinity
LimitNPROC=infinity
```
maybe now we need to pass the limit on run command ? http://stackoverflow.com/a/31474407  works for me but i didn't know how to pass this parameter with kubernetes on pod.

**Comment by dgoujard** [comment]
With privileged mode in the pod it works.
May be it can be added to the documentation ? i think it's related to ubuntu 16.04 or maybe docker version.

Now i have still a issue with my ingress controller, the port is not binded in the host but it's an issue with CNI https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-257797931 https://github.com/kubernetes/kubernetes/issues/31307

**Comment by aledbf** [comment]
@dgoujard please send information about the kernel and docker version

**Comment by aledbf** [comment]
> With privileged mode in the pod it works.

This is not required. Let me see if I can replicate the error.
did you follow some guide with kubeadm?

**Comment by dgoujard** [comment]
@aledbf 
I followed the kudeadm guide http://kubernetes.io/docs/getting-started-guides/kubeadm/ with ubuntu 16.0.4.

To reproduce the setrlimit error you didn't need to install kubernetes (just docker), it's more likely an docker/os issue.
If you run this command : 
`docker run -v /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf:ro gcr.io/google_containers/nginx-slim:0.9`
With this nginx.conf you will get the same error : 
```
worker_processes 1;

pid /run/nginx.pid;

worker_rlimit_nofile 131072;

pcre_jit on;

events {
    multi_accept        on;
    worker_connections  16384;
    use                 epoll; 
}

http {
    real_ip_header      X-Forwarded-For;
    set_real_ip_from    0.0.0.0/0;

    real_ip_recursive   on;
    sendfile            on;
    aio                 threads;
    tcp_nopush          on;
    tcp_nodelay         on;

    log_subrequest      on;

    reset_timedout_connection on;

    keepalive_timeout 75s;

    types_hash_max_size 2048;
    server_names_hash_max_size 512;
    server_names_hash_bucket_size 64;

    include /etc/nginx/mime.types;
    default_type text/html;

    client_max_body_size "1m";

    error_log  /var/log/nginx/error.log notice;

    # Map a response error watching the header Content-Type
    map $http_accept $httpAccept {
        default          html;
        application/json json;
        application/xml  xml;
        text/plain       text;
    }

    map $httpAccept $httpReturnType {
        default          text/html;
        json             application/json;
        xml              application/xml;
        text             text/plain;
    }

    server_name_in_redirect off;
    port_in_redirect off;


    # default server for services without endpoints
    server {
        listen 8181;
        set $proxy_upstream_name "-";

        location / {
            return 503;
        }
    }
}
```
`[alert] 5#5: setrlimit(RLIMIT_NOFILE, 131072) failed (1: Operation not permitted)`

**Comment by dgoujard** [comment]
`Kernel info : Linux ubuntutest 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Docker version : 
```
root@ubuntutest:/home/ubuntu# docker info
Containers: 19
 Running: 0
 Paused: 0
 Stopped: 19
Images: 1
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 46
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 975 MiB
Name: ubuntutest
ID: TUIB:KVHD:LXJU:3VBI:GKMO:NXMR:NIWP:O67C:XXXX:OHHJ:N42U:7TYB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by jhorwit2** [comment]
I'm also getting this issue except on centos. My systemd file has unlimited. 

```
docker info
Containers: 46
 Running: 21
 Paused: 0
 Stopped: 25
Images: 20
Server Version: 1.12.4
Storage Driver: devicemapper
 Pool Name: docker-9:1-59244903-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.77 GB
 Data Space Total: 107.4 GB
 Data Space Available: 103.6 GB
 Metadata Space Used: 6.66 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.22 GiB
Name: <thing>
ID: 2ZH5:IUAP:3NF5:KZ45:6X2O:U7YJ:2JVK:K2K7:ZU7H:T57B:V36T:RY2S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Comment by jhdehart** [comment]
I'm also encountering this issue on both CentOS 7 and Ubuntu 16.04.  I can supply more information if requested.

`
$ docker info
Containers: 18
 Running: 17
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-253:0-68730613-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.11 GB
 Data Space Total: 107.4 GB
 Data Space Available: 49.56 GB
 Metadata Space Used: 3.756 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.626 GiB
Name: kubes3
ID: PZ3Z:P4AC:5LSK:SUP7:46EM:ZQ5D:PCRY:QMGT:AOSX:3XVG:YYKU:LOJ3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8`

**Comment by xinzhongtianxia** [comment]
I'm also encountering this issue on both CentOS7 and the Docker version is 1.12.6

**Comment by aledbf** [comment]
Next version reads the `fs.file-max` value.
