### ISSUE TITLE
Mungegithub loop takes too long

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1967]
As we go over each issue in the bot's main loop, we go over issues like https://github.com/kubernetes/kubernetes/issues/33388 which has some 2500 comments, it spends some 20 seconds or so (and lots of API calls) to fetch comments.
Do we really need to look at these issues completely? 

cc @eparis

**Comment by apelisse** [comment]
I'll see if I have something smart to say in the next 24h :-)

**Comment by apelisse** [comment]
Yes, this is because of the flake nagger. It reads comments on issues. Not sure how to fix that right now.

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1623
