### ISSUE TITLE
Corporate contrib stats: CLA signature logs needed from CNCF

### ISSUE THREAD

**Issue by ryanj** [kubernetes/contrib#1972]
In order to quantify the amount of impact that various corporate groups are making, we need an effective way to establish and maintain a map of corporate affiliations per each individual contributor.

The CLA signing process is an excellent forcing function that will help ensure that this mapping is accurate and up-to-date.

CNCF should provide logs with the following information to help make these calculations independently verifiable by different corporate groups:

1. cla_signature_timestamp
2. github_id
3. corporate_affiliation (or "individual contributor" for CLA signatures without any corporate affiliation)

The CLA signature timestamp is needed to keep track of changes in corporate affiliations over time.

**Comment by ryanj** [comment]
FYI @foxish

**Comment by foxish** [comment]
cc @caniszczyk @emsearcy

**Comment by foxish** [comment]
cc @kubernetes/contributor-experience

**Comment by apelisse** [comment]
Should the data be public though?

**Comment by ryanj** [comment]
@apelisse good question. 
I think public disclosures and transparency around corporate involvement will be needed in order to ensure that the community can reliably answer questions of "which corporations are involved?" and "what are they involved in? / what are they doing?".

Details that are not required include: email addresses or real names of individual contributors.

**Comment by bgrant0607** [comment]
Handled by https://github.com/cncf/gitdm
