### ISSUE TITLE
How to use ingress controller for multiple namespaces in a K8s cluster?

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#1978]
Hi, K8s guys,

We plan to deploy multiple namespaces in a K8s cluster. At present we have an nginx ingress controller for default namespace and one nginx ingress controller service which replica number is 2 for each namespaces. We check the nginx.conf in the controllers, and we find that the nginx.conf includes configuration(upstream, locations and proxy_pass, etc) for the service in other namespaces. 

How can we isolate the ingress controllers for each namespace? Or we do it in a wrong way.

Here I want to mention that the content of the yamls are the same except the namespace is different.

Thanks

**Comment by aledbf** [comment]
@tjliupeng you can use the flag `--watch-namespace` to limit the scope to just one namespace

**Comment by tjliupeng** [comment]
@aledbf, any reference for this flag? I google it and found no formal introduction about it. I just want to know how to use it? Is this flag is for controller?

**Comment by aledbf** [comment]
@tjliupeng here https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/main.go#L73

**Comment by tjliupeng** [comment]
Thanks.

**Comment by furkanmustafa** [comment]
just for reference; new link for above is here => https://github.com/kubernetes/ingress-nginx/blob/56036ddc57343e5260f8f0d3d862dfacbd064200/cmd/nginx/flags.go
