### ISSUE TITLE
Cluster-autoscaler: add profiles so that CA can support multiple consistent strategies.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1984]
Currently you need to play with multiple flags with hard to predict results.

The profiles would be:
* Super aggressive - fast scale up, down, aggressive estimator etc.
* Conservative - slow scale ups, down, "calm" estimator etc
* Regular

cc: @fgrzadkowski @piosz

**Comment by fgrzadkowski** [comment]
I think we should be very careful with adding such profiles as it'd be a decision that would affect API, so hard to change. Once we really understand user needs and what they want to achieve, it may turn out that we should just improve current logic without actually exposing knobs to the users.

**Comment by mwielgus** [comment]
Profiles seem to be not really needed so far. Closing.
