### ISSUE TITLE
Cluster-autoscaler: reduce the number of HA-related logs

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1994]
Currently there is lots of renewed lease logs.

cc: @davidopp @fgrzadkowski @jszczepkowski @piosz

**Comment by fgrzadkowski** [comment]
Can you please explain which exactly line is too excessive? Looking at the code it seems that the only time we log something as `Info` is when a change happens, e.g. we become a leader, or we loose leadership. All other logs are logged as V(4).

https://github.com/kubernetes/kubernetes/blob/master/pkg/client/leaderelection/leaderelection.go

**Comment by fgrzadkowski** [comment]
@mwielgus explained to me offline which log messages he means and it is working as intended. V(4) is supposed to be very verbose. We added `--v=4` in CA command line, because we are currently debugging number of issues and we need all logs.
