### ISSUE TITLE
Cluster-autoscaler: scale on schedule

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#1995]
if I know a set of events that might produce higher load (dates/times, eg: sports events), I can specify a timetable and have the scaler preemptively scale instead of taking a hit

**Comment by davidopp** [comment]
There's this
https://github.com/kubernetes/contrib/tree/master/diurnal
but I think it would fight with autoscaler (autoscaler would just scale down before the load arrived).

For one-time events the user could adjust min_nodes ahead of time. For diurnal pattern, the autoscaler could theoretically model it and predict. For things like sporting events I'm not sure there's a good solution other than having good responsiveness once a load spike hits (seems like a configuration nightmare).

**Comment by bprashanth** [comment]
I can just specify a list of date/time and go about doing whatever I want right (vs waiting for that date/time, scaling up, then doing whatever i want)?

**Comment by davidopp** [comment]
I'm not doubting that you can do it, it just seems not very elegant to feed in the entire year's worth of sporting events ahead of time (in a ConfigMap, I guess?), modify it as changes occur, delete entries after they happen so it doesn't grow unbounded in length, etc. Presumably for each one you'd need an estimate of the intensity too (Super Bowl might require 200 nodes, normal events might require 50 nodes). I still think improving the responsiveness of the scaleup (maybe there can be a parameter for how aggressive to be in scaling up) might be better.

**Comment by davidopp** [comment]
@mwielgus

**Comment by bprashanth** [comment]
Yeah it surely is better, I think we're bounded by the time it takes to create a node, provision it with gke components, then register with apiserver though. When compared to pod startup time this is an eternity.

**Comment by mwielgus** [comment]
I agree with @davidopp. We should focus on making the scale operations faster and/or possibly adding some slack in resources (see #2251). Closing.
