### ISSUE TITLE
Is it possible to generate nginx.conf which the server in upstream uses K8s FQDN instead of IP Address in the ingress controller?

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#1996]
Hi, 

With the ingress controller, in the upstream of the nginx.conf, the server is IP address as follow;
upstream xxxx-svc-8080 {
        #least_conn;
        sticky;
        server 172.77.52.7:8080 max_fails=0 fail_timeout=0;
        server 172.77.57.6:8080 max_fails=0 fail_timeout=0;
}

Is it possible to generate the server with FQDN, such as [pod-name].[namespace].pod.cluster.local instead of IP Address?

Thanks

**Comment by aledbf** [comment]
@tjliupeng this is possible but requires a changes an the use of a resolver in nginx. The resolver in nginx is tricky and not good with updates and high number of queries. Also this introduce a percibible latency serving requests

**Comment by tjliupeng** [comment]
Ok. Thanks. So we won't consider this requirement at present.
