### ISSUE TITLE
How to config the nginx.tmpl for session sticky according to cookie JSESSIONID in nginx ingress controller?

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#1997]
Hi,

In the default nginx.tmpl, the session sticky setting for upstream is as follow:

{{ if $cfg.enableStickySessions -}}
sticky hash=sha1 httponly;

Does this setting support the session sticky? If yes, what is the session sticky by?  cookie or others?

In our environment, we try to access http://xxx.xxx.xxx.xxx/webtier, and I config the upstream as follow:
upstream itsma-sm-webtier-svc-8080 {
        sticky name=JSESSIONID hash=sha1 httponly;
        server 172.77.52.7:8080;
        server 172.77.57.6:8080;
}

Then I can't login http://xxx.xxx.xxx.xxx/webtier, it always show the login page. I check the request and response, the cookie name is JSESSIONID. If the configuration is as follow:
upstream itsma-sm-webtier-svc-8080 {
        sticky;
        server 172.77.52.7:8080;
        server 172.77.57.6:8080;
}

Then I login successfully.

What's wrong with my configuration?

Thanks
Liu Peng

**Comment by aledbf** [comment]
@tjliupeng the module to add sticky session support is https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng
This adds a new cookie with the name `route` (the name is not configurable now but you can change the template for this purpose)

**Comment by tjliupeng** [comment]
@aledbf , what do you mean "the name is not configurable now but you can change the template for this purpose"? I can change the template for what purpose? My purpose or using the cookie route?
