### ISSUE TITLE
AWS Cluster Autoscaler E2E Tests

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/contrib#2004]
I'd like to help add some E2E tests for the cluster autoscaler in AWS. Where would be a good place to start? Are there examples for the GCE E2E test suite I can reference?

**Comment by andrewsykim** [comment]
@mwielgus

**Comment by mwielgus** [comment]
@justinsb Could you please advice?

**Comment by zmerlynn** [comment]
@kubernetes/sig-aws

**Comment by chrislovecnm** [comment]
@andrewsykim sorry to keep you hanging, but all of us are at kubecon. @justinsb have you wrote a test like this? I know that there was a bunch of disscusion today about arch limitations of autoscalers today in ec2.

**Comment by andrewsykim** [comment]
Thanks for getting back to me @chrislovecnm, kubecon sounds like a blast, wish I was there! I did some digging into the current test suite and it seems like https://github.com/kubernetes/kubernetes/blob/master/test/e2e/cluster_size_autoscaling.go would be a good place to start. I'm just not sure what we use to get the cluster up for E2E testing and where the cluster autoscaler implementation should be added, was hoping to get some guidance on that.

**Comment by andrewsykim** [comment]
Seems like in the jenkins test suite we rely on `kube-up` to E2E tests, I also opened https://github.com/kubernetes/kubernetes/pull/36387 in preparation, but it seems like kube-up is deprecated.

**Comment by chrislovecnm** [comment]
@andrewsykim @zmerlynn can assist with this a tad.

**Comment by zmerlynn** [comment]
@andrewsykim: I also have `kops` e2e tests in Jenkins, if you want to get it working there.

**Comment by andrewsykim** [comment]
@zmerlynn whichever e2e test suite is preferred works for me. Does kops add cluster autoscaler to the cluster or is that something we would have to add?

**Comment by chrislovecnm** [comment]
/cc @arun-gupta 

Something else that needs testing tlc. Will let you coordinate with aws engineering

**Comment by chrislovecnm** [comment]
Is there a project manager that I can cc on these?

**Comment by arun-gupta** [comment]
@chrislovecnm @bchav will be the contact person from AWS for this.

**Comment by andrewsykim** [comment]
The cluster autoscaler was moved to https://github.com/kubernetes/autoscaler
