### ISSUE TITLE
Can least_conn and sticky work together in the nginx controller?

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#2005]
Hi,

In my environment, one upstream in nginx.conf include both

least_conn;
sticky hash=sha1 httponly;

Then in the nginx log I found the error message: 
E1108 04:33:07.380779       1 command.go:92] failed to execute nginx -s reload: 2016/11/08 04:33:07 [emerg] 156#156: You can't use sticky with another upstream module in /etc/nginx/nginx.conf:254

Is it possible to make least_conn and sticky work together?

Thanks
Liu Peng

**Comment by aledbf** [comment]
> Is it possible to make least_conn and sticky work together?

No. You can choose sticky sessions or custom balancing algorithm.

**Comment by tjliupeng** [comment]
@aledbf , for a new session, what algorithm is used to decide an upstream server for this session and then assign a cookie "route" to it?
