### ISSUE TITLE
Mungegithub doesn't handle identical blocking and non-blocking jobs

### ISSUE THREAD

**Issue by apelisse** [kubernetes/contrib#2006]
If a job is both in the non-blocking queue and the blocking queue, everything starts acting funny (can someone say what's actually broken?).

We should probably:
- [ ] Validate/test that the configuration is sane as early as possible
- [ ] Act properly even if the configuration is slightly misleading: consider jobs in both lists to be blocking.

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1630
