### ISSUE TITLE
[Ingress] 0.8.4 Release?

### ISSUE THREAD

**Issue by r2d4** [kubernetes/contrib#2010]
I understand ingress is being moved to kubernetes/ingress so if issues are being move there feel free to close this and I'll reopen there.  

Could we push a 0.8.4 release of the nginx-ingress controller?  The last one was released awhile ago

```
$ gcloud alpha container images list-tags gcr.io/google_containers/nginx-ingress-controller

820c338dc22e  0.8.3  2016-08-22T11:59:22
```

**Comment by aledbf** [comment]
@r2d4 I'm sorry for the delay. As you realized Ingress is being moved to `kubernetes/ingress`.
The reason for the delay is the refactoring done to the controller (temporal place https://github.com/aledbf/ingress-controller)

**Comment by whereisaaron** [comment]
Could the already merged changes here on `contrib` perhaps be pushed out as an 0.8.4.alpha1 or alternatively an alpha `kubernetes/ingress` release?

It seems like lots of important small improvements and fixes here over the last 6 months are neither being used nor tested while the refactoring project happens. If we had even an untested alpha or rc release from either `contrib` or `ingress` then we could contribute to testing and share some of that work.

**Comment by aledbf** [comment]
> It seems like lots of important small improvements and fixes here over the last 6 months are neither being used nor tested while the refactoring project happens

That's not correct. Here's is where I put the temporal images when I close a PR
 https://quay.io/repository/aledbf/nginx-ingress-controller?tab=tags

0.55 contains the refactoring from the PR https://github.com/kubernetes/ingress/pull/95

**Comment by whereisaaron** [comment]
> Here's is where I put the temporal images when I close a PR
https://quay.io/repository/aledbf/nginx-ingress-controller?tab=tags
0.55 contains the refactoring from the PR kubernetes/ingress#95

Thanks @aledbf that's great news they are builds we can test! And thanks for the 0.55 reference. Is there a way to map between those images and the PR that created them? Or the other direction, from the PR -> Travis CI -> image?

**Comment by aledbf** [comment]
>  And thanks for the 0.55 reference. Is there a way to map between those images and the PR that created them? 

Not yet. I've been working in that too but still is a work in progress.
https://github.com/kubernetes/ingress/tree/master/hack/e2e-internal

**Comment by r2d4** [comment]
Closing this, there are now pre-alpha releases in the kubernetes/ingress repo https://github.com/kubernetes/ingress/releases
