### ISSUE TITLE
Peer-finder unable to cope with non standard cluster domain

### ISSUE THREAD

**Issue by SchwarzM** [kubernetes/contrib#2011]
Currently the peer-finder is hardcoded to "svc.cluster.local" which is the default but cannot be overridden.

https://github.com/kubernetes/contrib/blob/master/pets/peer-finder/peer-finder.go#L35

myName constructed here is faulty for us:
https://github.com/kubernetes/contrib/blob/master/pets/peer-finder/peer-finder.go#L86

Ending in an endless loop here:
https://github.com/kubernetes/contrib/blob/master/pets/peer-finder/peer-finder.go#L98

Would it be okay if I submit a patch reading the cluster domain from ENV ?

Kind regards
Marian Schwarz

**Comment by Kuckkuck** [comment]
+1

**Comment by SchwarzM** [comment]
Done with #2013
