### ISSUE TITLE
Ingress Controller - external address value

### ISSUE THREAD

**Issue by mrmm** [kubernetes/contrib#2012]
Hi, 
I have been using Nginx Ingress Controller with Kubernetes cluster on AWS and i have noticed that the address field in the ingress object is updated automatically based on which host the Pod of IngressController is running on.
I think it would be better if the external IP or maybe a service name (will be LoadBalancer Service) to extract the external IP from.
Thanks.

**Comment by aledbf** [comment]
@mrmm this is fixed (not released yet). Next version will use the correct value in AWS and GCE

**Comment by mrmm** [comment]
@aledbf thanks for the reply, i am looking forward for the release ;)

**Comment by remoe** [comment]
@aledbf , could this also work with bare metal? Or is there a workaround to get a node public ip?

**Comment by aledbf** [comment]
>  could this also work with bare metal?

The behavior in baremetal is the expected. It returns the node where the ingress controller is running. What issue do you have with this?

**Comment by remoe** [comment]
@aledbf, we have discussed it in slack. You wrote the current release 0.8.3 doesn't work right with external-ip. Do you have release any beta of ingress-controller on gcr.io which i can test ?

**Comment by aledbf** [comment]
@remoe not yet. We are moving the code from this repo to `kubernetes/ingress`

**Comment by remoe** [comment]
i was wondering if this works. I've found this: https://github.com/kubernetes/contrib/issues/228 :

> In a general sense, there's just no way we could know how to provision
> external IPs for nodes short of a cloud provider hook, and sadly "bare
> metal" is not a cloud provider yet.

Is this no longer the case?

**Comment by remoe** [comment]
@aledbf , the main issue was:

https://github.com/kubernetes/kubernetes/issues/23920
