### ISSUE TITLE
Developer office hours for kops

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/contrib#2016]
We need to setup a zoom based office hours every week this is for developers to come ask questions about what they are working on.

@calebamiles HELP :)  Label and assign to me @kris-nova and @justinsb

**Comment by calebamiles** [comment]
assigning @justinsb per request, please let me know if you'd like to be unassigned.

**Comment by chrislovecnm** [comment]
@calebamiles please assign to me

**Comment by calebamiles** [comment]
you are also assigned to the issue, @chrislovecnm

**Comment by kris-nova** [comment]
After a meeting with @justinsb and @chrislovecnm here is what we decided for office hours :

https://github.com/kubernetes/kops/pull/956

**Comment by kris-nova** [comment]
All should we get this in `contrib` repo as well?

**Comment by chrislovecnm** [comment]
Closing, already havecthem
