### ISSUE TITLE
OWNERS for vendored dependencies

### ISSUE THREAD

**Issue by timstclair** [kubernetes/contrib#2019]
Once https://github.com/kubernetes/contrib/issues/1389 (OWNERS implementation) is complete, we should consider adding OWNERS (specifically approvers) for each vendored (godep) dependency. I'm concerned that dependencies are not sufficiently reviewed right now, and version-bumps are typically blind sync-to-head operations.

Since a thorough review (audit) of vendored code is probably off the table (especially for large projects), reviewers should be responsible for:

- Sanity checking (e.g. anything iffy in `init` methods?), skim the code changes
- Check whether the update makes sense (should we sync to master or a release branch/tag?)
- Check for significant known issues / open bugs that may be introduced by the update

Additionally, it would be great if approvers (or some new role, "maintainers"?) would be responsible for monitoring issues/PRs in the upstream, and be responsible for updating with critical fixes.

/cc @apelisse @kubernetes/contributor-experience

**Comment by apelisse** [comment]
Thanks for opening this issue Tim, I've had that same problem already (https://github.com/kubernetes/kubernetes/pull/36023) that we don't know exactly what we're supposed to do.

**Comment by timstclair** [comment]
BTW - to put this work in perspective, we have approximately 150 separate vendor dependencies.
```
# Not strictly correct
$ (ls -d -1 vendor/github.com/*/*; ls -d -1 vendor/!(github.com)/*) | wc -l
149
```
