### ISSUE TITLE
[ansible] kube2sky crashing, unable to connect to api

### ISSUE THREAD

**Issue by jayprakashji** [kubernetes/contrib#2022]
HI,
I'm fighting with an issue with (near) default install of ansible/kube.
Many logs an outputs in attached file.

It all comes down to :
I1111 10:17:40.832838       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.254.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.

virtualbox Centos 7.2
1 master 1 node

I tryed also 2-3 nodes, kube_source_type: github-release (which installed 1.2.7), in many different combinations with tweaking config values (each deploy-cluster.sh run on clean base snapshot of master and nodes).

Please, what am I missing ?

**Comment by jayprakashji** [comment]
[ansible_kube_logs.txt](https://github.com/kubernetes/contrib/files/585589/ansible_kube_logs.txt)

**Comment by jayprakashji** [comment]
after digging more into how proxy iptables work.

Problem is virtualbox and interface that proxy chooses.
On host-only network, guests do not have access to internet, but can comunicate with host and them selfs.
On Nat network, guests have internet, but can not communicate with each other or host.
https://bertvv.github.io/notes-to-self/2015/09/29/virtualbox-networking-an-overview/

Common config is to guests have both networks - Nat and Host-only .

kube-proxy, has chosen nat network interface for dnat to master. But that ip is for all guests the same, because they are isolated.
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ tcp to:10.0.4.15:443


Only solution I have found, is to use Bridged networking, instead of Nat, but also have Host-noly for guests.
And it works. (but has other dissadvantages.)


If you don't think kube-proxy could choose better network, configurable for example, or the same as is in inventory definition of nodes,
than you can close this issue.
I hope I've used enough keywords on text, that another unlucky tester of kubernetes can find it :)

**Comment by ingvagabund** [comment]
@jayprakashji can you try to set ``kube_master_api_port`` to ``6443`` in ``roles/kubernetes/defaults/main.yml``?
