### ISSUE TITLE
[GCE L7LB controller] Can't create new Google Cloud Load Balancer with ingresses

### ISSUE THREAD

**Issue by wittrock** [kubernetes/contrib#2023]
When trying to create an ingress with `kubectl create -f ingress.yaml` and watching the ingress description as it's created, I see an error from the Google API:

```  7m		2s		23	{loadbalancer-controller }			Warning		GCE	googleapi: Error 400: Invalid value for field 'resource.timeoutSec': '200'. TimeoutSec should be less than checkIntervalSec., invalid```

My intuition here is that the ingress controller is trying to create a health check via the GCE API, and sending an invalid value. 

The ingress file contains no timeout specifications of any kind.

Is there a way I can override this value with a flag or another setting? I'd like to avoid creating load balancers manually to point at my kubernetes cluster, and this leaves me completely unable to create new ingresses.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#health-checks
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/examples/health_checks/README.md#limitations

Do you have a readiness probe? (we should probably validate against readiness probes that have a timeout > interval at the kube api level too)

**Comment by wittrock** [comment]
I do, and in retrospect it totally makes sense that GLBC would use the readiness probes of the deployments for the services the ingress points at as health check parameters. I'm editing the deployment now and I'll let you know what happens.

**Comment by bprashanth** [comment]
Sorry, editing doesn't work yet for health checks (from link above): 
```
You must create the pods backing the endpoints with the given readiness probe. This will not work if you update the replication controller with a different readiness probe.
```

Health checks aren't surfaced through the api, so after first create, the ingress will backoff from any modifications to allow users the flexibility to change it. If you want ingress to recreate the health check for you, the backend service must disappear (so either delete the ingress or delete the backend service directly in gce).

**Comment by wittrock** [comment]
Editing the readiness probe in one of the services and recreating the ingress has fixed it.

Thanks for the quick response, as always!
