### ISSUE TITLE
Service loadbalancer should support multiple namespaces

### ISSUE THREAD

**Issue by aledbf** [kubernetes/contrib#203]

**Comment by bprashanth** [comment]
* Currently you can run it in namespace A and get it to watch services in namespace B via the --namespace=B flag.
* You can get it to watch ingresses in all namespaces with (https://github.com/kubernetes/contrib/pull/206) and the --watch-all flag, but this is only Ingress not Servcies.
* To get it to watch all Services, we'll have to modify the template logic so 2 services in different namespaces don't collide, at the same time the default namespace should be easy to get to (i.e we could give services paths of /ns/svcname in every ns except default)

I think eitherway we'll want to make this flag configurable, as there are people who use service loadbalancer and want it to watch just one namespace.
