### ISSUE TITLE
contrib/keepalived-vip can't create multiple VIPs

### ISSUE THREAD

**Issue by discostur** [kubernetes/contrib#2031]
Hi,

im trying to setup multiple VIPs inside of one Kubernetes cluster. One VIP is running smooth, but keepalived-vip doesn't setup another VIP:

**vip-configmap.yaml**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: vip-configmap
data:
  192.168.10.100: default/rc-ngx
  192.168.10.110: default/rc-ngx-dev
```

**kubectl exec kube-keepalived-vip-8lkjf cat /etc/keepalived/keepalived.conf**
```
global_defs {
  vrrp_version 3
  vrrp_iptables KUBE-KEEPALIVED-VIP
}

vrrp_instance vips {
  state BACKUP
  interface eth0
  virtual_router_id 50
  priority 102
  nopreempt
  advert_int 1

  track_interface {
    eth0
  }

  virtual_ipaddress { 
    192.168.10.100
  }
}

# Service: default/rc-ngx
virtual_server 192.168.10.100 443 {
  delay_loop 5
  lvs_sched wlc
  lvs_method NAT
  persistence_timeout 1800
  protocol TCP

  
  real_server 10.36.0.1 443 {
    weight 1
    TCP_CHECK {
      connect_port 443
      connect_timeout 3
    }
  }

  real_server 10.44.0.9 443 {
    weight 1
    TCP_CHECK {
      connect_port 443
      connect_timeout 3
    }
  }

  real_server 10.47.0.1 443 {
    weight 1
    TCP_CHECK {
      connect_port 443
      connect_timeout 3
    }
  }

} 
```

I expected keepalived-vip to read the second configuration from my configmap, raise an additional IP address and map the traffic to my second service.

Thanks
Greets
Kilian

**Comment by peterrosell** [comment]
I have tried the same configuration, but it seems like it's not supported. I also tried running two deamon sets with two different keepalived-vip, but then I get a conflict due to they use the same virtual_router_id=50.

Maybe someone can confirm that multiple services are not supported. If so, it might be interesting to create a PR that supports multiple services in the same configmap or setting the virtual_router_id or maybe both solutions.

**Comment by discostur** [comment]
I got it running by compiling / building a new docker-image with another keepalived.tmpl:

```virtual_router_id 51```

Then you can run two VIPs inside one cluster. But thats not the preferred way ... would be much better if you can setup "virtual_router_id" via configmap as @peterrosell said.

**Comment by aledbf** [comment]
@discostur please test aledbf/kube-keepalived-vip:0.13 (PR #2041)

**Comment by aledbf** [comment]
@discostur @peterrosell I will add the custom `virtual_router_id` configuration in the next version to allow running multiple instances without collisions

**Comment by aledbf** [comment]
> Maybe someone can confirm that multiple services are not supported

Yes it's supported. I'm running 1 keepalived-vip (daemonset) with 18 IPs (i.e. different services)

**Comment by discostur** [comment]
@aledbf sounds really cool, i'll test aledbf/kube-keepalived-vip:0.13 or the next release and give you feedback if it worked for me

**Comment by peterrosell** [comment]
@aledbf 

> Yes it's supported. I'm running 1 keepalived-vip (daemonset) with 18 IPs (i.e. different services)
Sound perfect for me. Maybe you can add a example configmap file where different services are specifed.

**Comment by peterrosell** [comment]
I have tested aledbf/kube-keepalived-vip:0.13 and have it running for a month or so. Works good with several IPs. The config file contains a row for each service like in the vip-configmap.yaml example file in this issue's first post.

**Comment by discostur** [comment]
@aledbf can you say when your changes will get merged to the contrib/keepalived-vip repo?
