### ISSUE TITLE
Cluster Autoscaler - cluster autoscaler thinks that a pod can scheduler, when it cannot 

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/contrib#2032]
I have created the cluster using these commands:

https://github.com/kubernetes/kubernetes/issues/34772#issuecomment-260594667

I see many pending pods and CA got blocked with the following logs:

```
W1115 14:40:17.711911       7 utils.go:96] Pod my-app-2781155866-p03b8 marked as unschedulable can be scheduled on gke-test-cluster-1-defa
ult-pool-a1904744-c141. Ignoring in scale up.
```

There are many of those lines for different pods.

I checked one of the nodes and it seems that scheduler is correct - it has 4 cores and 3480m are being used and pods requires 550m. It seems we have a serious bug in cluster autoscaler

**Comment by mwielgus** [comment]
It seems that the bug is somewhere in scheduler cache code (see #37232) that CA reuses. So this is in fact not a CA but. I will keep it open as we will have to update CA once it is fixed.

**Comment by wojtek-t** [comment]
@fgrzadkowski - are you sure you check all the nodes and it wasn't possible to schedule a pod on any of them?
To be honest, neither me not @mwielgus can't reproduce this bug, and we are able to relatively easily reproduce the bug in the other direction (CA is right, and scheduler is doing the wrong thing).

**Comment by mwielgus** [comment]
We were not able to reproduce the issue.
