### ISSUE TITLE
Service loadbalancer does not have SSL support

### ISSUE THREAD

**Issue by aledbf** [kubernetes/contrib#204]
Currently is not possible to expose a service using HTTPS with a custom SSL certificate.

**Comment by bprashanth** [comment]
Https example for haproxy in kube https://github.com/bprashanth/Ingress/tree/master/examples/https/haproxy, see daemonizer.go that creates the pem from secrets. In short term we can use annotations to transport secret name (eg: https://github.com/bprashanth/Ingress/blob/master/lib/receivers.go) essentially everytime the serviceloadbalancer pod sees something with the annotations it loads the secret into a pem like in the first example, and reloads haproxy. 

The ingress will support https configuration natively very soon.
