### ISSUE TITLE
Does the ingress controller monitor the change of nginx.tmpl?

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#2057]
Hi, 

Ingress controller can monitor the change of the container network environment. However, can I change the content of the nginx.tmpl and the controller regenerate the nginx.conf and reload the Nginx?

**Comment by aledbf** [comment]
@tjliupeng this is fixed in master but not released [1498](https://github.com/kubernetes/contrib/pull/1498)

**Comment by tjliupeng** [comment]
Does that mean I can change the nginx.tmpl in the running controller container?

**Comment by aledbf** [comment]
yes

**Comment by tjliupeng** [comment]
Wow. Thank so cool. I will try it.

**Comment by tjliupeng** [comment]
@aledbf , I change the content of /etc/nginx/template/nginx.tmpl in a running container, but no new nginx.conf is generated. What do I miss? I use "docker exec -ti containerid bash" to attach to the container and change /etc/nginx/template/nginx.tmpl via vim.

**Comment by aledbf** [comment]
@tjliupeng this is fixed in master but not released. This is not present in 0.8.3

**Comment by tjliupeng** [comment]
@aledbf , I checkout the code and build the ingress controller by myself. I check the code , it should include that code change.
