### ISSUE TITLE
Nginx ingress controller fails to start with custom template

### ISSUE THREAD

**Issue by vglazkov** [kubernetes/contrib#2061]
Hi,

I'm trying to create ingress controller with custom template like in the basic example. When I use the same nginx.tmpl file i get the following output from nginx controller log:
`
I1118 15:13:31.787977       1 main.go:94] Using build: https://github.com/bprashanth/contrib.git - git-92b2bac
I1118 15:13:31.829894       1 main.go:123] Validated default/default-http-backend as the default backend
W1118 15:13:31.830209       1 ssl.go:132] no file dhparam.pem found in secrets
F1118 15:13:31.832432       1 main.go:71] invalid NGINX template: template: nginx.tmpl:210: function "buildAuthLocation" not defined
`

**Comment by aledbf** [comment]
@vglazkov you need to use customize the template shipped with the docker image (use docker cp to extract the template)
Please keep in mind that the template is tied to go code. That's the reason of the failure.
(the template in the repo uses functions not present in the docker image)

**Comment by vglazkov** [comment]
@aledbf thanks for the quick response! I was able to fix the issue with template that you mentioned. I think, that instruction should be fixed, because it directly points to the wrong nginx template file, that i've tried before:
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/custom-template/README.md

**Comment by aledbf** [comment]
>  I think, that instruction should be fixed, because it directly points to the wrong nginx template file, that i've tried before:

Noted. Apologies for the error in the example.

**Comment by tzumby** [comment]
I ran into the same problem. Is this the Dockerfile you are referring to? https://github.com/kubernetes/ingress/blob/master/controllers/nginx/rootfs/Dockerfile
