### ISSUE TITLE
Is it possible for nginx ingress controller to use our own cookie for session sticky?

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#2068]
Hi,

At present nginx ingress controller uses a third-party session sticky module. But this module seems not support using our own cookie, such as JSESSIONID. It adds its own cookie route. Is it possible for nginx ingress controller to use our own cookie for session sticky?

Thanks

**Comment by daemonza** [comment]
+1

**Comment by lukasged** [comment]
+1
