### ISSUE TITLE
[nginx ingress controller] config reload question

### ISSUE THREAD

**Issue by afoninsky** [kubernetes/contrib#2073]
1) Im getting errors in logs like `upstream default-someingressname-8080 does not have any active endpoints. Using default backend`. Such ingresses was deleted long ago, but nginx din't know it. Is there way to reload config by hands?

2) External loadbalancer ip is changed every time then ingress pod restarts (example: cluster update). In case of "gce ingress" this can be fixed by writing annotation something like "keep ip permanent" (sorry, didn't remember configuration name exactly). Is there something similar in nginx ingress?

Thank you.

**Comment by sheerun** [comment]
I also get weird messages in logs with not existing endpoints. @aledbf?
