### ISSUE TITLE
Ingress only supports :80. GCLB supports :80 and :8080.

### ISSUE THREAD

**Issue by craigbox** [kubernetes/contrib#2077]
[GCLB docs](https://cloud.google.com/compute/docs/load-balancing/http/) says "HTTP requests can be load balanced based on port 80 or port 8080. HTTPS requests can be load balanced on port 443."

[Kubernetes source](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go) says 
```
 	// 2. The `:` delimiter is not respected because ports are not allowed.
	//	  Currently the port of an Ingress is implicitly :80 for http and
	//	  :443 for https.

```
Ingress can't be configured on port 8080.  (Low priority FR, I'll just change my endpoint, but documenting for search results.)

**Comment by bprashanth** [comment]
I don't see a valid reason to special case 8080, other than that GCE does. We don't expose frontend port through the Ingress for simplicity right now. We probably will when we evolve it to support TCP, at which point you can open any frontend port and we'll throw an error from the GCE backend if the user tries to open anything other than 80 or 8080.
