### ISSUE TITLE
milestones should rank higher in the submit queue

### ISSUE THREAD

**Issue by dims** [kubernetes/contrib#2083]
For example if we have 2 PR(s) with ["P3","v1.5"] or ["P2","v1.6"]

Currently we are prioritizing the 1.6 above the 1.5... Can we please do the opposite?

**Comment by dims** [comment]
cc @saad-ali @rmmh

**Comment by dims** [comment]
Note from @rmmh 
@dims: can you refile that against contrib? https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/submit-queue.go#L1082  is the badness

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1627
