### ISSUE TITLE
GLBC Ingress - allow using existing SSL Certificates

### ISSUE THREAD

**Issue by jrynyt** [kubernetes/contrib#2095]
The GCE Ingress [requires](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#tls) the actual SSL private key and certificate be defined inside of Kubernetes [via secrets], which the controller then applies to the GCE L7 load balancer. In order to protect the private key, we would like to instead refer to an existing certificate in the GCP Project _by name_ in the Ingress definition.

Example configuration:
```
kind: Ingress
spec:
  tls:
    - certName: my-cert
```
Or an annotation like for AWS is fine: http://kubernetes.io/docs/user-guide/services/#ssl-support-on-aws

GCP-equivalent example:
```
gcloud compute ssl-certificates create my-cert \
  --certificate my.crt --private-key my.pem

gcloud compute target-https-proxies create my-proxy \
  --ssl-certificate my-cert --url-map my-map
```

It appears you are already storing certs in the Project and referring to them by name: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/loadbalancers/loadbalancers.go#L354 -- we would just like to specify the name instead.

This allows the separation of roles: a certificate administrator can upload the key/cert into the GCP Project, where the key is not accessible to users, then a k8s/GKE administrator can use it without needing to have that very valuable secret.

Thanks.

**Comment by bprashanth** [comment]
A reasonable request, it just needs to be implemented. Today, if you don't have a tls section, the controller assumes you want HTTP.

**Comment by tonglil** [comment]
Should this issue be cross-posted in https://github.com/kubernetes/ingress (and closed here)?

**Comment by bprashanth** [comment]
Sure, @porridge volunteered to mass move bugs over anyway

**Comment by bprashanth** [comment]
https://github.com/kubernetes/ingress/issues/45

**Comment by tonglil** [comment]
Thank you.
