### ISSUE TITLE
Ansible rerun is not picking the latest variable changes.

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [kubernetes/contrib#2097]
Hi Team,
I have created a cluster with flannel subnet range and it got created successfully. Now i want to update flannel with the new subnet range but ansible re-run is not applying the latest change. I can see only the old subnet range still. 

Also i tried using the github-release instead of package manager to update etcd & flanneld. Both are trying to fetch the tar file from github release URL but the same is failing with 404 error. 

Some help/pointers would be much appreciated.

**Comment by ingvagabund** [comment]
By default, configuration is set to implicit values (set by the ansible playbook) unless the configuration part is skipped. What command are you running to update the flannel?
