### ISSUE TITLE
Nginx Ingress Controller ConfigMap support for header size

### ISSUE THREAD

**Issue by erie149** [kubernetes/contrib#2099]
I was wondering if we can add large_client_header_buffers and 	client_header_buffer_size to the ConfigMap.  We have a JWT that gets passed with information larger than 8K in some cases

**Comment by aledbf** [comment]
@erie149 please open an issue in https://github.com/kubernetes/ingress

**Comment by erie149** [comment]
ok done thanks

**Comment by aledbf** [comment]
@erie149 please close this one :)
