### ISSUE TITLE
SQ should indicate which commit statuses are preventing merge

### ISSUE THREAD

**Issue by ixdy** [kubernetes/contrib#2102]
It's not always obvious why SQ says "Github CI tests are not green." - e.g., it might be because a required status is missing, it might be because SQ is behind on its sync loop, or it might be a bug in SQ.

If we added the list of failing status(es), it would make it easier to understand how to fix a PR.

**Comment by fejta** [comment]
@ixdy @foxish @eparis it sounds like at least some subset of you are aware of and/or working on this per https://github.com/kubernetes/kubernetes/pull/37413#issuecomment-264000592 

Can we get a new SQ build with this change? @rmmh can then redeploy the SQ with it.

**Comment by eparis** [comment]
That comment in 37413 was something different, but this is a good idea too....

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1643
