### ISSUE TITLE
Ansible setup broken on Fedora 25

### ISSUE THREAD

**Issue by bjornl** [kubernetes/contrib#2120]
Red Hat Fedora project have changed the name of configuration parameters for Flannel in release 25. They are now FLANNEL_ETCD_ENDPOINTS and FLANNEL_ETCD_PREFIX instead of the previous FLANNEL_ETCD and FLANNEL_ETCD_KEY.

Then performing the setup on Fedora 25 the flanneld.service from the OS package is used and the /etc/sysconfig/flanneld from playbook. So flannel service will fail to start due to not being able to expand the configuration parameters for Etcd.

I believe the solution is to update the files in ansible/ to use the new Fedora parameters.

**Comment by ingvagabund** [comment]
Fixed via https://github.com/kubernetes/contrib/pull/2069
