### ISSUE TITLE
Ansible setup using deprecated and unavailable images

### ISSUE THREAD

**Issue by bjornl** [kubernetes/contrib#2124]
Ansible dns manifest references skydns image that is deprecated and not available to pull from Google Container Registry any more.

Error syncing pod, skipping: failed to "StartContainer" for "skydns" with ErrImagePull: "image pull failed for gcr.io/google_containers/skydns:2015-10-13-8c72f8c, this may be because there are no credentials on this request.  details: (manifest unknown: Failed to fetch \"2015-10-13-8c72f8c\" from request \"/v2/google_containers/skydns/manifests/2015-10-13-8c72f8c\".)"

https://gcr.io/google_containers/skydns:2015-10-13-8c72f8c

**Comment by dustymabe** [comment]
I'm hitting this as well. Looks like there was a move from skydns to kubedns https://github.com/kubernetes/kubernetes/commit/4ad06df18f3e269095f758cb9ef5f7b5f985facb

**Comment by dustymabe** [comment]
Note that a temporary workaround for the dns issue is to modify `roles/kubernetes-addons/templates/dns/skydns-rc.yaml.j2` and move the tag to `1.0`, such that it looks like: `image: gcr.io/google_containers/skydns:1.0`. This allows us to still use skydns, but does not get us to kubedns.

**Comment by bjornl** [comment]
Closing this issue as resolved. Ansible has been converted to use KubeDNS in commit 5bdcb1e
