### ISSUE TITLE
Ansible aws ubuntu instance Deploy etcd fails

### ISSUE THREAD

**Issue by smenon78** [kubernetes/contrib#2125]
I have a Ubuntu EC2 instance and it fails 

PLAY [Deploy etcd] *************************************************************

18:03:20 
18:03:20 TASK [setup] *******************************************************************
18:03:21 fatal: [35.164.0.226]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

**Comment by ingvagabund** [comment]
What Ubuntu version?

**Comment by ingvagabund** [comment]
This fails every time the aws creates ubuntu instance without python. I would recommend to either choose different image (if it is available) or run pre-ansible  scripts that can install python into the ubuntu instance.
