### ISSUE TITLE
Turn on 2FA for k8s-merge-robot

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#2129]
k8s-merge-robot needs to be an admin for https://github.com/kubernetes/contrib/pull/2121 to work correctly.

**Comment by lavalamp** [comment]
2fa is on now.

**Comment by lavalamp** [comment]
What does the bot need to be an admin of?

**Comment by foxish** [comment]
Thanks!

Needs to be an admin for every repo it runs on, if we want to [sync the required statuses](https://github.com/kubernetes/contrib/pull/2121) while still allowing the mergebot to merge without those statuses (for e.g. the CLA status throwing an error, but the bot still being allowed to merge because the `cla:human approved` label is set. I'm not sure if we want to set the `linuxfoundation/cla` status as a "required" status though.

**Comment by lavalamp** [comment]
OK, it's an admin of kubernetes, contrib, and kubernetes.github.io.
