### ISSUE TITLE
Batch results should use https.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/contrib#2131]
From https://github.com/kubernetes/contrib/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L176
```
  submit-queue.batch-url: http://prow.k8s.io/data.js
```

This should be https. Something strange happened last time we tried this.

**Comment by rmmh** [comment]
It was unhappy with the letsencrypt provided cert:

    E1129 01:48:50.015240 1 submit-queue-batch.go:245] Error reading batch jobs from Prow URL https://prow.k8s.io/data.js7:18 PM
    x509: certificate signed by unknown authority7:29 PM

**Comment by spxtr** [comment]
It might work now that I'm using the full chain. I think previously I was just providing the cert. Not sure how to find out other than just trying it out.

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1622
