### ISSUE TITLE
[Nginx ingress controller] OpenResty support

### ISSUE THREAD

**Issue by 21stio** [kubernetes/contrib#2150]
Hey,

we would like to provide OpenResty / Custom Lua stuff support. Maybe it's already working and if it doesn't but we may thinking of providing an additional Dockerfile.

If you would require an additional Dockerfile, would you merge it or is it too specific?

Best regards

**Comment by aledbf** [comment]
@21stio the nginx image already contains the lua-nginx-module.
Please check https://github.com/kubernetes/contrib/tree/master/images/nginx-slim
If you need additional modules you can build a custom version of both images.

> would you merge it or is it too specific?

it depends. Can you post more information about what do you want to add?

**Comment by 21stio** [comment]
Hi @aledbf,

true, but I am not sure if the lua-nginx-module will be suffient. According to a coworker our stuff won't work with your Dockerfile, but that's something I will figure out today.. I will close this issue now as I posted a more general big picture like issue #2152 that kinda includes this issue..
