### ISSUE TITLE
[Nginx ingress controller] Custom reloading command

### ISSUE THREAD

**Issue by 21stio** [kubernetes/contrib#2151]
Hey,

we would like to run the ingress controller in a dedicated container that triggers a config reload within an nginx container. To do so, we will need to call a custom command for this cross container operation (sth different than "nginx reload") 

We are thinking of adding the functionality to inject a custom command via a config flag. 

Is this feature a conceptual fit? Would you merge it?

Best regards

**Comment by aledbf** [comment]
@21stio you mean run a pod with 2 containers 1 for the ingress controller and another for nginx?

**Comment by 21stio** [comment]
Hi @aledbf,

exactly :) I just posted another issue #2152 that communicates the big picture and includes this one, so I will close this one now.
