### ISSUE TITLE
[Nginx ingress controller] Proposal: minimize loadbalancer downtime

### ISSUE THREAD

**Issue by 21stio** [kubernetes/contrib#2152]
Hey,

we really like your nginx ingress controller implementation. Unfortunately, it doesn't support our use case to the extend we would wish to, but we would be very happy to contribute to this project with some generic features.

Our vision is to have an ingress controller that feeds a loadbalancer continuously with hosts, endpoints and paths with as little downtime as possible (e.g. having to reload the configration, drain connection pools etc).

We already built an OpenResty based loadbalancer that spawns a http endpoint that accepts service pod's endpoints and adds them to the service's upstream pool without any downtime. We did not find a solution to change hosts and paths definitions in memory yet, so we would like to go the classy way, by simply rendering the configs and reloading nginx. 
We also strongly believe in the one container per process approach and would like to run the ingress controller within a dedicated container in the long term.

To support our use case and keep the nginx ingress controller flexible we would like to provide some features like:
- provide a way to react to ingress events in a more granular way like, e.g. whenever a new host or path is added config shoud be rendered and a command should be trigger and whenever a service's endpoints change a http request is send
- being able to inject a custom command that will be trigger whenever the configuration will be rendered
- run the ingress controller in a dedicated container (low short term priority, nice to have in the long term)

We would be very happy to hear your opinion on our thoughts and ideas how this can be realized with the greatest benefit for everybody :)

Best regards

**Comment by aledbf** [comment]
Just some comments

> provide a way to react to ingress events in a more granular way like, e.g. whenever a new host or path is added config shoud be rendered 

This is how it works now. Can you be more specific about any issue with the current approach?

> and a command should be trigger and whenever a service's endpoints change a http request is send
> being able to inject a custom command that will be trigger whenever the configuration will be rendered

This is easy to add. Please check [here](https://github.com/kubernetes/ingress/blob/master/core/pkg/ingress/controller/controller.go#L378)
Which kind of command? (please post an example)

> run the ingress controller in a dedicated container (low short term priority, nice to have in the long term)

I like this one but is hard because the "dependency" graph:
`go code (controller) -> go template -> nginx features (nginx.conf) -> nginx binary/image`
If the current pod (1 container) is divided you are giving the idea that you can swap any part, which is not true.

**Important:** keep in mind the controller is being migrated to this repo https://github.com/kubernetes/ingress/tree/master/controllers/nginx

**Comment by aledbf** [comment]
> We already built an OpenResty based loadbalancer that spawns a http endpoint that accepts service pod's endpoints and adds them to the service's upstream pool without any downtime

Can you post the code for this part?

The current approach is to use the nginx reload which provides no downtime but you lose track of the upstream server status

**Comment by 21stio** [comment]
>> provide a way to react to ingress events in a more granular way like, e.g. whenever a new host or path is added config shoud be rendered

>This is how it works now. Can you be more specific about any issue with the current approach?

It also renders the upstream. I our case the upstream does not need to be rendered, if there are any new endpoints there is no need to reload nginx.

>> and a command should be trigger and whenever a service's endpoints change a http request is send
being able to inject a custom command that will be trigger whenever the configuration will be rendered

>This is easy to add. Please check here
Which kind of command? (please post an example)

I don't want to hardcode it, even if it's conditional, so injection would be nice. Sth like `docker exec container_id nginx -c reload`, depends on the environment..

> Important: keep in mind the controller is being migrated to this repo https://github.com/kubernetes/ingress/tree/master/controllers/nginx

Yeah just stumpled about it by accident. It wasn't that obvious last time I checked. But yeah, really nice codebase! I guess we will go with the BackendController Interface and write a custom implementation. We would be very happy to contribute it back to you if it's of interest for you

>> We already built an OpenResty based loadbalancer that spawns a http endpoint that accepts service pod's endpoints and adds them to the service's upstream pool without any downtime

>Can you post the code for this part?

Sure, it's still work in progress though

api.conf
```
server {
     listen 8888;
     location /set {
         content_by_lua_file lua/apiset.lua;
     }
     location /get {
         content_by_lua_file lua/apiget.lua;
     }
}
```

apiset.lua
```lua
local ep = ngx.shared.k8seps
local json = require("cjson.safe")

if ngx.req.get_method() == "PUT" or ngx.req.get_method() == "POST" then
    ngx.req.read_body()

    local input, err = json.decode(ngx.req.get_body_data())
    ngx.say(input.urlpath)
    local epstr = json.encode(input.endpoints)
    ngx.say(epstr)
    ep:set(input.urlpath, epstr)
    local eparr = json.decode(epstr)
    if err then
      ngx.log(ngx.ERR, "error decoding input json" .. err)
      ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
    end

  else
    return ngx.exit(ngx.HTTP_BAD_REQUEST)
end
```

balancer.conf
```
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504 http_403 http_404;
proxy_next_upstream_tries 10;

upstream balancer-lua
{
  server 0.0.0.1; # just an invalid address as a place holder

        balancer_by_lua_file lua/balancer.lua;
        keepalive 10;  # connection pool
}

server {
    listen 80;
    server_name _;


    location / {

      access_log /tmp/access.log;
      #access_by_lua_file lua/auth.lua;
      #proxy_next_upstream_timeout 5s;
      #proxy_next_upstream_tries 3;
      proxy_pass http://balancer-lua;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }

}
```

balancer.lua
```lua
local balancer = require "ngx.balancer"

if not ngx.ctx.tries then
    ngx.ctx.tries = 0
end

local ep = ngx.shared.k8seps
local epcr = ngx.shared.k8sepcr
local crurl = ngx.var.host..ngx.var.request_uri

ngx.log(ngx.WARN, "crurl: ", crurl)
--local crurl_crc32 = ngx.crc32_long(crurl)
local jsonStr = ep:get(crurl)
ngx.log(ngx.WARN, "request_uri: ", ngx.var.request_uri)
local json = require("cjson")
local newEps = json.decode(jsonStr)

ngx.ctx.epCount = table.getn(newEps)

if ngx.ctx.epCount == 1 then
  local crepstr = newEps[1]
  local ok, err = balancer.set_current_peer(crepstr)
  if not ok then
      ngx.log(ngx.ERR, "failed to set the current peer: ", err)
      return ngx.exit(500)
  end
else
  --math.randomseed(os.time())
  --ngx.ctx.rndhit = math.random(1, ngx.ctx.epCount)
  --if not ngx.ctx.nxthit then
  --    ngx.ctx.nxthit = 0
  --end

  ngx.ctx.nxthit = epcr:incr(crurl, 1, 1)

  if ngx.ctx.nxthit >= ngx.ctx.epCount then
    ngx.ctx.nxthit = 0
    epcr:set(crurl, 0)
  end

  if ngx.ctx.tries < ngx.ctx.epCount then
         --ngx.log(ngx.WARN, "COUNT: ", ngx.ctx.epCount)
         --ngx.log(ngx.WARN, "UPSTREAM_RETRIES: ", ngx.ctx.tries)
    local ok, err = balancer.set_more_tries(1)
    if not ok then
        ngx.log(ngx.ERR, "failed to set more tries: ", err)
      elseif err then
        ngx.log(ngx.WARN, "set more tries: ", err)
    end
         --ngx.log(ngx.WARN, "NXTHIT: ", ngx.ctx.nxthit)
         --ngx.log(ngx.WARN, "TRIES: ", ngx.ctx.tries)
    local crepstr = newEps[ngx.ctx.nxthit + 1]
         --ngx.log(ngx.WARN, "CREPSTR: ", crepstr)
    local ok, err = balancer.set_current_peer(crepstr)
    if not ok then
        ngx.log(ngx.ERR, "failed to set the current peer: ", err)
        return ngx.exit(500)
    end
  ngx.ctx.tries = ngx.ctx.tries + 1
  end
end
´´´

We thought about adapting your implementation first, but we weren't sure if we could build a version that will suite our needs and will be merged by you. So we go the pragmatic way, by simply implementing our own controller. I'll let you know once we finished and maybe it's a good fit to be merged :)
