### ISSUE TITLE
feature: when pull requests are opened to a specific branch add the milestone

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/contrib#2168]
I find myself adding the milestone v1.4 to all the cherry-pick PRs and it would be nice if one of the bots could check the branch it is open on and automatically add the milestone.

since all branches are `release-x.x` and milestones are `vx.x` it shouldnt be too hard

BONUS: if the bot can ping the release person on that PR too :) but thats extra

**Comment by foxish** [comment]
cc @kubernetes/sig-contributor-experience-misc

**Comment by spxtr** [comment]
It would be pretty easy to do as a prow plugin.
