### ISSUE TITLE
nginx-ingress-controller failure to retrieve page relative resources

### ISSUE THREAD

**Issue by sigxcpu76** [kubernetes/contrib#2175]
Maybe I'm getting this wrong, but the base-url should be constructed from matched path instead of rewrite target. 

Problem description:

Ingress rule:
```
path = "/p"
rewrite-target = "/"
add-base-url = true
```

How it works:
```
base-url=protocol://host/target => http(s)://some.host/
```

- ```css/test.css``` becomes ```http(s)://some.host/css/test.css``` (ingress rule is not matched anymore)

How it should work:
```
base-url=protocol://host/target => http(s)://some.host/p
```
- ```css/test.css``` becomes ```http(s)://some.host/p/css/test.css``` (matches the ingress rule and URL is rewritten to ```/css/test.css``` for the backend to be loaded correctly)

If a path "/p" is matched by the ingress rule, the backend is rewritten to ```/```, but the resources should still be pulled by ```/p/``` from the browser point of view, otherwise there is no matching path in ingress rule.

**Comment by tommagowan** [comment]
I've also enabled the annotation:

`ingress.kubernetes.io/add-base-url: "true"`

I see something very similar. The current implementation does not seem to address the underlying probelm at all.
