### ISSUE TITLE
keepalived-vip - multiple services with one IP

### ISSUE THREAD

**Issue by sebbtl** [kubernetes/contrib#2176]
Actually, we have only one service per IP with kube-keepalived-vip. One solution is to accept a configmap entry like this:

192.168.0.1: default/svc1 default/svc2 default/svc3

I need this so I write this trivial patch for controller.go 0.7.0:
[keepalived-vip-multiple-services.txt](https://github.com/kubernetes/contrib/files/660752/keepalived-vip-multiple-services.txt)

There is no verification if svc1 and svc2 use same port, it's a trivial patch.

**Comment by kitch** [comment]
Nice idea and one that might prove useful to us. I'll give it a shot. Do you have a PR open with this change?

**Comment by sebbtl** [comment]
I have no PR open with this change. I'm not familiar with Go and kubernetes development so if somebody can write a write a nice patch with some checks... I think this feature will be very useful for sysadmins.

**Comment by gkopylov** [comment]
I think it is better to split multiple services with ```\n``` and use ```|-``` for it as described in official kubernetes documentation: https://kubernetes.io/docs/user-guide/configmap/

I created PR for this and also I add checking for allocation with another ports: https://github.com/kubernetes/contrib/pull/2424/files#diff-9bc041cb67013f86d411efc7e3e294e4R203

I also create my own image https://hub.docker.com/r/gkopylov/kube-keepalived-vip/ based on my PR and check it on my servers, everything is ok.

**Comment by yukiman76** [comment]
@gkopylov any traction on this, this PR would be perfect for what we are looking to do
