### ISSUE TITLE
kube-apiserver fails to start on secondary master node

### ISSUE THREAD

**Issue by bjornl** [kubernetes/contrib#2177]
Then setting up a cluster using Ansible with two masters on Fedora 25, the kube-apiserver service fails to start on the secondary master node.

There look to me like there is a certificate that is missing on the second node.

++ /usr/bin/kube-apiserver --logtostderr=true --v=0 --etcd-servers=http://kubelab1:2379,http://kubelab2:2379 --insecure-bind-address=127.0.0.1 --secure-port=443 --allow-privileged=true --service-cluster-ip-range=10.254.0.0/16 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota --tls-cert-file=/etc/kubernetes/certs/server.crt --tls-private-key-file=/etc/kubernetes/certs/server.key --client-ca-file=/etc/kubernetes/certs/ca.crt --token-auth-file=/etc/kubernetes/tokens/known_tokens.csv --service-account-key-file=/etc/kubernetes/certs/server.crt --bind-address=0.0.0.0
I1219 16:02:45.330796    9876 genericapiserver.go:629] Will report 192.168.20.39 as public IP address.
F1219 16:02:45.331033    9876 server.go:238] Invalid Authentication Config: open /etc/kubernetes/certs/server.crt: no such file or directory

Certificates on first master node:
[root@kubelab1 ~]# ls -l /etc/kubernetes/certs/
total 40
-r--r-----. 1 kube kube-cert 1338 Dec 19 15:51 ca.crt
-r--r-----. 1 kube kube-cert 4557 Dec 19 15:51 kubecfg.crt
-r--r-----. 1 kube kube-cert 1708 Dec 19 15:51 kubecfg.key
-rw-rw----. 1 root kube-cert 4557 Dec 19 15:51 kubelet.crt
-rw-rw----. 1 root kube-cert 1704 Dec 19 15:51 kubelet.key
-r--r-----. 1 kube kube-cert 5051 Dec 19 15:51 server.crt
-r--r-----. 1 kube kube-cert 1704 Dec 19 15:51 server.key

Certificates on second master node:
[root@kubelab2 ~]# ls -l /etc/kubernetes/certs/
total 16
-rw-r--r--. 1 root root 1338 Dec 19 15:51 ca.crt
-rw-r--r--. 1 root root 4557 Dec 19 15:51 kubecfg.crt
-rw-r--r--. 1 root root 1708 Dec 19 15:51 kubecfg.key

My inventory file look like this:

[masters]
kubelab1
kubelab2

[etcd:children]
masters

[nodes]
kubelab1
kubelab2

**Comment by galexrt** [comment]
See #2369 for a fix.

**Comment by xialonglee** [comment]
It is really helpful, thanks! @galexrt

**Comment by galexrt** [comment]
@xialonglee Did #2369 fix this issue for you?

**Comment by xialonglee** [comment]
@galexrt Yes, thanks. I use it before it was merged : )

**Comment by galexrt** [comment]
This can now be closed. The Ansible code has been changed so multi apiservers are now working.
