### ISSUE TITLE
[Typo] Its GCLB not GLBC

### ISSUE THREAD

**Issue by cobookman** [kubernetes/contrib#2179]
The following documentation uses the acronym of GLBC to represent the GCP Compute Engine Layer 7 Load Balancer:

https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce

However the correct acronym is GCLB.

**Comment by jeroenvisser101** [comment]
GLBC is for (G)CP (L)oad (B)alancer (C)ontroller right?

**Comment by cobookman** [comment]
Ah. Well gclb = (G)oogle (C)loud (L)oad (B)alancer. 
I couldn't find any official docs breaking down the acronym, but a quick google search found the following doc referencing it. https://cloud.google.com/compute/docs/load-balancing/http/using-http-lb-with-cloud-storage

However GCLB is used heavily in the google internal docs, and Google official in presentations.
