### ISSUE TITLE
cluster-autoscaler: Dynamic reconfiguration via ConfigMap

### ISSUE THREAD

**Issue by mumoshu** [kubernetes/contrib#2181]
> **Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

> **What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

I've searched for:

* cluster-autoscaler
* dynamic reconfiguration
* configmap
* config map
* cluster autoscaler

and their combinations but found nothing.

---

> **Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

> If this is a FEATURE REQUEST, please:
>  - Describe *in detail* the feature/behavior/change you'd like to see.

As a maintainer of [kube-aws](https://github.com/coreos/kube-aws), I'm planning to add out-of-box support for/integration with cluster-autoscaler into [kube-aws](https://github.com/coreos/kube-aws) and got to want a feature to reconfigure cluster-autoscaler without deleting it and then creating it with new `--nodes` parameters, hence "dynamic reconfiguration".

cc @andrewsykim @mwielgus 

## My use-case

My use-case is to reconfigure cluster-autoscaler automatically when a kube-aws user added/removed node pool(s) associated to a k8s cluster.

More complete context can be seen in [an corresponding issue](https://github.com/coreos/kube-aws/issues/148) of kube-aws.

### What could be done WITHOUT the requested feature

Currently, an user has to delete and then create cluster-autoscaler completely out of band from a k8s cluster created by deployment tools like kops and kube-aws, to reconfigure cluster-autoscaler to:

* stop auto-scaling on already removed node pool(s)
* start auto-scaling on newly created node pool(s)

With cluster-autoscaler as of today, we can achieve dynamic reconfiguration via writing e.g.:

* a shell script to `inotify-wait` on a configmap volume,
  * read the latest configuration from it,
  * and then updating cluster-autoscaler by restarting it while updating `--nodes` parameters,
     * via `kubectl` or inside the container running cluster-autoscaler.

Though it is technically possible, doing so in that way seems to involve more moving parts than necessary:
* a correct init process(a shell script as pid=0 may result in zombie processes)
* process supervisor(to keep cluster-autoscaler up and running)

and makes testing harder.

### What could be done WITH the requested feature

* cluster-autoscaler can be integrated to k8s deployment tools in easier ways/cluster-scaler can be deployed more widely
   * For example, for each k8s deployment tool like kops, kube-aws, implement a `configmap updater` application to periodically update the configmap read by cluster-autoscaler
   * and then our user is freed from manually recreating a cluster-autoscaler deployment object for each time he/she updated a cluster, thus less work to utilize cluster-autoscaler

### Thoughts on implementation

After looking around the k8s ecosystem, I've noticed that an existing k8s add-on like [cluster-proportional-autoscaler](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler) seems to have a well thought support for dynamic configuration via `--configmap` and `--default-params` flags, hence I'm "suggesting" dynamic reconfiguration "via ConfigMap".
It won't necessary be utilizing ConfigMap if dynamic reconfiguration is achieved.

FYI [cluster-proportional-autoscaler's code was helpful to imagine how it would work to achieve dynamic reconfiguration](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/blob/8ee4bd79b553fa21e0b7e420a6ba7148fdb946ca/pkg/autoscaler/autoscaler_server.go#L103). This matched my expectation on how I'd like cluster-autoscaler to support dynamic reconfiguration.

Btw, cluster-autoscaler seems to have [a similar control-loop](https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/cluster_autoscaler.go#L227-L229) to periodically update node groups.
If it is ok to extend the loop to periodically check a configmap for an update while changing a part of cluster-autoscaler's state from immutable to mutable, I guess I can submit a pull request to achieve what is requested in this feature request with it.

**Comment by andrewsykim** [comment]
Related tool regarding triggering rolling updates on config map changes: https://github.com/kargakis/configmap-rollout
And related issue: https://github.com/kubernetes/kubernetes/issues/22368

**Comment by Raffo** [comment]
This is a similar feature to what discussed in this PR: https://github.com/kubernetes/contrib/pull/1982 

I will update the PR in these days to address the comments. I would say that this can be done even without the configmap natively by the autoscaler. In my case, I am already using such a feature.

**Comment by mumoshu** [comment]
@Raffo Thanks for the info and the great work!

I've read through your PR and found it will also be useful for my use-case.
I'm definitely :+1: to see your work to be merged into master.

**Comment by mumoshu** [comment]
Would you all mind keeping this issue open, though?
Sorry for being not very clear about that but our use-case includes not only autoscaling groups but also **spot fleets** as the autoscaling targets.

Automatic reconfiguration just for autoscaling groups could be achieved via @Raffo's great work(#1982) without any problem. I'm looking forward to see his work merged into master.

On the other hand, a spot fleet is missing a well-known source-of-truth for auto scaling hence I've suggested configmaps. A spot fleet doesn't have properties like MinSize, MaxSize. It can't be tagged either. Therefore, kube-aws has opted to put the source-of-truth into tags assigned to a cloudformation stack managing the spot fleet. That's definitely not the way to go for everyone, though.

I guess supporting dynamic reconfiguration via a generic building block like the configmap alleviates the issue like mine which aries when building our own automatic reconfiguration for one's own k8s deployment. We could build our own automatic reconfiguration for cluster-autoscaler regardless of cloud provider, deployment method, exact place to store the source-of-truth, around the generic dynamic reconfiguration feature.

**Comment by mwielgus** [comment]
I agree with @mumoshu. While @Raffo's PR is definitely helpful it is AWS specific and cannot be generalized to other cloud providers (at least not to GCE/GLE where min/max size is not provided). Also, with config map it would be possible to easily change runtime parameters (timeouts, thresholds, etc). 

I would imagine that an extra flag pointing pointing to a config map would be added to CA. CA would periodically try to parse it and, in case of failure, surface an alarm.

**Comment by Raffo** [comment]
All sounds like great ideas! Happy to see a PR covering this use case and happy to contribute one or review it if needed.

**Comment by mumoshu** [comment]
Closing this as resolved via #2226 
cc @mwielgus
