### ISSUE TITLE
[mungegithub] Autoclose Issues Without Routing Labels

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/contrib#2199]
A Two Part Issue
Allow people to suggest area/labels or sig/labels when creating issues using issue template.  Something like 
`area-label: area/kubelet` or `sig-label:sig-cli` in the template could allow us to auto-detect routing labels

If issue opened, by member of org without routing label, auto-close and explain why.

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1626
