### ISSUE TITLE
[Nginx Ingress Controller] Specifying the loadBalancerIP used by the Ingress

### ISSUE THREAD

**Issue by paultiplady** [kubernetes/contrib#2221]
I'd like to use a static IP for my ingress. Currently, the Nginx Ingress Controller allocates a new loadBalancerIP each time it starts.

For Services, it's possible to pin the IP using `loadBalancerIP: 1.2.3.4`. Is this possible in the Nginx Ingress Controller?

If not, is there some other approach that can be used to pin the IP of an Ingress?

**Comment by r4j4h** [comment]
You can pin a chosen service with [keepalive-vip](https://github.com/kubernetes/contrib/tree/master/keepalived-vip) but it will not auto-discover your services.
