### ISSUE TITLE
Debugging problems with service-loadbalancer

### ISSUE THREAD

**Issue by piersharding** [kubernetes/contrib#225]
Hi -

I've built and launched the servicelb container and launched it using the rc.yml example.  I can connect to the stats port on 1936, and haproxy appears to be listening ok on 80.  I've launched a test container to get it picked up by the loadbalancer but when I curl -v http://10.100.41.6/test I get 'Not Found'.  If I query the logs for the loadbalancer I get the messages below.  From here, I'm not sure where to go to try and further diagnose why it's not working but I'm guessing that the launched test container has not been detected so the haproxy.cfg has not been automatically updated (if that's correct?) - any help on how to try and get to bottom of this would be greatly appreciated.

Thanks,
Piers.

Icore@master ~ $ kubectl logs service-loadbalancer-1t2qm  

I1110 05:58:36.959150       1 service_loadbalancer.go:550] Creating new loadbalancer: {Name:haproxy ReloadCmd:./haproxy_reload Config:/etc/haproxy/haproxy.cfg Template:template.cfg Algorithm: startSyslog:false lbDefAlgorithm:roundrobin}
E1110 05:58:36.959519       1 service_loadbalancer.go:241] Get : unsupported protocol scheme ""
I1110 05:58:36.988153       1 service_loadbalancer.go:294] haproxy -- cat: can't open '/var/run/haproxy.pid': No such file or directory

**Comment by aledbf** [comment]
@piersharding can you add the `--syslog` flag to get more information? 
Your service is using the default namespace?

**Comment by piersharding** [comment]
Hi -

I've added --syslog, but it does not seem to be changing any of the logging.  It seems like the --tcp-services is not being parsed correctly (maybe I have the format wrong? - I have an rc/svc called damwatch which listens on 5000).  For example, if I exec into the container and try "./service_loadbalancer --dry --syslog --tcp-services=damwatch:5000", I get the following message 'service_loadbalancer.go:241] Get : unsupported protocol scheme "" ' 


Current running state:
core@minion-1 ~ $ docker logs `docker ps -a | grep servicelb | head -1 | tail -1 | awk '{print $1}'` 2>&1 | more
I1110 18:21:56.320753       1 service_loadbalancer.go:550] Creating new loadbalancer: {Name:haproxy ReloadCmd:./haproxy_reload Config:/etc/haproxy/haproxy.cfg Template:template.cfg A
lgorithm: startSyslog:false lbDefAlgorithm:roundrobin}
E1110 18:21:56.321423       1 service_loadbalancer.go:241] Get : unsupported protocol scheme ""
I1110 18:21:56.322145       1 loadbalancer_log.go:38] Starting syslog server for haproxy using /var/run/haproxy.log.socket as socket
I1110 18:21:56.362709       1 service_loadbalancer.go:294] haproxy -- cat: can't open '/var/run/haproxy.pid': No such file or directory
core@minion-1 ~ $ docker exec -it `docker ps -a | grep servicelb | head -1 | tail -1 | awk '{print $1}'` bash
bash-4.3# ps
PID   USER     TIME   COMMAND
    1 root       0:00 /service_loadbalancer --tcp-services=damwatch:5000 --syslog
   18 root       0:00 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf
   19 root       0:00 bash
   25 root       0:00 ps


Thanks,
Piers.

**Comment by jangaraj** [comment]
Use the latest version - 0.2 and it should be OK. See issue #110 .
