### ISSUE TITLE
Reviewer assigned by the bot should not be the author

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/contrib#2250]
In kubernetes/kubernetes#39401, the k8s-merge-robot  assigned a reviewer who is the PR author.

**Comment by madhusudancs** [comment]
Another instance of it here - https://github.com/kubernetes/kubernetes/pull/40584#issuecomment-275608061. Bot recommended me as a potential approver on my own PR.

**Comment by apelisse** [comment]
Agreed, they are two different things though: reviewers and approvers. @grodrigues3 has a pull-request that will fix the later, we need to address the former.

**Comment by madhusudancs** [comment]
Agreed too. I was too lazy to open another issue ;-)

**Comment by grodrigues3** [comment]
Further clarification:

If you are the author, the bot is going to (not yet implemented) automatically assume you approve the PR. 
https://github.com/kubernetes/test-infra/pull/1730

You should still be required to get an /lgtm from a reviewer in the owners file.
