### ISSUE TITLE
[nginx-ingress-controller] Proxy protocol for TCP services

### ISSUE THREAD

**Issue by tyranron** [kubernetes/contrib#2258]
There is a possibility to [use Proxy protocol](https://github.com/kubernetes/contrib/tree/99cba026d6c42d08b944aae1fd9fac173d76e3a1/ingress/controllers/nginx#proxy-protocol) when Nginx accepts traffic from L4 proxy.

But is there a possibility to enable Proxy protocol for [exposed TCP services](https://github.com/kubernetes/contrib/tree/99cba026d6c42d08b944aae1fd9fac173d76e3a1/ingress/controllers/nginx#exposing-tcp-services) via Nginx Ingress Controller, so those services will receive a real client IP?

Something like following HAProxy configuration:
```
    frontend ft_pop3_secure
        bind :995
        mode tcp
        log global
        option tcplog
        default_backend bk_pop3_secure_dovecot

    backend bk_pop3_secure_dovecot
        mode tcp
        log global
        option tcplog
        server dovecot server.mail.svc.cluster.local:995 send-proxy-v2
```

**Comment by tyranron** [comment]
Actually, [yes by Nginx](https://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_protocol).  
But [no by Nginx Ingress Controller](https://github.com/kubernetes/contrib/blob/43c4e86a5400365f87d6f68e9472908a979ebcc7/ingress/controllers/nginx/nginx.tmpl#L379-L381) at the moment.

**Comment by aledbf** [comment]
@tyranron the problem with add this feature is that all the TCP apps must support proxy protocol.
Is not possible to configure the `stream` section per TCP service. 
I need to add change the configuration in the configmap

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-configmap-example
data:
  9000: "default/example-go:8080:PROXY"
```

I will add this to the TODO list

**Comment by tyranron** [comment]
@aledbf I like that ConfigMap modification.  
Would you mind if I try to contribute that?

**Comment by aledbf** [comment]
@tyranron sure. Please open the PR in this repo instead https://github.com/kubernetes/ingress

**Comment by jackspaniel** [comment]
Hey @tyranron - we have a concrete implementation/need for this at my company. We need to load balance some MQTT requests using the ingress controller. I can work with you and possibly provide some resources. We have a call with nginx on Monday to talk about this issue. I will bring up this issue comment stream.

**Comment by styxlab** [comment]
Any progress on this one?

**Comment by tyranron** [comment]
@styxlab it's actually [implemented](https://github.com/kubernetes/ingress-nginx/blob/nginx-0.9.0/docs/user-guide/exposing-tcp-udp-services.md).
