### ISSUE TITLE
[service-loadbalancer] HAproxy restarts all the time

### ISSUE THREAD

**Issue by Dmitry1987** [kubernetes/contrib#2261]
I've noticed an issue with this pod,
it shows this and restarts haproxy in a loop:
```
service_loadbalancer.go:338] haproxy --
service_loadbalancer.go:536] Sync triggered by service kube-system/kube-controller-manager
service_loadbalancer.go:497] Found service: {Name:nginx-service-1:90 Ep:[10.42.113.224:80] BackendPort:80 FrontendPort:80 Host: SslTerm:false AclMatch: Algorithm:roundrobin SessionAffinity:true CookieStickySession:false}
service_loadbalancer.go:497] Found service: {Name:nginx-service-2:90 Ep:[10.42.38.98:80] BackendPort:80 FrontendPort:80 Host: SslTerm:false AclMatch: Algorithm:roundrobin SessionAffinity:true CookieStickySession:false}
service_loadbalancer.go:497] Found service: {Name:etcdbrowser Ep:[10.42.3.112:8080] BackendPort:8080 FrontendPort:80 Host: SslTerm:false AclMatch: Algorithm:roundrobin SessionAffinity:true CookieStickySession:false}
service_loadbalancer.go:436] No endpoints found for service randomtest, port {Name: Protocol:TCP Port:3000 TargetPort:{Type:0 IntVal:3000 StrVal:} NodePort:31999}
service_loadbalancer.go:436] No endpoints found for service kubernetes, port {Name:https Protocol:TCP Port:443 TargetPort:{Type:0 IntVal:443 StrVal:} NodePort:0}
service_loadbalancer.go:338] haproxy --
```
what might be the reason for constant restarts? (i see in "ps" that haproxy process ID changes every moment, so guessed it gets restarted all the time)
kubernetes ingress and services remain the same. I've thrown a few examples and a random empty service definition into it, and that's it. Just to see how it renders HAproxy config file.

The log displays "Sync triggered by service kube-system/kube-controller-manager"  but I have nothing in "kube-system" namespace, because run this on Rancher, so I have all stuff in "default" namespace, and an "empty" kube-system :)  maybe this what caused restarts?

Also, I don't see hostnames in HAproxy config, only URI, but doesn't it support Ingress host based routing?

**Comment by maikotz** [comment]
+1
One thing I found out already is that the actual kube-dns addon creates a UDP and a TCP service for DNS and that confuses haproxy as well, since there were two upstream servers defined.

```service_loadbalancer.go:338] haproxy -- [WARNING] 019/164000 (7456) : parsing [/etc/haproxy/haproxy.cfg:187] : backend 'kube-dns:53', another server named '10.1.70.2:53' was defined without an explicit ID at line 186, this is not recommended.```

Is there a possibility to ignore namespaces or limit the service parsing to a certain namespace ?

**Comment by maikotz** [comment]
Ok, I got it to work with the one of the following:

* To disable the ``kubernetes``service to be discovered just add: ``        - --use-kubernetes-cluster-service=false`` to the ``args`` of the load balancer. This assumes that your cluster services have the annotation set.
* For me (on bare metal, selfhosted) I had to set the hostPort to another port and rebuild the image to use another port as well.
* enable also the ``--syslog`` arg to see whats happening

**Comment by Dmitry1987** [comment]
Thanks @maikotz  !  
For now we switched to using nginx ingress controller, from default K8s repo, and it works good.  
But this ticket might help others who get stuck on same.  thanks for solving and sharing :+1:

**Comment by bprashanth** [comment]
Thanks for the report, we're actually moving haproxy controller over to ingress. There's a community controller documented here: https://github.com/kubernetes/ingress/tree/master/examples/deployment/haproxy, please give that one a shot, and if it suffers from the same issue, we can take it up with the maintainers.

**Comment by bprashanth** [comment]
Closing for now in the hope that we can move discussion over to haproxy ingress

**Comment by gsaslis** [comment]
@bprashanth does this mean that the haproxy ingress should now be preferred over the service loadbalancer?
Are there any cases where this would not be the case?
