### ISSUE TITLE
[nginx-ingress-controller] Combine upstreams if hosts are the same

### ISSUE THREAD

**Issue by peterj** [kubernetes/contrib#2263]
I have two services deployed in two different namespaces:
```
namespace-1   service-a
namespace-2   service-a                
```

I've also deployed Ingress rules to both namespaces to route requests from "www.example.com" to "service-a": 

```
  "host": "www.example.com",
                "http": {
                    "paths": [
                        {
                            "backend": {
                                "serviceName": "service-a",
                                "servicePort": 80
                            },
                            "path": "/"
                        }
...
```
I can ping both "service-a.namespace-1" and "service-a.namespace-2". I've deployed the nginx ingress controller and I get two separate different upstreams: 

```
upstream namespace-1-service-a {
   ...
}

upstream namespace-2-service-a {
....
}
```

And the server block for "www.example.com" is doing a proxy_pass to the upstream that was defined last (e.g. if I deployed namespace1 first and then namespace2, I get the ```proxy_pass http://namespace-2-service-a```). 

My expectation was if the host names in the ingress are the same (www.example.com), I would only get 1 upstream that contains endpoints for pods in both namespaces. 

Am I missing something or is this just not supported or I am doing it completely wrong?

**Comment by aledbf** [comment]
@PeterJausovec in an Ingress rule you cannot reference services located in different namespaces.
This is the reason why you see two upstreams.

Also please keep in mind that you can have multiple services with the same name if they are located in different namespaces. By definition this services are not equals.

**Comment by PeterJausovec** [comment]
Thanks @aledbf! Yep, I am treating those two services as different services (e.g. V1 and V2). So, you're saying that this is by design? Is there another way I should look into to get this scenario working?

**Comment by aledbf** [comment]
> So, you're saying that this is by design?

Yes.

Or better yet, restricted by the Ingress specification design.
I cannot assume that two services, even with the same name, are equals if they are located in different namespaces and merge the upstreams.

**Comment by PeterJausovec** [comment]
I was thinking the way that you could determine they are equals is by using the host in Ingress?

**Comment by aledbf** [comment]
@PeterJausovec out of curiosity, what are you trying to achieve?

**Comment by PeterJausovec** [comment]
I am trying to do an upgrade of an existing deployment (v1) and ensure that services that are deployed in v1, continue to talk to services deployed in v1 while v2 is being deployed. Trying to draw this, it would look like this: 

```
Starting state:
External IP --> service-a (v1) --> service-b (v1) 

Deploy v2 services:

                     |--> service-a (v1) --> service-b (v1)
external IP--|
                     |--> service-a (v2) --> service-b (v2)
```

Or in words: service-a v1 is exposed through an external IP and talks to service-b v1 internally through http://service-b. I want to upgrade both service-a and service-b in such a way that when the external IP is hit, I either get proxied to service-a v1 OR service-a v2 and I can ensure that anytime I hit service-a v1, I will always get service-b v1. Note that internally service-a v2 talks to service-b v2 through the same hostname (http://service-b) as they are in a different namespace.

**Comment by aledbf** [comment]
@PeterJausovec so you trying to do a custom blue/green deployment.

I think you are missing an important point: is not possible to merge multiple Ingress rules.

What you cannot achieve using deployments with upgrades controlling `maxUnavailable` and using `readinessProbe` and `livenessProbe`?

**Comment by PeterJausovec** [comment]
I don't want service-a (v2) to call service-b (v1). 

In my code service-a is referencing to service-b as http://service-b (similarly as docker uses the add-host when linking services together) and I want to keep this.

**Comment by aledbf** [comment]
@bprashanth ping.
