### ISSUE TITLE
Nodes have no External IP

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/contrib#228]
Hi,

I am trying to run the example, but I get stuck in "Expose services"; none of my nodes have any external IP. The following command gives me nothing:

kubectl get nodes  -o json | grep -i externalip -A 1

How can I activate the external IP for the role=loadbalancer nodes? 

Thank you

**Comment by thockin** [comment]
on what cloud platform?  In general, if you want nodes to serve public traffic, they need public IPs.  We don't really manage nodes at that level.

**Comment by andrejvanderzee** [comment]
Hi Tim,

Thanks for you reply. I am woking on a bare metal deployment on
AliYun/AliCloud.

I have noticed though that in Kubernetes V1.1.1 we can specify our own
public IPs for services, outside the cluster VIP range.

Thanks,
Andrej

**Comment by thockin** [comment]
The externalIPs field is specifically un-managed IPs.  The assumption is
that you, the admin or developer, has arranged for the IP to to exist and
for the routing to bring that traffic into kubernetes. We just accept
traffic as that IP.

In a general sense, there's just no way we could know how to provision
external IPs for nodes short of a cloud provider hook, and sadly "bare
metal" is not a cloud provider yet.

**Comment by andrejvanderzee** [comment]
Hi Tom,

That being said, where does the public IP come from when i do not specify
it in the service? You mentioned a cloud provider hook. How does such a
hook look like? Is this documented somewhere?

Thank you,
Andrej

**Comment by thockin** [comment]
If you ask for a service with `spec.type=LoadBalancer` we call out to the
cloud provider to allocate an IP for you.  If you use the contrib service
LB, it assumes node IPs must exist.  The new Ingress object and related
controllers do one or the other depending on which controller you use (GCE
vs haproxy)

**Comment by andrejvanderzee** [comment]
Hi Tim,

Thanks for this.

My cloud provider is AliYun. I assume every provider has its own specific
way to provide a public IP, so I better find out how AliYun does this? Is
that correct? If so, I guess Kubernetes requires a patch for AliYun support?

Thanks,
Andrej

**Comment by thockin** [comment]
Yeah, getting first-class support for Ali would be nice!

**Comment by linkmancheng** [comment]
Hi Tim,

Can Kubernetes support Ali loadbalance or storage now?  
Thanks.

**Comment by thockin** [comment]
As far as I know, nobody has sent us any patches for AliCloud support.

**Comment by denverdino** [comment]
@linkmancheng FYI https://github.com/kubernetes/kubernetes/pull/40334 the PR to support the Alibaba Cloud with SLB for ingress access.

It is closed but, We will figure out how to integrate it after the refactoring Cloud provider architecture of K8S

**Comment by cmluciano** [comment]
/close

issue is stale
