### ISSUE TITLE
[nginx-slim] update to nginx 1.11.8

### ISSUE THREAD

**Issue by andrenarchy** [kubernetes/contrib#2283]
nginx-slim is currently building nginx 1.11.6. Current is 1.11.8.

**Comment by aledbf** [comment]
@andrenarchy PR already open to update to 1.11.8 https://github.com/kubernetes/contrib/pull/2225

**Comment by andrenarchy** [comment]
thank you! I probably couldn't find it because the PR's title is a bit generic. :smiley:

**Comment by aledbf** [comment]
@andrenarchy good point :)

**Comment by aledbf** [comment]
@andrenarchy image released. Please close this issue.

**Comment by andrenarchy** [comment]
Thanks!
