### ISSUE TITLE
[nginx-ingress-controller] update nginx-slim

### ISSUE THREAD

**Issue by andrenarchy** [kubernetes/contrib#2284]
The nginx ingress controller currently pulls nginx-slim:0.9 (nginx 1.11.3) while nginx-slim:0.11 (nginx 1.11.6) is current. I suggest that nginx-slim is first updated to build nginx 1.11.8 (nginx-slim:0.12) before the ingress controller is updated, see https://github.com/kubernetes/contrib/issues/2283.

**Comment by aledbf** [comment]
@andrenarchy already open :) https://github.com/kubernetes/ingress/pull/99

**Comment by aledbf** [comment]
@andrenarchy the development of ingress is now located in https://github.com/kubernetes/ingress

**Comment by andrenarchy** [comment]
ah, will it be removed from this repo then? could be confusing otherwise...

**Comment by aledbf** [comment]
@andrenarchy yes after the first release from the new repo

**Comment by andrenarchy** [comment]
Thank you! Is there a rough estimate about when this will be released?
