### ISSUE TITLE
[nginx-ingress-controller] question: port_in_redirect flag set to off by default

### ISSUE THREAD

**Issue by rithujohn191** [kubernetes/contrib#2293]
I was trying to find some documentation as to why the port_in_redirect flag in the nginx.tmpl file is set to off by default when nginx has it as on (http://nginx.org/en/docs/http/ngx_http_core_module.html#port_in_redirect).

We have a use case where all we have to do is turn on port_in_redirect and currently it requires us to mount the entire nginx.tmpl.

**Comment by aledbf** [comment]
@rithujohn191 usually when nginx is used as reverse proxy the flag port_in_redirect is disabled to avoid unexpected port changes (keep the port used by the client during redirects)

I will open an issue in https://github.com/kubernetes/ingress to add this as a global configuration and annotation to allow the change of this flag

**Comment by aledbf** [comment]
https://github.com/kubernetes/ingress/issues/127

**Comment by rithujohn191** [comment]
Thank you @aledbf
