### ISSUE TITLE
Have the bot apply sig label on sig mentions.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/contrib#2302]
I know folks are working on new submission template but it would likely save a bunch of time if the bot just applied the sig label on the sig mention.  For those that can't label it allows them to reach the right audience most of the time.  

@kubernetes/sig-contributor-experience-misc

**Comment by spxtr** [comment]
This could be done pretty easily as a prow plugin.

**Comment by apelisse** [comment]
Yeah, just be careful because the github api will create the label that you apply if it doesn't exist. Meaning if you match @sig-.* and blindy add that label, then it will create stupid labels every time someone types @sig-$something_stupid.

**Comment by sig-** [comment]
Yeah, I don't know exactly what you're doing, but since it's apparently connected to GitHub you might want to double check that it doesn't give me a mention notification every time someone types @sig-$something_or_other 😜

**Comment by foxish** [comment]
This issue was moved to kubernetes/test-infra#1640
