### ISSUE TITLE
Nginx ingress controller difference

### ISSUE THREAD

**Issue by Dmitry1987** [kubernetes/contrib#2313]
Hi, what is the difference between nginx controller in this repo, and this one:  https://github.com/nginxinc/kubernetes-ingress  (it's official from nginx company as I understand?)

which one better to use?

**Comment by aledbf** [comment]
> https://github.com/nginxinc/kubernetes-ingress (it's official from nginx company as I understand?)

Yes, that controller is from nginx inc.

> Hi, what is the difference between nginx controller in this repo, and this one:

The biggest difference is the use of endpoints instead of services and the number of annotations this controller provides.

> which one better to use?

You should decide that :)

**Comment by Dmitry1987** [comment]
thanks @aledbf ,
if you had experience with those controllers (I'm just trying to learn how to use), was it possible to deploy 1 in "default" namespace (and all loadbalancer pods will also be in 'default' for example) but the ingress points to all services in several namespaces. is it possible somehow?  from what I see now, seems like it doesn't work...  I did few deployments and exposed services, listed in ingress, from several namespaces. 

The nginx config does show all those "upstream names" but doesn't point to the real IPs and ports where pods in other namespaces are deployed... so seems like it _can see the ingress_ - but not the services, which are listed in that ingress.  I'll be digging the docs of course, but if you have an advice it could be great :)  , thanks!

**Comment by aledbf** [comment]
@Dmitry1987 the Ingress spec only allows the reference of services that are located in the same namespace. You need to create multiple Ingress in different namespaces (where the service is located).

> The nginx config does show all those "upstream names" but doesn't point to the real IPs and ports where pods in other namespaces are deployed

The ingress controller does not uses services. It uses the endpoints instead. This allows the bypass of `kube-proxy` enabling things like sticky sessions and custom load balancing algorithms.

**Comment by Dmitry1987** [comment]
Ok, I understand, 
thanks a lot for clarification @aledbf  !
