### ISSUE TITLE
Cluster Autoscaler: Enable instance protection in AWS

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/contrib#2316]
To ensure cluster-autoscaler will only terminate nodes that are valid candidates, we can enable instance protection on all nodes visible to cluster-autoscaler. This will give cluster-autoscaler a lot of flexibility regarding decreasing ASG sizes without accidentally terminating nodes that shouldn't be. 

related issue/PR: https://github.com/kubernetes/contrib/pull/2300

**Comment by patrickshan** [comment]
we just had this problem with cluster autoscaler running inside AWS and I added a comment in this issue: https://github.com/kubernetes/autoscaler/issues/144 . But basically the fix for us is to enable "Protect From Scale In" for our ASG.
