### ISSUE TITLE
[nginx-ingress-controller] Why is header "connection: close" is added when request is passed to upstream in Nginx ingress?

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/contrib#2322]
Hi,

With the Nginx ingress controller, the header "connection: close" is added when the request is passed to upstream. I read the upstream server log and find that. Why? What I hope is the original header relating to connection status should be passed to upstream server without any change.

**Comment by tjliupeng** [comment]
Connection is hop-by-hop header. It won't be forwarded by proxy. Adding configuration below

proxy_set_header Connection $http_connection

to nginx.conf to solve it.

**Comment by rcarmo** [comment]
I'm trying to track down why the ingress controller is closing keepalive connections to my backends, and... this appears to be part of the reason. Is there a specific repo where I can discuss this?
