### ISSUE TITLE
[keepalived-vip] multi-nic systems not supported

### ISSUE THREAD

**Issue by kitch** [kubernetes/contrib#2328]
If the worker nodes of the cluster have multiple NICs there is currently no way to control where nic the VIP will be attached to. If there is a private (eth0) and public interface (eth1) for the worker there must be a way to choose which adapter to associate the VIP to.

**Comment by genti-t** [comment]
I don't know how, but at first it was attached con the right interface (eth1) and working perfectly,
now after some restart / delete /create still working but is attached on my private interface (eth2)

Does that make sense ?

**Comment by vadapalliravikumar** [comment]
I am also seeing the same issue. I see the track_interface in vrrp_instance config section also set to a wrong interface. May be, it is not sure which nic to pick and is probably picking an interface randomly.

If we can pick the interface that has an IP from the same subnet as the VIP, the problem would be fixed for our setup.

**Comment by andreashartke** [comment]
Is there any solution? I have the same issue and idea to solve it. Multiple nics and the VIP do not match the nic configured in the keepalived.conf.

**Comment by zuberahmed1987** [comment]
Is there any solution?
/reopen
/remove-lifecycle rotten
