### ISSUE TITLE
Move mungegithub to the test-infra repo

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#2333]
All the bots can live in one place and we can have documentation for commands and such.

- [x] Preserve history during move
- [ ] Open issues against mungegithub must be moved out to test-infra
- [ ]  Redirect to new location

This should help new contributors trying to understand our bots and contribute code to them have one place to look.
Long term: eventually unify prow and mungegithub.

/cc @eparis @grodrigues3 @apelisse

**Comment by foxish** [comment]
@eparis do you have any objections?

**Comment by eparis** [comment]
i think its a great idea

**Comment by spxtr** [comment]
I can help out with getting testing working in the new repo, since we have a few different conventions over there.

**Comment by fejta** [comment]
This will also make it easier to do certain types of testing. For instance ensure that blocking SQ jobs are configured in prow to always run, and that all SQ jobs are in testgrid, etc.

**Comment by apelisse** [comment]
I think we can call it done.
