### ISSUE TITLE
[addon-resizer] Set logging levels to reduce amount of logs produced

### ISSUE THREAD

**Issue by Crassirostris** [kubernetes/contrib#2337]
Currently, nanny produces a lot of meaningful messages by default, like

```go
log.Infof("The number of nodes is %d", num)
```

or

```go
log.Infof("Resources are within the expected limits.")
```

IMO, logging levels should be set up according to [the developer's guide](https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md) and such messages shouldn't be visible by default.

CC @piosz

**Comment by piosz** [comment]
cc @Q-Lee

**Comment by jmn** [comment]
When can/will this be deployed on GKE?

**Comment by piosz** [comment]
I bumped the version on HEAD https://github.com/kubernetes/kubernetes/pull/40707. I'll cherry-pick it to 1.5, then it will be released in a patch release and then rolled out to GKE. Should be in ~2-3 weeks. In the meantime you can just bump addon resizer version in your deployment to 1.7.

**Comment by jmn** [comment]
Just noting, as I upgraded to Kubernetes 1.5.2 that editing deployments for addons no longer seems to work. The edit gets reverted to addon-resizer:1.6.
