### ISSUE TITLE
Cluster Autoscaler: Add Least-Cost Node Group Expander Strategy

### ISSUE THREAD

**Issue by Capitrium** [kubernetes/contrib#2347]
This expands upon issue #1921 and PR #2118, which added support for node group expansion strategies which allow the cluster autoscaler to determine the ideal node group to expand instead of just selecting a node group at random. Adding a strategy that selects the node group to expand based on the cost of nodes within each configured group allows us to better take advantage of cloud provider discount options (i.e. AWS Spot Instances), thereby minimizing the cost of running clusters.

**Comment by Capitrium** [comment]
#2348 provides the implementation we've been using in our cluster for the last several weeks, although it look like support for Azure was recently added and I don't have any test coverage for that yet so the build is currently failing. Fun.

**Comment by tuananh** [comment]
@Capitrium 
I have a question re. this issue. if the `cluster-autoscaler` picks spot group but unable to scale up due to price spike, will cluster-scaler be aware of this and scale the other group instead?

**Comment by Capitrium** [comment]
> if the cluster-autoscaler picks spot group but unable to scale up due to price spike

I'm not sure exactly what you mean by this - the node cost is evaluated for each group before the least-cost expander picks a node group to expand, so it should always be able to scale up the node group that it picks.

Generally, requests for instances can fail to be fulfilled due to a cloud provider api error - adding instances to AWS AutoScaling groups can fail for a variety of reasons, i.e. insufficient capacity for the requested instance type, insufficient bid price for spot instances, etc. So if the spot price were to spike above your bid price _after_ the least-cost expander has selected a node group for expansion but _before_ instances have been added to the group, that could potentially cause an issue for the cluster-autoscaler. I haven't run into that issue running the least-cost expander for several weeks now, including in situations where the spot price in at least one AZ exceeded my maximum bid price, but that's not to say that it couldn't happen.

I think the ideal behaviour would be to failover to an alternate node group in the case of any such cloud provider error, but I think such a feature would belong in a separate PR if it doesn't already exist.

**Comment by tuananh** [comment]
Thank you. Could you point me to the part where that logic is?

Btw is there a recent image for cluster autoscaler prebuilt somewhere? The
one on gcr.io is stuck at v0.4

**Comment by Capitrium** [comment]
- [least-cost expander](https://github.com/NickelMedia/contrib/blob/add-least-cost-expander/cluster-autoscaler/expander/leastcost/leastcost.go) (main node group selection logic here)
- [aws cloud provider NodeCost function implementation](https://github.com/NickelMedia/contrib/blob/add-least-cost-expander/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L137) (update node cost for a node group)
- [current aws spot instance price update](https://github.com/NickelMedia/contrib/blob/add-least-cost-expander/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L215) (gets the current spot instance price for a node group)

We're using a custom-built image of the cluster-autoscaler stored in a private repo for now since the least-cost expander isn't merged in yet; I'm not sure where the latest official image can be found, but I'd assume it's the one on gcr.io.

**Comment by andrewklau** [comment]
@Capitrium are you able to share your custom-built image? (or hopefully get the PR merged).
I've primarily been using spotfleets over ASGs, so I'm just curious what happens if a spot instance is terminated from the ASG, it seems there may be quite a delay until a new node would come up to replace it?

**Comment by mwielgus** [comment]
cc: @andrewsykim

**Comment by tuananh** [comment]
@andrewklau v0.5.0 is published on gcr.io

**Comment by andrewklau** [comment]
@tuananh I don't believe that has the least-cost expander mentioned above

**Comment by tuananh** [comment]
@andrewklau my bad. I haven't tried it myself either.

**Comment by Capitrium** [comment]
@andrewklau I haven't had much time to work on this since I opened the PR, but I'm hoping to have some time to get this merged in the next few weeks as I'm making some other updates on our cluster. Unfortunately I can't share my image in the meantime, as I can't give access to our private registry.

**Comment by mwielgus** [comment]
This is implemented as https://github.com/kubernetes/autoscaler/issues/82. Please consider implementing https://github.com/kubernetes/autoscaler/issues/131.
