### ISSUE TITLE
Cluster-autoscaler: provide a mechanism to grow node groups simultaneously.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#2352]
We are receiving request to provide an option to grow and shrink node groups more evenly - in many cases the node groups are in different zones/subregions but contain the same type of machines. Having the inbalance in the node groups increase the max severity of a node group outage.

**Comment by mumoshu** [comment]
@mwielgus I'd like to work on this.

AFAIK, CA as of today already randomly choose an ASG from candidates(=ASGs which serves currently unschedulble pods hence to be scaled out).
If that's true, what you meant is to make CA first tries to choose the ASG with the fewest nodes, right?

**Comment by mumoshu** [comment]
Assuming my assumption above is correct, I'm going to implement the `balance` expander.
It will try to balance number of nodes among target node groups by returning an `expander.Option` with the least `NodeCount`.

**Comment by mumoshu** [comment]
This issue had been moved to https://github.com/kubernetes/autoscaler/issues/47 and then resolved there.

**Comment by mwielgus** [comment]
Closing in favor of https://github.com/kubernetes/autoscaler/issues/47
