### ISSUE TITLE
Latest nginx-ingress-controller version?

### ISSUE THREAD

**Issue by styxlab** [kubernetes/contrib#2355]
The latest tag of this contrib is on version 0.7.0, but many examples show the following container image: gcr.io/google_containers/nginx-ingress-controller:0.8.3. However, nowhere did I find version 0.8.3.

So, what is the latest (official) version of the nginx ingress controller?

**Comment by aledbf** [comment]
@styxlab the development of ingress controllers is now located in https://github.com/kubernetes/ingress. 
We are in the process to release the next version. Please check https://github.com/kubernetes/ingress/pull/181
