### ISSUE TITLE
Cluster-autoscaler: Update GCR image regularly

### ISSUE THREAD

**Issue by jleonar** [kubernetes/contrib#2357]
When testing the auto-scaling functionality, specifically the multiple AWS ASG capability.  The latest image (v0.4.0) on gcr does not support the new flag --expander.

**Comment by whereisaaron** [comment]
Related to #2434 request to have a regularly built 'latest' labelled image

**Comment by javapapo** [comment]
+1

**Comment by tuananh** [comment]
Just so you know, there is a more recent image now `0.5.0-beta1`

**Comment by mwielgus** [comment]
We update the image along with major Kubernetes releases. 
0.5.1 has been released with 1.6.

As CA is still in beta we don't maintain full compatibility with all K8S releases. Until GA, Cluster-Autoscaler should be used only with the release it is meant for. See README.md for details.
