### ISSUE TITLE
Add a "cla-ok" label

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/contrib#236]
I propose a "CLA affirmed by human" label that @googlebot won't flip, so that the submit queue can have two positive CLA signals to go off of. (It's frustrating to fight @googlebot on cherry-picks and known-good committers.)

cc @brendandburns @jlowdermilk

**Comment by eparis** [comment]
It's really easy to do if I get a +1 from someone else on the idea I can probably get it running today...

Not sure I love the "cla-ok" name as the difference with 'cla: yes' is not obvious.   "cla: human-approved"

**Comment by jlowdermilk** [comment]
+1. I would love it if the label were `go home cla-bot you're drunk`, but I digress...

**Comment by zmerlynn** [comment]
You can change the name. `cla: human-approved` is fine. :)

**Comment by eparis** [comment]
So #238 works. The bot would merge https://github.com/kubernetes/kubernetes/pull/17235 even though it also has 'cla: no'

I'm a little tiny bit worried about this flag though, what if someone pushes completely new changes after the human adds 'cla: human-approved'.  Would we also like to have a 'remove human-approvaed if changed'? Exactly the same as the 'remove LGTM is changed?'

**Comment by zmerlynn** [comment]
Hrm. It probably increases the complexity a fair amount to check that the commit authorship hasn't changed between labels.

**Comment by eparis** [comment]
a lot....

**Comment by zmerlynn** [comment]
It feels like the risk is minimal, since the LGTM would disappear, so human could also remove the CLA-approval as well. Does the seem right? But I'm worried I'm missing something.

**Comment by eparis** [comment]
It's live and working.  Called `cla: human-approved`
