### ISSUE TITLE
Make cluster autoscaler work with Kubernetes 1.6

### ISSUE THREAD

**Issue by davidopp** [kubernetes/contrib#2381]
Taints are being moved from annotation to field of Node. See kubernetes/kubernetes#25320 and kubernetes/kubernetes#38957

There's no 1.6 milestone in this repo, but it is needed for 1.6.

**Comment by davidopp** [comment]
Also, write release notes for any special considerations when upgrading to 1.6.

**Comment by davidopp** [comment]
cc/ @fgrzadkowski

**Comment by davidopp** [comment]
#38957 has merged, so HEAD now has the new behavior (taint/toleration annotations are ignored by scheduler, and now scheduler pays attention to taint/toleration fields).

Code freeze is getting close...

**Comment by fgrzadkowski** [comment]
@mwielgus What's the status of this issue?

**Comment by davidopp** [comment]
ping @mwielgus -- this is getting pretty urgent

cc/ @kubernetes/release-team

**Comment by mwielgus** [comment]
CA was done last week. We are polishing couple things/bugfixing before bumping the version in k8s repo.

**Comment by mwielgus** [comment]
ref https://github.com/kubernetes/contrib/pull/2437
