### ISSUE TITLE
flag --ingress-class  not work

### ISSUE THREAD

**Issue by 1071496910** [kubernetes/contrib#2383]
log for ingress-controller:
![image](https://cloud.githubusercontent.com/assets/9696208/22924292/8aa08300-f2df-11e6-8eff-d58b41ed50a2.png)

ingress:
![image](https://cloud.githubusercontent.com/assets/9696208/22924158/10968c6c-f2df-11e6-8b0f-e6c70a70fbdc.png)
nginx.conf
![image](https://cloud.githubusercontent.com/assets/9696208/22924249/61965656-f2df-11e6-8bb2-c4fb8b0ce8ad.png)

only test-ingress2 has location /pear2 

is this a bug?

**Comment by fanhaozzu** [comment]
i find this problem too, the  ingressClass = flags.String("ingress-class", "",
			`Name of the ingress class to route through this controller.`) not work
			`
