### ISSUE TITLE
Cannot have a valid client certificate

### ISSUE THREAD

**Issue by metal3d** [kubernetes/contrib#2394]
As in #651 I will explain my problem here with more details.

Installed on CentOS 7, kubernetes is now working. I want to access UI from my computer and give access to other peaple.

I tried this:

```bash
# on my computer
openssl genrsa -out client.key 1024
openssl req -key client.key -new -out client.csr

# Passing my key and csr to kubernetes server, I now
# create a pem file
openssl x509 -req -in client.csr \
    -CA /etc/kubernetes/certs/server.crt \
    -CAkey /etc/kubernetes/certs/server.key \
    -CAcreateserial \
    -out client.pem \
    -days 3650
```

It's OK, I now get back my client.pem file and create a pkcs12 file on my computer:

```bash
openssl pkcs12 -export -out client.pfx -in client.pem -inkey client.key 
```

I finally import that pfx file into Chrome, the given certificate is prompted while I'm connecting to my UI. But I always get "Unauthorized" response.

I tried different options, when I generating pkcs12 file I tried to add "-certfile"  with ca.crt, server.crt, and so on...

Is anyone here can tell me if there is a solution, or if I do something wrong.

**Comment by metal3d** [comment]
Notes:

- I set password to pkcs12 file
- I use CN to my kubernetes master IP
- I see that error in journalctl:
   ```
   févr. 19 10:19:51 k8s-master kube-apiserver[23615]: E0219 10:19:51.654190   23615 handlers.go:55] Unable to authenticate the request due to an error: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "163.172.136.247")
   ```

**Comment by galexrt** [comment]
@metal3d I think you need to use the Kubernetes CA from the first master server to sign the key(s) you are creating with.

**Comment by metal3d** [comment]
Yes, but the CA.key is not present, so I cant sign.
I just fixed this and I will provide a PR :)

**Comment by galexrt** [comment]
You would just need to add a cp instruction to the `make-ca-cert.sh` script to also copy the ca.key to the certs dir. So the ca key is at least on the first master available. Isn't that what you just need?

Would you then mind linking/mentioning the PR here in a comment as I'd like to follow this.

**Comment by metal3d** [comment]
Yes this is exactly what I did. I also added that file in the "check right" task.
I will push the contrib PR in 1 hour.

It's a pleasure to help :)

**Comment by metal3d** [comment]
OK... It's been one week ago... But I did it :)

**Comment by metal3d** [comment]
@galexrt Just to say that the PR is reviewable now

**Comment by xialonglee** [comment]
There is a simple solution to make you can access to UI, you can try it.
Specified apiserver args `--basic-auth-file=[your_basic_auth_file]`, add password/username/userid content and then you can access UI through username/password.

**Comment by metal3d** [comment]
Yes but that's not what we need. We need authentication by cert. Some
admins want to be able to not use basic auth 🙂
