### ISSUE TITLE
cluster-autoscaler assumes kube-system as its namespace

### ISSUE THREAD

**Issue by dhawal55** [kubernetes/contrib#2402]
I'm trying to run cluster-autoscaler in a namespace other than kube-system and get below error:
`leaderelection.go:210] failed to renew lease kube-system/cluster-autoscaler`

The leaderElection section assumes that cluster-autoscaler is running in kube-system namespace. It should lookup the namespace OR at-least update the ReadMe to mention that this will only run in kube-system namespace.

**Comment by mumoshu** [comment]
Hi @dhawal55!
AFAIK, [there's `--namespace` flag](https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/main.go#L68) as of today, to override the namespace to which CA is scheduled, to whatever you'd like.
Would it solve your problem?

**Comment by dhawal55** [comment]
Oh great, that's what I was looking for. Closing the issue
