### ISSUE TITLE
NGINX cannot access basic auth data in /etc (nginx-ingress-controller:0.9.0-beta.1)

### ISSUE THREAD

**Issue by evgf** [kubernetes/contrib#2403]
Hello,
When upgrading the NGINX Ingress Controller image from v. 0.8.3 to v. 0.9.0-beta.1 (gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.1) we discovered that all our Ingresses using basic authentication do not work (HTTP 500). 
The reason is that the auth data are stored in /etc/ingress-controller/auth but the privileges of the /etc directory were changed from 755 (in 0.8.3) to 750 (in 0.9.0 beta 1). The NGINX worker processes run as nobody and cannot open these files:
> 2017/02/22 09:45:01 [crit] 341#341: *11 open() "/etc/ingress-controller/auth/default-kibana.passwd" failed (13: Permission denied), 

It seems that some work was invested into moving the NGINX-specific files under /ingress-controller but this does not cover the auth data and the new directory also has the 750 privileges.

**Comment by aledbf** [comment]
@evgf this is already fixed in [master](https://github.com/kubernetes/ingress/pull/281) and included in the [next beta](https://github.com/kubernetes/ingress/pull/303)

**Comment by evgf** [comment]
Thank you @aledbf  - do you know when the new image will be available?

> docker pull gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.2
> Pulling
> repository gcr.io/google_containers/nginx-ingress-controller
>Tag 0.9.0-beta.2 not found in repository gcr.io/google_containers/nginx-ingress-controller

**Comment by evgf** [comment]
Got it, thanks again!
