### ISSUE TITLE
cluster-autoscaler: Remove minimum ASG size requirement of 1

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/contrib#2425]
I use 3 different ASGs for my cluster.  One of them I have set to a minimum of 3 for my cluster's main components to live on.  The other two ASGs are only for batch jobs that require specific types of instances.  I'd like to be able to have the other two ASGs have a minimum count of 0.  

e.g.  I'd like this configuration to be valid:
--nodes=3:10:primary-asg
--nodes=0:10:batch-job-a-asg
--nodes=0:10:batch-job-b-asg

I specifically use the 2nd two ASGs in conjunction with Kubernetes Jobs, so I don't need those instances sitting around when no jobs are running.

**Comment by whereisaaron** [comment]
Hi @ryanwalls, I was wanting have a fix primary group, and a secondary ASG that scaled from 0 too.
```
--nodes=0:10:secondary-asg
```

When you have multiple ASG as in you example, how does the autoscaler know which batch job ASG will suit you batch job? E.g. do you use a node label selector on your batch job and the autoscaler works out which pool to scale up that way?

**Comment by dmcnaught** [comment]
@whereisaaron : we do that with node label selectors and it's working fine.

**Comment by mwielgus** [comment]
Closing in favor of https://github.com/kubernetes/autoscaler/issues/132

**Comment by ryanwalls** [comment]
@whereisaaron like @dmcnaught said.  We use node selectors as well.
