### ISSUE TITLE
ansible: failed load flannel config file if use IP in inventory

### ISSUE THREAD

**Issue by gouyang** [kubernetes/contrib#243]
TASK: [flannel | Load the flannel config file into etcd] ********************** 
failed: [10.66.15.133 -> 10.66.15.133] => {"changed": true, "cmd": "/usr/bin/etcdctl --no-sync --peers=http://10.66.15.133:2379 set /cluster.local/network/config < /tmp/flannel-conf.json", "delta": "0:00:00.214135", "end": "2015-11-15 01:33:17.547932", "rc": 4, "start": "2015-11-15 01:33:17.333797", "warnings": []}
stderr: Error:  501: All the given peers are not reachable (failed to propose on members [http://10.66.15.133:2379] twice [last error: Put http://10.66.15.133:2379/v2/keys/cluster.local/network/config: dial tcp 10.66.15.133:2379: connection refused]) [0]

FATAL: all hosts have already failed -- aborting

**Comment by gouyang** [comment]
it failed because etcd client does not listen to host's IP

**Comment by PeterLamar** [comment]
I hang forever at the step TASK: [flannel | Load the flannel config file into etcd] *****
Any workarounds?

**Comment by gouyang** [comment]
the issue does not exist anymore
