### ISSUE TITLE
cluster-autoscaler: Add debug logging and flag to help troubleshoot scaling issues

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/contrib#2433]
Using release 0.4.0 I have 7 nodes in my ASG and at least 3 of them are running well below 50% utilization and I think should be candidates for scale-in.  It would be great if I could run the autoscaler with a debug flag so it would print out hints as to why each node isn't eligible for scale in.

**Comment by zdevwu** [comment]
these flags work for me:
```
--vmodule=*=4
--logtostderr
```

**Comment by ryanwalls** [comment]
Thanks @zdevwu.  I had found those as well.  Just forgot to revisit this issue and close it.
