### ISSUE TITLE
cluster-autoscaler: Feature request: publish "latest" or "beta" docker image 

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/contrib#2434]
I don't see any Docker image past 0.4.0 on the registry.  Would be great to try some of the latest additions in a "latest" or some sort of "beta" tagged Docker image.

**Comment by mwielgus** [comment]
We update the image along with major Kubernetes releases.
0.5.1 has been released with 1.6.

As CA is still in beta we don't maintain full compatibility with all K8S releases. Until GA, Cluster-Autoscaler should be used only with the K8S release it is meant for. See README.md for details.
