### ISSUE TITLE
cluster autoscaler: Kubernetes scheduler places Jobs on AWS nodes that are scaling in

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/contrib#2435]
Seems there is a race condition between cluster autoscaler (CA) and the kubernetes job scheduler.  Using CA 0.4.0 and Kubernetes 1.5.2 we are getting Jobs scheduled on nodes that are being terminated by the CA.  This is in AWS.

The sequence of events seems to be:
* CA scales up a node
* Node becomes available for scale in
* CA scales in node
* Kubernetes scheduler schedules a Job on the node that is in the process of terminating.
* Job fails because instance dies

**Comment by ryanwalls** [comment]
May be related to: https://github.com/kubernetes/contrib/issues/2316

cc @mwielgus @andrewsykim

**Comment by andrewsykim** [comment]
@ryanwalls I believe CA 0.4.0 doesn't have any logic for gracefully terminating nodes. In AWS it will just do `TerminateInstance` without drain/cordon. I think @mwielgus is doing some work on this but not sure how far he's gone. Because of this behaviour, the scheduler actually has no idea which nodes are about to terminate and can't make any scheduling decisions for jobs.

**Comment by andrewsykim** [comment]
You could argue that Jobs should make nodes invalid for termination (see https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/utils/drain/drain.go#L114-L127). Not sure what the correct answer for that is

**Comment by mumoshu** [comment]
I'm not sure if I'm following you correctly, but isn't it a cluster deployment tool's responsibility to cordon(or drain) nodes being terminated?
For example, kube-aws sets up a systemd unit to (1) drain all the pods running in the node being terminated (2) and then mark it unschedulable(=cordon) for each node.
FYI, [the relevant setting](https://github.com/kubernetes-incubator/kube-aws/blob/9038a0e/core/controlplane/config/templates/cluster.yaml#L417-L419) and [the systemd unit](https://github.com/kubernetes-incubator/kube-aws/blob/9038a0e4d8c84d2f358af53936aa2ba158388fa3/core/controlplane/config/templates/cloud-config-worker#L241-L270) can be seen in the kube-aws repo.

**Comment by mwielgus** [comment]
In 0.5.x we put an unschedulable taint on a node before we start removing it from the cluster. It should prevent the scheduler from putting new tasks on the node that is currently being deleted.

**Comment by ryanwalls** [comment]
> In 0.5.x we put an unschedulable taint on a node before we start removing it from the cluster.

@mwielgus Does this work with kubernetes 1.5.x or does it only work with 1.6.x?
