### ISSUE TITLE
In the service_loadbalancer contain(gcr.io/google_containers/servicelb:0.4) , haproxy always restart

### ISSUE THREAD

**Issue by wangjianghuan** [kubernetes/contrib#2477]
![image](https://cloud.githubusercontent.com/assets/16407843/23945420/65efd086-09b1-11e7-81ce-968192e34592.png)

Because the process is always restart, so can't see the haproxy statistical data

**Comment by gsaslis** [comment]
had a similar problem. 

Ran the service-loadbalancer `rc.yaml` with the `- --syslog` argument to get a better feel of what's happening in the logs. 

My problem was that I was deploying this in the `kube-system` namespace and haproxy didn't like the `kube-dns` service (sth with having both port 53 udp AND tcp). 

Moved my services and the haproxy rc into a different namespace and problem was solved.

**Comment by gsaslis** [comment]
also, just came across #2261 - something there might be relevant for you.

**Comment by wangjianghuan** [comment]
thanks @gsaslis
