### ISSUE TITLE
Documentation requirement for kubernetes cluster upgrade.

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [kubernetes/contrib#2484]
Hi Team,
Unable to upgrade properly from a current version to 1.5.X and the ansible scripts fails due to various error. Is there any proper documentation link we can follow to perform cluster up gradation using ansible.

Thanks.

**Comment by ingvagabund** [comment]
Nothing I am currently aware of. @derekwaynecarr @eparis @sjenning do you know?

**Comment by sjenning** [comment]
Me neither.

**Comment by UlaganathanNamachivayam** [comment]
Ok. So can we conclude this method is outdated. This became a mess like we provisioned a cluster using this & it cant support the upgrade of it. The solution will be recreating the cluster again with some better options to gain access to the latest features k8s provides.

**Comment by galexrt** [comment]
I used the Ansible deployment to upgrade clusters across multiple versions.
I just re-ran the Ansible deployment to upgrade to the latest version of Kubernetes. Upgrading using local build binaries and with packages (at least under Fedora) works fine for me.

**Comment by smenon78** [comment]
How does it work on CentOS. I am using packagemanager.
