### ISSUE TITLE
Cluster Autoscaler: Documentation request - release notes for 0.5.0

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/contrib#2489]
There is a new version of the cluster autoscaler as of a day or two ago.  But I can't find any release notes or indications of what has changed.  

In my ideal world it would be great if CA could live in it's own repo so that tags, issues, release notes, etc would be more easy to browse.  But if that's not possible, a release log of closed issues, new features, etc in the main CA readme would be a good compromise.  

Thanks!

**Comment by davidopp** [comment]
+1 for separate repo and release notes.

I believe I endorsed putting it in contrib originally, for expediency, but at this point I think it would be better to move it out.

@fgrzadkowski @mwielgus

**Comment by fgrzadkowski** [comment]
+1

**Comment by mwielgus** [comment]
Release notes for 1.6 added.
