### ISSUE TITLE
Cluster Autoscaler: Does not set node to unschedulable when trying to scale down

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/contrib#2491]
Version: CA 0.5.0

Still digging through the code, but here's what I'm seeing in the logs.

```
I0323 14:13:03.952083       1 scale_down.go:292] Scale-down: removing node ip-172-31-45-132.us-west-2.compute.internal, utilization: 0.1, pods to reschedule: default/prometheus-operator-188658439-l50sl,default/parametric-aggregator-2173763796-zggm3,default/part-processor-2731341995-b6qp4
I0323 14:13:03.952628       1 event.go:217] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"81f28c35-0fc1-11e7-a76e-02fda4b511cb", APIVersion:"v1", ResourceVersion:"2556450", FieldPath:""}): type: 'Normal' reason: 'ScaleDown' Scale-down: removing node ip-172-31-45-132.us-west-2.compute.internal, utilization: 0.1, pods to reschedule: default/prometheus-operator-188658439-l50sl,default/parametric-aggregator-2173763796-zggm3,default/part-processor-2731341995-b6qp4
I0323 14:13:04.110792       1 delete.go:53] Successfully added toBeDeletedTaint on node ip-172-31-45-132.us-west-2.compute.internal
I0323 14:13:04.110997       1 event.go:217] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"prometheus-operator-188658439-l50sl", UID:"affad382-0fcf-11e7-a76e-02fda4b511cb", APIVersion:"v1", ResourceVersion:"2553091", FieldPath:""}): type: 'Normal' reason: 'ScaleDown' deleting pod for node scale down
I0323 14:13:04.111046       1 event.go:217] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"parametric-aggregator-2173763796-zggm3", UID:"185ab916-0fd1-11e7-a76e-02fda4b511cb", APIVersion:"v1", ResourceVersion:"2554692", FieldPath:""}): type: 'Normal' reason: 'ScaleDown' deleting pod for node scale down
I0323 14:13:04.111075       1 event.go:217] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"part-processor-2731341995-b6qp4", UID:"185b2c33-0fd1-11e7-a76e-02fda4b511cb", APIVersion:"v1", ResourceVersion:"2554683", FieldPath:""}): type: 'Normal' reason: 'ScaleDown' deleting pod for node scale down
I0323 14:13:04.111414       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-172-31-45-132.us-west-2.compute.internal", UID:"5769d390-0f4f-11e7-a5d1-02fda4ca2c4b", APIVersion:"v1", ResourceVersion:"2556463", FieldPath:""}): type: 'Normal' reason: 'ScaleDown' marked the node as toBeDeleted/unschedulable
E0323 14:13:04.361220       1 scale_down.go:435] Not deleted yet &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:prometheus-operator-188658439-l50sl,GenerateName:prometheus-operator-188658439-,Namespace:default,SelfLink:/api/v1/namespaces/default/pods/prometheus-operator-188658439-l50sl,UID:affad382-0fcf-11e7-a76e-02fda4b511cb,ResourceVersion:2556482,Generation:0,CreationTimestamp:2017-03-23 13:50:34 +0000 UTC,DeletionTimestamp:2017-03-23 14:15:03 +0000 UTC,DeletionGracePeriodSeconds:*120,Labels:map[string]string{operator: prometheus,pod-template-hash: 188658439,},Annotations:map[string]string{kubernetes.io/created-by: {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"prometheus-operator-188658439","uid":"6bae9c80-0f70-11e7-8473-02fda4cfdadf","apiVersion":"extensions","resourceVersion":"2550663"}}
```

Basically... what I'm seeing is that CA identifies the node is eligible for scale down.  It tries to mark the node as unschedulable.  It deletes the pods.  Then it checks if the pods are deleted.  

What is happening is the pods are being rescheduled immediately on the same node.  And if I look in my k8s dashboard, it shows `unschedulable = false` on the node details while CA is waiting for the pods to be deleted in its 5s loop.

![image](https://cloud.githubusercontent.com/assets/842653/24251983/a901282a-0fa1-11e7-9530-84ece41ed5c7.png)

So for some reason, CA is not successfully setting `unschedulable` to `true`.

**Comment by ryanwalls** [comment]
cc @mwielgus @davidopp @fgrzadkowski

**Comment by andrewsykim** [comment]
I'm seeing a similar issue, which leads to deleted pods on that node being rescheduled on the same node, which leads to timeouts on the drain loop.

**Comment by andrewsykim** [comment]
Maybe I just need to set `maxPodEvictionTime` I'll do some debugging and post updates here

**Comment by mwielgus** [comment]
What version of Kubernetes are you on?

**Comment by mwielgus** [comment]
We are using taints for marking the node unschedulable. Taints changed in 1.6 - moved from alpha annotations to beta field in node. If you are running 0.5.0 CA on K8S 1.5.X then there might be some problems.

**Comment by andrewsykim** [comment]
Nodes aren't considered "unscheduable"  if you use taints so this issue can probably be closed. I opened another issue re: compatibility with 1.4. Works fine for me with 1.5 after I applied this fix https://github.com/kubernetes/contrib/pull/2494

**Comment by mwielgus** [comment]
@andrewsykim  CA 0.5.0 is not compatible with 1.4 in two places:
  - it uses taint structs which were not present in 1.4
  - it uses eviction requests for evicting pods under pod disruption budget

I guess it also fails on 1.5 due to lack of taint structs in the api. Using short graceful terminations may hide this issue a bit.

**Comment by ryanwalls** [comment]
@mwielgus I'm on k8s 1.5.x.

**Comment by andrewsykim** [comment]
@mwielgus is there any reason why we can't add both the taint and the annotation for the time being?

**Comment by mwielgus** [comment]
I guess we could do it. Some utility code for handling taints was removed on the way of graduating them from alpha to v1 but we could probably hack it around in 0.5.1

**Comment by davidopp** [comment]
@mwielgus Can you remind me why we thought this wouldn't be a problem for people upgrading from 1.5 to 1.6? Is it that we thought they would upgrade scheduler and CA approximately atomically so this problem, while it would happen, would only be for the short duration while they were out of sync? We should definitely add something to the release notes about this. (Likewise for rescheduler but I think @piosz already said he was going to write a release note for that.)

**Comment by mwielgus** [comment]
I don't recall the discussion fully however it was more like this:

* CA is not a critical component of the system can be turned off for 10 min without much problems. Some new pods may potentially not get a new node but as the administrator is quite close he can probably react quite fast. 
 
* CA, contrary to rescheduler, won't get to infinite loop here. The worst thing that can happen here is that that some pods (backed by RS,D,Job, etc) may be killed twice. First by CA and then couple seconds later, if it is rescheduled to the same machine, by node deletion. Rescheduler, with broken taints, can go crazy and cause mess in the whole cluster running from node to node and deleting stuff while trying to schedule a critical pod. 

I will add release notes to this.
