### ISSUE TITLE
Cluster Autoscaler 0.5.0 beta is not compatible with Kubernetes 1.4

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/contrib#2492]
Seems like cluster autoscaler 0.5.0 relies on the `PodDisruptionBudget` which was introduced in 1.5.   Makes it completely unusable in 1.4 which is unfortunate because some of the new features (drain logic + handling unready nodes) is desirable. Is this a known issue? Should it be backwards compatible? 

```
E0323 17:54:56.270355       1 reflector.go:201] k8s.io/contrib/cluster-autoscaler/utils/kubernetes/listers.go:241: Failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
```

**Comment by andrewsykim** [comment]
@mwielgus @MaciekPytel

**Comment by mwielgus** [comment]
I'm afraid that we cannot make the 0.5.0 CA immediately compatible with 1.4. There are two things that 1.4 does not support:
- Pod disruption budgets and deleting pods via eviction. 
- Taints inside node structs (not as annotation).

In theory it might be possible to make 0.5.0 compatible with 1.4 but I would rather recommend to consider updating master to 1.6 as soon as it becomes available.

**Comment by andrewsykim** [comment]
Thanks!
