### ISSUE TITLE
Autoscaling: accept min-nodes value of 0

### ISSUE THREAD

**Issue by fredrik955** [kubernetes/contrib#2516]
**FEATURE REQUEST**

It would be convenient to accept `min-nodes` to be equal to `0` for autoscaling on node-pools.
If you want to run a resource-intensive batch process now and then this will save a lot of costs.

**Comment by rvrignaud** [comment]
Hello,

I have the exact same need. I use (on GKE) a regular node-pool with pretty small vms (8 CPUs in my case) for the standard workload.
But time to time, I need to be able to schedule kubernetes jobs with very high CPU needs. It would be very ideal if I could create a second node-pool with a default number to 0 instances using very large instances (64 CPUs in my case). This second node-pool should bring up a large node only when pods request a really large amount of CPU.

Ideally this autoscaler would use taints / tolerations to schedule very large node only when pods with tolerations are trying to be scheduled.

**Comment by mwielgus** [comment]
Duplicate of #2425.
