### ISSUE TITLE
[rescheduler] Logs going to /tmp/rescheduler.INFO

### ISSUE THREAD

**Issue by c-knowles** [kubernetes/contrib#2518]
We've recently introduced the rescheduler to [kube-aws](https://github.com/kubernetes-incubator/kube-aws/issues/441).

I've been trying to do the prep for the v1.6 updates, i.e. upgrading to rescheduler v0.3.0. Our setup is a similar to the [salt manifest](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest).

However, when using the same log volume mount as the salt config the logs are not ending up in `/var/log/rescheduler.log` as expected and seem to be going to tmp files like `/tmp/rescheduler.INFO`. I've also tried some of the setup from [glog](https://github.com/golang/glog/blob/master/glog.go#L42), for example setting `logtostderr` to try to get the output to stderr but this seems to fail the flag parsing:

```
unknown flag: --logtostderr
Usage of rescheduler: rescheduler --running-in-cluster=true:
   --housekeeping-interval duration   How often rescheduler takes actions. (default 10s)
   [other flags...]
```

**Comment by mumoshu** [comment]
Probably we need to enable `logtostderr` by default like e.g. kops does [here](https://github.com/kubernetes/kops/blob/cb4641f/cmd/kops/root.go#L68-L69)?
Also to prevent the `unknown flag: --logtostderr` error which seems to be emitted by pflags, we need to teach pflags about the go-native flags like [kops does](https://github.com/kubernetes/kops/blob/cb4641f/cmd/kops/root.go#L89)?

**Comment by mumoshu** [comment]
Hi @ingvagabund @piosz @wojtek-t, thanks for maintaining rescheduler!
Would you mind taking a look into this?

**Comment by piosz** [comment]
Thanks for reporting. Something has changed in Kubernetes deps and this is a side effect. @mumoshu @c-knowles do you want to fix this as described in https://github.com/kubernetes/contrib/issues/2518#issuecomment-292381704 or should I do it?

**Comment by hchenxa** [comment]
@piosz , do we plan to have this issue fixed?

**Comment by piosz** [comment]
@hchenxa sorry about the delay, I haven't had free cycles to fix this so far. I'm happy to accept a contribution.

**Comment by piosz** [comment]
cc @MaciekPytel

**Comment by vboginskey** [comment]
@piosz ☝️ Here's a PR that should resolve this. I didn't enable `logtostderr` by default, as that can be done in the [manifest](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest) and won't break anyone relying on the existing behavior.
