### ISSUE TITLE
[fluentd-gcp-image] constant memory spikes

### ISSUE THREAD

**Issue by Bekt** [kubernetes/contrib#2519]
Using the [fluentd-gcp-ds](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml) (fluentd-gcp:2.0.2), we have been seeing (1) consistently high memory usages when the google-fluentd output is used (500-600mb), and (2) memory spikes when no output plugin is specified.

For (2), the pattern is the same on all nodes with this configuration:

```
containers.input.conf: |-
  <source>
    type tail
    format json
    time_key time
    path /var/log/containers/*.log
    pos_file /var/log/fluentd-containers.log.pos
    time_format %Y-%m-%dT%H:%M:%S.%N%Z
    tag reform.*
    read_from_head true
  </source>

  <filter reform.**>
    type parser
    format /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<log>.*)/
    reserve_data true
    suppress_parse_error_log true
    key_name log
  </filter>

output.conf: |-
  <match **>
    type null
  </match>
```

![](https://cloud.githubusercontent.com/assets/1221480/24634300/c266ef08-1892-11e7-8522-628be82c148b.png)

There are ~30 pods on this node, none of which are heavy load. I can't tell if this is a fluentd-specific issue or not.

/cc @piosz @crassirostris @igorpeshansky

**Comment by Bekt** [comment]
Maybe it has something to do with the livenessProbe.

**Comment by crassirostris** [comment]
@Bekt Thanks for reporting! I don't know right now, I haven't observed this behavior before, I will look into it closely soon.

@repeatedly Could you please help here? Have you seen this before?

**Comment by repeatedly** [comment]
No. There is no report in issues and mailing list.
I want to know the traffic and is fluentd launched with GC releated environment variables.

**Comment by crassirostris** [comment]
@repeatedly Thanks! The only GC related env variable is LD_PRELOAD, set to jemalloc

@Bekt That's the image from my cluster on GCE with fluentd-gcp:2.0.2 and the default k8s ds

![jywpyc0ai5a](https://cloud.githubusercontent.com/assets/1756505/24654207/0a915ae2-1939-11e7-8aff-7b1c446396dc.png)

**Comment by crassirostris** [comment]
@Bekt Exactly with you config:

![4zrzwtgqjp7](https://cloud.githubusercontent.com/assets/1756505/24655124/2d12644a-193d-11e7-8f9b-b3e15e86bd6d.png)

Is the config the only thing that differs from the default installation? Could you please attach to the container and make sure config was mounted correctly?

**Comment by Bekt** [comment]
@crassirostris is this with the DaemonSet I linked above that includes the livenessProbe?

Config is the only difference, with minor adjustments to the DS definition because I'm on k8s 1.5.

I don't think it makes any difference but I'm on AWS, CoreOS with hyperkube.

Lemme test without the livenessProbe and get back.

**Comment by crassirostris** [comment]
@Bekt Yes, exactly like in the repo, only with your config.

I'm running k8s 1.6 on GCE + COS

**Comment by Bekt** [comment]
@crassirostris I've verified the config files are being correctly mounted and also recreated the DS.

When I removed the livenessProbe, there are no more spikes (however memory is still >80Mb unlike what you see). I've glanced over the livenessProbe and didn't see much going on. Could this be tied to jemalloc somehow?

![](https://cloud.githubusercontent.com/assets/1221480/24667156/0af65566-1928-11e7-9375-b36a018f27ec.png)

**Comment by crassirostris** [comment]
@Bekt That's interesting

@Random-Liu Could you please tell if it's possible that [a simple exec liveness probe](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L66) causes resource usage spikes?

**Comment by crassirostris** [comment]
@Bekt On k8s 1.5, with full config, with only tolerations and rollout policy changed

![extbvfbj0p9](https://cloud.githubusercontent.com/assets/1756505/24672412/ea0723ec-1974-11e7-9151-60dc89af0b9c.png)

**Comment by Bekt** [comment]
Thanks for checking that. Anything I can check to test if it's something to do with my k8s environment? (cloud provider, VM, OS etc?) I'm going to try the same thing on a different AWS cluster for now.

**Comment by crassirostris** [comment]
@Bekt Omg, I figured that out! Ofc there are spikes :) Liveness probe has interval of 1 minute, so spikes don't correspond to liveness probe runs BUT liveness probe actually fails if you don't write anything to buffers, so pod gets restarted. Check the number of pod restarts to confirm. FYI, liveness probe is only applicable for our configuration of output plugin, feel free to remove it, if you use anything but google-cloud output.

@Random-Liu Sorry for bothering you, disregard the previous message to you.

**Comment by Bekt** [comment]
Okay, I didn't know `/var/log/fluentd-buffers` was google-fluent specific, that would explain the interval. Why the memory spike though when container is restarting?

Also, didn't you say you tested the exact same config (without google-output) but livenessProbe didn't fail?

**Comment by crassirostris** [comment]
@Bekt Maybe because it starts to process all those logs it didn't process during restart, it causes memory spike and then it takes some take to GC? Just a wild guess, I don't know for sure.

> Also, didn't you say you tested the exact same config (without google-output) but livenessProbe didn't fail?

That's a good point, I didn't check, I'll double-check and will let it run for a longer period of time

**Comment by Bekt** [comment]
It may be because that file was being generated from somewhere else, but that 100% explains the number of restarts which correspond to the spike intervals. I should have checked if that file exists from the very beginning.

**Comment by crassirostris** [comment]
@Bekt Feel free to ask more questions or close this issue :)

**Comment by Bekt** [comment]
Thanks. My end goal is try to nail down why there's so much memory usage (1).

Without any output and config from above, I see around 110mb usage. But as soon as I add [system configs](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-configmap.yaml#L98), the memory usages spikes up to 600-1200Mb (without any output) on a node with ~30 pods with low usage.

I'm just trying to understand if this is normal or not. Any pointers on what else to try would be appreciated.

**Comment by crassirostris** [comment]
@Bekt Wow, this is really strange, as you can see we have a 300MB limit in the default config and it works for all setups on GCE we've seen so far. Try to bisect the problematic plugin and make sure you didn't remove env variable `LD_PRELOAD` with `jemalloc`.

**Comment by Random-Liu** [comment]
@crassirostris Sorry for being late. Tuesday is our meeting day. :p

> @Random-Liu Could you please tell if it's possible that a simple exec liveness probe causes resource usage spikes?

IIUC, the exec process is running in the same cgroup inside the container, so yeah if the exec consumes too much memory, it is possible. However, it doesn't seem to be the case based on the simple exec script you linked to.

And it seems that you have already figured out the issue. :)

**Comment by crassirostris** [comment]
@Random-Liu Thanks for clearing that out though! It's definitely useful knowledge
