### ISSUE TITLE
GLBC Ingress TLS - new secret did not get applied because of redundant "k8s-ssl-1*" cert

### ISSUE THREAD

**Issue by bbzg** [kubernetes/contrib#2521]
Kubernetes 1.5.4 on GKE

Similar/same as https://github.com/kubernetes/contrib/issues/1396

After replacing the secret holding the TLS cert, nothing happened. Found #1396, that pointed me in the right direction - deleting the extra certificate that was not connected to any ingress. After doing that (about 5-10 minutes) the certificate was swapped out on the ingress and used.

**Comment by aledbf** [comment]
@bbzg please open the issue in the new ingress repository https://github.com/kubernetes/ingress

**Comment by bbzg** [comment]
https://github.com/kubernetes/ingress/issues/609
