### ISSUE TITLE
[keepalived-vip] Active/Active HA cluster

### ISSUE THREAD

**Issue by eugene-chow** [kubernetes/contrib#2527]
@aledbf Is an active-active configuration supported? If not, are there plans to support it?

Let's say there're 3 public nodes with 3 VIPs. Each node will be a master for a VIP. With DNS RR, incoming traffic will be load-balanced among the nodes, instead of sending all traffic to the current master.
```
vrrp_instance vip0 {
  state MASTER
  interface ens3
  virtual_router_id 100
  priority 102
  nopreempt
  advert_int 1

  track_interface {
    ens3
  }

  virtual_ipaddress {
    172.16.32.110
  }
}

vrrp_instance vip1 {
  state BACKUP
  interface ens3
  virtual_router_id 101
  priority 101
  nopreempt
  advert_int 1

  track_interface {
    ens3
  }

  virtual_ipaddress {
    172.16.32.111
  }
}

vrrp_instance vip2 {
  state BACKUP
  interface ens3
  virtual_router_id 102
  priority 100
  nopreempt
  advert_int 1

  track_interface {
    ens3
  }

  virtual_ipaddress {
    172.16.32.112
  }
}
```

**Comment by aledbf** [comment]
> Is an active-active configuration supported?

this is not supported right now

> If not, are there plans to support it?

no but we can add this feature.

To enable this we need to change the configmap understand that multiple mappings of the same service with different IPs implies active-active configuration

**Comment by eugene-chow** [comment]
I can look into it.

Do you think it's a good idea to have special config params dedicated to the ingress? I presume that the gold standard for exposing web services would be through an ingress rather than a service. Active/Active keepalived only for the ingress is currently my requirement.

For example, it could watch the API for available ingresses and routes HTTP(S) traffic to it. This way, no manual config would be needed.

**Comment by discostur** [comment]
@eugene-chow @aledbf  is there any update on this?

**Comment by eugene-chow** [comment]
Nope. I was swamped the past few months and still am. Will probably look at it again in 2-3 months.
