### ISSUE TITLE
[Ansible] inconsistent key name in ansible/roles/flannel/templates/flanneld.j2

### ISSUE THREAD

**Issue by gouyang** [kubernetes/contrib#2555]
Some begin with `FLANNEL` and some begin with `FLANNELD`, it would be better to have them all begin with `FLANNEL`, after this change, the flannel code itself might need to make changes accordingly.

```
FLANNEL_ETCD_KEY="/{{ cluster_name }}/network"
FLANNEL_ETCD_PREFIX="/{{ cluster_name }}/network"

{% if etcd_url_scheme is defined and etcd_url_scheme == 'https' %}
FLANNELD_ETCD_CAFILE="{{ flannel_etcd_ca_file }}"
FLANNELD_ETCD_CERTFILE="{{ flannel_etcd_cert_file }}"
FLANNELD_ETCD_KEYFILE="{{ flannel_etcd_key_file }}"
```

**Comment by galexrt** [comment]
@gouyang The reason for this is `FLANNELD_` vars are directly used as configuration options by flanneld and `FLANNEL_` vars are used in the service unit file for configuration over flags (see https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/templates/flanneld.service#L9).

**Comment by gouyang** [comment]
@galexrt The reason does not matter to change the config files to make them looks consistent. To avoid make code changes in flannel, the better solution is to change all prefixs to begin with `FLANNELD` and changes the `flanneld.service` accordingly.

**Comment by galexrt** [comment]
@gouyang I'm working on a PR to make it more consistent. I'll let you know when I pushed it.

**Comment by galexrt** [comment]
@gouyang #2605 should make this more consistent.

**Comment by gouyang** [comment]
The issue is fixed already
