### ISSUE TITLE
[keepalived-vip] build failing

### ISSUE THREAD

**Issue by nickjbyrne** [kubernetes/contrib#2559]
After godep restore -v running make controller fails with 

`rm -f kube-keepalived-vip
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-w' -o kube-keepalived-vip
_/path/kubernetes/contrib/keepalived-vip
./main.go:65: cannot use flags (type *"github.com/spf13/pflag".FlagSet) as type *"k8s.io/kubernetes/vendor/github.com/spf13/pflag".FlagSet in argument to util.DefaultClientConfig`

These are my versions

`godep v79 (linux/amd64/go1.7.5)
go version go1.7.5 linux/amd64`

I'm not familiar with go dependencies and resolution, any quick fix would be appreciated

**Comment by aledbf** [comment]
@nickjbyrne you need to follow the [Getting the Code](https://github.com/kubernetes/contrib#getting-the-code) steps to compile.

**Comment by nickjbyrne** [comment]
Thanks, that resolved it. I'll try and spend some time understanding go deps better
