### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/contrib#2561]
I see the ansible install has Kubernetes 1.4.5 referenced. Is there a plan to move or option this to the current 1.6 release (I think 1.6.2)?

-DB

**Comment by gouyang** [comment]
https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes/defaults/main.yml#L2

Don't know why it's hard coding here. 

But what's the kubernetes version on your system after the script finish? it should be latest package which available by your package manage system(apt/dnf/yum), not 1.4.5.

**Comment by smenon78** [comment]
I was confused about the version variable defined as well. After the script finished, it was 1.5.2 in my case.

**Comment by DarkBlaez** [comment]
I was able to specify the version to use in:

https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes/defaults/main.yml#L2

Basically changed to the native version supported in the OS distro repo. In this case for Centos 7.3 I switched to Kubernetes 1.6.1, and for etcd 3.1.3 and then pulling Flannel .0.7.0

What I did find is there are some script issues when attempting to pull from a github release. There are inconsistencies where where just a minor change is needed to resolve. However, sticking with the OS distro release for Centos 7.3 the above versions work.

Now as it pertains to enabling RBAC within 1.6 there are some issues which I have not started to resolve as of yet and have left RBAC disabled.

I'd like to see these scripts tightened up, tested on fresh installs across OS's that are claimed to be supported. Just doing this myself on Centos 7.3 and Ubunutu 16.04 many of the issues immediately surfaced.

Likewise to enable others to quickly discern where to make some version changes it would have been nice to add a sections in the main git webpage indicating location to change, etc. Furthermore the default behavior should not be to pull latest version (which I think it was eluded to but have not seen that behavior) would be the right course of action since you can only validate an install based on specific versions to negate any deltas with newer versions.

DB

**Comment by githubvick** [comment]
@DarkBlaez @smenon78 Were you able to get it installed with 1.6?  I tried as suggested, but still it installs 1.5.2

kube_version: 1.6.1 , 
kube_download_url_base: https://storage.googleapis.com/kubernetes-release/release/v1.6.1/bin/linux/amd64

Please help. Thx

**Comment by gouyang** [comment]
@githubvick It was 1.6.7 on Fedora 26 system.

```

TASK [contiv : Netplugin | Start Netplugin] ******************************************************************************************************
skipping: [localhost]

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=269  changed=45   unreachable=0    failed=0   

[root@fedora scripts]# rpm -qa | grep kube
kubernetes-master-1.6.7-1.fc26.x86_64
kubernetes-client-1.6.7-1.fc26.x86_64
kubernetes-node-1.6.7-1.fc26.x86_64
```

By default, it will install the latest packages available to your system, which defines by:

```
# grep  source_type inventory/group_vars/all.yml  
source_type: packageManager
```

**Comment by githubvick** [comment]
Okay @gouyang , got it. Im installing on Centos 7.3 and that answers why it had been installing 1.5.2 all the time whatever value was given,.

**Comment by gouyang** [comment]
@githubvick You can install new kubernetes packages manually and change the source_type to `localBuild`.

**Comment by githubvick** [comment]
@gouyang thx a bunch, This is what I wanted and was stuck for almost a week for not reading the documentation properly.
