### ISSUE TITLE
Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by smenon78** [kubernetes/contrib#2564]
OS: CentOS 7

Ansible playbook stops at 
TASK [node : Start kubelet] ***********************************************************************************************************************************************************
fatal: [172.22.16.62]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service kubelet: A dependency job for kubelet.service failed. See 'journalctl -xe' for details.\n"}

Logs says:
Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured

This was working a week ago. Any ideas?

**Comment by gouyang** [comment]
I think you can debug by yourself. First, go to check the kubelet log to see which dependency job is failed and go to check that job logs to see why it failed to be started.

**Comment by smenon78** [comment]
Worked after yum update.
