### ISSUE TITLE
Change to expose hostname rather than localhost

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/contrib#2565]
Surprised a prior issue around this was closed without resolution. Summary of issue

All nodes Ubuntu 16.04

    Inventory containing IP addresses only of each master, node
    A) run ansible, result localhost referenced as indicated in the original issue above. this should be considered a failure of the install. One would expect IPs defined to be used, not localhost

    Inventory containing fully qualified server names
    A) ansible blows chunks when trying to reference the certs with flanneld indicating the actual IPs over fqdn. Might be a cert generation issue

Either way has anyone gone back and checked the current ansible install on fresh VMs. I've already found one issue with the current and Ubuntu 16.04

This issue should be considered still open until resolved as default behavior with FQDN or IP defined in inventory should not default to services on localhost or even referencing localhost/127.0.0.1.

DB

**Comment by gouyang** [comment]
I don't have Ubuntu, so I just test it on my Fedora 25. Both FQDN and IP works well.

Please keep in mind use `kubectl --kubeconfig=/etc/kubernetes/kubectl.kubeconfig ` instead of using `kubectl`, if you just want to use `kubectl`, you can do `cp /etc/kubernetes/kubectl.kubeconfig ~/.kube/config`. Second, if you get any certficates error,  please `rm -fr /etc/kubernetes/*` and deploy the cluster again.

I wish these tips will solve your problems hopefully.

```
# kubectl --kubeconfig=/etc/kubernetes/kubectl.kubeconfig  cluster-info 
Kubernetes master is running at https://dhcp-14-234.nay.redhat.com:443
Elasticsearch is running at https://dhcp-14-234.nay.redhat.com:443/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at https://dhcp-14-234.nay.redhat.com:443/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at https://dhcp-14-234.nay.redhat.com:443/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://dhcp-14-234.nay.redhat.com:443/api/v1/proxy/namespaces/kube-system/services/kube-dns
Grafana is running at https://dhcp-14-234.nay.redhat.com:443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://dhcp-14-234.nay.redhat.com:443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[root@dhcp-14-234 ~]# rm -fr /etc/kubernetes/*
[root@dhcp-14-234 ~]# kubectl --kubeconfig=/etc/kubernetes/kubectl.kubeconfig  cluster-info 
Kubernetes master is running at https://10.66.14.234:443
Elasticsearch is running at https://10.66.14.234:443/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at https://10.66.14.234:443/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at https://10.66.14.234:443/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://10.66.14.234:443/api/v1/proxy/namespaces/kube-system/services/kube-dns
Grafana is running at https://10.66.14.234:443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://10.66.14.234:443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
```

**Comment by DarkBlaez** [comment]
It's actually an issue with the ansible scripts as it pertains to Ubuntu. I can run this on Centos, Fedora, RHEL and not have this issue. On those OS it uses the IP or FQDN I use in the inventory. However, using the same inventory but using the base OS of Ubuntu it does not resolve the IP or FQDN correctly. Instead it always places localhost and 127.0.0.1 in the configs. This is why I opened this issue again since this was prematurely closed do to lack of understanding the full issue. This is evident in the follow up reply which basically attempts to asset that is has something to do with kubectl.kubeconfig, which is very obviously not the case.

If you try the current and legacy ansible scripts on Ubuntu you will see this result repeatedly. If you go to /etc/kubernetes on the master and review along with the nodes you will see the localhost/127.0.0.1 references in many of the config files. This this is an issue with the Ubuntu specific tasks that need to be resolved. Until this is resolve this issue needs to remain open and not prematurely closed like it was back in 2016

DB
