### ISSUE TITLE
Ingress glbc pod: NodePort should have a firewall rule auto-created for health check

### ISSUE THREAD

**Issue by wstrange** [kubernetes/contrib#257]
It looks like the glbc pod gets created with a dynamic NodePort.

Under the GCE HTTP console, the health check for this service shows up as "unhealthy" - because no firewall rule has been created to allow the HTTP load balancer to probe the service. 

Users should not be required to create the firewall rule for this to work (very confusing). Ideally, any firewall rules should be auto-created.

**Comment by bprashanth** [comment]
Thanks for the report. I agree we should create the firewall rule for the default backend service because this service is create as part of kube-up. It shouldn't affect traffic to your other endpoints, though.
