### ISSUE TITLE
[Question] Enabling RBAC in 1.6.0

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/contrib#2572]
In the ansible scripts now that I have set this for v1.6.0 which is provided from the Centos 7.3 repo, how would I enable RBAC. I see that adding --authorization-mode=RBAC to the apiserver ARGS should be all that it takes. But doing so does not result in a functional cluster where other nodes cannot interact with the master. Is there more needed then just adding the above to the apiserver config args?

Thanks
DB

**Comment by DarkBlaez** [comment]
Anyone have any idea on this?

DB

**Comment by liggitt** [comment]
that's all that is required to enable RBAC, but you would need to start the components that speak to the API server (kubelets, kube-proxy, kube-scheduler, kube-controller-manager, etc) with credentials that have the correct RBAC roles.

See https://kubernetes.io/docs/admin/authorization/rbac/#core-component-roles for details about which users/groups are automatically granted permission by default RBAC policy. You can either start those components with credentials for those users/groups, or grant the RBAC roles to different deployment-specific users/groups yourself.
