### ISSUE TITLE
Update fluent-plugin-google-cloud version in fluentd-gcp-image image to the latest (>= v0.6.1)

### ISSUE THREAD

**Issue by qingling128** [kubernetes/contrib#2579]
Two related `fluent-plugin-google-cloud` issues https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/84 and https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/85 were fixed in fluent-plugin-google-cloud [`v0.6.1`](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/releases/tag/v0.6.1).

Yet the `fluent-plugin-google-cloud` [version](https://github.com/kubernetes/contrib/blob/1c6a67cb723ceb7fd997f6c3d6a2fe0d780eaff4/fluentd/fluentd-gcp-image/Gemfile#L6) in `fluentd-gcp-image` is still pinned to `v0.5.*`.

A newer image needs to be built with the latest `fluent-plugin-google-cloud` to have the fix applied.

**Comment by chaintng** [comment]
Hi, i wonder does this issue fix in `fluentd-gcp` which version?
I tried to find changelog, but cannot found. Not sure if it has ?

**Comment by qingling128** [comment]
We are switching to another container image in the coming release. `fluent-plugin-google-cloud` version will be brought to the latest in that image. So it's fine closing this stale PR.
