### ISSUE TITLE
[keepalived-vip] - VIP only ?

### ISSUE THREAD

**Issue by genti-t** [kubernetes/contrib#2580]
Is it possibile to use keepalived-vip, only just as an IP-failover mechanism?
For example, instead of exposing the services on a specific namespace, keeping only the virtual ip in on the keepalived template, like this :

```
{{ $iface := .iface }}{{ $netmask := .netmask }}

global_defs {
  vrrp_version 3
  vrrp_iptables {{ .iptablesChain }}
}

vrrp_instance vips {
  state BACKUP
  interface {{ $iface }}
  virtual_router_id {{ .vrid }}
  priority {{ .priority }}
  nopreempt
  advert_int 1

  track_interface {
    {{ $iface }}
  }

  {{ if .useUnicast }}
  unicast_src_ip {{ .myIP }}
  unicast_peer { {{ range .nodes }}
    {{ . }}{{ end }}
  }
  {{ end }}

  virtual_ipaddress { {{ range .vips }}
    {{ . }}{{ end }}
  }
}
```

I use traefik as loadbalancer and having only virtual ip assigned, is enough for me.

Thanks

**Comment by aledbf** [comment]
@genti-t that is how it works by default. Keepalived is just used to forward traffic directly to the endpoints.

**Comment by genti-t** [comment]
@aledbf that is what I am missing here, (without making a new custom build) how exactly do you set the static IP, without forwarding the traffic to the pods ?
Based on the docs:
1 - the vip-configmap, need a {{ KEEPALIVED_VIRTUAL_IP }}: {{namespace}}/{{service}} pair data, 
2 - args:
```
          - --services-configmap=kube-system/vip-configmap
```

Thank you

**Comment by claytononeill** [comment]
@aledbf I think he's looking to use it without IPVS at all.  What do you think of adding another type of "NONE" in addition to NAT/DR that would just skip ipvs entirely?  If you're running keepalived-vip on all nodes you're running ingress or LB on, then it's not strictly needed.  NAT or DR may be difficult for some people depending on network topology.
