### ISSUE TITLE
Add README to prometheus-to-sd

### ISSUE THREAD

**Issue by bowei** [kubernetes/contrib#2582]
It would be good to add a readme to describe how to use this component.

**Comment by pires** [comment]
@piosz I am interested in contributing to this. Can we chat and can you move it to an external repo?

**Comment by kwiesmueller** [comment]
Hey there,
I would be interested in trying this with our new GCE Cluster but would require a readme or manual of some kind. How is the status on this?

**Comment by piosz** [comment]
@pires @kwiesmueller this was primary designed for our internal GKE purposes but I'm happy to see that you are interested in this. I'll write down something hopefully early next week.

**Comment by piosz** [comment]
@loburm could you please start with a short readme explaining how to use it?

**Comment by piosz** [comment]
The documentation can be found https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/prometheus-to-sd/README.md
