### ISSUE TITLE
Ansible for centosatomic fails on kube-apiserver validation - missing.

### ISSUE THREAD

**Issue by gintautassulskus** [kubernetes/contrib#2584]
Hi,

I am trying to build a local cluster of centosatomic instances, but the Ansible script validation fails with the following error:
```
TASK [master : Enable apiserver] ***********************************************
fatal: [kube-master-1]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service kube-apiserver: host"}
```
Probably the scripts need to be modified due to the following changes: https://wiki.centos.org/SpecialInterestGroup/Atomic/ContainerizedMaster

Any advice/confirmation would be very welcome.

Best,
Gintas

**Comment by gouyang** [comment]
CentosAtomic is recommending to be used as a node only, so the simple solution is only have CentosAtomic in the `[node` in your inventory file.

**Comment by gintautassulskus** [comment]
Thanks, I must have missed this recommendation in the documentation.

**Comment by Bconteh** [comment]
Did you mean in the inventory file you have an entry like this?

[node]
CentosAtomic

**Comment by gouyang** [comment]
@Bconteh The package kubernetes-master for kube-apiserver, kube-controller-manager and kube-scheduler  is not installed on atomic host, so it cannot be a kube-master.

And this repository is deprecated, please use https://github.com/kubernetes-incubator/kubespray.
