### ISSUE TITLE
Ingress Proposal: nginx-alpha controller should be configurable through environment variables

### ISSUE THREAD

**Issue by maklemenz** [kubernetes/contrib#259]
I currently run into some trouble: nginx refuses to start with the following message:

    2015/11/17 11:01:49 Failed to execute nginx -s reload:
    nginx: [emerg] could not build the server_names_hash,
    you should increase server_names_hash_bucket_size: 32

I don't think it makes much sense to just set this option to a higher value, since nginx has a lot of options to tune.

Maybe its better if the controller.go would catch up environment variables or parameters to configure nginx.
So on could add the configuration in the environment variables part of the controller definition:

    NGINX_HTTP_SERVER_NAMES_HASH_BUCKET_SIZE=128
    NGINX_HTTP_GZIP=on

The controller would catch up all the environment variables starting with NGINX_HTTP_, lowercase the keys and use them as config option in the http-config block of the generated nginx.conf.

Sadly I've to admit that I'm still not familiar with golang.

**Comment by bprashanth** [comment]
Thanks for the report. This is a recurring problem that we need to address, see discussion on https://github.com/kubernetes/kubernetes/issues/16891. Ideally we should figure out a way to pass configuration options to nginx without adding config options that don't make sense to other loadbalancers to the Ingress. Till now we've used annotations to solve this problem, but I'm sure we can do better. https://github.com/kubernetes/contrib/pull/260 addresses this in part.

**Comment by maklemenz** [comment]
@bprashanth sounds good.
