### ISSUE TITLE
Kubeadm vs Kubernetes Ansbile. 

### ISSUE THREAD

**Issue by smenon78** [kubernetes/contrib#2591]
More of a question. For a production system, what are the advantages/disadvantages of using kubeadm to deploy kubernetes vs contrib/ansible? 
Currently we are using terraform to create the infrastructure to aws/vsphere and use kubeadm to deploy kubernetes. I have also used contrib/ansible to deploy to CentOs vms and now considering  which option to choose.

**Comment by githubvick** [comment]
@smenon78 Were you able to decide on this? Currently there is kubespray as well that adds to the confusion. Also read somewhere that Kubeadm shouldnt be used in production.
