### ISSUE TITLE
TASK [flannel : Load the flannel config file into etcd] , fails

### ISSUE THREAD

**Issue by dimthe** [kubernetes/contrib#2593]
hello 
i get this error , what do i need to take a look at please?

TASK [flannel : Load the flannel config file into etcd] ******************************************************************************************************************************************************
fatal: [centos-atomic-01 -> None]: FAILED! => {"changed": true, "cmd": "/usr/bin/etcdctl --no-sync --peers=http://centos-atomic-02:2379 set /cluster.local/network/config < /tmp/flannel-conf.json", "delta": "0:00:00.046901", "end": "2017-05-11 14:36:23.550022", "failed": true, "rc": 4, "start": "2017-05-11 14:36:23.503121", "stderr": "Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup centos-atomic-02: no such host\n\nerror #0: dial tcp: lookup centos-atomic-02: no such host", "stderr_lines": ["Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup centos-atomic-02: no such host", "", "error #0: dial tcp: lookup centos-atomic-02: no such host"], "stdout": "", "stdout_lines": []}

**Comment by jberkus** [comment]
It looks to me like the hostnames don't resolve inside the individual nodes.  How are those hostnames being assigned?

**Comment by dimthe** [comment]
i edited /etc/hosts in all nodes and the problem went away
