### ISSUE TITLE
New release of gcr.io/google_containers/kube-keepalived-vip

### ISSUE THREAD

**Issue by xeor** [kubernetes/contrib#2598]
Can we get a build of `gcr.io/google_containers/kube-keepalived-vip`, bumping the container from the current `0.9`?

There are a couple of pull-requests that have been added, example https://github.com/kubernetes/contrib/pull/2344, which might be important for some people.

**Comment by discostur** [comment]
+1

**Comment by claytononeill** [comment]
What can be done to help out with this?  It's been a very long time since a release was done.

**Comment by xeor** [comment]
@bprashanth @mikedanese @bowei 
Can you please share the state of the next release? It's been 10 months and many bugs have been fixed. Or is there another project/solution that are about to replace this `keepalived` solution?
