### ISSUE TITLE
TASK [atomic-k8s-master-post : Install the k8s dashboard]       fails

### ISSUE THREAD

**Issue by dimthe** [kubernetes/contrib#2600]
hello 

any tips why this fails and how can i continue?

TASK [atomic-k8s-master-post : Install the k8s dashboard] ****************************************************************************************************************************************************
fatal: [atomic01]: FAILED! => {"changed": true, "cmd": ["/usr/bin/kubectl", "create", "-f", "https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml"], "delta": "0:00:00.962618", "end": "2017-05-15 11:49:29.138992", "failed": true, "rc": 1, "start": "2017-05-15 11:49:28.176374", "stderr": "Error from server (AlreadyExists): error when creating \"https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml\": serviceaccounts \"kubernetes-dashboard\" already exists\nError from server (BadRequest): error when creating \"https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml\": ClusterRoleBinding in version \"v1beta1\" cannot be handled as a ClusterRoleBinding: no kind \"ClusterRoleBinding\" is registered for version \"rbac.authorization.k8s.io/v1beta1\"\nerror validating \"https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml\": error validating data: found invalid field tolerations for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false", "stderr_lines": ["Error from server (AlreadyExists): error when creating \"https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml\": serviceaccounts \"kubernetes-dashboard\" already exists", "Error from server (BadRequest): error when creating \"https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml\": ClusterRoleBinding in version \"v1beta1\" cannot be handled as a ClusterRoleBinding: no kind \"ClusterRoleBinding\" is registered for version \"rbac.authorization.k8s.io/v1beta1\"", "error validating \"https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml\": error validating data: found invalid field tolerations for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [atomic-k8s-master-post : restart k8sapi] ****************************************************************************************************************************************************
	to retry, use: --limit @/var/home/centos/centos-atomic-k8s/atomic-master-post.retry

PLAY RECAP ***************************************************************************************************************************************************************************************************
atomic01                   : ok=6    changed=2    unreachable=0    failed=1

**Comment by dimthe** [comment]
i see the url path has changed ?

**Comment by rootsami** [comment]
which version are you running ?..
# kubectl --version 

If you are using Kubernetes 1.5 or earlier, you can install the latest stable release by running the following command:

$ kubectl create -f https://git.io/kube-dashboard-no-rbac

**Comment by dimthe** [comment]
hello @rootsami 

kubectl --version
Kubernetes v1.5.2


i see its running
 kubectl get pods --all-namespaces | grep dashboard
kube-system   kubernetes-dashboard-3585514280-1nj2n   1/1       Running   0          6d


how do i access it though ? http://floatingip of this node will not work

**Comment by BubacarrC** [comment]
I'm also having the same issue. The dashboard is running after the `get pods` command but I'll have a timeout in the browser after visiting http://myserver:8080/ui/

Error: 'dial tcp someServer:9090: getsockopt: connection timed out'
Trying to reach: 'http://someServer:9090/'

**Comment by BubacarrC** [comment]
after leaving the dashboard running for a day, revisiting http://myserver:8080/ui/ did gives me back my awesome dashboard.
