### ISSUE TITLE
Ansible  : TASK [master : Create symlinks]  fails

### ISSUE THREAD

**Issue by dimthe** [kubernetes/contrib#2604]
on ubuntu 16.04 the ansible role fails at the point where it has to create symlinks with the error below. Can someone give me some guidance on this ? thanks

TASK [master : Create symlinks] ***********************************************************************************************************************************************************************************************************
failed: [ubuntu1] (item=kube-apiserver) => {"failed": true, "gid": 0, "group": "root", "item": "kube-apiserver", "mode": "0755", "msg": "refusing to convert between file and link for /usr/bin/kube-apiserver", "owner": "root", "path": "/usr/bin/kube-apiserver", "size": 124759446, "state": "file", "uid": 0}
failed: [ubuntu1] (item=kube-controller-manager) => {"failed": true, "gid": 0, "group": "root", "item": "kube-controller-manager", "mode": "0755", "msg": "refusing to convert between file and link for /usr/bin/kube-controller-manager", "owner": "root", "path": "/usr/bin/kube-controller-manager", "size": 101623874, "state": "file", "uid": 0}
failed: [ubuntu1] (item=kube-scheduler) => {"failed": true, "gid": 0, "group": "root", "item": "kube-scheduler", "mode": "0755", "msg": "refusing to convert between file and link for /usr/bin/kube-scheduler", "owner": "root", "path": "/usr/bin/kube-scheduler", "size": 52878477, "state": "file", "uid": 0}
failed: [ubuntu1] (item=kubectl) => {"failed": true, "gid": 0, "group": "root", "item": "kubectl", "mode": "0755", "msg": "refusing to convert between file and link for /usr/bin/kubectl", "owner": "root", "path": "/usr/bin/kubectl", "size": 50351990, "state": "file", "uid": 0}

**Comment by rndmh3ro** [comment]
```refusing to convert between file and link for /usr/bin/kube-apiserver```

Seems that the binary is already installed.

**Comment by dimthe** [comment]
i had to manually symlink the binaries and then the role worked
