### ISSUE TITLE
[Nginx ingress controller] - Error when rule host is too long

### ISSUE THREAD

**Issue by cbarillet** [kubernetes/contrib#2609]
Hello.

I notice that I have this error `E0523 05:05:06.946179       1 command.go:87] failed to execute nginx -s reload: 2017/05/23 05:05:06 [emerg] 240#240: could not build server_names_hash, you should increase server_names_hash_bucket_size: 64` when rule host is too long (in my case : dep-kuber-test-machine5.westeurope.cloudapp.azure.com).

If I try to request my ingress server with `dep-kuber-test-machine5.westeurope.cloudapp.azure.com`, I obtain this error : `75.131.204.163 - [75.131.204.163] - - [23/May/2017:05:06:34 +0000] "POST / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko" 637 0.000 10.1.10.2:80 0 0.000 502
2017/05/23 05:06:34 [error] 202#202: *878 connect() failed (111: Connection refused) while connecting to upstream, client: 75.131.204.163, server: _, request: "POST / HTTP/1.1", upstream: "http://10.1.10.2:80/", host: "13.73.161.177"`.

I confirm my analyze by replacing host 'dep-kuber-test-machine5.westeurope.cloudapp.azure.com' by another shorter 'mm2.cyril-barillet.com'.
So my ingress server responds correctly with this last host.

After some research on Internet, I found this web site which maybe give the solution : http://charles.lescampeurs.org/2008/11/14/fix-nginx-increase-server_names_hash_bucket_size

How can I apply this patch on all my instance of nginx ingress controller ?

Thank you for response.

**Comment by aledbf** [comment]
@cbarillet what version of the ingress controller are you using?

**Comment by aledbf** [comment]
@cbarillet please close this issue and open a new one in the new [Ingress repo](https://github.com/kubernetes/ingress)
