### ISSUE TITLE
[prometheus-to-sd] Flaky tests

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/contrib#2615]
Example: https://travis-ci.org/kubernetes/contrib/builds/237194320

**Comment by mborsz** [comment]
I think this was fixed in https://github.com/kubernetes/contrib/pull/2616

**Comment by crassirostris** [comment]
@mborsz Thanks! FYI, you can add `Fix https://github.com/kubernetes/contrib/issues/2615` to you PR to automatically close the related issue
