### ISSUE TITLE
[keepalived-vip] No real Service Loadbalancing

### ISSUE THREAD

**Issue by discostur** [kubernetes/contrib#2656]
Hi,

i've 3 k8s worker nodes and 3 pods running one on each node. I have defined a service and a keepalived-vip, which routes the traffic to the service:

keepalived-vip -> k8s service -> k8s pods

I did some tests and figured out, that the whole traffic which comes through the keepalived-vip only hits one pod. There is no loadbalancing across each of the 3 pods, only one does all the work.

Is this an expected behaviour?

Thanks
Greets Kilian

**Comment by barclaac** [comment]
This should be expected because you're going through ipvs which is doing a weighting selection by default. I suspect that if you put your vip under some load that you should start to see the distribution occur.

**Comment by barclaac** [comment]
/remove-lifecycle stale

This shouldn't be the case. The keepalived-vip uses ipvs and then when you get to the k8s service you'll be using percentage based routing.

If you cache the connection then you'll keep hitting the same node.
