### ISSUE TITLE
Can it add an example which using DaemonSet to deploy logrotate pod in every nodes of the cluster?

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/contrib#2666]
Can it add an example which using DaemonSet to deploy logrotate pod in every nodes of the cluster ?

So it can give the cluster enhanced ability to collector logs.

**Comment by crassirostris** [comment]
@yan234280533 I don't think it's a great idea overall:

- AFAIK, logrotate (or preferrably, docker config) is set up as part of deployment tool for all popular tools, kubeadm, kopf, etc.
- Logrotate doesn't allow to collect logs, more often it actually interferes in the logs collection process
- Contrib repo is deprecated, we're going to remove it at some point, so let's not add more content there
- DaemonSet is a poor choice for something that runs to completion, I'm not even sure API will allow it

**Comment by crassirostris** [comment]
I'm going to close the issue due to these reasons, feel free to reopen it if you feel that there's something else to consider
