### ISSUE TITLE
simple fanout failed  in ingress

### ISSUE THREAD

**Issue by luotian-git** [kubernetes/contrib#2676]
Use the example in https://kubernetes.io/docs/concepts/services-networking/ingress/#simple-fanout

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginxingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kubenode1.inspur
      http:
        paths:
        - path: /nginx
          backend:
            serviceName: nginx
            servicePort: 80
        - path: /demoshow
          backend:
            serviceName: demoshowsub
            servicePort: 5000

But falied to generate the fanour rules:
[root@localhost kuby-ingress]# kubectl get ing
NAME           HOSTS              ADDRESS   PORTS     AGE
nginxingress   kubenode1.inspur             80        10s
[root@localhost kuby-ingress]#

In the document, it should be:
$ kubectl get ing
NAME      RULE          BACKEND   ADDRESS
test      -
          foo.bar.com
          /foo          s1:80
          /bar          s2:80

How can I generate loadbalance in nginx.conf 's upstream?
I'm using kubenetes 1.5.2  ingress 0.9.0

**Comment by githubvick** [comment]
I'm able to get basic ingress working by env  configured by this code base. I used this https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example
