### ISSUE TITLE
Kube-dns can't be installed (Image not found).

### ISSUE THREAD

**Issue by ngnmhieu** [kubernetes/contrib#2697]
I'm deploying kubernetes using ansible script onto a virtual machine (Centos 7). The kube-dns addon couldn't be installed. After checking the google container registry, I found that the image `gcr.io/google_containers/kube-dnsmasq-x86_64:1.4` doesn't exist - there're only images for amd64. I guess it's because of the new support for Multi-Arch in Ansible scripts. The `ansible_architecture` might have not been correctly assigned to amd64. See  #2642 

Error message: 
```
Failed to pull image "gcr.io/google_containers/kube-dnsmasq-x86_64:1.4": image pull failed for gcr.io/google_containers/kube-dnsmasq-x86_64:1.4, this may be because there are no credentials on this request. details: (Error: Status 405 trying to pull repository google_containers/kube-dnsmasq-x86_64: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices")
```

**Comment by jasonbrooks** [comment]
I'm hitting this as well. @Pensu, can you tell where this is going wrong? Did it work for you?

**Comment by jasonbrooks** [comment]
This seems to work, though I'm only testing on amd64...

```
image: gcr.io/google_containers/kubedns-{{ (ansible_architecture == 'x86_64') | ternary('amd64', ansible_architecture) }}:1.8
```

**Comment by Pensu** [comment]
@jasonbrooks yeah, it worked for me. Not sure why it is taking x86_64 as arch while it is already set as amd64, I have tried both on amd64 and ppc64le, let me have a look and get back.

**Comment by jasonbrooks** [comment]
See also #2730
