### ISSUE TITLE
nginx Ingress controller does not work without authentication

### ISSUE THREAD

**Issue by runseb** [kubernetes/contrib#270]
Hi,

I have a kubernetes setup on my own hardware (not GKE), it seems that the nginx Ingress controller is looking for a token file for a service account ala GKE.

    # docker logs 6653c3332d9b
    2015/11/20 13:45:03 Failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory.

https://github.com/kubernetes/contrib/tree/master/Ingress/controllers/nginx-alpha

Any ideas what's happening

thanks

**Comment by macropin** [comment]
I did not experience this issue. Did you build the container from the latest source?

**Comment by runseb** [comment]
@macropin sorry for the late response. I did not have time to test this again, but it seems to be a problem with the docker deployment. Which causes issues in mounting volumes that carry the secret of the service account https://github.com/kubernetes/kubernetes/pull/19069. So I will close this. thanks
