### ISSUE TITLE
Every user in an OWNERS file should be a kubernetes member or outside collaborator

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/contrib#2713]
/kind bug
/sig contributor-experience

Inspired by https://github.com/kubernetes/kubernetes/issues/50048

**What happened**:
OWNERS files contain users who are not collaborators. These users cannot be assigned to PRs or Issues which is what the bots use OWNERS files for.

**What you expected to happen**:
If you are in this list please become a kubernetes member or an outside collaborator.

The following github users are listed in an at least one OWNERS file in this repo, but are not collaborators or members of the kubernetes GitHub org

@3cky: podex/OWNERS
@BenTheElder: netperf-tester/OWNERS
@MikeSpreitzer: cni-plugins/OWNERS
@alekssaul: scale-demo/OWNERS
@igorpeshansky: fluentd/OWNERS
@paulbakker: git-sync/OWNERS
@raggi: go2docker/OWNERS
@sgallagher: init/OWNERS

If you would like to become a an outside collaborator, please see: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-for-outside-collaborators

If you would like to become a member of the kubernetes GitHub org, please see: https://github.com/kubernetes/community/blob/master/community-membership.md#member

If you would like to know more about OWNERS files, please see: https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md

If you would like to see the horrible bash I wrote for this, please see:
```sh
for u in \
  $(for of in $(find . -name 'OWNERS' | grep -v vendor); do \
      cat $of | grep -v 'approvers\|reviewers:' | awk '{print $2}'; 
    done | sort | uniq \
  ); do \
  if ! grep -iq $u\ ~/w/go/src/k8s.io/kubernetes/members; then \
    echo @$u: $(ag -l -G OWNERS $u .); \
  fi; \ 
done
```

If you would like to hear no more of this nonsense, sorry for the spam, and we'll eventually have a PR out to prune users in OWNERS who aren't members of collaborators.

**Comment by spiffxp** [comment]
@kubernetes/sig-contributor-experience-misc FYI

**Comment by BenTheElder** [comment]
Noting that I have requested membership :upside_down_face: 
Thanks @spiffxp, we should get this fixed.

**Comment by stevekuznetsov** [comment]
@spiffxp we use [this](https://developer.github.com/v3/repos/collaborators/#list) endpoint for the collaborator list in Blunderbuss. I am not certain that's the same as looking at that membership list.

**Comment by spiffxp** [comment]
@stevekuznetsov fair point, my method misses collaborators, but I don't have push access to this repo so I can't view that endpoint

maybe @cjwagner can chime in with blunderbuss logs to see if we've got the right set of logins here?

**Comment by cjwagner** [comment]
Here you go:

Username: @bentheelder (approver), file: 'contrib/netperf-tester/OWNERS'
Username: @alekssaul (approver), file: 'contrib/scale-demo/OWNERS'
Username: @mikespreitzer (approver), file: 'contrib/cni-plugins/OWNERS'
Username: @sgallagher (approver), file: 'contrib/init/OWNERS'
Username: @raggi (approver), file: 'contrib/go2docker/OWNERS'
Username: @bobbyrullo (approver), file: 'contrib/election/vendor/k8s.io/kubernetes/plugin/pkg/client/auth/oidc/OWNERS'
Username: @igorpeshansky (approver), file: 'contrib/fluentd/OWNERS'
Username: @sig-cli-maintainers (approver), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/kubectl/OWNERS'
Username: @paulbakker (approver), file: 'contrib/git-sync/OWNERS'
Username: @3cky (approver), file: 'contrib/podex/OWNERS'
Username: @rkouj (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/volume/OWNERS'
Username: @goltermann (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/credentialprovider/aws/OWNERS'
Username: @lixiaobing10051267 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/credentialprovider/aws/OWNERS'
Username: @igorpeshansky (reviewer), file: 'contrib/fluentd/OWNERS'
Username: @mikespreitzer (reviewer), file: 'contrib/cni-plugins/OWNERS'
Username: @paulbakker (reviewer), file: 'contrib/git-sync/OWNERS'
Username: @sgallagher (reviewer), file: 'contrib/init/OWNERS'
Username: @m1093782566 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/apis/apps/OWNERS'
Username: @249043822 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/apis/componentconfig/OWNERS'
Username: @mfanjie (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/apis/componentconfig/OWNERS'
Username: @goltermann (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/credentialprovider/OWNERS'
Username: @lixiaobing10051267 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/credentialprovider/OWNERS'
Username: @bentheelder (reviewer), file: 'contrib/netperf-tester/OWNERS'
Username: @girishkalele (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/cloudprovider/OWNERS'
Username: @249043822 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/tools/cache/OWNERS'
Username: @ddysher (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/tools/cache/OWNERS'
Username: @feihujiang (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/tools/cache/OWNERS'
Username: @lixiaobing10051267 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/tools/cache/OWNERS'
Username: @sdminonne (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/tools/cache/OWNERS'
Username: @alekssaul (reviewer), file: 'contrib/scale-demo/OWNERS'
Username: @lixiaobing10051267 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/pkg/apis/rbac/OWNERS'
Username: @feihujiang (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/api/install/OWNERS'
Username: @goltermann (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS'
Username: @lixiaobing10051267 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/apis/rbac/OWNERS'
Username: @raggi (reviewer), file: 'contrib/go2docker/OWNERS'
Username: @goltermann (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS'
Username: @juanvallejo (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/rest/OWNERS'
Username: @lixiaobing10051267 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/rest/OWNERS'
Username: @lojies (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/rest/OWNERS'
Username: @m1093782566 (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/pkg/apis/apps/OWNERS'
Username: @sig-cli (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/kubernetes/pkg/kubectl/OWNERS'
Username: @feihujiang (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS'
Username: @feihujiang (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/client-go/pkg/api/install/OWNERS'
Username: @3cky (reviewer), file: 'contrib/podex/OWNERS'
Username: @feihujiang (reviewer), file: 'contrib/rescheduler/vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS'

**Comment by cjwagner** [comment]
In order to support sig aliases in OWNERS files this repo needs an OWNERS_ALIASES file. Once that exists the mungegithub deployment can be updated to use the alias file.

**Comment by BenTheElder** [comment]
I'm now an org member (thanks everyone)!
See also this tool I wrote for finding people we might want to suggest membership to in general:
https://gist.github.com/BenTheElder/de2688f28069e7289cd6ba4997446c88
In the #contribex slack channel @dims produced a list from it:
http://paste.openstack.org/show/617997/

**Comment by raggi** [comment]
I'm happy to take ownership of go2docker if that would be helpful.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
If I had push access to this repo I'd audit again to see where we're at in resolving the discrepancy here

**Comment by raggi** [comment]
I have open PRs against go2docker that have gone unreviewed, and i'm not able to submit them. Please decide if I should have push access or consider removing that code. The certs in there are now extremely stale, and the tool should not be used.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/test-infra/issues/10553 about automating this through the `verify-owners` plugin.
