### ISSUE TITLE
while deploying 1.6.8 K8s , we still get 1.5.2 

### ISSUE THREAD

**Issue by shdowofdeath** [kubernetes/contrib#2718]
while using k8s installed by ansibe 
ansible/roles /kubernetes/defaults/main.yaml 
# Version of Kubernetes binaries
kube_version: 1.5.2 < changed to 1.6.8 
and we still see kube version is Kubernetes v1.5.2
help is needed :)

**Comment by kirecek** [comment]
Had same problem.

I guess you also should update package repositories of your distors. For deployment to fedora machines I've tried to update `kube_rpm_url_base` and `kube_rpm_url_sufix` located in `roles/kubernetes/defaults/main.yml` and it worked for me.

Anyway, try this playbook: https://github.com/kubernetes-incubator/kubespray
