### ISSUE TITLE
Keepalived-vip pod crashed in kubernetes

### ISSUE THREAD

**Issue by ajmulhollan1** [kubernetes/contrib#2729]
Hello,

I've got keepalived-vip setup as a kubernetes deployment, alongside my Nginx ingress controller.

I'm trying to figure out why I had the following error for about 15 minutes.

```
F0822 07:13:14.932629       1 keepalived.go:122] keepalived error: signal: hangup
goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0x1d9fd00, 0xc400000000, 0x52, 0x9b)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1d7f800, 0xc400000003, 0xc420318000, 0x1d19fea, 0xd, 0x7a, 0x0)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1d7f800, 0x3, 0x14ff53a, 0x14, 0xc42071fd10, 0x1, 0x1)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x14ff53a, 0x14, 0xc42071fd10, 0x1, 0x1)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.(*keepalived).Start(0xc4200df540)
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/keepalived.go:122 +0x249
main.main()
    /usr/local/google/home/beeps/goproj/src/k8s.io/contrib/keepalived-vip/main.go:124 +0x402
```

I also couldn't ping the VIP, I just got `Destination Host Unreachable` after a lot of researching I couldn't find an answer, and I'd like to know how to fix this if it happens again?

It just started working again after a while, it was around 15-30 minutes.

Any help appreciated.

**Comment by tbomberg** [comment]
Hello, 

we encounter the very same error stack under the following conditions:

cluster node is rebootet. The pod from the keepalived-vip daemonset tries to start and dies with the
above error. Any further restartt results in the same error.

After deleting the pod, the respawning pod works just fine.

**Comment by barclaac** [comment]
This could well be the same as #2744  PR #2745 may well be a fix that you're looking for.

**Comment by f0** [comment]
i got the same error

**Comment by grailsweb** [comment]
I got the same error also.

> F1127 20:35:13.396730       1 main.go:108] unexpected error: exit status 1
> goroutine 1 [running]:
> k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0xc4202ca000, 0xc4201fe960, 0x4b, 0x9d)
> 	/usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa7
> k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1e2a9c0, 0xc400000003, 0xc420060420, 0x1d9086d, 0x7, 0x6c, 0x0)
> 	/usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x348
> k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1e2a9c0, 0xc400000003, 0x157a081, 0x14, 0xc420585ee8, 0x1, 0x1)
> 	/usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14f
> k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x157a081, 0x14, 0xc420585ee8, 0x1, 0x1)
> 	/usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
> main.main()
> 	/usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/main.go:108 +0x32

**Comment by jansony1** [comment]
same error

**Comment by FNaughton** [comment]
Same error - but the pods never start up.
```
F0115 14:13:35.239271       1 main.go:108] unexpected error: exit status 1
goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0xc4202d6a00, 0xc420280a00, 0x4b, 0x9d)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1e2a9c0, 0xc400000003, 0xc420090420, 0x1d9086d, 0x7, 0x6c, 0x0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1e2a9c0, 0xc400000003, 0x157a081, 0x14, 0xc420589ee8, 0x1, 0x1)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x157a081, 0x14, 0xc420589ee8, 0x1, 0x1)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/main.go:108 +0x32e
```

**Comment by eceglov** [comment]
Same problem. Any update on this?
`goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0xc4202fdb00, 0xc4205062c0, 0x4b, 0xa3)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1e2a9c0, 0xc400000003, 0xc420506210, 0x1d90865, 0x7, 0x6c, 0x0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1e2a9c0, 0xc400000003, 0x157a081, 0x14, 0xc4205a9ee8, 0x1, 0x1)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x157a081, 0x14, 0xc4205a9ee8, 0x1, 0x1)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/main.go:108 +0x32e`

**Comment by stephan2012** [comment]
+1

Any chances that this issue will be fixed?
