### ISSUE TITLE
[keepalived-vip] kube-keepalived-vip sends SIGHUP to keepalived before keepalived has installed signal handler

### ISSUE THREAD

**Issue by barclaac** [kubernetes/contrib#2744]
The kube-keepalived-vip daemon starts the keepalived daemon and almost immediately sends it a SIGHUP. Because the default action on a SIGHUP is to terminate the process the keepalived process will continually exit and be restarted.

The fix here should be ensure that kube-keepalived-vip waits until keepalived is fully operational with an installed SIGHUP handler.

**Comment by alwinmarkcf** [comment]
Hello @all, 

I made it, to run the keepalived after debugging a while. 
I had to run a modprobe on each host manually:

`sudo modprobe ip_vs`
