### ISSUE TITLE
[Keepalived VIP] Help about Logs

### ISSUE THREAD

**Issue by walteraa** [kubernetes/contrib#2746]
How can I read the logs that I have added in the Controller using `glog.Info` statement?

I mean, I have added this logs in the controller, but when I run `kubectl logs pod_name` these logs don't appear.

Is there a way to see this logs?

**Comment by crassirostris** [comment]
Please provide more information (what controller, can you see the logs by sshing to the machine and running docker logs and so on) and steps to reproduce
