### ISSUE TITLE
scripts/deploy-cluster.sh fail

### ISSUE THREAD

**Issue by cyberh0me** [kubernetes/contrib#2749]
following https://kubernetes.io/docs/getting-started-guides/fedora/fedora_ansible_config/
$ pwd
/home/admin/cluster/contrib/ansible
$ ./scripts/deploy-cluster.sh
./scripts/deploy-cluster.sh: line 17: ./init.sh: No such file or directory
./scripts/deploy-cluster.sh: line 20: ansible_playbook: command not found

Edit: it looks like this is related to Fedora since the script works on Ubuntu

**Comment by torvitas** [comment]
just cd to the scripts dir and run the script, works on fedora

$ cd scripts; ./deploy-cluster.sh

**Comment by cyberh0me** [comment]
well meanwhile I have installed the cluster manually but what you say implies the linked documentation is wrong 
"Tell ansible to get to work!
This will finally setup your whole Kubernetes cluster for you.
cd ~/contrib/ansible/
./scripts/deploy-cluster.sh"

**Comment by torvitas** [comment]
That's true.

Am 16.09.2017 13:34 schrieb "Andre Marschalek" <notifications@github.com>:
