### ISSUE TITLE
[Keepalived VIP] Handle IPv6

### ISSUE THREAD

**Issue by Anthony25** [kubernetes/contrib#2776]
Hi,
Keepalived VIP does not seem to handle IPv6 yet. Even if kubernetes internally does not support it, as Keepalived VIP uses the host network, it would be great to provide IPv6 access.

The issue I see right now is, as you use configmap keys to handle the VIPs, you cannot use directly an IPv6 (':' is forbidden). However, you could cheat by replacing ':' by either a dot or a dash. It is not nice, but it would work by keeping the same design as now.

**Comment by schmitch** [comment]
I would want to know that as well...

**Comment by zuberahmed1987** [comment]
Is there any update?

Thanks
/remove-lifecycle rotten
