### ISSUE TITLE
[Ansible] deploy-cluster.sh script points to wrong inventory file

### ISSUE THREAD

**Issue by mwasilew2** [kubernetes/contrib#2777]
ansible/scripts/deploy-cluster.sh is pointing to a file called inventory but it doesn't exist

it should either be pointing to inventory=${INVENTORY:-${INVENTORY_DIR}/localhost.ini}  or the localhost.ini file should be renamed to inventory

happy to submit a PR, can someone let me know which file name is the intended one?

**Comment by DapengJiao** [comment]
Yes, that file doesn't exist.
But according to the [instruction](https://github.com/kubernetes/contrib/tree/master/ansible#setup)
the missing file is asked to be manually created.

**Comment by mwasilew2** [comment]
I was following this guide: https://kubernetes.io/docs/getting-started-guides/fedora/fedora_ansible_config/ which says to edit localhost.ini and since the file is present in the repo I did just that, but then ansible/scripts/deploy-cluster.sh failed cause it's looking for a file called inventory.

so maybe it's a matter of getting rid of localhost.ini and updating docs on the kubernetes website?
