### ISSUE TITLE
system_container.yml fails in Vagrant Deployer for Kubernetes Ansible

### ISSUE THREAD

**Issue by humectant** [kubernetes/contrib#2791]
Following the instructions in Vagrant Deployer for Kubernetes Ansible I get the following:

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/waxberg/k8s-install-contrib-master/ansible/roles/etcd/tasks/system_container.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

- name: Install or Update Etcd system container package
  ^ here

The offending bit appears to oc_atomic_container:

- name: Install or Update Etcd system container package
  oc_atomic_container:
    name: etcd
    image: "{{ etcd_system_image }}"
    state: latest

**Comment by humectant** [comment]
Juts discovered kubespray, so never mind.

**Comment by llarsson** [comment]
I think this should still be open, since either the instructions or the offending file need to be updated. This is an annoying hurdle for people new to the project.

**Comment by Bconteh** [comment]
Facing the same issue here. What's the hack @humectant @llarsson ?

**Comment by haarchri** [comment]
same problem here @humectant @llarsson @Bconteh what is the trick ?
