### ISSUE TITLE
service-loadbalancer goes into an infinite loop of Restart container

### ISSUE THREAD

**Issue by mattma** [kubernetes/contrib#28]
I followed the step described in [README](https://github.com/kubernetes/contrib/tree/master/service-loadbalancer). 

I run into an issue of 

```
core@kube-node-01 ~ $ docker logs c3e318d07f32
I0827 21:43:17.144454       1 service_loadbalancer.go:383] Creating new loadbalancer: {Name:haproxy ReloadCmd:./haproxy_reload Config:/etc/haproxy/haproxy.cfg Template:template.cfg Algorithm:roundrobin}
I0827 21:43:17.144510       1 service_loadbalancer.go:426] All tcp/https services will be ignored.
F0827 21:43:17.145153       1 service_loadbalancer.go:436] Failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

I was using the same command `kubectl create -f ./rc.yaml`. The state of the `pods` show Running, but it goes into an infinite loop of Restart container.

**Comment by brendandburns** [comment]
How did you turn up the cluster?  You are missing the admission controller that adds the service account credentials.

--brendan

**Comment by bprashanth** [comment]
fyi https://groups.google.com/forum/#!topic/google-containers/dDhlTIWS1pI

**Comment by mattma** [comment]
@brendandburns 

I have an [open source project](https://github.com/mattma/coreos-distro) using `fleet` to deploy `service` files to `CoreOS` distro. I am sure that I have missed a lot of *args* in my setup. I am gradually making it better and better. 

I met you in person at `CoreOS Fest`. You and Kelsey influenced me to start this project. Although I have read a few books and online documentation, most of my K8S knowledge is still pre v1.0. Heard about the service account, but never used or implemented one. 

The link provided by @bprashanth helps. Thanks.
