### ISSUE TITLE
etcd installation fails on Fedora Atomic 27

### ISSUE THREAD

**Issue by mbovo** [kubernetes/contrib#2811]
As in title the installation of etcd fails at the enabling etcd service step on `ansible/roles/etcd/tasks/etcd-start.yml `
The error is the following:
```

TASK [etcd : include] *********************************************************************************************
included: /home/manuel/prjs/k8/contrib/ansible/roles/etcd/tasks/etcd-start.yml for 10.10.10.82, 10.10.10.83

TASK [etcd : Enable etcd] *****************************************************************************************
fatal: [10.10.10.83]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service etcd: host"}
fatal: [10.10.10.82]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service etcd: host"}
```

The problem is, starting from fedora atomic 27 kubernetes and etcd are no longer included in the base image (https://www.projectatomic.io/blog/2017/11/migrating-kubernetes-on-fedora-atomic-host-27/)

**A possible workaround:**
` atomic install --system --system-package=no --storage=ostree --name etcd registry.fedoraproject.org/f27/etcd`
on every host where you plan to install etcd

I'll investigate further if there are other issues with this specific os version (in order to submit a pr)

**Comment by jfmatth** [comment]
I'm having the same issue on installing Openshift 3.6+ too
