### ISSUE TITLE
Kubernetes features - deciding which pod runs on which worker

### ISSUE THREAD

**Issue by abhaynayak24** [kubernetes/contrib#2886]
Hi,

I'm exploring kubernetes and I see that when the pod is created, the master automatically assigns it to some worker (I'm guessing randomly) in the cluster.

However, if the worker1 (low CPU specs) gets overloaded it extends the pod to worker2 (high-end CPU specs) eventually. I know that every time the pod will be overloaded and shifted to this high-end worker but still the master always initializes the pod on worker1.

Is there any feature which can allow me to configure the master such that it deploys the pods directly on the high-end worker rather than deploying it on a weak system and then shifting on to a better one?

**Comment by saurav-ionos** [comment]
if you have node pools for high end CPU worker.
you can use nodeSelection in deployment/statefulsets to run the pod in specific pool

**Comment by champsaurav** [comment]
@abhaynayak24 can you elaborate on what you mean by analysing the nodes before deploying pods.
Any particular use case.

You can also look into resource request, affinity and taints which will help decide where the pods should be scheduled.

**Comment by abhaynayak24** [comment]
@champsaurav my thought process is something like this
If I can get the CPU usage/Memory usage of all the workers, then I can choose on which node should the pod be deployed according to the pods load.

the other option that I've is to create a database where in I've the final state of pods (which worker the pod runs at maximum load). From this database I can learn and next time when the pod is initialized I can make the master deploy the pod on the final worker directly
