### ISSUE TITLE
[keepalive-vip] Are there any plans to update the project?

### ISSUE THREAD

**Issue by ms4720** [kubernetes/contrib#2907]
Hi,

Are there any plans to update the project?  It does not work with k8s v1.10.  If there are no plans to update could you mark it as abandoned to make things clearer.

Thanks

**Comment by aledbf** [comment]
@ms4720 after a couple of delayed PRs being merged I returned the development to my personal repo https://github.com/aledbf/kube-keepalived-vip

**Comment by ms4720** [comment]
OK thanks

**Comment by noudAndi** [comment]
Looks like this project is in a bad shape right now. One has to pick up bits and peaces from issues and pull requests, in order to get it up and running :(
