### ISSUE TITLE
Rebuild gcr.io/google-containers/startup-script image needed

### ISSUE THREAD

**Issue by Dm3Ch** [kubernetes/contrib#2914]
There is new commit one year ago for startup-script. That commit makes possible to run multiple different scripts. 
https://github.com/kubernetes/contrib/tree/master/startup-script

But in gcr.io registry latest image was uploaded at 2016 before this commit.
Please push new version to gcr.io

**Comment by Dm3Ch** [comment]
@mikedanese

**Comment by cicerocomp** [comment]
/remove-lifecycle stale


The image remains outdated.

**Comment by cicerocomp** [comment]
/remove-lifecycle stale

The image remains outdated.
