### ISSUE TITLE
Add a new node with the ansible configuration

### ISSUE THREAD

**Issue by sroze** [kubernetes/contrib#293]
I've a running cluster that I setup so easily with the Ansible playbook (thank you very much!), but now the cluster is growing and I need to add new nodes. 

If I just add it in the `[nodes]` list of the inventory file, then it'll reinstall the whole cluster (tried it, on a staging cluster thankfully). Is there a way to just add a new node?

Thanks you very much.

**Comment by zaa** [comment]
I guess you can try to run ansible-playbooks manually and add "--limit" parameter to the command. Something like this:
```
ansible-playbook -i inventory cluster.yml --tags=nodes --limit=NEW_NODE
```

**Comment by eparis** [comment]
Please let us know what does/doesn't work....    I'm a little concerned we do some per node generation of access tokens in the `kubernetes` role and I have no idea how the working with --tags and --limit...

**Comment by eparis** [comment]
But re-running against the entire cluster, should work. It `should` not break, harm, or destroy anything else. If it does, that's a bug.

**Comment by sroze** [comment]
Without the `--limit` option, all the custom Kubernetes & Docker configurations were replaced (ie in the systemd services definition). Maybe the ideal would be to actually updates these configuration in the Ansible playbook.

**Comment by eparis** [comment]
You mean that you updated docker/kube outside of ansible and then re-ran ansible which undid your custom changes? Running this playbook a second time `should` leave the cluster unchanged.

**Comment by sroze** [comment]
Exactly what I did and it revert everything :smiley:

**Comment by eparis** [comment]
Might I suggest doing those docker customization in ansible (but yes, sorry about that, how did --limit work?)

**Comment by sroze** [comment]
Yes I'll probably do the updates on a fork of this repository, that might be better :) 

And actually didn't try the `--limit` because my cluster was already broken and don't really want to do that again for now.

I'm leaving this issue opened in case somebody else can add details if they experiment the same problem.

**Comment by sroze** [comment]
@zaa, @eparis: after trying the `--limit` option, it looks like it's not working because the token is not generated on the master node:
```
TASK [node : Get the node token values] ****************************************
failed: [new-node -> master] => (item=system:kubelet) => {"failed": true, "item": "system:kubelet", "msg": "file not found: /etc/kubernetes/tokens/system:kubelet-new-node.token"}
```

**Comment by carljmosca** [comment]
I agree with the original comment, yes, the Ansible installer is very nice.  I am wondering about the status of adding a node.  

I have not tried yet but I wondered about how it was handled by the OpenShift/Origin Ansible installer.  They respect a "new_nodes" section addition to the inventory file:
[new_nodes]
node3.example.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}"

Then once complete the line is moved to [nodes].
