### ISSUE TITLE
[peer-finder] let on-start/on-change write to stdout/stderr directly

### ISSUE THREAD

**Issue by andrenarchy** [kubernetes/contrib#2944]
Currently peer-finder waits until the script finishes before writing the output to stdout. This makes it hard/impossible to debug when the script hangs. 

Instead it should write to both stdout and stderr directly. There was a PR https://github.com/kubernetes/contrib/pull/2866 to address this but it got closed because the approach apparently had some drawbacks.

**Comment by lenalebt** [comment]
Some time ago a coworker and me implemented something to workaround this. I don't have a good amount of time for testing etc, but I wanna make it possible for others to use our changes, so this is what we are using currently: https://gist.github.com/lenalebt/9b2ed4abe659fe78a8f68b796d24fad7
