### ISSUE TITLE
Leader Elector: endpoints "example" is forbidden.

### ISSUE THREAD

**Issue by naeemkhan12** [kubernetes/contrib#2952]
I tried to run leader elector but failing with `crashLoopbackOff`.
Logs show the output of 
```
kubectl logs -f leader-elector-765897d8db-86cxw
F0918 09:07:53.969034       6 main.go:108] failed to create election: endpoints "example" is forbidden: User "system:serviceaccount:default:default" cannot get endpoints in the namespace "default"
```
Is this something related to RBAC.

kubernetes version: v1.10.0

**Comment by lasshpanzer** [comment]
I also fail with
`root@ubuntu:~/gopath/src/github.com/opensds/nbp/csi/server/deploy/kubernetes# kubectl logs leader-elector-8697bc6447-7xkrg
F1016 14:11:08.905463       8 main.go:108] failed to create election: endpoints "example" is forbidden: User "system:serviceaccount:default:default" cannot get endpoints in the namespace "default"
`

**Comment by yeswanthmenni** [comment]
# NOTE: The service account `default:default` already exists in k8s cluster.
# You can create a new account following like this:
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: <new-account-name>
#  namespace: <namespace>

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
==========================================
This helped me.. In my case am using different namespace to create endpoint / using leader elector there. Modifined according to my requirement. But if we want default namespace .. we can use above YAML.
