### ISSUE TITLE
zookeeper.yaml file Format indentation error

### ISSUE THREAD

**Issue by ilanni2460** [kubernetes/contrib#2978]
zookeeper.yaml file Format indentation error
this is a error Format ：
        - name : ZK_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
XXXXXXXXname: zk-cm
XXXXXXXXkey: jvm.heap
        - name : ZK_TICK_TIME
          valueFrom:
            configMapKeyRef:
XXXXXXXXname: zk-cm
XXXXXXXXkey: tick
        - name : ZK_INIT_LIMIT
          valueFrom:
            configMapKeyRef:
XXXXXXXXname: zk-cm
XXXXXXXXkey: init
        - name : ZK_SYNC_LIMIT
          valueFrom:
            configMapKeyRef:
XXXXXXXXname: zk-cm
XXXXXXXXkey: tick
        - name : ZK_MAX_CLIENT_CNXNS
          valueFrom:
            configMapKeyRef:
XXXXXXXXname: zk-cm
XXXXXXXXkey: client.cnxns
        - name: ZK_SNAP_RETAIN_COUNT
          valueFrom:
            configMapKeyRef:
XXXXXXXXname: zk-cm
XXXXXXXXkey: snap.retain
        - name: ZK_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
XXXXXXXXname: zk-cm
XXXXXXXXkey: purge.interval

theX have 8

**Comment by duanzhanling** [comment]
Can refer to this file：
https://gitee.com/ilanni/kubernetes_contrib/raw/master/statefulsets/zookeeper/zookeeper.yaml
