### ISSUE TITLE
Merge-bot is not doing anything because of lack of API-tokens

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/contrib#300]
Today I observed (for the second time) the following situation.

- mergebot initiates e2e/unit tests before merging the PR
- in the meantime it stucks because of lack of api-tokens:

        E1201 09:10:07.238529       1 github.go:1079] no mergeability information for "docs(getting-started): add AZ_LOCATION information to README" 17926, Skipping
        E1201 09:10:23.883793       1 github.go:63] Ran out of github API tokens. Sleeping for 38.70193685148333 minutes
        E1201 09:10:38.578980       1 github.go:63] Ran out of github API tokens. Sleeping for 38.45701710115 minutes

- once tests are finished, and PR is ready for merged (the internal e2e suites are also green) - it doesn't merge it
- once it is awake again, it starts again from the beginning

 Today - I manually merge https://github.com/kubernetes/kubernetes/pull/17836 exactly because of that (it was ready for merging and merge-bot was waiting for api-tokens).

 However, we can't afford for such situations with huge backlog of PRs.

@eparis @lavalamp

**Comment by wojtek-t** [comment]
@k8s-oncall

**Comment by eparis** [comment]
I asked github for more tokens, they told me no. I'm also being a bit conservative with the token usage (the bot isn't really out when it pauses). I can't imagine a 38 minute pause though, that's nuts.  No way we should have used all the tokens in 12 minutes, they almost always last an hour...

I'll look at little today to make him more resilient...

**Comment by wojtek-t** [comment]
Thanks @eparis 

I've also seen 44 minutes pause few days ago (I don't have logs from then though).
So it would be great if you could look into it!

**Comment by lavalamp** [comment]
Maybe we can track how many tokens are consumed by each PR, and put that in
the status dashboard to find what triggers the corner case?

On Tue, Dec 1, 2015 at 6:42 AM, Wojciech Tyczynski <notifications@github.com

**Comment by eparis** [comment]
Hopefully this is working much better, closing.
