### ISSUE TITLE
Intent to archive kubernetes/contrib

### ISSUE THREAD

**Issue by fejta** [kubernetes/contrib#3007]
https://github.com/kubernetes/contrib/issues/2987 has gone unresolved for more than a quarter. 

During that time there has been only a single commit or so and no issues were fixed.

I intend to archive this repo and make it read only. If this is not the right course of action please create the required SECURITY_CONTACTS file (see above issue).

FYI @krzysied

**Comment by fejta** [comment]
FYI will archive the repo next week unless I hear otherwise

**Comment by bgrant0607** [comment]
See also #762

**Comment by bgrant0607** [comment]
Contributions went to ~zero around October 2017:
https://github.com/kubernetes/contrib/graphs/contributors

Inventory from a couple years ago:
https://github.com/kubernetes/contrib/issues/762#issuecomment-235334556

I just sending email to kubernetes-dev if that hasn't already been done.

**Comment by krzysied** [comment]
@fejta It turned out I need to add fix for my last commit - https://github.com/kubernetes/contrib/pull/3009. I will post update when pr is merged.

**Comment by krzysied** [comment]
#3009 merged.

**Comment by cblecker** [comment]
@fejta Explicit +1 to archiving via our [procedure](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#procedure-for-removal).

**Comment by spiffxp** [comment]
Also a +1 to archiving (file an issue against kubernetes/org and we'll get it done)

**Comment by lavalamp** [comment]
LGTM
G
T
M
