### ISSUE TITLE
Update ansible default subnet "stand out" a little bit  (i.e. non 172)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/contrib#308]
Since docker conatainers are often 172.x.y.z even without flannel running, i wonder if we should consider a unique subnet for the default (200.x.y.z).  I realize this isn't a bug of any sort, so feel free to close if Im the only one that likes flannel to be on a totally different subnet :).  

For me, it just helps with debugging and sanity checking when running e2e tests and so on.

**Comment by eparis** [comment]
I like the idea, but I also feel like we should stay in an RFC 1918 address block instead of stealing some random block that exists on the internet...
