### ISSUE TITLE
Nginx based ingress controller container not starting

### ISSUE THREAD

**Issue by gayanlggd** [kubernetes/contrib#316]
Hi all,

I am trying to deploy the nginx based ingress controller as of in [1]. But I have been unable to do so. Simply the container won't start. It gives the following error.

nginx-ingress-rm4p7       0/1       CrashLoopBackOff   9          18m

and 

18m		1s		106	{kubelet 10.245.1.3}	spec.containers{nginx}			Backoff		Back-off restarting failed docker container

Any help on this is highly appreciated.

[1] https://github.com/kubernetes/contrib/tree/master/Ingress/controllers/nginx-alpha

**Comment by antimack** [comment]
Hello, you can check my public image dimamack/ingressrc:0.1
 Also, make sure that you have Ingress configured properly.

**Comment by gayanlggd** [comment]
Hi,

There was an issue in my ingress yaml. Sorry for creating the noise. Thanks for your reply.

**Comment by zmerlynn** [comment]
Sounds like things are resolved. Closing. cc @bprashanth

**Comment by pleshakov** [comment]
Hello,

The issue indeed exists if you create an Ingress resource before creating services this resource references.

**Comment by gayanlggd** [comment]
Thanks pleshakov.

I had created the replication controller and the server prior to creating the ingress.
