### ISSUE TITLE
[ansible] Automate vbox  networking for mac os / vagrant

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/contrib#322]
Now that iface is parameterizable, im on the hook to make vbox "just work".
cc @eparis .  Will look at this sunday, 
- there is some generic /etc/hosts  functionality that needs to be used, rather than vagrant-hostmanager (which is what i currently use for vbox ips).
- I Will also try to see if there are any smarts that might be going into flannel to make it smarter before i automate it.

**Comment by v1k0d3n** [comment]
did you get this working by chance? i noticed that the virtualbox --provider=openstack is failing too unfortunately. i created a separate issue for it.

**Comment by jayunit100** [comment]
I have a hacked up patch somewhere for vbox but never merged it. It used hostmanager.  I'll have to circle back and look again soon

**Comment by v1k0d3n** [comment]
Thanks for checking! If I can come up to speed with this repo and learn Ansible a little more, I'd be happy to help keep up with it and document some. I think it's a great resource.
