### ISSUE TITLE
Deploying on Fedora 23 Fails with flannel opts

### ISSUE THREAD

**Issue by MrMitch17** [kubernetes/contrib#323]
Hello:

When deploying to Fedora 23 with one master and two nodes I get the following error.

TASK: [flannel | Install Flannel config file] ********************************* 
{'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'flannel_opts' is undefined", 'failed': True}

I tried commenting out line 12 in ansible/roles/flannel/templates/flanneld.j2 to see if that would do anything, but I still get the same error.

I also tried ./setup.sh --tags=flannel and get the following.

ERROR: tag(s) not found in playbook: flannel.  possible values: addons,binary-update,dns,docker,etcd,masters,network-service-config,network-service-install,nodes,pre-ansible,secrets

**Comment by eparis** [comment]
`git revert a9eaecaa064060dd20ffe67e251d2db315d081b9` will get you back something that works.

I'll try to get it fixed in the morning (US east coast time).  I'm so sorry!

**Comment by jayunit100** [comment]
..looking at this now

**Comment by jayunit100** [comment]
`FLANNEL_OPTIONS="{{ flannel_opts | default('') }}` appears to be the **right** way to implement a "if this parameter exists". 

I'm sorry, I hadn't tested this in the negative condition when i issued the original PR to parameterize iface.

I'll issue a PR shortly.
