### ISSUE TITLE
[submit queue] Add a way to override the submit queue for a given Jenkins build

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/contrib#326]
This can be Google-only for now, but for long builds like `kubernetes-e2e-gce-autoscaling`, it would be really useful if the build cop could dump a file in GCS that just overrode the submit queue status and said "look, I know what I'm doing, it's a known issue, keep going".

(Also useful for, say, `gke-ci`, where it might actually be GKE oncall that needs to fix something, and it might be a while.)

**Comment by zmerlynn** [comment]
cc @brendandburns @eparis

**Comment by eparis** [comment]
easiest thing to do from my PoV would be a URL, per test, which may return a date. The submit queue could check that url every time it found a failure and would pretend it was a success until that date.  How/where you want to expose such a thing on your end, I don't care.

I can write the bot part to poll the URLs you tell me....

**Comment by zmerlynn** [comment]
@lavalamp: I presume #1177 fixes this as well?

**Comment by lavalamp** [comment]
Yup, sorry, I was unaware of this issue!
