### ISSUE TITLE
Fails on Fedora23 for apiserver_runtime_config undefined variable

### ISSUE THREAD

**Issue by MrMitch17** [kubernetes/contrib#329]
TASK: [master | write the config file for the api server] ********************\* 

fatal: [x.x.x.x] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'apiserver_runtime_config' is undefined", 'failed': True}
ansible/roles/master/templates/apiserver.j2:26

Appears it's possibly the same issue as #323

**Comment by eparis** [comment]
@jayunit100

**Comment by jayunit100** [comment]
might require a similar patch,  let me see

**Comment by jayunit100** [comment]
@MrMitch17  hi ! 
For now, uncomment `group_vars/all.yml ` that should be enough for it to work. 
Meanwhile ill submit a quick patch!

**Comment by jayunit100** [comment]
Hi @MrMitch17 is this now all working for you?  I tested it on os x but i think ansible behaviour can vary a little esp . since I make a few changes to the files before running.  Just let us know.  thanks again for rapidly reporting these.
