### ISSUE TITLE
Heapster Deployment Broken

### ISSUE THREAD

**Issue by rsmitty** [kubernetes/contrib#337]
The heapster deployment seems to be broken because in the Ansible playbooks because of a recent-ish change to the controller definition to allow for dynamic configurations. I suspect this is usually handled by Salt, but this does not occur during an Ansible based deployment. Here is the relevant commit that seems to introduce this issue:

https://github.com/kubernetes/kubernetes/commit/eee87558e06e07ee62362c61c3d0b49e29de4fdf

Removing the templating from the top of the service file seems to allow for creation as expected.

**Comment by eparis** [comment]
@rsmitty I haven't tested #339, but it should fix your problem. Are you able to test?
