### ISSUE TITLE
AWS Ingress controller

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#346]
What follows are some very rough notes and a high level implementation sketch. Do not use it as an authoritative guide. When in doubt, please ask. 
# Motivation behind the Ingress 

These are what we expect the Ingress to support: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/ingress.md

In short, the ingress is the resource someone would create to handle user traffic into the cluster. This involves name based virutal hosting, url routing, ssl termination etc (at least, in theory it can support ddos protection, firewalling, and a lot more -- think anything a CDN, nginx, haproxy does, but through a mixin of cloud and bare metal). This is convenient because clouds are great for HA and centralized certificate management, but bare metal counterparts have their strenghts too (or just cost cutting, or you already have hand tuned nginx configs, the list goes on...).

I'd suggest a rough sketch of how one might fulfill an Ingress on aws to begin with. 
# Rough implementation plan

The goal is to support an ingress like: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/ingress.md#simple-fanout on aws. IIUC (I'm still learning about AWS) this will involve:
1. SSL termination through ELB
2. Leading to a bank of nodeport haproxies that implement the url/host routing

For 2 you can use the serviceloadbalancer (https://github.com/kubernetes/contrib/tree/master/service-loadbalancer), so lets focus on 1. Here's what you'll need to do:
- Implement support for a very basic Ingress: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/ingress.md#single-service-ingress. When I create this it should trigger the aws controller (running in a pod in the cluster as a cluster addon) to facilitate HTTP routing to the specified backend service.
- Implement SSL support  
  - Create a secret with your certs
  - Add an annotation to the above ingress, this can be achieved via: kubectl annotate ing foo ssl='namespace/secretname' (http://kubernetes.io/v1.1/docs/user-guide/kubectl/kubectl_annotate.html)
    When I do this, the aws controller should create the appropriate cloud cert and open 443 for ssl traffic. 
- Replace your backend service with serviceloadbalancer, so you can use a single cert for all services in your cluster. You can ignore this for now.
# Overview of the gce controller

This is an overview of how the gce controller works, Don't let it limit your design capabilities :) https://github.com/kubernetes/contrib/tree/master/Ingress/controllers/gce#overview

In short: 
- There are a bunch of cloud resources we need to hook up to create a working l7 in gce. Each of thses is abstracted behind a pool interface. Each pool only knows how to handle one thing (eg: health checks, backends, instance groups, the l7 itself etc). 
- The bridge between the cloud provider and Kube are services of type node port. This is required because cloud providers don't allow us to shove random container ips into loadbalancers (yet). 
- The body of the gce controller only operates against the afore mentioned interfaces (https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/gce/interfaces.go#L23), so you should be able to reuse a lot of that code. The job of the controller (https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/gce/controller.go#L223) is to watch the kubeapi for changes to instances, services, ingresses and trigger the appropriate changes in the cloud objects, using one of the pools. I suggest not teaching the controller about cloud provider api directly. 
- If this controller feels too daunting, I suggest starting simple with a control loop like: https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/nginx-alpha/controller.go. At the end of the day all you need is notifications when the Ingress in Kube changes.

**Comment by bprashanth** [comment]
@adamfeuer

**Comment by adamfeuer** [comment]
Thanks @bprashanth - I will look at the code and take a start on this.

**Comment by adamfeuer** [comment]
@bprashanth To ship my project, I wrote an AWS Ingress in python. It handles SSL termination on the ELB, and can configure the ELB to do websockets over SSL. I will begin porting this to golang to fit into Kubernetes next week.

**Comment by bprashanth** [comment]
@adamfeuer just checking in, need help with anything? @justinsb fyi

**Comment by adamfeuer** [comment]
@bprashanth I will need help - but didn't get started on it this week due to other work. Will take a shot at it this week!

**Comment by brendandburns** [comment]
FWIW,
Porting to go isn't required, were happy to point to the python code. (In
some ways it's nicer, to show that is possible to do things in other
languages...)

So your call, if you want to port, go for it (pun intended ;), other wise
feel free to keep the Python

Best
Brendan

**Comment by adamfeuer** [comment]
>
> Porting to go isn't required, were happy to point to the python code. (In
> some ways it's nicer, to show that is possible to do things in other
> languages...)
>
> So your call, if you want to port, go for it (pun intended ;), other wise
> feel free to keep the Python
>

Brendan,

Python would be faster since I have a working program (that works for my
use case) - but it is outside of Kubernetes right now. I am unsure how to
integrate the Ingress with Kubernetes if it's not written in go. Would you
be willing to say more about how that would work, or point me at some code?

cheers
adam

**Comment by bprashanth** [comment]
@adamfeuer you can write a Kubernetes controller in any language that has REST bindings (https://pypi.python.org/pypi/python-kubernetes/0.2, https://github.com/kubernetes/kubernetes/blob/master/docs/devel/client-libraries.md). As far as Kubernetes is concerned, your controller is a black box that it schedules onto a node. As users create Ingresses (json/yaml), your conctroller reacts to notifications over HTTP, and updates the Ingress via HTTP POST. 

Once you have a working controller we can plumb through the right bits to ensure that it is the only Ingress controller that comes up on AWS (i.e so it doesn't end up fighting with, say, the nginx controller).

**Comment by brendandburns** [comment]
Right now, each ingress controller has its own directory here:

https://github.com/kubernetes/contrib/tree/master/Ingress/controllers

But really, it could its own github repo, since each controller is deployed
as it's own Docker image running in the cluster.

Let me know if you have any questions.


Brendan

**Comment by bprashanth** [comment]
ping @adamfeuer, did you give the python REST bindings a shot? Don't mean to be a pest, just checking if we can help or improve an integration point if you're stuck

**Comment by therc** [comment]
I can help with this in Go. I have some experience with the AWS cloud provider. We live on the bleeding edge and can test PRs as they evolve.

**Comment by adamfeuer** [comment]
@bprashanth Sorry, didn't have a chance to do it yet - I had to write a horizontal node scaler for my AWS cluster, since there isn't currently an easy way to do that inside Kubernetes. We did end up writing an HTTPS Ingress script in Python to get the cluster deployed to prod.

I'm going to port the Ingress script to go soon. I want to contribute it to Kubernetes, so would rather have it in go.

**Comment by adamfeuer** [comment]
@bprashanth Here's the [Python HTTPS Ingress script](https://gist.github.com/adamfeuer/03832702033c5da2380a) that I wrote for our own use. It interfaces with another program that orchestrates Kubernetes by using `kubectl`.

**Comment by therc** [comment]
Is it OK to rely on the Kubernets cloudprovider that is currently embedded in the controller manager? It already deals with a lot of the stuff like creating load balancers and security groups (it'll be interesting to make sure the two don't clash for the same resources).

Also, I guess it would be in scope for the controller to also allow additional annotations that trigger calls to Route53 so that a DNS entry can be pointed to the current load balancers?

**Comment by bprashanth** [comment]
@therc Yes for both questions, the gce controller uses the kubernetes gce cloudprovider through Godeps. 

Also fyi, we need to figure out if we're moving type=loadbalancer out of the Service into Ingress or not for 1.3. 

Ingress will also most likely go GA in 1.3, so it would be nice to kick off e2e testing on an AWS controller ASAP, are you still working on this?

**Comment by therc** [comment]
It got put on the backburner as I had to tackle other stuff (logging and ES...), but I want to get back to it this week.

**Comment by bprashanth** [comment]
Cool, no hurry, just checking that we don't have 0 people working on some sort of AWS controller for 1.3. Just let me know if you are completely swamped so we can try and find someone to help.

**Comment by therc** [comment]
When/how will the type=loadbalancer will be made?

**Comment by bprashanth** [comment]
Instead of changing the Type=Loadbalancer on your Service, you'd create an Ingress which looks something like:
Normal tcp:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: no-rules-map
spec:
  backend:
    serviceName: backendSvc
    servicePort: 80
```
and
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: another-no-rules-map
spec:
  tls:
  # SNI on :443
  - hosts:
    - www.foo.com
    - foobar.com
  rules:
    - host: www.foo.com
      backend:
        serviceName: backendSvc
        servicePort: 80
```

We'd need to flesh this out in the main repo, there are pros and cons of doing so. 

The Ingress controller would essentially execute the same code the service controller does today if we decide to do this, and Type=Loadbalancer would be deprecated. `kubectl expose` would just create this behind the scenes.

**Comment by therc** [comment]
Sorry, I dropped a word and it changed the meaning of my question. Minus the `expose` part, I had a broad idea of how this would work. I rather wanted to ask: when/how will the type=loadbalancer DECISION be made? I.e., will it be up to the bgrant gods? :-)

**Comment by bprashanth** [comment]
Oh, there will be some fighting. I will file an issue with the proposal. It will be upto you, me and whoever else cares :) (so probably Clayton and Tim will have some thoughts)

**Comment by abourget** [comment]
what about the new AWS Load Balancers that are Level7 ? any work being done on that ?

**Comment by yissachar** [comment]
My understanding is that ALBs would be a good fit for this if not for the limitation of only 10 URL routes.

**Comment by bprashanth** [comment]
it also doesn't allow host header based routing. I think there's room for both implementations, an ELB pointing to nginx ingress controller that handles l7, and an ingress going straight to ALB. Cloud l7s have their strengths but depth of features isn't one of them, so if you want to do any interesting routing (even http redirect to https) you need something like nginx.

**Comment by radius314** [comment]
Will this deal with internal ELBs as well?

**Comment by craigbox** [comment]
For anyone interested, Sky have built and released an ingress controller for AWS called [Feed](https://github.com/sky-uk/feed).

**Comment by bprashanth** [comment]
Sweet, @justinsb @aledbf might be an opportunity here for a generic_controller backend since it's built on nginx

**Comment by bprashanth** [comment]
https://github.com/sky-uk/feed/issues/111

**Comment by donaldguy** [comment]
ALBs now allow host based routing https://aws.amazon.com/blogs/aws/new-host-based-routing-support-for-aws-application-load-balancers/

**Comment by c-knowles** [comment]
Part of this seems to be covered now in [coreos/alb-ingress-controller](https://github.com/coreos/alb-ingress-controller). There seems to be plans to align ingress controllers a bit more?
