### ISSUE TITLE
[ansible] how-to build certificates for a multi-master setup?

### ISSUE THREAD

**Issue by stephenwithav** [kubernetes/contrib#347]
A public/private key pair is only created for the first master.

How would I create and sign those pairs for the other masters?

As it stands, the Ansible playbook ends with a single failure on each of the masters except for the first.

**Comment by drocsid** [comment]
Should this issue be addressed by the ansible playbook? If so, should you file the issue on that project?

**Comment by stvcooke** [comment]
I'm asking the same questions you asked 2 years ago. Check out this playbook: https://github.com/pawankkamboj/HA-kubernetes-ansible
