### ISSUE TITLE
[ansible] vagrant openstack error: Multiple possible networks found, use a Network ID to be more specific.

### ISSUE THREAD

**Issue by v1k0d3n** [kubernetes/contrib#349]
No matter what I seem to do, this error doesn't go away. I have added the variable in the openstack_config.yml file via NetName and NetID. I have added it directly to the vagrant file, thinking that would resolve the issue...no luck. Are others having this issue as well?

**Comment by jayunit100** [comment]
I haven't ran the openstack provider recently.  Thanks for noting this, I think it sounds like an issue with the plugin, so maybe paste the plugin version and openstack version here....

**Comment by v1k0d3n** [comment]
@jayunit100 thanks looking into it!

you're right, i think the issue is ultimately related to: https://github.com/ggiamarchi/vagrant-openstack-provider/issues/236#issuecomment-120437430

but i'm wondering how you guys worked around it? i saw that both eparis and you created or commented on issues with the vagrant plugin, but it took me a couple of days to trace the issue back to the provider (i commented on the closed ticket, but I'm not sure how much "love" i'm going to get there. how did you guys work around it?

**Comment by jayunit100** [comment]
Thanks for digging.! 
I use my Mac for vagrant, so maybe I lucked out and never hit it?

Sometimes I just hack into the plugins in ~/.vagrant/ and change the source in my local machine to debug stuff.  Usually when I do that, I forget to write down what I did :).

**Comment by v1k0d3n** [comment]
I used my Mac first, and that caused even bigger problems. I'll have to try again, but If it doesn't work, I guess I have to think of something else...I'm not very good with Ruby and I'm just starting to learn Ansible. I'm not sure I'd be much help at this point. Like, at this rate, I'm even having a hard time determining all of the correct dependencies...this seems to be a nested dependency issue.
