### ISSUE TITLE
[Nginx Ingress Loadbalancer] Support daemonset 

### ISSUE THREAD

**Issue by gtcno** [kubernetes/contrib#357]
Should the loadbalancer pods be created by a daemonset instead of a rc thus we can be able to ensure that the pods will always be present on, say edge nodes?

**Comment by bprashanth** [comment]
Should it? can you tell me how you're using it? generally one doesn't want a loadbalancer per node, which is the typical use case for daemon set. Maybe you're using it behind an ELB? or in conjunction with  nodeport services?

**Comment by gtcno** [comment]
We are trying the newly merged Nginx Ingress Loadbalancer and have Dns  resolving to two edge nodes. So in our case we would want Nginx to be present on both nodes serving on the same ports. Following the examples using the pods Hostport, a daemonset seemed to be way to go.

Wouldn't a service and Nodeport be a round robin loadbalancer on top of Nginx?

And yes ELB might be usecase as well.

**Comment by bprashanth** [comment]
What advantage will a daemon set give you over an rc with node labels? Eitherways a daemon set should work too. I'm fine accepting a daemon set config and a modification to the docs that adds that as an example

>Wouldn't a service and Nodeport be a round robin loadbalancer on top of Nginx?

yes

**Comment by gtcno** [comment]
A rc with labels, to my understanding, does not guarantee that pods are
present on all the nodes matching the labels. Daemonset does. So in our
case two Nginx pods are running on the same node and Dns lookup will
randomly resolve to an ip with no nginx running.

fre. 8. jan. 2016, 20.27 skrev Prashanth B <notifications@github.com>:

**Comment by bprashanth** [comment]
If you're using hostPort they will not land on the same node, i.e 2 nodes with labe=foo and an rc with replicas=2, hostport=80, nodelabel=foo is guaranteed to create a replica on each node unless there are insufficient resources on one/both nodes

**Comment by gtcno** [comment]
I see. That will work for us for now. I still believe a daemon set would be more appropriate. Say we increase/decrease  the number of edge nodes. We would have to remember to scale up/down the replication controller as well , while a daemon set would automatically ensure that the edge nodes are running the pod. 

I'll close the issue and hopefully open a pull request later. 
Thanks for the quick answers.

**Comment by glerchundi** [comment]
+1.

Same issue here, will solve as you stated but DaemonSet fits better in our use case too.

In order to do just the strictly required hops:
`ELB -> nginx (on all nodes) -> app pod`

**Comment by glerchundi** [comment]
@bprashanth, @gtcno what about rolling-updates? I tried to update an existing rc and kubernetes failed due to:

`1m          17s        7         lb-v250116.2-xfhe6   Pod                                                         FailedScheduling        {scheduler }                Failed for reason PodFitsHostPorts and possibly others`

I think this reinforces the idea of using DaemonSet in our cases.

**Comment by madhurranjan** [comment]
I've the same issue. I tried running it as a daemonset and get this error :



   1 controller.go:316] Starting nginx loadbalancer controller
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x404994]

goroutine 1 [running]:
main.(*loadBalancerController).Run(0xc8200b1a80)
	/Users/aledbf/go/src/k8s.io/contrib/Ingress/controllers/nginx-third-party/controller.go:324 +0x1f4
main.main()
	/Users/aledbf/go/src/k8s.io/contrib/Ingress/controllers/nginx-third-party/main.go:79 +0x4d7

goroutine 17 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x18b2120)
	/Users/aledbf/go/src/k8s.io/contrib/Ingress/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
	/Users/aledbf/go/src/k8s.io/contrib/Ingress/Godeps/_workspace/src/github.com

**Comment by bprashanth** [comment]
Hmm, nil ptr deref looks unrelated to daemon set. @aledbf fyi, I'll take a look when i get a chance.
