### ISSUE TITLE
[submit queue] Add submit-blocking label

### ISSUE THREAD

**Issue by timstclair** [kubernetes/contrib#359]
**Proposal:**
Add an `unmerged-dependencies` label, which prevents LGTM'd and otherwise good-to-go PRs from being automatically merged. Alternatively, a more general `no-merge` label could accomplish the same thing.

**Motivation:**
There are sometimes PRs which have a dependency on another (unmerged) PR. If the dependency is soft (code runs & tests pass), then there is a risk that if the *depending* PR is LGTM'd before the *dependent* PR, it can be submitted first.

Here is an example of this happening: https://github.com/kubernetes/kubernetes/pull/17548

/cc @erictune

**Comment by eparis** [comment]
we have `ok-to-merge` and `needs-ok-to-merge`    maybe `not-ok-to-merge`?  I'm not opposed to `unmerged-dependencies` just throwing out a suggestion.

**Comment by timstclair** [comment]
I'm ok with `not-ok-to-merge`, but I do worry a little that it's too similar to `needs-ok-to-merge`.

**Comment by timothysc** [comment]
+1 to ```unmerged-dependencies```

**Comment by eparis** [comment]
@thockin suggest just not adding LGTM label...    Put it in a comment.  And the PR author could add it when the dep lands?

**Comment by thockin** [comment]
We're building a DSL in labels.  It's getting silly.  Do we really need
this?  I was only half kidding on ORC when I suggested building a command
center into merge bot.

It might be interesting to have the bot use comments for this.

```
thockin: @k8s-merge-bot depends on #12345
k8s-merge-bot: @thockin: ACK.  This PR will not be merged until #12345 is
in.
thockin: @k8s-merge-bot clear depends on #12345
k8s-merge-bot: @thockin: ACK.  This PR no longer depends on #12345.
```

**Comment by timstclair** [comment]
@eparis - my concern with that system is that reviewers are often juggling reviews of many different PRs and it's easy to forget that a particular PR should not be LGTM'd yet. If a PR is accidentally LGTM'd while the author is offline it can be merged before the author has time to remove the label (this is less of a problem these days with our multi-day queue, but hopefully that will be fixed).

@thockin - I agree that would be nice, but I haven't looked at the bot code enough to know how much effort that would be.

**Comment by timstclair** [comment]
Fixed by https://github.com/kubernetes/contrib/pull/534
