### ISSUE TITLE
GCE Loadbalancer controller doesn't report events anymore

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#367]
From logs:
```
E0111 00:56:27.615692       1 event.go:252] Unsupported event type: 'ADD'
...
E0111 00:57:39.362128       1 event.go:252] Unsupported event type: 'CREATE'
```

Maybe https://github.com/kubernetes/contrib/pull/358

**Comment by brendandburns** [comment]
@bprashanth it's possible, please check:

https://github.com/brendandburns/contrib/commit/cdccdfdafe0a537530433b7467a6de7ac9497512
