### ISSUE TITLE
git-sync should have an option to exit instead of looping forever

### ISSUE THREAD

**Issue by wstrange** [kubernetes/contrib#370]
Currently git-sync loops forever (with a 0 second delay) to sync changes from a git repo.

There are cases where you want  to sync once and then exit (Jobs, for example). 

The delay for syncing should probably be set to something more friendly (30 seconds?)

**Comment by rwehner** [comment]
In progress PR https://github.com/kubernetes/contrib/pull/493 appears to contain the "sync once" option you are requesting. The existing `wait` (or `GIT_SYNC_WAIT` env var) appears to give you the ability to override the default sync interval. You might subscribe to that PR to track progress.

**Comment by aledbf** [comment]
@wstrange please check the code in master. PR#493 is merged and the option to exit after the first fetch is implemented
