### ISSUE TITLE
change exec-healthz container so that it's based on alpine

### ISSUE THREAD

**Issue by 0rc** [kubernetes/contrib#380]
On my current project we are heavily using kubernetes and I’ve found healthz container very useful.
However, it can become even more useful if we can add command-line tools to perform more sophisticated health checks, like curl.
That is why I think changing base image to alpine may be helpful for other people as well. Container size will grow from about 7 to 11 Mb, but it will become extendable. People can just build their own containers based on original one and add any command-line tools they need for their health checks without changing original container.

**Comment by bprashanth** [comment]
> However, it can become even more useful if we can add command-line tools to perform more sophisticated health checks, like curl.

So you want a decent package manager, makes sense. Can you propose an image of the same size that doesn't suffer from the same DNS search problems alpine has? i.e a simple `nslookup kubernetes.default` should work in the pod.

**Comment by 0rc** [comment]
Unfortunately I think this is can only be fixed by using FQDN in alpine
http://gliderlabs.viewdocs.io/docker-alpine/caveats/

**Comment by 0rc** [comment]
closed
