### ISSUE TITLE
service loadbalancer - unsupported protocol scheme

### ISSUE THREAD

**Issue by rnagarajan12** [kubernetes/contrib#388]
I am running kube cluster with three servers acting as master and node.
Overlay networking is flannel.

I0119 15:53:00.203897       1 service_loadbalancer.go:550] Creating new loadbalancer: {Name:haproxy ReloadCmd:./haproxy_reload Config:/etc/haproxy/haproxy.cfg Template:template.cfg Algorithm: startSyslog:false lbDefAlgorithm:roundrobin}
E0119 15:53:00.204072       1 service_loadbalancer.go:241] Get : unsupported protocol scheme ""
I0119 15:53:00.204514       1 loadbalancer_log.go:38] Starting syslog server for haproxy using /var/run/haproxy.log.socket as socket

This is the error, when I run rc.yaml,

cat rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer
  labels:
    app: service-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: service-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
      - image: gcr.io/google_containers/servicelb:0.2
        imagePullPolicy: Always
        name: haproxy
        ports:
        # All http services
        - containerPort: 8080
          hostPort: 80
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 1936
          protocol: TCP
        resources: {}
        args:
        - --tcp-services=hellotom-svc:8080
        - --syslog

$ kubectl get svc
NAME           CLUSTER_IP       EXTERNAL_IP   PORT(S)    SELECTOR        AGE
hellotom-svc   10.254.230.169   <none>        8080/TCP   app=hello-tom   2h

**Comment by rnagarajan12** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4", GitCommit:"a5949fea3a91d6a50f40a5684e05879080a4c61d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4", GitCommit:"a5949fea3a91d6a50f40a5684e05879080a4c61d", GitTreeState:"clean"}

Cluster running on ubuntu 14.04.3

**Comment by remoe** [comment]
@rnagarajan12 can you please try service-loadbalancer from master to get the correct log line ?

**Comment by rnagarajan12** [comment]
@remoe in the cluster node is also master, 
I found something else in the logs,

api-server.log
logs.go:40] http: TLS handshake error from :42853: remote error: bad certificate

kube-proxy.log
24726 proxysocket.go:165] I/O error: write tcp 172.17.41.9:43514: broken pipe

$ kubectl  exec -it lb-tom-7v3cu -- ip ad li |grep eth0
507: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue state UP 
    inet 172.17.41.9/24 scope global eth0

looks like, api server not accepting connection load-balancer pod.

I am running load balancer with these args, still certificate errors???
args:
 26         - --tcp-services=hellotom-svc:8080
 27         - --syslog
 28         - --server=https://api-server-url:6443
 29         - --insecure-skip-tls-verify

**Comment by remoe** [comment]
@rnagarajan12 your logs are not from https://github.com/kubernetes/contrib master, so you don't use the original code from here: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer

And the other errors are configuration issues of your kube setup.

**Comment by rnagarajan12** [comment]
@remoe 
Hey , 
Right now I am using gcr.io/google_containers/servicelb:0.2 image!
How can I run service-loadbalancer from master branch? 

Thanks

**Comment by remoe** [comment]
ok, you don't need to build from master, your issue is not a service-loadbalancer issue. 

You can try to ask here: http://stackoverflow.com/questions/tagged/kubernetes

**Comment by rnagarajan12** [comment]
I think it is, service-loadbalancer can not connect to api-server. My other services can connect to api-server, for ex, controller, scheduler, proxy but not this loadbalancer. 

So far I explored kubernetes myself, I will try to figure it out.
Thanks for your help

**Comment by rnagarajan12** [comment]
I found the problem and fixed.
KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT  env variables needed to be changed, the default one had pointing to cluster IP, but the cert is only valid for FQDN.

**Comment by remoe** [comment]
great! now you can close the issue?

**Comment by rnagarajan12** [comment]
Thanks , I am having other issues, I will debug further.
