### ISSUE TITLE
[mungegithub] submit queue e2e status page should link to logs on GCS

### ISSUE THREAD

**Issue by ixdy** [kubernetes/contrib#396]
Recommendation from @justinsb: the http://submit-queue.k8s.io/ e2e status page should link to the logs on storage.cloud.google.com, ideally the most build # corresponding to the status shown.

For example, for `kubernetes-e2e-gce` build 10000, we'd link to https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/10000/.

Whenever we get around to a better external UI, we can link to that instead.

cc @kubernetes/goog-testing @eparis @lavalamp @brendandburns

**Comment by ihmccreery** [comment]
@spxtr as visibility point person?

**Comment by spxtr** [comment]
I probably won't get around to this for a while. If anyone else wants to take it, please do.

**Comment by eparis** [comment]
anyone way to review #404 so I can turn it live?

**Comment by eparis** [comment]
live and in production.
