### ISSUE TITLE
[submit queue] should process older PRs sooner

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/contrib#407]
Currently, submit queue sorts the PRs based on PR number. This could be very misleading because many PRs stay open for a long time and become ready to merge only recently. We should have a better metric to gauge how long the PR has stayed in the queue and respect the order when processing. 

One idea is to sort the PRs by the lgtm label timestamps, so that the PR that has been ready the longest time gets to be picked up first.

**Comment by eparis** [comment]
while #408 does not address this request, it creates a framework to do so if we so choose.

**Comment by yujuhong** [comment]
> while #408 does not address this request, it creates a framework to do so if we so choose.

#408 seems like a great start. Thanks!
