### ISSUE TITLE
kube-up fails to upload release tars to gce if prefix changes

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/contrib#411]
Currently kube-up determines if it should stage the tars based on if the sha1 file exists.  However, as the staging is based on KUBE_GCE_INSTANCE_PREFIX, if one changes the prefix fetching the tars fails as they aren't where they are expected to be.

**Comment by sjpotter** [comment]
I dont think this matter anymore, as it uploads all the time now.

**Comment by roberthbailey** [comment]
Great, I'll close it then.
