### ISSUE TITLE
Possible for submit queue to merge a sha other than what was tested

### ISSUE THREAD

**Issue by pmorie** [kubernetes/contrib#422]
There's a race condition in the submit queue where the queue may merge a sha other than what was tested:
For example: kubernetes/kubernetes#19716 : this PR was 5/5 checks green, then needed rebase after the merge bot had called for a final test.  I rebased, repushed, and re-added the LGTM label, and the PR merged even though 1/5 checks was green (presumably CLA check) in github for that sha.

@eparis

**Comment by pmorie** [comment]
@eparis does #450 fix this?

**Comment by ixdy** [comment]
Possibly related race condition: I created kubernetes/kubernetes/pull/21519 with `e2e-not-required`. It was LGTM'd, and then I realized I needed to change something else. I force-pushed this change, but instead of removing the LGTM (since the sha1 changed) the submit queue merged the new commit.

**Comment by euank** [comment]
Still not fixed, I slipped something through without a lgtm label: https://github.com/kubernetes/kubernetes/pull/34958#issuecomment-254312053

**Comment by ixdy** [comment]
this happened again in https://github.com/kubernetes/kubernetes/pull/36407.

**Comment by apelisse** [comment]
This one is probably even worse. It has `do-not-merge` and doesn't have `lgtm`...

**Comment by ixdy** [comment]
Well, it's basically the same issue, I think. It had `lgtm` when SQ started testing it, and then I removed `lgtm` and added `do-not-merge`, but the SQ never looked again, apparently.
