### ISSUE TITLE
kube-keepalived-vip:0.1 not available at gcr.io

### ISSUE THREAD

**Issue by wienczny** [kubernetes/contrib#426]
The docker image referenced from project keepalived-vip is not available at gcr.io.

> \# docker pull gcr.io/google_containers/kube-keepalived-vip:0.1
> Pulling repository gcr.io/google_containers/kube-keepalived-vip
> Tag 0.1 not found in repository gcr.io/google_containers/kube-keepalived-vip`

**Comment by aledbf** [comment]
ping @bprashanth

**Comment by bprashanth** [comment]
Sorry, I just pushed out `gcr.io/google_containers/kube-keepalived-vip:0.2` which uses alpine (https://github.com/kubernetes/contrib/pull/435). You'll need to modify the rc config thus: https://github.com/kubernetes/contrib/pull/437

**Comment by wienczny** [comment]
Thx
