### ISSUE TITLE
keepalived-vip using alpine package 

### ISSUE THREAD

**Issue by wienczny** [kubernetes/contrib#427]
The keepalived-vip is building keepalived from source. Since some days keepalived is available in apline testing (https://pkgs.alpinelinux.org/package/testing/x86_64/keepalived). I suppose it has not been availablel when keealived-vip was built. Are there any reasons not to use the repository package? If there are please document them ;)

**Comment by aledbf** [comment]
> I suppose it has not been availablel when keealived-vip was built

Exactly.
