### ISSUE TITLE
Ansible: Flannel Install Fails on Ubuntu

### ISSUE THREAD

**Issue by rsmitty** [kubernetes/contrib#428]
While attempting to deploy a k8s cluster on Ubuntu hosts, I've encountered an issue where flannel does not install. This is because of the [client.yml](https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/client.yml) file and the way that the installation is handled. It wrongly assumes that flannel is in the package repository, regardless of OS (as long as it's not AtomicOS). This will need to be fixed to install from github releases for Ubuntu and I presume Debian. I'll take this on when I have a free moment, if someone will go ahead and assign it to me.

**Comment by rsmitty** [comment]
Digging in further, it seems that none of the flannel playbooks support anything but RHEL/CentOS. Looks like this may be a bigger issue than I initially thought. Working around the initial issue lead to a failure in the next step when trying to put the sysconfig file down.

**Comment by eparis** [comment]
At one point in time i made the playbook run on debian. I it's very hazy...  I remember being frustrated because of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792704

**Comment by danehans** [comment]
@eparis @rsmitty I am working on adding CoreOS support to the Ansible playbooks and I am sseing issues with flanneld starting due to incorrect ENV key names in flanneld.j2. Please refer to [1] for the list of flannel environment variable names that are supported. For example,  flanneld.j2 uses FLANNEL_ETCD_KEY when it should be FLANNELD_ETCD_PREFIX.

[1] https://github.com/coreos/flannel#environment-variables

**Comment by eparis** [comment]
ok, we might need to 'disto-ize' that. RHEL/Fedora use those as command line args, not as ENV vars. They are launching flannel with something like:
```
/usr/bin/flanneld -etcd-endpoints=${FLANNEL_ETCD} -etcd-prefix=${FLANNEL_ETCD_KEY} $FLANNEL_OPTIONS
```
I don't know how easy/possible it would be to get the distro to switch, so we might have to put that config file only on RHEL/Fedora and use a new config file with the ENV vars on Debian...

**Comment by danehans** [comment]
@eparis I was wondering if that was the case, so I distro-ized the flanneld.j2. [2] is the PR that I'm ready to submit for adding CoreOS support... just waiting on the Corp CLA stuff to complete. It would be much appreciated if you could check out [2] and let me know if any changes are required for a LGTM.

[2] https://github.com/danehans/contrib/commit/7a85d7aecdb4e343879c0213e66ba3b314895251
