### ISSUE TITLE
Ansible: Etcd Gets Symlinked to Wrong Location

### ISSUE THREAD

**Issue by rsmitty** [kubernetes/contrib#429]
On Ubuntu hosts, etcd gets installed via a github release; however, the [symlink portion](https://github.com/kubernetes/contrib/blob/master/ansible/roles/etcd/tasks/github-release.yml#L27) of the play links to /usr/local/bin. This seems to be incorrect later in the run where flannel tries to look for etcdctl to exist at /usr/bin, as seen [here](https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/config.yml#L16). I suspect that the github release play simply needs to be updated to link to /usr/bin instead (this seems to fix it in my environment). I'll take this on later this week if someone can assign to me.

**Comment by eparis** [comment]
Assigned to myself as I can't assign it to you for some reason. But rest assured, I won't be fixing it, I'll be anxiously awaiting to commit your fix!
