### ISSUE TITLE
Memory Leak on nginx-third-party

### ISSUE THREAD

**Issue by ekozan** [kubernetes/contrib#430]
Hello,

I think they has an memory leak or no GC on the lua part of nginx-third-party
In stand-by the memory constantly grow of 6 mb per hour

Config standard less than 100 access / hours 

https://snapshot.raintank.io/dashboard/snapshot/iuAQVc2zfj2ikLFeXZQA9j8vlobcQ8EJ
the memory drop is a restart of the po

**Comment by aledbf** [comment]
@ekozan how many Ingress rules do you have?

**Comment by ekozan** [comment]
20 only for test purpose

**Comment by ekozan** [comment]
@aledbf any idee ?

**Comment by aledbf** [comment]
@ekozan I'm sorry for the delay. On Saturday I will take a look to this

**Comment by aledbf** [comment]
@ekozan can you update the image to `aledbf/nginx-third-party:0.2`?
