### ISSUE TITLE
Ansible: Etcd not available to dict "groups"

### ISSUE THREAD

**Issue by claytantor** [kubernetes/contrib#439]
https://github.com/kubernetes/contrib/blob/4d3c7d4e9599812872abc1ddd5536e290792efe7/ansible/roles/master/templates/apiserver.j2

When attempting to stand up a master node using:

```
INVENTORY=hosts ./setup.sh --tags=masters
```

The ansible setup for a master node fails when trying to write the config file to the api server:

```
TASK: [master | write the config file for the api server] *********************
fatal: [10.81.77.104] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'etcd'", 'failed': True}
fatal: [10.81.77.104] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'etcd'", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

From the task file:

```
- name: write the config file for the api server
  template: src=apiserver.j2 dest={{ kube_config_dir }}/apiserver
  notify:
    - restart apiserver
```

The call in question seems to be that the groups dict does not have an `etcd` entry:

```
# Location of the etcd cluster
KUBE_ETCD_SERVERS="--etcd-servers={% for node in groups['etcd'] %}http://{{ node }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
```

If this is an error on my part please excuse, and an explanation would be appreciated.

**Comment by eparis** [comment]
Your inventory file must define
[masters]
[etcd]
[nodes]

Looks like you didn't define etcd in your hosts file.

**Comment by claytantor** [comment]
THANKS!
