### ISSUE TITLE
[mungegithub] rebuild-request munger misses some requests

### ISSUE THREAD

**Issue by eparis** [kubernetes/contrib#452]
https://github.com/kubernetes/kubernetes/pull/20464#issuecomment-179030471

**Comment by foxish** [comment]
@spxtr, this functionality is now in Prow. Correct?

**Comment by spxtr** [comment]
I think so. What did this munger do?

**Comment by foxish** [comment]
Looks like you removed the munger last year (https://github.com/kubernetes/contrib/pull/1781). Closing related issues. :)
