### ISSUE TITLE
keepalived password truncated

### ISSUE THREAD

**Issue by wienczny** [kubernetes/contrib#460]
The authentication password added to keepalived.conf is too long (strange thing to say).  But keepalived can't handle it:

```
kube-keepalived-vip: Opening file '/etc/keepalived/keepalived.conf'.
kube-keepalived-vip: Truncating auth_pass to 8 characters
kube-keepalived-vip: Configuration is using : 73471 Bytes
```

This is not fatal.

**Comment by wienczny** [comment]
#465

**Comment by bprashanth** [comment]
hmm, 8 chars is really small. @wienczny looking at the pr, thanks.

**Comment by wienczny** [comment]
I would agree with you about the length but it seems to be a vrrp limitation (https://tools.ietf.org/html/rfc2338 5.3.10). In the latest vrrp version the authentication has been removed (https://tools.ietf.org/html/rfc3768 13.) ;(

**Comment by aledbf** [comment]
@wienczny please check the latest version of the image. It uses keepalived 1.2.20. The authentication was removed

**Comment by wienczny** [comment]
lgtm thx
