### ISSUE TITLE
[mungegithub] ignore CI for gh-pages branch

### ISSUE THREAD

**Issue by ixdy** [kubernetes/contrib#473]
PRs to `gh-pages` won't be tested on Travis or Jenkins, so the munger shouldn't try to make tests run. (See e.g. kubernetes/kubernetes/pull/20344)

**Comment by eparis** [comment]
https://github.com/kubernetes/contrib/pull/432

Fixed this for ping-ci.
But it is still broken for ok-to-test

**Comment by bgrant0607** [comment]
We're not using gh-pages any longer.
