### ISSUE TITLE
Grafana with NodePort Fails with InfluxDB Error

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#487]
Grafana UI shows the following error:

Dashboard init failed
Template variables could not be initialized: InfluxDB Error: <br/>404 page not found

I'm using a NodePort to externally expose grafana/influxdb. I am able to hit these endpoints using the node ip/port. However, grafana is displaying: Dashboard init failed
Template variables could not be initialized: InfluxDB Error: <br/>404 page not found. Additionally, no data or graphs are present.

Per documentation, I commented out the grafana env's used for proxy api. Here is a gist that provides more details of my environment: https://gist.github.com/danehans/ffbf7642863ab9845b39

Any insight you can provide would be appreciated.

**Comment by innovia** [comment]
I'm having the same issue with 1.2, did you made any progress?

**Comment by innovia** [comment]
i just went to the settings on the left and it was set on influxdb 0.8, i've set mine to whats installed 0.9 and the error is gone but im getting empty dashboards now with no data

**Comment by danehans** [comment]
@innovia I had the same issue with 1.2 as well. I've been working on something else and have not made progress on this issue. Please provide an update if you get it working. Thanks.

**Comment by innovia** [comment]
here's the issue:

[1003](https://github.com/kubernetes/heapster/issues/1003)

i'll link  this ticket  to it

**Comment by mwielgus** [comment]
New Grafana config and dashboards were pushed in https://github.com/kubernetes/kubernetes/pull/22347. Please reopen if the problems persist.
