### ISSUE TITLE
Add code slush mode to merge bot

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/contrib#496]
We want to lock down what gets merged while we prepare for release. Last time we required two TLs to sign off on something, adding both LGTM and ok-to-merge labels.

Maybe we could do something simpler and make the bot look for the 1.2 milestone?

We'd like a small set of people to be aware of everything that is going in before we cut the release branch.

I can throw something together, but I thought I'd ask if anyone has opinions on how it should work first.

**Comment by david-mcmahon** [comment]
We need to define our slush as a feature freeze so we can have a couple of weeks to stabilize with bug fixes only.  

I don't what kind of ACL controls github has but what goes in during these lock down periods should be controlled by a short list of gatekeepers who very carefully monitor test signal and let in things that are only going to reduce the number of failures as we head toward a full code freeze and branch.

I believe the "1.2 milestone" is something anyone can add?  That's too relaxed and dangrous, IMO.
Someone mentioned "lgtm-1.2" in the meeting today.  If we can restrict that somehow as something on the short list of gatekeepers can label, that's a good option.

**Comment by lavalamp** [comment]
I'm pretty sure we can make the merge bot pay attention to the author of a
comment. Github doesn't have great ACLs.

**Comment by eparis** [comment]
Taking control away before it is abused is a bad idea. If people abuse the 1.2 milestone we educate. I see no problem with the milestone concept, or even a 2ack requirement, but the project already suffers greatly from a lack of 'gatekeepers' and a more explicit restriction of access isn't going to help us.

**Comment by lavalamp** [comment]
@eparis I take your point. We can revisit this in the future if necessary.

**Comment by eparis** [comment]
@lavalamp what do you think about us adding milestones to the merge queue priorities?  I'm not sure how to relate a p0 with no milestone vs a p2 with a 1.2 milestone...

**Comment by lavalamp** [comment]
I'm not sure how to sort that, either...
