### ISSUE TITLE
[Ingress nginx-third-party] nginx does not get initial configuration if nginx-third-party rc is annotated with a TCP Service which does not exist

### ISSUE THREAD

**Issue by oyvindio** [kubernetes/contrib#511]
If the nginx-third-party Ingress controller is configured to expose a TCP Service and that Service does not exist, the initial configuration for nginx is not created in time, and the Pod ends up in a restart loop. 

To reproduce:
1. Deploy http-default-backend `kubectl create -f $contrib/Ingress/controllers/nginx-third-party/examples/default-backend.yaml && kubectl expose --port 8080 rc default-http-backend`
2. Deploy nginx-third-party: `kubectl create -f $contrib/Ingress/controllers/nginx-third-party/examples/rc-tcp.yaml`
3. Annotate with tcpservices annotation: `kubectl annotate rc nginx-ingress-3rdpartycfg "nginx-ingress.kubernetes.io/tcpservices=default/bogus:1337"`
4. Kill the nginx-third-party Pods to force the new configuration: `k delete po -l name=nginx-ingress-lb`

Now you'll see something like this in the logs:
```
I0225 13:14:32.982404       1 utils.go:177] Waiting for default/bogus
...
E0225 13:14:37.910683       1 utils.go:65] Requeuing default/some-service, err Post http://127.0.0.1:8080/update-ingress: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E0225 13:14:37.911002       1 utils.go:65] Requeuing default/some-other-service, err Post http://127.0.0.1:8080/update-ingress: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

From what I can understand, this is because [the code path that should write the initial config](https://github.com/kubernetes/contrib/blob/ae06390f72b0d5893a1fe318af51e6ee867da39b/Ingress/controllers/nginx-third-party/controller.go#L220) ends up spinning in [this wait.Poll loop](https://github.com/kubernetes/contrib/blob/ae06390f72b0d5893a1fe318af51e6ee867da39b/Ingress/controllers/nginx-third-party/utils.go#L178). This means that nginx doesn't start, so nothing is listening on localhost:8080, hence the connection refused errors. This continues untill the Pod is killed by Kubernetes due to failing health checks, as nginx is supposed to handle these as well, but it doesn't since it is not running.

I'm not really sure how to fix this, but I think it's a bad thing that one misconfigured TCP Service should end up breaking the Ingress controller for all Services.

Verified on Kubernetes 1.1.2/custom setup with `gcr.io/google_containers/nginx-third-party:0.3`.

**Comment by aledbf** [comment]
> I'm not really sure how to fix this, but I think it's a bad thing that one misconfigured TCP Service should end up breaking the Ingress controller for all Services.

@oyvindio first thanks for finding this.
The issue is the `wait.Pool` so I only see two possible solutions to this problem:
- remove the `wait.Pool` and just print a warning if the service is not found (in the next resyncPeriod it will try to find the service/s)
- remove the `wait.Pool` and terminate the execution of the ingress controller (i think this is not a real solution)

What do you think about the first option?

**Comment by aledbf** [comment]
@oyvindio can you test if the image `aledbf/nginx-third-party:0.4` provides a better UX?
Thanks in advance

**Comment by oyvindio** [comment]
> remove the wait.Pool and just print a warning if the service is not found (in the next resyncPeriod it will try to find the service/s)
> remove the wait.Pool and terminate the execution of the ingress controller (i think this is not a real solution)

Yeah, I think we'd either have to remove the wait.Pool or reduce the timeout drastically to avoid being killed due to health checks failing.

I'll try and see how the updated image behaves - I assume that it includes the patch in your PR

**Comment by oyvindio** [comment]
I've done a quick test now, and it seems to me like #512 solves the issue. Nice work :+1:
