### ISSUE TITLE
Submit queue includes PRs that have been manually merged

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/contrib#518]
I was scanning through http://submit-queue.k8s.io/#/queue this evening and noticed that multiple PRs I've been following (https://github.com/kubernetes/kubernetes/pull/21004, https://github.com/kubernetes/kubernetes/pull/21441, https://github.com/kubernetes/kubernetes/pull/21507, https://github.com/kubernetes/kubernetes/pull/21721, and https://github.com/kubernetes/kubernetes/pull/21770) are listed in the queue (current length is 64) even though they have been manually merged. 

This means that the queue length is being reported incorrectly. 

/cc @goltermann

**Comment by goltermann** [comment]
Yes, the queue over-reports issues, but once it goes to process one, it will just quickly remove it and not waste time rerunning anything.

Still, it'd be nice if manual merges were removed from the queue more quickly.

**Comment by eparis** [comment]
The queue gets created and updated by running all open PRs.  So once a PR gets merged it will never get updated and just sits there. Like goltermann said, as soon as it gets to the top it will get noticed and updated/listed as merged.

We certainly can add another control loop that every X minutes updates everything in the queue. But I'm in no rush to do so.....

**Comment by eparis** [comment]
fixed this.
