### ISSUE TITLE
[Ingress nginx-third-party] Cannot utilize multiple destination TCP ports pointing to the same `<namespace>/<service>`

### ISSUE THREAD

**Issue by thecanadianbaker** [kubernetes/contrib#543]
Currently there is no way to select the destination port for a service. The annotation specifies the source port in `<namespace>/<service>:<source-port>`, but the destination port is [defaulted to the first port listed](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx-third-party/utils.go#L168) in the service spec.

Per [the existing documentation](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx-third-party#exposing-tcp-services) we expose a TCP service via adding the annotation `nginx-ingress.kubernetes.io/tcpservices=<namespace>/<service>:<source-port>` to the replication controller.

We have a few options on how to identify the destination port, but I think the most logical would be to change the annotation to: `nginx-ingress.kubernetes.io/tcpservices/<source-port>=<namespace>/<service>:<destination-port>` where `<destination-port>` can either be the port or name from the ServicePort

/cc @bprashanth @aledbf

**Comment by thecanadianbaker** [comment]
After some testing, kubernetes does not allow a subpath for annotations. As such, I would like to put forward `nginx-ingress.kubernetes.io/tcp-port<source-port>=<namespace>/<service>:<destination-port>`

@aledbf, any objections or alternative suggestions?

**Comment by aledbf** [comment]
> nginx-ingress.kubernetes.io/tcp-port<source-port>

I think in this case [ConfigMap](https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/configmap) is a better abstraction to avoid unnecessary code to verify/extract information about the tcp ports

**Comment by aledbf** [comment]
@thecanadianbaker please check the last version of the image `gcr.io/google_containers/nginx-third-party:0.4`. Now it's possible to use multiple ports for a particular service
