### ISSUE TITLE
Perfdash should support more e2e performance test.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/contrib#564]
Now, the implementation of *Perfdash* is specific to Density test and Load test. It is almost impossible to add support for other e2e performance tests without a refactoring.

We should refactor and generalize the code to make it support more e2e performance test.

@gmarek @yujuhong 
/cc @kubernetes/sig-testing

**Comment by gmarek** [comment]
+/infty

cc @hongchaodeng @kubernetes/sig-scalability

**Comment by Random-Liu** [comment]
Close this one since #565 and kubernetes/kubernetes#22912 have been merged.
