### ISSUE TITLE
[mungegithub] Add a [ROBOT] tag to comments from the robots to make them easier to filter.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/contrib#57]

**Comment by eparis** [comment]
VERY easy to do after my rewrite, as there is a single place comments are made in the code...

**Comment by eparis** [comment]
what would you like this to look like?
```
@k8s-bot test this
[robot]
```

```
Labeling as size XL
[robot]
```

Look ok?

**Comment by eparis** [comment]
I'm worried it will needlessly make the github history longer and people won't really use it....   we only have 2 bots, so it should be easy enough to filter on that....

**Comment by foxish** [comment]
Notifications now have this. e.g. https://github.com/kubernetes/contrib/pull/2319#issuecomment-273300329
Closing.
