### ISSUE TITLE
[service-loadbalancer] Name based virtual doc

### ISSUE THREAD

**Issue by talset** [kubernetes/contrib#573]
In the document it is written 

```
Name based virtual hosting: Currently undocumented but possible via annotations.
```

How can we define the Host field ?

**Comment by aledbf** [comment]
@talset like this:
 `kubectl annotate svc <your svc name>  "serviceloadbalancer/lb.host=www.domain.com"`

**Comment by talset** [comment]
oh serviceloadbalancer/lb.host not just "host" ! Thanks @aledbf . I will try.
Maybe you should add that just below the sentence (or I can summit a PR if you want) ?
