### ISSUE TITLE
ansible Flanneld on centos doesnt start

### ISSUE THREAD

**Issue by MansM** [kubernetes/contrib#586]
TASK [flannel : Launch Flannel] ************************************************
changed: [kube-master]
fatal: [kube-node-1]: FAILED! => {"changed": false, "failed": true, "msg": "Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}
fatal: [kube-node-2]: FAILED! => {"changed": false, "failed": true, "msg": "Job for flanneld.service failed because a timeout was exceeded. See \"systemctl status flanneld.service\" and \"journalctl -xe\" for details.\n"}

journalctl -xe on node-1:
Mar 18 15:44:52 kube-node-1 flanneld[13777]: E0318 15:44:52.157605 13777 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Mar 18 15:44:53 kube-node-1 flanneld[13777]: E0318 15:44:53.158587 13777 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Mar 18 15:44:54 kube-node-1 flanneld[13777]: E0318 15:44:54.160032 13777 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured

[root@kube-master ~]# flanneld --version
0.5.3

[root@kube-master ~]# etcd --version
etcd Version: 2.2.2
Git SHA: 6335fdc
Go Version: go1.4.2
Go OS/Arch: linux/amd64

didnt make any changes to any vars
vagrant 1.8.1 (virtualbox)
ansible 2.0.1.0
OSX

**Comment by rutsky** [comment]
@MansM take a look at my changes in #619. They fix flannel configuration issues on Vagrant + VirtualBox.

**Comment by danehans** [comment]
@MansM can you pull the latest master and retry. I believe https://github.com/kubernetes/contrib/commit/33c1671bb42b13a7712771c68118a092565668c0 fixes your issue.

**Comment by rutsky** [comment]
@danehans I don't think 33c1671 fixes @MansM issue: he runs on Ansible on Vagrant+Virtualbox, in this configuration non-default Ethernet device should be used as I described in #619.

**Comment by danehans** [comment]
@rutsky thanks for the clarification. @MansM can you verify if https://github.com/kubernetes/contrib/pull/619 fixes your issue.

**Comment by MansM** [comment]
It works now, but I would recommend source_type: packageManager
in group_vars instead of localBuild

**Comment by rutsky** [comment]
@MansM I opened #636 with suggestion to use `source_type: packageManager` by default.

**Comment by rutsky** [comment]
`localBuild` doesn't work, which is reported in #636
