### ISSUE TITLE
update kube-addons.sh with upstream version

### ISSUE THREAD

**Issue by rutsky** [kubernetes/contrib#626]
I see that `kube-addons.sh` in this repo was patched to support custom Python (e.g. for Core OS), latest related fix is #624.

I propose to update `kube-addons.sh` with upstream version that already includes workaround for missing python - it uses Python from docker image when local Python is not available:
https://github.com/kubernetes/kubernetes/blob/b103f0f/cluster/saltbase/salt/kube-addons/kube-addons.sh#L28

This will reduce differences between contrib version and upstream version of `kube-addons.sh` and will simplify contrib Ansible scripts.

/cc @danehans, @eparis, @atosatto

**Comment by danehans** [comment]
@rutsky I spent time testing python in a docker container for coreos and came to the conclusion that the con's outweighed the pro's. Take a look at: https://github.com/danehans/contrib/tree/coreos_python_docker

Keep the broader picture in mind of supporting coreos and not just the addons scripts.

The python_dir was introduced in7604d83e337e85af5c2ff32681067d5c7e75f127 This is b/c coreos does not include a python interpreter and /usr/bin, /usr/local/bin, etc.. are read-only.

Another option could be updating the python path for coreos so the script simply use "python".

**Comment by rutsky** [comment]
@danehans I *don't* suggest to remove `python_bin` Ansible fact, but I suggest to remove our Python-related patches from `kube-addons.sh` and `kube-addon-update.sh`.

Core OS requires custom Python at least to run Ansible plugins, so we need that custom Python bootstrap.
But upstream `kube-addons.sh` and `kube-addon-update.sh` don't need any Python-releated modifications — they will work out of the box.

**Comment by danehans** [comment]
@rutsky OK. Let me test the addons w/o the python mod's.

**Comment by rutsky** [comment]
@danehans I tested upstream `kube-addons.sh` and there are at least two issues with it:

1. Looks like `TRUSTY_MASTER` environment variable should be set to `true` to pull images from the Internet.

2. When Python is not available `kube-addons.sh` uses python from [local image `python:2.7-slim-pyyaml`](https://github.com/kubernetes/kubernetes/blob/b103f0f/cluster/saltbase/salt/kube-addons/kube-addons.sh#L31) which is not available in public Docker registry, so this fails.

Any idea what is `python:2.7-slim-pyyaml` and how it should be delivered to a host?

So we can't "just" update `kube-addons.sh` with upstream version.

**Comment by rutsky** [comment]
`python:2.7-slim-pyyaml` image is built in [build/common.sh](https://github.com/kubernetes/kubernetes/blob/0a8e68/build/common.sh#L890) from [this Dockerfile](https://github.com/kubernetes/kubernetes/blob/0a8e68fb49c33d91d83fb1556d1639145bdd2bee/cluster/addons/python-image/Dockerfile).

**Comment by rutsky** [comment]
Fixed by #672
