### ISSUE TITLE
Strange regexp in vagrant-ansible.yml

### ISSUE THREAD

**Issue by rutsky** [kubernetes/contrib#627]
Can someone comment on this part in https://github.com/kubernetes/contrib/blob/79b0123/ansible/vagrant/vagrant-ansible.yml#L15:

```
    - name: "Remove hostname from localhost line"
      replace:
        dest=/etc/hosts
        regexp="{{ item }} localhost?"
        replace="localhost"
```

As far as I understand this regexp will match for example `kube-master localhost` and `kube-master localhos` (note missing last letter due to `?` in regexp) — is this expected behavior?
I think `{{ item }}\s+localhost$` regexp should be used if we want to just match string like `kube-master     localhost`.

This was introduced by @jasonbrooks in 79b0123a. Jason, can you comment on this?

**Comment by jasonbrooks** [comment]
Yes, it should be `$`

**Comment by rutsky** [comment]
@jasonbrooks, thanks for the quick reply!
What about space? Should it be replaced with `\s+`: `{{ item }}\s+localhost$`?

**Comment by jasonbrooks** [comment]
Actually, I just tested these and the `$` doesn't work. The line this is changing starts like:

```
127.0.0.1   kube-master localhost localhost.localdomain localhost4 localhost4.localdomain4
```

And we're getting rid of `kube-master` w/ this.

**Comment by rutsky** [comment]
Then how about `{{ item }}\s+localhost`?
