### ISSUE TITLE
move ansible to github.com/kubernetes/turn-up

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/contrib#635]
I'm planing on creating a new repo to hold cluster deployment related automation. The goal is to eventually move `cluster/`into it. ansible/ would be a good seed since it's self contained. Yay or nay?

cc @eparis

**Comment by eparis** [comment]
I know we had some people suffer pain when last it was moved, but Yay, iff we will definitely get the cluster/salt stuff over there too. I'd like to be able to de-dup between the two a little. And that was easier way back when they were in the same tree...

**Comment by eparis** [comment]
@ingvagabund I know you actually have a CI system that uses ansible...

**Comment by mikedanese** [comment]
I'm absolutely serious about getting salt out of core. Ok, I've created https://github.com/kubernetes/kube-deploy

**Comment by rutsky** [comment]
If Ansible scripts will be moved to other repository, can this be done with preserving at least some history?
I don't think it's hard to do so, there are [guides](http://blog.mattsch.com/2015/06/19/move-directory-from-one-repository-to-another-preserving-history/) on the Internet about it.

It's already not very convenient to do blame first in `kubernetes/contrib` repository and then continue in `kubernetes/kubernetes` repository...

**Comment by ingvagabund** [comment]
@mikedanese I like the idea. Any suggestion what to do first (beside obvious mv/copy ansible under kube-deploy)? cluster directory is a black box for me. I can definitely start using kubernetes/kube-deploy once ansible is moved there. Still, it will take some time before people start sending PR to it.

How much contrib/ansible and kuberntes/cluster intersect? Would be great to index content of both folders to see what is common. I believe simple copy paste will not be enough. Any plans to rewrite part of cluster to ansible scripts? What are your expection on reusability? 90% will stay unchanged, the rest needs to be refactored? Roadmap for final kube-deploy repo could be useful.

**Comment by ingvagabund** [comment]
@mikedanese  ``move ansible to github.com/kubernetes/turn-up`` -> ``move ansible to github.com/kubernetes/kube-deploy`` or turn-up is the final name and kube-deploy WIP name?

**Comment by mikedanese** [comment]
@ingvagabund turn-up == kube-deploy :) Which name do we like best? The goal is to whittle away at salt until it can be removed. The replacement will be developed in the new repo. See https://github.com/kubernetes/kubernetes/issues/23174.

Enabling code re-usability is not my goal but if that is a side effect then that's great. Deployment automation is a large enough relm that I think users trying to deploy kubernetes in new environments would benefit from having one place to look with a bunch of examples (terraform / cloudformation / ansible / puppet / chef) to reference. Also if there is more than one chef cookbook for Kubernetes, I think that's ok too. Think of it as contrib/ for deployment automation :)

I sent out https://github.com/kubernetes/kube-deploy/pull/1

I plan on moving the kube_addon_manager into a top level directory in the new repo the next couple of days. I think it can be reasonably shared between automations with the right packaging (i.e. run in a pod)

**Comment by mikedanese** [comment]
@rutsky I will do my best to preserve history :)

**Comment by colemickens** [comment]
@mikedanese Are GCE and AWS going to move to a new bring up style during this transition? Has the deployment and change management mechanism been decided upon?
