### ISSUE TITLE
Broken link in Ansible scripts for getting the kube-ui-rc.yaml file when kube-ui: true in all.yaml

### ISSUE THREAD

**Issue by deromka** [kubernetes/contrib#650]
@danehans 
Broken link: https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/kube-ui/kube-ui-rc.yaml

When kube-ui: true in all.yaml

TASK [kubernetes-addons : KUBE-UI | Assures /etc/kubernetes/addons/kube-ui dir exists] ***
changed: [10.57.50.161] => {"changed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/etc/kubernetes/addons/kube-ui", "secontext": "unconfined_u:object_r:etc_t:s0", "size": 4096, "state": "directory", "uid": 0}

TASK [kubernetes-addons : KUBE-UI | Download kube-ui files from Kubernetes repo] ***
failed: [10.57.50.161] => (item=kube-ui-rc.yaml) => {"dest": "/etc/kubernetes/addons/kube-ui/", "failed": true, "gid": 0, "group": "root", "item": "kube-ui-rc.yaml", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "secontext": "unconfined_u:object_r:etc_t:s0", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/kube-ui/kube-ui-rc.yaml"}
failed: [10.57.50.161] => (item=kube-ui-svc.yaml) => {"dest": "/etc/kubernetes/addons/kube-ui/", "failed": true, "gid": 0, "group": "root", "item": "kube-ui-svc.yaml", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "secontext": "unconfined_u:object_r:etc_t:s0", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/kube-ui/kube-ui-svc.yaml"}
    to retry, use: --limit @cluster.retry

PLAY RECAP *********************************************************************

**Comment by deromka** [comment]
Should not these be updated to use [dashboard](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dashboard) instead?

**Comment by danehans** [comment]
@deromka Yes this is an issue and the ansible code should be updated to use https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dashboard

Could you submit a PR to make the necessary changes? It would be a big help.

**Comment by deromka** [comment]
@danehans I fixed the issue, here is a [PR](https://github.com/kubernetes/contrib/pull/676)
