### ISSUE TITLE
[Ansible] Core OS' Python generates warning "pypy: /lib64/libssl.so.1.0.0: no version information available (required by /opt/bin/pypy/bin/pypy)"

### ISSUE THREAD

**Issue by rutsky** [kubernetes/contrib#659]
Running Python installed on Core OS using [`pre-ansible` play](https://github.com/kubernetes/contrib/blob/master/ansible/roles/pre-ansible/tasks/coreos.yml) generates warnings:

```
# python 
/opt/bin/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /opt/bin/pypy/bin/pypy)
/opt/bin/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /opt/bin/pypy/bin/pypy)
Python 2.7.8 (f5dcc2477b97, Sep 18 2014, 11:33:30)
[PyPy 2.4.0 with GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> 
```

I see same warnings in kube-addons service log.

@adamschaub do you see same warnings with bootstrapped by your PR #621 Core OS?

/cc: @danehans

**Comment by adamschaub** [comment]
@rutsky Yeah, I see the same warnings crop up.

**Comment by danehans** [comment]
@rutsky @adamschaub I believe we are hitting this issue: https://github.com/ansible/ansible/issues/9650 In my testing the eror does not cause a problem. The other option to drop these lines from bootstrap: https://github.com/kubernetes/contrib/pull/621/commits/a748d18633aa357ac770c6fd5aa862fdcaff72c1#diff-7cbbed46c8297de8e15ea89e00c6ac31R17 thru https://github.com/kubernetes/contrib/pull/621/commits/a748d18633aa357ac770c6fd5aa862fdcaff72c1#diff-7cbbed46c8297de8e15ea89e00c6ac31R25

**Comment by rutsky** [comment]
> The other option to drop these lines from bootstrap: a748d18#diff-7cbbed46c8297de8e15ea89e00c6ac31R17 thru a748d18#diff-7cbbed46c8297de8e15ea89e00c6ac31R25

Looks like @adamschaub squashed changes in these lines... What was there?

**Comment by rutsky** [comment]
@danehans I though without this workaround pypy wont work at all... But if it is, lets drop this hack.

**Comment by jl-montes** [comment]
Is there an end user  work-around for this issue?
After a recent apt-get update for my Ubuntu ansible work-station we started getting these erros and cannot run our ansible scripts

$ ansible --version
ansible 2.1.0.0
 
~$ uname -a
Linux irlkjump01 3.19.0-59-generic #66~14.04.1-Ubuntu SMP Fri May 13 17:27:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by rutsky** [comment]
@jl-montes please post your error logs.
I don't see any reason this bug can arise on Ubuntu, which has it's own properly installed and configured Python interpreter.

**Comment by jl-montes** [comment]
Hi @rutsky thanks for the reply. Let me re-phrase a little. I'm attempting to run plays or even just a simple ansible ping from my ansible workstation onto my coreos machines--which had been working great for months--then all of a sudden after ubuntu workstation apt-get updates we started seeing failures mentioning the libssl.so.1.0.0 file, below is an example.

Nothing has changed on the CoreOS machines in terms of OS or the pypy package and all CoreOS machines return the same errors now

jmontes:~$ ansible -vvvv 10.200.138.1 -m ping
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<10.200.138.1> ESTABLISH SSH CONNECTION FOR USER: montana
<10.200.138.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=montana -o ConnectTimeout=10 -o ControlPath=/home/jmontes/.ansible/cp/ansible-ssh-%h-%p-%r 10.200.138.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465565267.85-230468629625702 `" && echo ansible-tmp-1465565267.85-230468629625702="` echo $HOME/.ansible/tmp/ansible-tmp-1465565267.85-230468629625702 `" ) && sleep 0'"'"''
<10.200.138.1> PUT /tmp/tmpPgr985 TO /home/montana/.ansible/tmp/ansible-tmp-1465565267.85-230468629625702/ping
<10.200.138.1> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=montana -o ConnectTimeout=10 -o ControlPath=/home/jmontes/.ansible/cp/ansible-ssh-%h-%p-%r '[10.200.138.1]'
<10.200.138.1> ESTABLISH SSH CONNECTION FOR USER: montana
<10.200.138.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=montana -o ConnectTimeout=10 -o ControlPath=/home/jmontes/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.200.138.1 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 PATH=/home/montana/bin:$PATH python /home/montana/.ansible/tmp/ansible-tmp-1465565267.85-230468629625702/ping; rm -rf "/home/montana/.ansible/tmp/ansible-tmp-1465565267.85-230468629625702/" > /dev/null 2>&1 && sleep 0'"'"''
10.200.138.1 | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ping"
    },
    "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 21058\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 10.200.138.1 closed.\r\n",
    "module_stdout": "/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\n/home/montana/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/montana/pypy/bin/pypy)\r\n/home/montana/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/montana/pypy/bin/pypy)\r\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\r\nTraceback (most recent call last):\r\n  File \"app_main.py\", line 75, in run_toplevel\r\n  File \"/home/montana/.ansible/tmp/ansible-tmp-1465565267.85-230468629625702/ping\", line 114, in <module>\r\n    exitcode = invoke_module(module, zipped_mod, ZIPLOADER_PARAMS)\r\n  File \"/home/montana/.ansible/tmp/ansible-tmp-1465565267.85-230468629625702/ping\", line 28, in invoke_module\r\n    p = subprocess.Popen(['PATH=/home/montana/bin:$PATH python', module], env=os.environ, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)\r\n  File \"/home/montana/pypy/lib-python/2.7/subprocess.py\", line 710, in __init__\r\n    errread, errwrite)\r\n  File \"/home/montana/pypy/lib-python/2.7/subprocess.py\", line 1331, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}

**Comment by juanwolf** [comment]
Hi, if anyone is still experiencing the issue, I solved the problem by replacing the `ansible_python_interpreter` in `inventory/group_vars/all.yml`  to `/opt/bin/python`.

Hope it helps.

**Comment by gintautassulskus** [comment]
@juanwolf, did not work for me.

CoreOS 1353.7.0; Ansible 2.3.0.0

**Comment by CodeShane** [comment]
I had this problem with another coreos pypy bootstrapping script; the problem was also resolved by setting the ansible_python_interpreter correctly; in my case I needed:
ansible_python_interpreter="/home/core/bin/python"

**Comment by gintautassulskus** [comment]
Thanks, @CodeShane, it worked.

In make case, I updated vagrant box to 1353.8.0 and set the path to "/opt/bin/python".
