### ISSUE TITLE
Update CICD to Include Ansible Deployment Tests

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#660]
Recently, several commits have been merged that cause breakage. This is understandable because the Ansible project supports different distros and developers typically test a patch against one distro. The existing contrib CICD system should be updated to run ansible deployment tests.

**Comment by danehans** [comment]
cc @eparis @rutsky @stephenrlouie @ingvagabund

**Comment by ingvagabund** [comment]
Something, that would set fake facts for all supported distribution (e.g. ansible_distribution, etc.) and run all important tasks.

**Comment by rutsky** [comment]
If there is some free machines available, it should be not hard to setup running of Ansible+Vagrant+VirtualBox in CI.
This setup can run on single machine and test a lot of different configurations in VMs managed by Vagrant (currently there are only efforts to run on CentOS 7 and Core OS in Vagrant, but it's easy to enable other OS').

Does K8S project have free computation powers to do this?

**Comment by ingvagabund** [comment]
Let's assume we have enough resources to test it. Another problem is a free public place for uploading test results. @danehans, @rutsky are you aware of any such place? In the worst case I could  upload the artefacts to a github repository. However, http server would be better. At the same time we will need a garbage collector removing all results older than a month (depending on the disk usage).

**Comment by rutsky** [comment]
@ingvagabund which artifacts do you mean?
Is it just log of Ansible/Vagrant (i.e. maybe few kilobytes of logs per build)?
I think such logs can be stored even on CI machines.

**Comment by ingvagabund** [comment]
At the moment just logs. Running on CentOS, Fedora, RHEL, CoreOS, Ubuntu, etc. it can get few KB * 10. So at the beginning it is more likely about any storage.

Assuming the CI logs are publicly available, it could work as well.
