### ISSUE TITLE
ansible tag "binary-update" doesn't apply to Kubernetes on Core OS

### ISSUE THREAD

**Issue by rutsky** [kubernetes/contrib#664]
@eparis @danehans any idea why binaries are downloaded on CoreOS in `kubernetes` role, not in `masters`/`nodes` roles as done in other distributions?

I asked this question in #663, but I think this should be discussed as separate issue.

**Comment by eparis** [comment]
I'd bet on an oversight when we merged the CoreOS support.

**Comment by rutsky** [comment]
@danehans this doesn't bother me at this moment, so I'll not implement this (splitting across master/node roles + adding proper `binary-update` tag).
Feel free to fix this if this functionality is needed for you, I'll will return to this issue later.

**Comment by danehans** [comment]
@rutsky I'll leave it alone for now. Please keep this issue open until a PR is merged to move the k8s bin downloads from the kubernetes role to the master/node roles. I truly appreciate all the great work you're doing for the project.

**Comment by ingvagabund** [comment]
Fixed as a part of https://github.com/kubernetes/contrib/pull/1444

**Comment by ingvagabund** [comment]
#1444 got merged, closing the issue as binary downloading is split between ``node`` and ``master`` role.
