### ISSUE TITLE
[ansible] addons fails to install on CoreOS due to missing python dependencies

### ISSUE THREAD

**Issue by rutsky** [kubernetes/contrib#667]
Currently bootstrapped in `pre-ansible` python doesn't include some modules which are required by [kube-addon-update.sh script](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/kube-addon-update.sh#L103):

```
try:
        import pipes,sys,yaml
        y = yaml.load(sys.stdin)
        labels = y["metadata"]["labels"]
        if ("kubernetes.io/cluster-service", "true") not in labels.iteritems():
            # all add-ons must have the label "kubernetes.io/cluster-service".
            # Otherwise we are ignoring them (the update will not work anyway)
            print "ERROR"
        else:
            print y["kind"]
except Exception, ex:
        print "ERROR"
```

/cc: @danehans

**Comment by rutsky** [comment]
@adamschaub perhaps this issue will be interesting to you, since you refactored Python bootstrapping on Core OS in #621.

**Comment by danehans** [comment]
Here is a gist that provides more details of the issue https://gist.github.com/danehans/36e0f7148914be6e5f87

**Comment by rutsky** [comment]
Thanks for the details @danehans!
I debugged that it fails to run Python code by adding `set -x` to `kube-addon-update.sh` and `kube-addons.sh` and reading log of ran commands.

IMO, it would be nice to fix this issue by using image with properly configured Python as it done in upstream scripts, as I suggested in #626

**Comment by danehans** [comment]
K8s cluster deployment proposal, note the addons section:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/cluster-deployment.md

**Comment by danehans** [comment]
@rutsky check out ^ You will see @mikedanese is working on a solution that appears to address our issue. Do you have cycles to work with him and test his solution: https://github.com/kubernetes/kubernetes/pull/23600 and dep: https://github.com/kubernetes/kube-deploy/pull/3

**Comment by mikedanese** [comment]
It's a WIP I'll try to finish it up today but don't waste your time debugging it just yet.

**Comment by rutsky** [comment]
@danehans  @mikedanese Yay! Running addons manager in container is very good, thanks!

@danehans At this moment I managed to update addons scripts with upstream version in #672 and addons are finally started on my test setup (Vagrant+VirtualBox+Ansible+CoreOS):

```
# kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY     STATUS             RESTARTS   AGE
kube-system   elasticsearch-logging-v1-01dsc           1/1       Running            0          24m
kube-system   elasticsearch-logging-v1-kfoou           1/1       Running            0          24m
kube-system   fluentd-elasticsearch-kube-node-1        1/1       Running            0          3h
kube-system   fluentd-elasticsearch-kube-node-2        1/1       Running            0          3h
kube-system   heapster-v1.1.0-beta1-1898144085-onfli   4/4       Running            0          24m
kube-system   kibana-logging-v1-r2vun                  0/1       CrashLoopBackOff   8          24m
kube-system   kube-dns-v11-tqbkk                       3/4       CrashLoopBackOff   9          24m
kube-system   monitoring-influxdb-grafana-v3-ihe66     2/2       Running            0          24m
```

**Comment by rutsky** [comment]
This issue is resolved by using upstream version of addons script with Python from custom Docker image: #672
