### ISSUE TITLE
[ansible] deploy etcd with authentication by default

### ISSUE THREAD

**Issue by rutsky** [kubernetes/contrib#677]
Currently deployed etcd available to all machines that have network access to the master node, which is undesirable for example when deploying Kubernetes in local network, when cluster is isolated from the Internet, but not isolated from machines in corporate network.

etcd role has configuration options to use certificate authentication (e.g. `etcd_url_scheme: https`), but doesn't include tasks to automatically generate certificates and distribute them along nodes.

**Comment by adamschaub** [comment]
+1, also have to set up server-to-server SSL/TLS correctly for clustered deployments.

**Comment by ekozan** [comment]
+1
