### ISSUE TITLE
service loadbalancer - document needed service annotations

### ISSUE THREAD

**Issue by edevil** [kubernetes/contrib#678]
I have created the loadbalancer replication controller, added the label to the nodes, and the balancer pods have started:

```
$ kubectl get pods
NAME                         READY     STATUS    RESTARTS   AGE
guestbook-8jycj              1/1       Running   0          19h
guestbook-o05ii              1/1       Running   0          19h
guestbook-xocz7              1/1       Running   1          19h
redis-master-s2y7n           1/1       Running   1          21h
redis-slave-a9f38            1/1       Running   1          20h
redis-slave-c81b0            1/1       Running   1          20h
service-loadbalancer-x1pkg   1/1       Running   0          53m
simpleweb-5vxiq              1/1       Running   0          19h
simpleweb-cpx32              1/1       Running   1          19h
```

However now I don't know to expose my existing services on the load-balancer. It's possible that I need to add some annotations to the services but this is not clear from the documentation. Output from balancer:

```
$ curl -v http://guestbook-brpx.westeurope.cloudapp.azure.com/
*   Trying 13.94.195.197...
* Connected to guestbook-brpx.westeurope.cloudapp.azure.com (13.94.195.197) port 80 (#0)
> GET / HTTP/1.1
> Host: guestbook-brpx.westeurope.cloudapp.azure.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Wed, 30 Mar 2016 11:21:54 GMT
< Content-Length: 9
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host guestbook-brpx.westeurope.cloudapp.azure.com left intact
```

**Comment by bprashanth** [comment]
Just hitting the lb ip should work, ie `http://public ip of node with role=loadbalancer/serviceName` for services in default namespace. If you want to choose your url, you will either need annotations (https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/service_loadbalancer.go#L55, syntax haproxy acl match) or use the ingress: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx, http://kubernetes.io/docs/user-guide/ingress/. 

If that doesn't work please post /etc/haproxy/haproxy.cfg within your lb pod.
