### ISSUE TITLE
Nginx ingress controller sometimes cannot parse certs

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#689]
With the default rc and gcr.io/google_containers/nginx-ingress-controller:0.4, try: 
```
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/tls.key -out /tmp/tls.crt -subj "/CN=echoheaders/O=echoheaders"
$ echo "
apiVersion: v1
kind: Secret
metadata:
  name: tls
data:
  tls.crt: `base64 -w 0 /tmp/tls.crt`
  tls.key: `base64 -w 0 /tmp/tls.key`
" | kubectl create -f -

$ echo "
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  tls:
  - secretName: tls
  backend:
    serviceName: echoheaders
    servicePort: 8080
" | kubectl create -f -
```

Logs show:
```
W0331 19:58:05.403185       1 controller.go:511] err asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 s
```

We should also print out the error btw.
@aledbf

**Comment by aledbf** [comment]
@bprashanth ok, with the code in the open PR I see this
```
W0331 23:24:55.384779       1 controller.go:575] No valid SSL certificate found in secret tls
```

that's ok?

**Comment by bprashanth** [comment]
But that's a valid cert?

**Comment by bprashanth** [comment]
To clarify, I mean:
1. If there's a restriction on the types of certs/formats etc we use with the nginx controller, we should clarify. 
2. If this is a valid cert to nginx but x509 for some reason is rejecting it (maybe go version x openssl non-compat) we should just send an event(type=Warning) and load it in nginx.
3. If this is user error, we should do best effort to surface it (but I don't think it is because the same cert seems to work on GCE)

**Comment by aledbf** [comment]
@bprashanth after 0.5 this should not be a problem anymore.

**Comment by bprashanth** [comment]
Cool thanks
