### ISSUE TITLE
[election] split-brain scenario 

### ISSUE THREAD

**Issue by cevian** [kubernetes/contrib#690]
I have this in the log of my election container (named postgres-system-1) :

> postgres-system-1 is the leader
> E0331 22:29:34.261269       7 leaderelection.go:281] err: Endpoints "postgres-system" is forbidden: unable to UPDATE endpoints at this time because there are too many concurrent requests to increment quota
> I0331 22:29:38.577846       7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
> I0331 22:29:43.902087       7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
> I0331 22:29:48.398030       7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
> E0331 22:29:57.136505       7 leaderelection.go:281] err: endpoints "postgres-system" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
> I0331 22:30:00.912678       7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
> I0331 22:30:05.480872       7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired
> I0331 22:30:08.180503       7 leaderelection.go:259] lock is held by postgres-system-0 and has not yet expired

And yet a curl to 127.0.0.1:4040 gives:
`{"name":"postgres-system-1"}`

I believe this is a split-brain bug.

**Comment by cevian** [comment]
Ok, I looked into this issue some more. It looks like a bug in the leaderelection client. I'll talk about the bug as it is in the GoDep version of the client lib, visual inspection shows its still there in the master version of the client lib (I will cross-post an issue there too). What happens is that the library encounters an error in ttps://github.com/kubernetes/contrib/blob/master/election/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go#L281

**Comment by cevian** [comment]
The above is not quite correct. The race condition  between the callback here: https://github.com/kubernetes/contrib/blob/master/election/lib/election.go#L83:
and the start of the leaderelection client here:
https://github.com/kubernetes/contrib/blob/master/election/lib/election.go#L122

Pretty much postgres-system-1 was the leader when the original leader was queried on line 71 but lost the leadership before the client started and thus neither OnStartedLeading or OnStoppedLeading was called and so the name was never changed in the election container.

**Comment by ostrain** [comment]
I just hit a scenario that I strongly suspect is a manifestation of this bug. I used helm to upgrade my deployment, which re-created the three pods that were participating in the leader election. Afterwards, one of the pods became the new leader and its leaderelector container correctly reports over HTTP that it is the leader. However, the other two pods' leaderelector containers still report over HTTP that the old no-longer-existant pod from the previous deployment is the leader, and they keep logging lines like "lock is held by <new leader> and has not yet expired."
