### ISSUE TITLE
HA setup using ansible

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/contrib#694]
Hello,
There is an inventory file inventory.example.ha provided in this repo. Does this ha setup work as in the readme it mentions that the setup is only valid for single master?

Thanks.

**Comment by gouyang** [comment]
Have you tried it? It's valid for multiple masters here.

The important thing is that there is an etcd cluster and all masters are configured to point to the etcd cluster. As long as the etcd are running healthy, any master could work well.

**Comment by shilpapadgaonkar** [comment]
I will give it a try.. So if I understood it right, I just need to use the inventory.ha file and the rest stays as is ? Or is there some variable that I need to set?

Thanks

**Comment by shilpapadgaonkar** [comment]
@gouyang: On trying i came across this issue - https://github.com/kubernetes/contrib/issues/682

**Comment by shilpapadgaonkar** [comment]
I used the suggestions mentioned in #682 to get rid of the issue.. The etcd cluster as you mentioned gets setup without issues. I then however had to install masters individually and do further changes in nodes to make the whole thing work.
