### ISSUE TITLE
Implicit SecurityContext setting for admission control

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/contrib#695]
What is the expected goal of the ansible playbook? To deploy/install kubernetes on cluster without further modification of configuration files and be able to run e2e tests successfully? Or the highest goal is to deploy the cluster and keep the default configuration for running e2e tests on user?

My situation: When I run the e2e tests after deploying my cluster with ansible, all EmptyDir e2e tests fail because SecurityContext for admission control is set to Deny all pods that set ``pod.Spec.SecurityContext`` in pod's specification (e.g. RunAsUser, SELinuxOptions).

Is it expected that a user must set admission control the way it conforms with his use cases? So actually it is expected for all EmptyDir tests to fail? I am assuming it is always expected to set/update  some minimal configuration (e.g. set secure port, change location of binaries, etc). However, I would expect that all e2e tests pass with the current default configuration settings.

**Comment by ingvagabund** [comment]
@eparis, @mikedanese, @danehans any higher thoughts?

**Comment by ncdc** [comment]
@smarterclayton @pweil- @kubernetes/rh-cluster-infra

**Comment by pweil-** [comment]
@ingvagabund the SCDeny admission plugin should've been taken out of the default setups.  It sounds like something was missed.  Reference convo: https://github.com/kubernetes/kubernetes/pull/21004#issuecomment-187533797

This is probably a dupe of https://github.com/kubernetes/kubernetes/issues/16456

**Comment by ingvagabund** [comment]
@pweil- thanks, in that case it needs to be fixed in ansible as well. Will create the patch.

**Comment by ingvagabund** [comment]
https://github.com/kubernetes/contrib/pull/697
