### ISSUE TITLE
submit queue UI looks terrible on wide screens

### ISSUE THREAD

**Issue by krousey** [kubernetes/contrib#70]
Perhaps make it wider? Or at least center it?

![image](https://cloud.githubusercontent.com/assets/157083/9771180/38955ed4-56e9-11e5-8017-4730f9335559.png)

**Comment by zmerlynn** [comment]
For me, the UI is completely unreadable because there's 0 height. (Note the empty scrollbox.)

![screenshot from 2015-09-09 13 04 09](https://cloud.githubusercontent.com/assets/4942464/9772855/a7544c22-56f3-11e5-9267-79769281eaad.png)
