### ISSUE TITLE
Conditional Downloads of tars / packages

### ISSUE THREAD

**Issue by stephenrlouie** [kubernetes/contrib#702]
- Locally host large files such as K8s tar and flannel tar to speed up deployment
- Provide the option to host these files local to the deployment, if not we can still find them on the internet
- @danehans has demonstrated a significant speed up for deployment by adding download_variables in [group_vars/all/yml](https://github.com/danehans/contrib/blob/gem_master/ansible/group_vars/all.yml#L99)

Not sure what would be optimal for upstream, but having this feature would be helpful and I wanted to document it.

cc @rutsky @eparis @adamschaub @danehans

**Comment by rutsky** [comment]
One of the options would be to download tars/packages on local machine (where Ansible is being run), and them upload them (or untarred/processed parts) from local machine to target nodes (all via Ansible of course, I think Ansible have proper tasks for this pattern).

Also serious speedup can be achieved using `checksum` of `get_url` of Ansible 2.0, as I described [here](https://github.com/kubernetes/contrib/pull/701#issuecomment-204594484).

/cc @unicell

**Comment by danehans** [comment]
@rutsky we using this role https://github.com/gemini-project/ansible-role-ansible-controller to support downloading the k8s/flannel to the ansible controller

@eparis Let me know if you would like this role added to contrib

/cc @stephenrlouie

**Comment by rutsky** [comment]
One more idea about caching downloads: if we will switch to container-based installation by default (i.e. #673) containers images will be cached by default by Docker (however they will still be downloaded for the first time for each host).

**Comment by danehans** [comment]
@rutsky in that scenario, I imagine adding a role to the ansible controller to setup and manage a private docker registry. As part of that role, we have an option to pre-fetch images. What do you think?
