### ISSUE TITLE
It should be possible to run a local submit queue with fake GitHub/Jenkins.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/contrib#713]
Right now we have the ability to do a `--dry-run`, which doesn't mutate GitHub but still tries to read from it and Jenkins. It would be useful to have `--fake`, which just generates fake PRs and the like for local testing.

I haven't quite looked through everything so this might be possible already, but if not I'd be happy to implement it.

@kubernetes/sig-testing what do you think?

**Comment by eparis** [comment]
there is probably a lot of that code already written in the submit-queue_test.go.  Sounds like a good idea to me...

**Comment by spxtr** [comment]
The combination of `--dry-run` and `--fake-e2e` is enough to do most of what I need.
