### ISSUE TITLE
Ingress - Unable to connect to LB on port 80

### ISSUE THREAD

**Issue by microadam** [kubernetes/contrib#717]
Following the examples mentioned here:

https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

I get everything created and running, however when I try and connect to my host on its external IP address and port 80, I just get connection refused.

Even trying to `curl http://127.0.0.1` on the machine itself returns connection refused, so its like the load balancing Pod is not actually listening on the hosts port 80.

Anyone have any suggestions as to how to go about debugging?

Thanks a lot

**Comment by aledbf** [comment]
@microadam how are you running the controller? can you post your yaml file?

**Comment by MariusVolkhart** [comment]
@aledbf I'm seeing the same symptoms. I'm using the yaml from https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/default/rc-default.yaml verbatim.

The echo service is working if I hit it straight on the `NodePort`. If it helps, when I do `kubectl get ing` I see that the address is not assigned. http://kubernetes.io/docs/user-guide/ingress/#simple-fanout seems to suggest that I should see an address

**Comment by aledbf** [comment]
@MariusVolkhart can you test if using `aledbf/nginx-third-party:0.11` you see the same behavior (that image contains https://github.com/kubernetes/contrib/pull/707)

**Comment by MariusVolkhart** [comment]
After some digging, this doesn't appear to be container related.

Logs for the LB pod show `main.go:102] failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`, and a [search](https://groups.google.com/forum/#!topic/google-containers/dDhlTIWS1pI) led me to look into the `admission-controllers` flag. This led me to https://github.com/kubernetes/kubernetes/pull/22957 which suggests this is a problem with the default vSphere setup (that's what I've got).

Will try adding the flag and see if that fixes things.

**Comment by microadam** [comment]
I am using the same Yaml file as Marius (rc-default.yaml from the `nginx` echoheaders example folder).

I am running a different setup to Marius though and I do have addresses assigned to the ingress, so I think this maybe two different issues.

Not sure if this could be related to this: https://github.com/kubernetes/kubernetes/issues/23920 ? It seems like the same underlying issue

Also tried using `aledbf/nginx-third-party:0.11` and have the same issue

**Comment by aledbf** [comment]
@microadam please use the latest version `gcr.io/google_containers/nginx-ingress-controller:0.5`

**Comment by microadam** [comment]
@aledbf Thats the image I have been using and having the issues with

**Comment by aledbf** [comment]
@microadam which kubernetes are you using and where (GCE,AWS,etc)?

> Even trying to curl http://127.0.0.1

That will not work, the examples do not use `hostNetwork: true`. You need to check the announced IP in the Ingress rule/s (`kubectl get ing`)

**Comment by microadam** [comment]
@aledbf I am on k8s 1.2.0 currently. Running on a Linode VM. The setup I am using is done via ansible using this repo:

https://github.com/microadam/ansible-kubernetes-tinc

The IP address that I get from `kubectl get ing` is the public IP address of the machine that is running the ingress controller. Curling that from anywhere has the same issue...

Please let me know if there is anything else I can provide to help debug.

Assuming that I shouldn't expect to see anything listening on port 80 on the host machine when running `netstat`? (still trying to understand how various bits k8s work, especially the networking)

Thanks

**Comment by PaoloneM** [comment]
Same issue with k8s 1.4.3 on CoreOS cluster and `gcr.io/google_containers/nginx-ingress-controller:0.8.3` ingress controller image.
I can reach nginx pod from inside the cluster curling its IP, but can't reach it from inside or outside the cluster using node IP.

**Comment by jleavers** [comment]
I have also seen this issue testing with k8s 1.4.4 + ```gcr.io/google_containers/nginx-ingress-controller:0.8.3```, running on an Ubuntu cluster.

The nginx pod IP responds and forwards to echoheaders as expected:

```
# kubectl describe po -l name=nginx-ingress-lb | grep IP
IP:		10.44.0.1

# curl 10.44.0.1/foo -H 'Host: foo.bar.com'
CLIENT VALUES:
client_address=10.44.0.1
command=GET
real path=/foo
query=nil
request_version=1.1
request_uri=http://foo.bar.com:8080/foo

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=*/*
connection=close
host=foo.bar.com
user-agent=curl/7.47.0
x-forwarded-for=10.32.0.1
x-forwarded-host=foo.bar.com
x-forwarded-port=80
x-forwarded-proto=http
x-real-ip=10.32.0.1
BODY:
-no body in request-
```

The node IP does not respond, even from another host on the same network or from the node itself:

```
# kubectl describe po -l name=nginx-ingress-lb | grep Node
Node:		k8s-node-3/10.1.2.3

# kubectl describe ing
Name:			echomap
Namespace:		default
Address:		10.1.2.3
Default backend:	default-http-backend:80 (<none>)
Rules:
  Host		Path	Backends
  ----		----	--------
  foo.bar.com
    		/foo 	echoheaders-x:80 (<none>)
  bar.baz.com
    		/bar 	echoheaders-y:80 (<none>)
    		/foo 	echoheaders-x:80 (<none>)
Annotations:
No events.

# curl 10.1.2.3/foo -H 'Host: foo.bar.com'
curl: (7) Failed to connect to 10.1.2.3 port 80: Connection refused
```

**Comment by jleavers** [comment]
I suspect this is a known issue, documented here: https://github.com/kubernetes/kubernetes/issues/35875

**Comment by thockin** [comment]
This issue was moved to kubernetes/ingress#552
