### ISSUE TITLE
submit queue dashboard should display time since last merge

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#721]
To make it easier to detect when it's been blocked.

**Comment by bgrant0607** [comment]
cc @eparis @fejta

**Comment by eparis** [comment]
doesn't sound too hard.

**Comment by eparis** [comment]
https://github.com/yaru22/angular-timeago/tree/master/dist for future reference.

**Comment by eparis** [comment]
Should be fixed by #758   You can also see what happens when I don't read any academic literature and make up my own exponential smoothing function for non-constant time series data   :)

**Comment by fejta** [comment]
Nice!
