### ISSUE TITLE
[ansible] Add support for kube-master HA

### ISSUE THREAD

**Issue by adamschaub** [kubernetes/contrib#725]
Production environments will require kube-master components to be run in a highly-available manner. See [1] and [2] for official guidelines.
#673 is a dependency for running these components in containers.

[1] http://kubernetes.io/docs/admin/high-availability/
[2] https://coreos.com/kubernetes/docs/latest/deploy-master.html

/cc @danehans @rutsky @stephenrlouie

**Comment by danehans** [comment]
+1
