### ISSUE TITLE
e2e links on submit queue dashboard are broken

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/contrib#726]
Links on http://submit-queue.k8s.io/#/e2e are currently broken. 

/cc @spxtr

**Comment by spxtr** [comment]
cc @ixdy who has been dealing with this lately

**Comment by ixdy** [comment]
Yup, we either need to change them to https://console.cloud.google.com/storage-browser or ideally http://ci-test.k8s.io, though for the latter we need to fix #20161 first.
