### ISSUE TITLE
Submit Queue should show size of PRs

### ISSUE THREAD

**Issue by goltermann** [kubernetes/contrib#727]
Both http://submit-queue.k8s.io/#/queue and http://submit-queue.k8s.io/#/prs should probably include size info (lines added/deleted).

This can be useful for build cop to get an idea of which ones might be good candidates for manual merges when the queue is struggling.

**Comment by spxtr** [comment]
What do you think about just showing the label (size/M, for instance), instead of additions/deletions?

**Comment by goltermann** [comment]
I think that'd work if easier.  Currently the cut off for XS is 10 lines, so that'd probably capture all the "trivial to merge" ones.

**Comment by spxtr** [comment]
Done :)
