### ISSUE TITLE
Auto-label long-latency PRs

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#73]
Proposals:
* New files in docs/proposals

Major API changes:
* Changes to pkg/api/register.go or pkg/expapi/register.go (note that the latter will move soon https://github.com/kubernetes/kubernetes/issues/13772)

Minor API changes:
* Changes to pkg/api/types.go or pkg/expapi/types.go

Will be useful if/when we start tracking PR latency

**Comment by eparis** [comment]
sure, I can probably implement such a thing tomorrow.  Any suggestions for what you'd like in label names?

**Comment by bgrant0607** [comment]
Thanks.

I suggest kind labels.

kind/design for proposals

We should create new kind labels for the API categories: kind/new-api, kind/api-change

**Comment by eparis** [comment]
implemented.
