### ISSUE TITLE
Ingress controller should verify contents of Kube secret match certs used for termination

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#730]
All controllers should do this so a user can simply update the Kubernetes Secret to update certs.
The fix in GCE would go here: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/loadbalancers/loadbalancers.go#L332, while we're fixing this, we should probably also fix this todo: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/controller/tls.go#L59, so updates to the secret are noticed immediately.

**Comment by bprashanth** [comment]
@aledbf fyi

**Comment by aledbf** [comment]
@bprashanth the nginx controller uses the current information stored in the secret

**Comment by aledbf** [comment]
for nginx this was fixed in https://github.com/kubernetes/contrib/pull/1063

**Comment by bprashanth** [comment]
This is fixed in the gce controller as well, but it doesn't yet watch secrets. That can be handled in another bug.
