### ISSUE TITLE
[ansible] Add Cloud Provider Support

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#732]
Currently, the contrib/ansible project supports bare-metal and vagrant deployments. Deploying Kubernetes to a cloud such as AWS, GCE or OpenStack is a common request. Adding cloud provider support, i.e. 'cloud_provider == 'gce' will increase the adoption of contrib/ansible and provide a single interface to meet a wide range of deployment types.

/cc @eparis @rutsky @adamschaub @stephenrlouie

**Comment by rutsky** [comment]
Is contrib/ansible with AWS/GCE will be almost same as kube-up v2 described here:
https://github.com/kubernetes/kubernetes/issues/23174 ?

@mikedanese perhaps we can unite our efforts in this scope?
