### ISSUE TITLE
CI and PR test result viewer

### ISSUE THREAD

**Issue by ixdy** [kubernetes/contrib#734]
Pony project: rather than having ci-test.k8s.io and pr-test.k8s.io redirect to the GCS storage browser, we should have a website that's smarter about showing test results/logs/etc.

At a minimum, giving a Jenkins project name and build, we should show
* start time, duration, Kubernetes version, overall result (trivial from the `started.json` and `finished.json` files)
* list of all tests that ran/passed/failed and their duration (pretty simple from parsing the junit XML files) - and maybe expandos to show failing messages etc
* the build log
* download links for all artifacts

Getting more advanced, we could have an interface to show all build results for a given PR (already pretty trivial from the directory structure we have).

Getting much more advanced, it'd be great to have an interface to provide a git sha1 and see everywhere that has been tested - PR, CI, etc.

We can start by just looking at the Google-run kubernetes-jenkins GCS bucket, but we should plan to support federated results here too.

@kubernetes/sig-testing

**Comment by spxtr** [comment]
I think this would be pretty awesome, and a good part of the infrastructure required to do it is already in place. Maybe a simple start would be to incorporate the actual failing test names into the PR comment when a build fails?

**Comment by ixdy** [comment]
I'm not sure it's possible to plumb through information about the tests to PR comments short of adding that functionality to the plugin. I'd also like to eventually get rid of the PR comments and use the commit status hooks exclusively. (Ideally the Details link would go to this viewer, rather than the GCS browser as is currently done.)

**Comment by spxtr** [comment]
Could start using a munger to post those detailed comments rather than the Jenkins plugin. Eventually it could also open/link an issue for each test that fails so that there's no issues with naming, but we need to do a bit more work to get to that point.

**Comment by spxtr** [comment]
What do you think about making and uploading a static html page at the end of the job with this information to the gcs folder for the build. The "Details" link can go to that?

**Comment by spiffxp** [comment]
what do we think about closing this?  /cc @rmmh https://github.com/kubernetes/test-infra/tree/master/gubernator
