### ISSUE TITLE
NGINX Default backend seems to be broken

### ISSUE THREAD

**Issue by paralin** [kubernetes/contrib#739]
The NGINX config makes two servers, one on 80 and one on 8080. 

The one on `80` does not have the default backend configured, it just returns 200.

The one on `8080` has the default backend configured, but despite the backend returning `Content-Type: text/html`, the nginx server changes it to `Content-Type: application/octet-stream` which results in an Invalid in chrome.

**Comment by aledbf** [comment]
@paralin this is being fixed in https://github.com/kubernetes/contrib/pull/707

**Comment by aledbf** [comment]
@paralin please use the latest version `gcr.io/google_containers/nginx-ingress-controller:0.5`

**Comment by aledbf** [comment]
@paralin please check the latest version `gcr.io/google_containers/nginx-ingress-controller:0.61`

**Comment by bprashanth** [comment]
assuming this is fixed
