### ISSUE TITLE
NGINX ingress controller does not work properly with a named targetPort

### ISSUE THREAD

**Issue by paralin** [kubernetes/contrib#743]
When using a named targetPort on the service it does not resolve which endpoint port to use, as far as I can tell.

This is a bit of a hard problem to solve because it's not immediately apparent from the endpoints list what the port name is.

**Comment by bprashanth** [comment]
> This is a bit of a hard problem to solve because it's not immediately apparent from the endpoints list what the port name is.

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1635
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/controller.go#L644

@aledbf

**Comment by aledbf** [comment]
@paralin can yo provide an example of the yaml you are using?

**Comment by aledbf** [comment]
@paralin https://github.com/kubernetes/contrib/issues/781
