### ISSUE TITLE
Move code that should be maintained to dedicated repos

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#762]
contrib isn't monitored adequately for maintained code. Issues aren't triaged. PRs aren't reviewed. We need to fix those problems, but it's not a good idea to mix maintained and unmaintained code. 

Examples:
- addon-resizer
- ingress and service-loadbalancer
- test infra/utils and mungeithub
- do we still need release-notes?
- ansible?

cc @bprashanth @eparis @david-mcmahon @mikedanese @ixdy @Q-Lee

**Comment by bprashanth** [comment]
Yeah I've brought this up before. 
I think we decided (at the time) that we don't really get much from splitting Ingress out into another repo. 

Fwiw both serviceloadbalancer and ingress have e2es (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/ingress.go) in the main repo that consume released images from: https://github.com/kubernetes/contrib/releases. Unittests will run as part of contrib pre-checking github hooks. I usually include a line in the release notes when I bump up the image in: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-loadbalancing/glbc/glbc-controller.yaml#L21

It's a hand wavy process that I'd like to improve. 

The meta issue is: How do we manage cluster addons?    
* Where are they run? 
  - If they're on the node, then we need to be really careful about increasing request limits 
  - If they're on the master, we need to allow users to swap them out (eg: gce l7 for nginx)
* Where do they live? 
  - kube-dns is checked into main 
  - heaptster has it's own repo but not sure about e2es 
  - Ingress is described above
  - cadvisor runs as part of kubelet but still has its own repo/release.
* Are they all shipped by default, with every cluster? 
   - Increases resources required for smallest cluster
   - If we don't, Ux is worse, docs harder to write (eg: start an Ingress controller, then create this)
* How are they tested?
  - Ingress would benefit from a builder available to the community
  - Running e2es from contrib/-HEAD would also be a big simplification
  - But if each of these gets a seperate e2e-builder how do these block a release?

**Comment by bgrant0607** [comment]
I would like to nuke contrib. It's no longer needed by the community.

**Comment by davidopp** [comment]
> I would like to nuke contrib. It's no longer needed by the community.

Can you clarify? What would we do with the stuff that's currently in kubernetes/contrib?

**Comment by bgrant0607** [comment]
@davidopp See the PR description.

**Comment by davidopp** [comment]
Ah OK, so what you're saying is "once we move everything from contrib out of contrib, contrib will no longer be needed"? I can't really disagree with that. :)

**Comment by eparis** [comment]
Where does mungegithub go? I don't care mind you....

**Comment by bgrant0607** [comment]
@eparis mungegithub would go into something like "productivity-tools". Some repo with a clear set of responsible owners, who would review its PRs, triage its issues, build and push updates to the tool(s), etc.

**Comment by bgrant0607** [comment]
Note that we might just delete some things (e.g., podex, which is totally broken at this point).

**Comment by spxtr** [comment]
mungegithub could go into test-infra.

**Comment by bprashanth** [comment]
>contrib isn't monitored adequately for maintained code. Issues aren't triaged. PRs aren't reviewed. We need to fix those problems, but it's not a good idea to mix maintained and unmaintained code.

If there're projects suffering from this in subdirectories of contrib/, I feel like they'll suffer from it in another repo too. 

I also think we should be clear about the bar for a new project under kubernetes/ repo. 

I want a place to incubate ideas without putting serious time and effort into making it production ready. For example, the keepalived project: https://github.com/kubernetes/contrib/tree/master/keepalived-vip is a useful prototype of an ipvs replacement of kube-proxy. Splitting that out into kubernetes/keepalived-vip doesn't help, it'll still be only a prototype. Keeping it under bprashanth/keepalived-vip doesn't either, because I want people to use it/contribute etc.

**Comment by bgrant0607** [comment]
@bprashanth Github is optimized for small, single-purpose repos. Separate repos have several benefits.
* Clear ownership, even without additional tooling
* Independent management of admin and write access
* Easy to set up independent CI
* Small and focused enough to make notification subscription feasible
* More easily independently forked/cloned
* Can't accrue spurious dependencies

Bar should be something potentially reasonably useful that someone on the project is willing to maintain, at least so long as it exists. If we're not going to maintain it (at least respond to PRs and issues), it belongs elsewhere.

**Comment by ingvagabund** [comment]
Ansible will go under kubernetes/kube-deploy repository (sooner or later).

**Comment by bgrant0607** [comment]
As mentioned by @thockin in https://github.com/kubernetes/contrib/issues/1389#issuecomment-235161997 and in comments above, we should move mungegithub to another repo. I'm currently thinking `github-tools`. We also need to move the doc munger, as mentioned in https://github.com/kubernetes/kubernetes/issues/29314. Other github-related tools could go into that repo, also.

**Comment by thockin** [comment]
+1, having a distinct repo would further the goal of being repo-agnostic
and generic.

**Comment by bgrant0607** [comment]
Stab at suggesting where each thing should go. Will gradually fill these in. Suggestions welcome.

* 404-server: For testing Ingress. Move to ingress repo or test-infra.
* addon-resizer: Move to kube-deploy.
* ansible: Move to kube-deploy or merge with kargo and delete.
* cluster-autoscaler: Move to cluster-autoscaler repo.
* cni-plugins: Move to cni-plugins repo.
* compare: Move to test-infra repo.
* continuousdelivery: Move to kubernetes/examples (which should be moved to a new repo eventually).
* diurnal: Not maintained. Delete.
* dnsmasq:
* docker-micro-benchmark:
* election: 
* exec-healthz: 
* for-demos: 
* git-sync: 
* hack: 
* images: 
* ingress: Move to ingress repo.
* init:
* keepalived-vip
* kubeform:
* kubelet-to-gcm:
* logging
* micro-demos
* mungegithub
* netperf-tester
* perfdash: 
* pets:
* podex: Obsolete. Delete.
* prometheus: Move to kubernetes/examples.
* recipes
* release-notes: Move to release repo.
* rescheduler: Move to rescheduler repo.
* scale-demo
* service-loadbalancer
* test-utils: Move to test-infra repo.

**Comment by bprashanth** [comment]
Filed https://github.com/kubernetes/contrib/issues/1441 for ingress

**Comment by rmmh** [comment]
Mungegithub should be in its own repo.

Travis CI should work well for almost all of these repos, since they should have small, fast test suites. This also means the submit queue flow shouldn't be necessary-- just merge when the CI status is green.

**Comment by bgrant0607** [comment]
@rmmh If tests are fast, then submit queue will be fast.

**Comment by rmmh** [comment]
OK, we can make the submit-queue trigger a travis build to test the merge commit then. Travis is a *much* better experience for everyone involved.

**Comment by thockin** [comment]
dnsmasq should probably move into a kube-dns repo, along with the kube-dns
code.

**Comment by spxtr** [comment]
I agree that travis should be sufficient for most repos. However, travis can be a bit of a pain when you have multiple languages, or when you want to do long or continuous testing. Travis also limits to 5 concurrent builds per org, so that's not great. I'm working on something better right now but it won't be ready right away.

I would really rather not run the submit queue/mungers against every repo. Just click the big green merge button when it's passed CI.

**Comment by bgrant0607** [comment]
Created pr-bot repo for mungegithub.

**Comment by kokhang** [comment]
I have this PR https://github.com/kubernetes/contrib/pull/1343, which adds a new project in contrib. In light of this discussion, where should i make it go? I would like to make this project available and open for the community.

**Comment by bgrant0607** [comment]
@kokhang I suggest your own github account.

**Comment by kokhang** [comment]
@bgrant0607 If i have it in my own github account, how would the kubernetes community know about it so that it can be used and contributed?
Would that be done through links and docs?

Thanks,

**Comment by bgrant0607** [comment]
@kokhang Good question for https://kubernetes.slack.com/messages/community-sites/

**Comment by Q-Lee** [comment]
@spxtr clarification needed: i18n or programming languages?

**Comment by Q-Lee** [comment]
@bgrant0607 @bprashanth I'm confused now - where will new service loadbalancers go? Imo, a netscaler implementation is a great addition for on-premise k8s deployments.

**Comment by thockin** [comment]
This is a two-edged sword, of course.  If users who wan to assemble a k8s
cluster have to pull pieces from all over the internet to do it, the
perception will be that this is a piecemeal, cobbled-together system.  we
have to find a balance.

**Comment by kokhang** [comment]
@bprashanth  I am all for trying to get the multi-backend service LB (#1343) in kubernetes incubator. Having it in my own repo would be hard for the community to know about and contribute to it.

Did this incubator process result as part of the elimination of  /contrib? There doesnt seem to be any project being incubated.

**Comment by vipulsabhaya** [comment]
@kokhang @bprashanth Just to be clear, #1343 is not a drop-in replacement (yet) of service-loadbalancer.  We would need to add L7 ingress support to it.

**Comment by thockin** [comment]
I don't MIND adding new repos under kubernetes, if we think that they will
lead towards generally useful, generic, components.  I have not had a
chance to digest this repo in particular, but maybe you should START with
it in your own space, and get it to a place where it's really useful to a
few folks and then talk about incubating it?

There's a certain gravitas that projects under kubernetes/* should have (I
said SHOULD - not all do)

**Comment by bgrant0607** [comment]
git-sync has its own repo:
https://github.com/kubernetes/git-sync

**Comment by thockin** [comment]
git-sync is an example of a really self-contained thing that doesn't even
really have to live in kubernetes, except we don't have a better place to
stick it (and we want to rely on it, I guess).  Many repos will not be sol
self-contained, but that's what we should strive for.

**Comment by porridge** [comment]
@thockin when creating new repos, do you think there should be a naming convention? For example in case of https://github.com/kubernetes/contrib/issues/1441, should its new home be github.com/kubernetes/controller-ingress or just plain github.com/kubernetes/ingress?

Something worth thinking about before there are 10 pages of repos under kubernetes...

**Comment by thockin** [comment]
We could also use multiple orgs, since GitHub has no other nesting.

Something like kubernetes-sidecars/git-sync and kubernetes-addons/ingress

I don't know if we need to impose naming conventions yet, or if we do it is
not clear what they should be...

**Comment by spiffxp** [comment]
/lifecycle frozen
The only way this repo ever goes away is if we find a home for or explicitly deprecate the code within
