### ISSUE TITLE
flannel_use_upstart = "False" instead of false on ansible version 1.9.4

### ISSUE THREAD

**Issue by stephenrlouie** [kubernetes/contrib#773]
In Ansible 1.9.4, [flannel_use_upstart](https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/client.yml#L17) is set to "False"

```
TASK: [flannel | set_fact ] *************************************************** 
<192.168.2.3> ESTABLISH CONNECTION FOR USER: core
ok: [192.168.2.3] => {"ansible_facts": {"flannel_use_upstart": "False"}}
<192.168.2.4> ESTABLISH CONNECTION FOR USER: core
ok: [192.168.2.4] => {"ansible_facts": {"flannel_use_upstart": "False"}}
<192.168.2.5> ESTABLISH CONNECTION FOR USER: core
ok: [192.168.2.5] => {"ansible_facts": {"flannel_use_upstart": "False"}}
```

In Ansible 2.0.1 [flannel_use_upstart](https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/client.yml#L17) is set to false

```
TASK [flannel : set_fact] ******************************************************
task path: /Users/stelouie/Documents/RIO/contrib/ansible/roles/flannel/tasks/client.yml:16
ok: [kube-master] => {"ansible_facts": {"flannel_use_upstart": false}, "changed": false, "invocation": {"module_args": {"flannel_use_upstart": false}, "module_name": "set_fact"}}
ok: [kube-node-1] => {"ansible_facts": {"flannel_use_upstart": false}, "changed": false, "invocation": {"module_args": {"flannel_use_upstart": false}, "module_name": "set_fact"}}
ok: [kube-node-2] => {"ansible_facts": {"flannel_use_upstart": false}, "changed": false, "invocation": {"module_args": {"flannel_use_upstart": false}, "module_name": "set_fact"}}
```
- This causes a CoreOS install using ansible 1.9.4 to skip [systemd-service.yml](https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/systemd-service.yml) instead of running it like it should.

_Possible Fix_
- Require ansible 2.0.1
- Sloppily check for the string values [here](https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/github-release.yml#L39)

cc @rutsky @danehans 
## Edit

It attempts both _flannel_use_upstart_ and _not flannel_use_upstart_. I don't imagine that this is desired. Maybe connected to this https://github.com/ansible/ansible/issues/8629

[systemd-service.yml](https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/systemd-service.yml)
[upstart-service.yml](https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/upstart-service.yml)

```
TASK: [flannel | assert ] ***************************************************** 
skipping: [192.168.2.3]
skipping: [192.168.2.4]
skipping: [192.168.2.5]

TASK: [flannel | Add Flanneld Systemd Unit File] ****************************** 
skipping: [192.168.2.4]
skipping: [192.168.2.5]
skipping: [192.168.2.3]

TASK: [flannel | Create Docker systemd dropin directory] ********************** 
skipping: [192.168.2.3]
skipping: [192.168.2.5]
skipping: [192.168.2.4]

TASK: [flannel | Add Docker drop-in with dependency on Flannel] *************** 
skipping: [192.168.2.3]
skipping: [192.168.2.5]
skipping: [192.168.2.4]

TASK: [flannel | assert ] ***************************************************** 
skipping: [192.168.2.3]
skipping: [192.168.2.5]
skipping: [192.168.2.4]

TASK: [flannel | Create Upstart Script] *************************************** 
skipping: [192.168.2.4]
skipping: [192.168.2.3]
skipping: [192.168.2.5]
```

**Comment by danehans** [comment]
Looks like we are hitting the upstream issue. The issue was fixed here: https://github.com/ansible/ansible/commit/a571fd4efecf0b7a870f40e9b5433559def4244e

From reading the upstream issue details, it seems as though ansible/roles/flannel/tasks/client.yml should be reverted in: https://github.com/stephenrlouie/contrib/commit/86c3df1ffcd76496218f60049aecddef878f0858

Can you try reverting ^ and test both ansible versions?
