### ISSUE TITLE
[service-loadbalancer] Service load balancer SSL termination should rewrite URLs

### ISSUE THREAD

**Issue by jdavis7257** [kubernetes/contrib#780]
The service load balancer should rewrite URLs to root based on the AclMatch annotation that is used to setup SSL termination. The template for the httpsTerm backend template doesn't contain the reqrep that the http backend does. This causes requests to be sent to the backend server on whatever path is in the acl instead of root. 

Adding `reqrep ^([^\ :]*)\ /{{$svc.AclMatch}}[/]?(.*) \1\ /\2`
to the backend for httpsTerm within the template should resolve this issue and make https termination behave the same as http loadbalancing.

**Comment by bprashanth** [comment]
@jdavis7257 that sounds like a good change, can you send a pr? Ideally we'd want to pick one behavior as the default and allow the other to still work, eg: through an annotation on the Service. 

Can you use the aclmatch annotation to do this? https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/service_loadbalancer.go#L55
https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/template.cfg#L93

This is how you'd set the annotation: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer#ssl-termination

**Comment by jdavis7257** [comment]
Hmm, Now that I think about it using the name for both the acl and rewrite like on the http services is a better option.  Then rewrite customization can be added via annotation later. This would make https termination work just like http and require only the httpsTerm annotation, eliminating the aclMatch unless customization was needed. Thoughts?
