### ISSUE TITLE
HTTPS automatic redirect

### ISSUE THREAD

**Issue by nottix** [kubernetes/contrib#784]
Hi,

i'm using the new TLS feature on 2 of our domains, is it possibile to disable automatic redirect from HTTP to HTTPS? 

Thank you.

**Comment by CeccoCQ** [comment]
+1

**Comment by 85simo** [comment]
+1

**Comment by bprashanth** [comment]
Yes, how are you using it? (nginx or GCE controller, and what does your Ingress look like?). HTTPS should be the default but there should be an opt-out.

**Comment by bprashanth** [comment]
Is this the same as https://github.com/kubernetes/contrib/issues/782 ?

**Comment by nottix** [comment]
No it isn't the same.
I configured nginx controller with ingress TLS rules. But now every request i make to http://domain is redirected to https://domain. Can i disable automatic redirection without editing default nginx.tmpl provided with 0.5 version?

Thank you.

**Comment by bprashanth** [comment]
There are 3 modes for https:    

1. both https and http  
2. redirect http to https
3. block http

The third is the least important, I think we shold allow at least 1, 2 through an annotation. @aledbf thoughts?

**Comment by aledbf** [comment]
@bprashanth the default behavior in the nginx controller is 2. In #766  is possible to use `force-hsts=false` to disable the redirect. The third mode is included when `force-hsts=true` (default)

**Comment by sekka1** [comment]
Is this fixed with a new container built with it?  

I am using `gcr.io/google_containers/nginx-ingress-controller:0.6` and this does not work.

**Comment by aledbf** [comment]
@sekka1 please check with the last version `gcr.io/google_containers/nginx-ingress-controller:0.61`

**Comment by bprashanth** [comment]
assuming this is fixed in 0.61
