### ISSUE TITLE
addon-resizer pod_nanny doesn't work in kubernetes cluster with disabled auth

### ISSUE THREAD

**Issue by ApsOps** [kubernetes/contrib#785]
I run a kubernetes cluster without `ServiceAccount` in `admission-control` flag so it doesn't have any secrets available. Hence, `pod_nanny` fails to start with the following error:

```
F0415 12:05:06.053612 1 pod_nanny.go:73] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

I was facing same issue with heapster, which I could resolve by using `?inClusterConfig=false` in source url as per [these instructions](https://github.com/kubernetes/heapster/blob/master/docs/source-configuration.md#kubernetes).

I believe the issue is at [this line](https://github.com/kubernetes/contrib/blob/master/addon-resizer/nanny/main/pod_nanny.go#L71) since instantiating the client with `InClusterConfig`.

There should be an option to run `pod_nanny` without auth.

cc: @Q-Lee

**Comment by xmik** [comment]
I have this problem too and I agree that
> There should be an option to run `pod_nanny` without auth.

A similar issue is: https://github.com/kubernetes/contrib/issues/1180 but it concerns `gcr.io/google_containers/servicelb:0.4` docker image.

**Comment by shanhuhai5739** [comment]
I got same problem too, I was looking for the code that without auth.  token is necessary, that's no good
