### ISSUE TITLE
nginx-ingress-controller:0.5 build from forked repo

### ISSUE THREAD

**Issue by andrewmichaelsmith** [kubernetes/contrib#789]
When I run nginx-ingress-controller:0.5 the log line says it comes from anothr repo (bprashanth/contrib) which hasn't been updated in 8 months. This seems like it might be wrong? But I'm not sure how I can check what images are supposed to be built where.

```
$ docker run -it gcr.io/google_containers/nginx-ingress-controller:0.5
I0417 15:40:14.852814       1 main.go:94] Using build: https://github.com/bprashanth/contrib.git - git-7fbd252
```

**Comment by aledbf** [comment]
@andrewmichaelsmith please check the commit [7fbd252](https://github.com/kubernetes/contrib/commit/7fbd2520863b3c6a1d4a2e503cd76497f3ebc0e2). 
The log do not includes the branch.

**Comment by andrewmichaelsmith** [comment]
@aledbf So we're talking about https://github.com/kubernetes/contrib/commit/7fbd2520863b3c6a1d4a2e503cd76497f3ebc0e2#diff-c5f50015a7af6b5dfb050056b4d9338fL89 ?

My problem is the git repo logged is "bprashanth/contrib.git", I would expect it to be "kubernetes/conrtib.git"

**Comment by aledbf** [comment]
> My problem is the git repo logged is "bprashanth/contrib.git", I would expect it to be "kubernetes/contrib.git"

This is not an error. The procedure to build is to use a fork of the main repo. The important part of this is the sha of the commit. This is what allows the tracking of the code running in case of an error.

**Comment by andrewmichaelsmith** [comment]
@aledbf OK, so if I want to run from kubernetes/contrib.git I should just build it myself?

**Comment by aledbf** [comment]
@andrewmichaelsmith what's the issue with the published images?
From the workflow imposed by the [development docs](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md) is not possible to build an image with "kubernetes/contrib.git" as git repo.
