### ISSUE TITLE
Ingress nginx controller Readme references a --custom-error-service flag but doesn't exist

### ISSUE THREAD

**Issue by alanhartless** [kubernetes/contrib#790]
See https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#custom-errors. When I use the suggested `--custom-error-service` flag, the pod fails to deploy with `unknown flag: --custom-error-service`.

**Comment by aledbf** [comment]
@alanhartless that flag was removed in 0.4. Please check https://github.com/kubernetes/contrib/pull/893 for an example on how to configure custom error pages in the NGINX Ingress controller
