### ISSUE TITLE
Nginx Ingress Controller - Secure default backend and/or support for wildcards?

### ISSUE THREAD

**Issue by alanhartless** [kubernetes/contrib#799]
Currently it's not possible to support wildcard subdomains for the Nginx ingress controller due to Kubernetes Ingress resources only allowing a legitimate domain for host. In the scenario that a wildcard domain SSL cert needs to be used for a lot of subdomains (think SaaS with custom subdomain names), it's a bit overkill to list every subdomain. 

I thought of two solutions. 

One - support via a flag to secure the default backend server with the default SSL certificate where the backend server can be something more than just a simple 404. This of course limits to a single cert and wouldn't be able to support multiple wildcard domains. 

Two - use a flag with a "wildcard" placeholder that's replaced with `*` when generating the hosts. The placeholder can be a little funny looking since the host is limited to alphanumeric keys (like `0wildcard0`, `wildcard-` or just `wildcard` if for sure not being used. 

I've implemented both for my uses but wanted to see if either (or both) would be something interested in  before I submit a PR (they feel a little hackish :-) ). Thoughts?

It would be GREAT if paths would support Nginx location regex but I know that's an Ingress limitation.

**Comment by bprashanth** [comment]
This is valid:
https://github.com/kelseyhightower/talks/blob/master/kubecon-eu-2016/demo/ingress/ghost.yaml#L12
You can also specify a list of hosts, and a wildcard cert, or just a list of hosts without a cert for something like SNI.

So I guess the request is that we allow wildcard matches in the host field of the ingress *rules*?  

> Two - use a flag with a "wildcard" placeholder that's replaced with * when generating the hosts

This is the specce'd behavior actually: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L675

@alanhartless can you give me a yaml sketch of the proposed modifcations?

**Comment by alanhartless** [comment]
@bprashanth Sorry for the long delay in replying!

`So I guess the request is that we allow wildcard matches in the host field of the ingress rules?`

That's exactly what I'm looking for. If I could define a wildcard host in the ingress rules that would result in  a nginx config similar to the following, no hack would be needed: 

```
 server {
        listen 80;
        listen 443 ssl http2;

        server_name *.example.com;
```

**Comment by aledbf** [comment]
@alanhartless using `server_name *.example.com;` means only the first matched server (in the generated nginx.conf) will route traffic to the service, the rest is not going to be reachable. That's why you need to specify the host.

**Comment by aledbf** [comment]
This issue was moved to kubernetes/ingress#8

**Comment by thockin** [comment]
This issue was moved to kubernetes/ingress#553
