### ISSUE TITLE
Nginx Ingress Controller - Config file not updated when a secret is updated

### ISSUE THREAD

**Issue by alanhartless** [kubernetes/contrib#800]
It seems that updating a secret does not trigger the config file to be updated. I have a script that is automating let's encrypt. But after the certificate is fetched and the Secret resource updated, the nginx configuration is not rebuilt (so hosts waiting on the certificate are updated). Is this intentional?

**Comment by aledbf** [comment]
>  Is this intentional?

Currently there is no watch on secret changes. Next add/update in a service or endpoint the secret will be regenerated with the new content of the secret

**Comment by bprashanth** [comment]
yeah I'm going to write a method that does the reverse lookup soon (secret to ingress) but I figured people aren't really going to cut it too close to cert expiration, so an extra couple of minutes to update pems is OK

**Comment by alanhartless** [comment]
Ok. No big deal. I worked around it. For my use case, certs will be updated relatively frequently as new domains are added up to Let's Encrypt limit of 100 domains/cert.

**Comment by bprashanth** [comment]
Just make it resync more often> :) 
If you want to write some go code, the reverse lookup shoudlnt' be too hard. You'll just need to watch secrets and anytime one changes, force all associated ingresses to sync.

**Comment by bprashanth** [comment]
Fyi you can configure the resync interval through https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/main.go#L76 like https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/rc.yaml#L98. I don't *think* this will have an adverse effect on nginx, we should only be hupping it if the config or something else actually changed.

**Comment by alanhartless** [comment]
Ah, I didn't even notice the resync flag. Please forgive my stupidity if I'm misinterpreting that code; is that re-syncing every 30 seconds already by default? Seems like it didn't catch the newly available cert within several minutes that I waited.

**Comment by bprashanth** [comment]
> Seems like it didn't catch the newly available cert within several minutes that I waited.

That sounds like a bug, I'll need to investigate when I have some time to comment more

**Comment by aledbf** [comment]
> That sounds like a bug,

Actually the issue here is that the generated `nginx.conf` file is the same and in that case nginx is not reloaded.

**Comment by bprashanth** [comment]
Ah, so compare certificates as well? 
Actually for the gce controller I'm doing a 2 phase thing, where I create the new cert, try switching, and delete the old if it passes (https://github.com/kubernetes/contrib/pull/791). I figured people won't want to black hole traffic if the second cert is bad but we've overwritten the first. If we did this the config would change.
