### ISSUE TITLE
[ansible] remove enablerepo pkgMgrInstallers/fedora-install.yml

### ISSUE THREAD

**Issue by gitpveck** [kubernetes/contrib#801]
enablerepo is not applicable in the Fedora | Install kubernetes master and Fedora | Install kubernetes node  tasks. It causes the play on fedora hosts to fail.

**Comment by gitpveck** [comment]
This applies to fedora-install.yml  in both the master and node role

**Comment by ingvagabund** [comment]
It depends on available repos. By default, the ``updates-testing`` repository is available on all released Fedoras. Can you check out content of /etc/yum.repos.d/ directory and grep for the ``updates-testing``? I have been running the ansible on F23 (and F22 before) without any problems.

**Comment by gitpveck** [comment]
Hi, I've just tested it again with the current master branch on 2 F23 hosts. All looked good. Issue can be closed I guess.
