### ISSUE TITLE
The submit queue page takes forever to load

### ISSUE THREAD

**Issue by spxtr** [kubernetes/contrib#819]
Looking at the timeline, we've loaded all of the JSON within about a second, but we spend the next 5-7 seconds laying out the tabs/lists and then loading a billion github avatars.

http://submit-queue.k8s.io/

**Comment by spxtr** [comment]
It looks like we spend 3s handling`/prs`, 1.5s handling `/history`, and 1s handling `/usrs`, and we're doing a whole lot of DOMSubtreeModified events.

**Comment by ixdy** [comment]
We can probably save some time/bandwidth by adding a size parameter to the avatar URLs, e.g. `&s=40`.

**Comment by eparis** [comment]
Things might be made a lot faster if we use https://material.angularjs.org/1.0.7/demo/virtualRepeat on the PRs (and maybe history/queue) pages. I'm not sure how that plays with the search boxes and things...

**Comment by spxtr** [comment]
It's much better for now thanks to #831.
