### ISSUE TITLE
Nginx Ingress Controller - Routing to service

### ISSUE THREAD

**Issue by nottix** [kubernetes/contrib#829]
Hi,

i found that "Nginx Ingress Controller" routes all traffic directly to pod bypassing services, why?
@aledbf 

Thank you.

**Comment by aledbf** [comment]
@nottix to delegate the load balancing to nginx and be able to use sticky session (`EnableStickySessions` option)

**Comment by nottix** [comment]
Using this way is it possible that Pod (that was deleted and recreated) IP inside Nginx is not synched with the new current Pod IP?
I'm having this problem with 2-3 of our 30 pods.

**Comment by aledbf** [comment]
@nottix please add `--v=2` to see the delay in the controller to changes in pods (it will show the diff in nginx.conf).

> IP inside Nginx is not synched with the new current Pod IP?

I never saw this behavior. Please change the `--v` flag to see what's happening

**Comment by nottix** [comment]
Ok @aledbf , i'm running a local instance of controller to monitoring the differences.

To enable sticky session on nginx is required ip_hash parameter or i'm wrong? In the nginx.tmpl i see least_conn.

**Comment by aledbf** [comment]
@nottix ip_hash is not a "real" sticky session. This functionality is only available in the comercial version of nginx. That's the reason why I'm adding the [nginx-sticky-module-ng](https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng) module in https://github.com/kubernetes/contrib/pull/825

**Comment by nottix** [comment]
Ah ok, thank you @aledbf

**Comment by nottix** [comment]
Last question: if i want to use sticky session now, i should wait for integration of nginx-sticky-module-ng ?

**Comment by aledbf** [comment]
@nottix if you can wait, I will try to get #825 and #766 before monday

**Comment by nottix** [comment]
@aledbf it would be great! Thanks.

I have to go on production with big portal that expects 30000 visitors weekly :-)

**Comment by nottix** [comment]
We actually place pod IP on upstream instead of service IP.

I found that Kubernetes 1.1 was introduced "Proxy-mode: iptables" on service, so why don't leverage on service layer for dispatching requests to pods instead of replicate load balance feature with nginx upstream?

**Comment by aledbf** [comment]
> so why don't leverage on service layer for dispatching requests to pods instead of replicate load balance feature with nginx upstream?

because is not possible to specify things like how to balance or use sticky sessions

Please check the new version `gcr.io/google_containers/nginx-ingress-controller:0.61`. It contains the sticky sessions module.

**Comment by aledbf** [comment]
>  so why don't leverage on service layer for dispatching requests to pods instead of replicate load balance feature with nginx upstream?

Please check this answer https://github.com/kubernetes/contrib/issues/1140#issuecomment-228934295

**Comment by nottix** [comment]
Thank you

**Comment by jsindy** [comment]
Can someone link how to enable sticky sessions for the nginx ingress controller? Having some trouble finding it.

**Comment by dgoujard** [comment]
Hi,

I'm looking to enable sticky sessions too. I tried to add this configmap but it's didn't affect the ingress controller (also with manual pod kill):

> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: ingress-enable-sticky-sessions
> data:
>   enable-sticky-sessions: 'true'

**Comment by jsindy** [comment]
@dgoujard if you figure it out, please post back!

**Comment by aledbf** [comment]
@jsindy you need to specify the configmap (`--nginx-configmap`) that contains the custom configuration for the ingress controller

**Comment by jsindy** [comment]
Perfect! thanks

**Comment by julianvmodesto** [comment]
Hi @aledbf, could you please elaborate what you mean by your statement about ip_hash below?

> @nottix ip_hash is not a "real" sticky session. This functionality is only available in the comercial version of nginx. That's the reason why I'm adding the nginx-sticky-module-ng module in #825

It looks like ip_hash is available in NGINX and not just in NGINX Plus, the commercial version, based on [this article](https://www.nginx.com/blog/choosing-nginx-plus-load-balancing-techniques/).

Would applying the ip_hash upstream directive work? I'm looking for Client IP affinity without the use of cookies.
