### ISSUE TITLE
[ansible] run tests to verify operational status of cluster

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#832]
Currently the contrib/ansible project does not perform tests to validate the operational status of the k8s cluster deployed by ansible. I suggest creating a test role that performs the following:

check cluster health
`$ kubectl cluster-info`
The exit code should be 0

Check that nodes have registered. Each node should show STATUS Ready. Use grep/awk/print to verify for each node in list STATUS Ready
`$ kubectl get nodes`

Create web svc manifest for testing:
$ cat > web-svc.yml << EOF
https://gist.githubusercontent.com/danehans/b797bd6f8fb1d9d3aa7a/raw/72e14298e7b21666956bd31987059910acaef4e6/web-app.yml
EOF

Deploy web.yml to the k8s cluster
`$ kubectl create -f web.yml`

Verify the svc nodePort works using curl:
`$ curl kube-node-1:30302 # should return a 0 exit code
$ curl kube-node-2:30302 # should return a 0 exit code`

List the pods to get their names
**Note**: Use grep/awk/print to get the name of the first pod in the rc.
`$ kubectl get pods
NAME        READY     STATUS    RESTARTS   AGE
web-6rydi   1/1       Running   0          20m
web-zibtt   1/1       Running   0          20m`

Get the IP of the first pod in the rc:
`$ kubectl describe pod web-6rydi | grep IP`

Use kubectl exec to curl from pod 1 to pod 2’s IP:
`$ kubectl exec web-6rydi -i -t -- ping 172.16.47.6`

**Comment by rutsky** [comment]
We can try to run K8s conformance tests on cluster: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#conformance-tests
