### ISSUE TITLE
[ansible] Fix Cluster Addons for CentOS

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#834]
Cluster addons were fixed for coreos deployments with https://github.com/kubernetes/contrib/pull/672/files

However, the addons are not functioning for centos. Review https://github.com/kubernetes/contrib/pull/672/files and investigate why it only works on coreos, port the req'd functionality to centos

**Comment by rakesh-k** [comment]
Having the same issue for redhat (should be similar to centos, I guess)

**Comment by ingvagabund** [comment]
This should be fixed https://github.com/kubernetes/contrib/issues/886

**Comment by ingvagabund** [comment]
Closing as duplicate of #886.
