### ISSUE TITLE
[ansible] Support Lifecycle Management

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#852]
Currently, the contrib/ansible project does a good job of performing an initial deployment of a Kubernetes cluster. After the cluster is initially deployed, operators have a multitude of tasks that must be performed to manage the lifecycle of the cluster. For example:
- Add a master or node to the cluster
- Upgrade the version of Kubernetes
- etc..

Ansible playbooks should be created, tested, documented, supported, etc. to support common lifecycle management tasks. Additionally, the overall design of the project should be addressed to support multiple playbooks.

**Comment by galexrt** [comment]
From my perspective there is currently especially one thing that keeps us from having a better lifecycle management for clusters with Ansible:
The certificate generation. This can be added/fixed by altering the scripts to check with `openssl` what names are in the current certificate and generating a new one for newly added services (/servers) (that require a certificate "change".

Another point to mention is that it would be better to use notify instead of the `*_modified` variables to restart the services (something I have been working on a bit already, if it is wanted).

**Comment by smenon78** [comment]
What's the best way to Upgrade kubernetes on CentOS 7?

**Comment by galexrt** [comment]
@smenon78 Have you just trying to re-run the deployment? That's the way I updated my clusters as already mentioned.
See https://github.com/kubernetes/contrib/blob/master/ansible/roles/master/tasks/pkgMgrInstallers/centos-install.yml#L5 as the latest version of Kubernetes master and nodes will be always installed by running the playbook(s).

**Comment by smenon78** [comment]
Latest package available for me via packageinstall is 1.5.2. I would like to upgrade to 1.6.1
yum --showduplicates list kubernetes
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.usf.edu
 * epel: mirror.compevo.com
 * extras: repos-va.psychz.net
 * updates: ftp.osuosl.org
Available Packages
kubernetes.x86_64                                                                                                          1.3.0-0.3.git86dc49a.el7                                                                                                          extras
kubernetes.x86_64                                                                                                          1.4.0-0.1.git87d9d8d.el7                                                                                                          extras
kubernetes.x86_64                                                                                                          1.5.2-0.2.gitc55cf2b.el7                                                                                                          extras
kubernetes.x86_64                                                                                                          1.5.2-0.5.gita552679.el7

**Comment by galexrt** [comment]
Then there are three posibilites to do it with the Ansible deployment:
**a)** Use `github-release` as `kube_source_type ` value.
**b)** Use `distribution-rpm` as `kube_source_type` value.
**c)** Use local build binaries (`localBuild`).

**Comment by smenon78** [comment]
I tried distribution-rpm, with kubernetes 1.5.6, api server had problem starting. with kubernetes 1.6.1, dns never worked. I am troubleshooting now.

**Comment by galexrt** [comment]
@smenon78 Upgrading to 1.6.x and higher is currently not supported by the addons (dns, etc.) as the service accounts rbac stuff is missing.

**Comment by smenon78** [comment]
Oh, thank you so much...For 1.5.6, api server has this in the log
 Failed to start Kubernetes API Server.
May 16 21:47:19 devtricorder01-master-01 systemd[1]: kube-apiserver.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2297]: panic: parse 127.0.0.1:8080: first path segment in URL cannot contain colon
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2297]: E0516 21:47:19.554347    2297 server.go:254] Failed to create clientset: parse 127.0.0.1:8080: first path segment in URL cannot contain colon
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2297]: I0516 21:47:19.553430    2297 config.go:527] Will report 172.22.16.86 as public IP address.
May 16 21:47:19 devtricorder01-master-01 systemd[1]: Starting Kubernetes API Server...
May 16 21:47:19 devtricorder01-master-01 systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
May 16 21:47:19 devtricorder01-master-01 systemd[1]: kube-apiserver.service failed.
May 16 21:47:19 devtricorder01-master-01 systemd[1]: Unit kube-apiserver.service entered failed state.
May 16 21:47:19 devtricorder01-master-01 systemd[1]: Failed to start Kubernetes API Server.
May 16 21:47:19 devtricorder01-master-01 systemd[1]: kube-apiserver.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /usr/lib/golang/src/runtime/asm_amd64.s:2197
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:52
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:97
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:96
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:198
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:243
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/listwatch.go:90
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:95
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /usr/lib/golang/src/runtime/signal_unix.go:290
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /usr/lib/golang/src/runtime/panic.go:63
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /usr/lib/golang/src/runtime/panic.go:489
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /usr/lib/golang/src/runtime/asm_amd64.s:514
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:51
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:65
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: /builddir/build/BUILD/kubernetes-114f8911f9597be669a747ab72787e0bd74c9359/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:72
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: E0516 21:47:19.316373    2276 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: E0516 21:47:19.315795    2276 server.go:254] Failed to create clientset: parse 127.0.0.1:8080: first path segment in URL cannot contain colon
May 16 21:47:19 devtricorder01-master-01 kube-apiserver[2276]: I0516 21:47:19.314883    2276 config.go:527] Will report 172.22.16.86 as public IP address.
May 16 21:47:19 devtricorder01-master-01 systemd[1]: Starting Kubernetes API Server...
May 16 21:47:19 devtricorder01-master-01 systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
May 16 21:47:18 devtricorder01-master-01 systemd[1]: kube-apiserver.service failed.
May 16 21:47:18 devtricorder01-master-01 systemd[1]: Unit kube-apiserver.service entered failed state.

**Comment by galexrt** [comment]
@smenon78 Can you post your `/etc/kubernetes/apiserver` and `/etc/kubernetes/config` file, seems like the addresse for the local bind of the apiserver is missing `http://` for some reason.
