### ISSUE TITLE
Auto-assigner should be smarter about cherry picks

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/contrib#855]
We should codify the release branch owner(s) and auto-assign all cherry picks to a release branch to the onwer(s). 

/cc @bgrant0607 @zmerlynn @eparis

**Comment by eparis** [comment]
That's super reasonable...

How would we want to codify the assignees?  A new section in the OWNERS file in the root of github.com/kubernetes/kubernetes ?

**Comment by bgrant0607** [comment]
Maybe part of the release process could just remove all the OWNERS files and put one in the root with the branch owners?

**Comment by bgrant0607** [comment]
cc @david-mcmahon

**Comment by eparis** [comment]
@bgrant0607 that would solve the problem with existing tools....
