### ISSUE TITLE
Ingress servers duplicated when multiple ingresses

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/contrib#858]
When I test against the ingress controller in https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx, using the ingresses in https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/ingress.yaml, multiple of each IP are listed the server config of nginx:
```
    upstream default-echoheaders-x-80 {
        least_conn;
        server 10.138.27.3:8080;
        server 10.138.27.3:8080;
        
    }
    
    upstream default-echoheaders-y-80 {
        least_conn;
        server 10.138.27.3:8080;
        
    }
```

From what I can tell, this causes issues when combined with the `proxy_next_upstream` flag in nginx for bigger server configs like:
![nginx vhost traffic status monitor 2016-04-27 16-21-41](https://cloud.githubusercontent.com/assets/881965/14866961/3333a9b2-0c94-11e6-80a9-9470df96f55f.png)

Is it possible to de-dup this server list or is this for some reason intentional?

**Comment by aledbf** [comment]
> is this for some reason intentional?

No, is not intentional. Different upstreams will have a different server list. In this case the services `default-echoheaders-x-80` and `default-echoheaders-y-80` uses the same endpoints.

Let me see if I can reproduce the duplication in the upstream of  `default-echoheaders-x-80`

**Comment by mikesplain** [comment]
@aledbf Great thanks, let me know if you need anything from me.
