### ISSUE TITLE
[Ingress] Error with execute examples/default/rc-default.yaml

### ISSUE THREAD

**Issue by prefer** [kubernetes/contrib#864]
When I try to execute `kubectl create -f examples/default/rc-default.yaml` I get error in docker:

```
[root@node1 ~]# docker logs 3d61f7980354
I0429 10:43:06.322202       1 main.go:94] Using build: https://github.com/bprashanth/contrib.git - git-7fbd252
E0429 10:43:06.322292       1 config.go:239] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
F0429 10:43:36.350474       1 main.go:123] unexpected error getting runtime information: timed out waiting for the condition
```
What can decide this problem?
k8s v1.2.3

**Comment by bprashanth** [comment]
you don't have the service account secrets needed to talk to the apiserver. How did you deploy your cluster?

**Comment by prefer** [comment]
Thanks for the tip! I was need to [prepare certs](http://kubernetes.io/docs/getting-started-guides/scratch/#preparing-certs) and add it in the apiserver.
We build our rpm package with k8s, there was not function for generating certs.

**Comment by stevesloka** [comment]
Hey @prefer / @bprashanth, I'm hitting this same issue now. I have my ca.crt in the secret that the service account uses, do I need others as well?

**Comment by bprashanth** [comment]
The service account controller (in kube-controller-manager) and the apiserver need to use the same private key because the bearer token inserted by the service account is encrypted with it.
