### ISSUE TITLE
[Ansible] k8s without ingress

### ISSUE THREAD

**Issue by prefer** [kubernetes/contrib#865]
When I create new cluster with master and one node. I get k8s v1.2.0 without [Ingress](http://kubernetes.io/docs/user-guide/ingress/).
How I can add ingress support to ready cluster?
Or how I can add something in provision to add Ingress functionality?

**Comment by cescoferraro** [comment]
@prefer have you tried `apiVersion: extensions/v1beta1`

**Comment by prefer** [comment]
```
[root@master ~]# kubectl api-versions
Available Server Api Versions: v1
```

How can I enable it?

**Comment by prefer** [comment]
Very strange. I've added "--runtime-config=v1,extensions/v1beta1=true" in the apiserver config and it anyway not working.. Config file - http://termbin.com/t74f

**Comment by cescoferraro** [comment]
Ingress works on 1.2.0.
The only thing I do is specify extensions/v1beta1 on my yaml files.
```
core@master ~ $ kube-apiserver --version
Kubernetes v1.2.0
core@master ~ $ kubectl get ing
NAME           RULE                         BACKEND   ADDRESS           AGE
```

**Comment by cescoferraro** [comment]
it works on 1.2.0
all I do is set the apiVersion to extensions/v1beta1

```
core@master ~ $ kube-apiserver --version
Kubernetes v1.2.0
core@master ~ $ kubectl get ing
NAME           RULE                         BACKEND   ADDRESS           AGE
```

**Comment by prefer** [comment]
Yep. My mistake. Ingress works after addition "--runtime-config=v1,extensions/v1beta1=true". 
`kubectl api-versions` always show `Available Server Api Versions: v1`, but ingress work. Thank you!
