### ISSUE TITLE
More PR automation

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#869]
- Explicitly notify the PR author if the PR is stuck: tests failed, needs rebase, needs release note, etc. The notifications that don't mention anyone won't rise above github notification noise.
- Explicitly notify the PR assignee if the PR needs them to do something: ok to test, ok-to-merge, e2e--not-required, reapply lgtm label after rebase, release note label, etc.
- Ping the PR due to lack of inactivity, notifying either the PR author or the assignee, depending on who last touched the PR (keep track of whose court it's in)
- Create a way to postpone the next ping for a fixed amount of time (day, week, month, next release cycle)
- Reassign PRs whose assignees never responded
- Reassign PRs that need approval from someone other than the current assignee (part of OWNERS proposal)

@fejta @philips @eparis

**Comment by philips** [comment]
@bgrant0607 for someone wanting to start working on this is it expected to be an extension of the existing k8s-bot? And if so where does that code live?

cc @mike-saparov

**Comment by bgrant0607** [comment]
@philips Yes, I'd extend the existing bot. 

Existing code is here:
https://github.com/kubernetes/contrib/tree/master/mungegithub

For example, the existing auto-assigner:
https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/blunderbuss.go

**Comment by bgrant0607** [comment]
Other ideas:
* Dashboard with numbers of PRs stuck in each state: needs rebase, needs review, comments to address, waiting in queue, etc.
* Dashboard with histograms of number of rebases per PR, PR latency (by PR size)

cc @apelisse @goltermann

**Comment by bgrant0607** [comment]
If a commenter didn't notify the other party, we should explicitly notify them, without waiting for the full inactivity threshold.

If the author performed some action that doesn't generate a notification (e.g., pushed changes), we should generate the notification.

Tests passing should notify the reviewer.

**Comment by bgrant0607** [comment]
See also #481

**Comment by bgrant0607** [comment]
We should check out https://github.com/facebook/mention-bot (#1250).

**Comment by bgrant0607** [comment]
Looks like I also filed this here: https://github.com/kubernetes/kubernetes/issues/24844

**Comment by bgrant0607** [comment]
@apelisse This is the task I was referring to.

cc @matchstick

**Comment by bgrant0607** [comment]
Example: https://github.com/kubernetes/kubernetes/pull/28936

**Comment by bgrant0607** [comment]
The Google CLA bot doesn't explicitly notify the author. Example:
https://github.com/kubernetes/kubernetes/pull/29452

Our bot will likely take over notification and labeling when we switch to the CNCF CLA (https://github.com/kubernetes/kubernetes/issues/27796).

**Comment by bgrant0607** [comment]
We need notifications for:
* PR assignment
* Commit push
* Build / unit test failure

**Comment by bgrant0607** [comment]
PR workflow proposal:
https://docs.google.com/document/d/194MGgJHlm4ovXtvzvkjzzBZG_v47d95nsjuuaUe1Log/edit?ts=57929ed1#

**Comment by bgrant0607** [comment]
Github added more signals to notification emails. I'll adjust my filters to take advantage of these and will report whether it helped. We should add a link to this in our PR workflow documentation:
https://help.github.com/articles/about-notification-emails/#the-cc-address

**Comment by bgrant0607** [comment]
We could autodetect messages like "this should be closed".
Example: https://github.com/kubernetes/kubernetes/issues/28817

**Comment by apelisse** [comment]
Somewhat related but @fejta and I agreed that it would be nice to have a close-stale-flake-issues munger.

**Comment by bgrant0607** [comment]
"ok to test" messages don't notify anyone.
Example: https://github.com/kubernetes/kubernetes/pull/30208

**Comment by bgrant0607** [comment]
As discussed, we should change all bot instructions to clear commands, like:

```
/TEST
/RETEST
/LGTM
/APPROVE
/PTAL
```

Plain english can be misinterpreted ("lgtm if you do X"), long phrases ("@k8s-bot test this issue: #IGNORE")  are hard to remember, and sometimes requiring bot notification and sometimes not is confusing.

**Comment by janetkuo** [comment]
Now if you LGTM in reviewable it prints this:

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.kubernetes.io/lgtm.png" height="20" width="61"/>

Can bot also respond to this?

**Comment by bgrant0607** [comment]
I'm finding that many reviewers are not aware of `/lgtm`. I think that when the bot assigns a reviewer, it should post tips for reviewing, including common commands, info about Reviewable, link to more info, etc.
