### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by cescoferraro** [kubernetes/contrib#877]
I want to be able to protect some of my kube-system service (dashboard, kubedash, ...) yet still exposing them with the nginx-controller without having to change thos service's code base.
But cannot find a way to implement basic authentication as described in [the NGING docs](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html)

Am I missing something?

**Comment by aledbf** [comment]
@cescoferraro please check this https://github.com/aledbf/contrib/blob/6d61ea81bb0bdbbc115cd6a6e9c59ef653afb213/ingress/controllers/nginx/examples/auth/README.md

**Comment by cescoferraro** [comment]
is this on 0.61 @aledbf  ?

**Comment by aledbf** [comment]
@cescoferraro no, next release
