### ISSUE TITLE
Add release-note-experimental to release-note label checking

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/contrib#882]
Can we add this one to the mix too?  More probably coming.

**Comment by david-mcmahon** [comment]
I already added the label and am parsing for it in the release notes generation tool.  So we can just add enforcement when we get to it.

**Comment by david-mcmahon** [comment]
cc @bgrant0607

**Comment by david-mcmahon** [comment]
Just a run down here on what we currently have.  The release notes have a previously agreed upon list of [headings](https://github.com/kubernetes/release/pull/1/files#diff-d2b70fc121f3dab046b476fbfcd7f7abR298).  Here they are with associated labels in order of how they appear.  

Heading | Label
---------- | --------
Major Themes | _curated_
Other notable improvements | _curated_
Experimental Features | release-note-experimental
Action Required | release-note-action-required
Known Issues | _curated_
Provider-specific Notes | _curated_
Other notable changes | release-note

The idea is that the _curated_ headings only appear in the release notes for .0 releases and are populated by hand by the release owner (soon) after the initial notes are published during the release.

I believe the only one of these likely get a label is "known issues" - being discussed in another thread.  cc @roberthbailey

**Comment by bgrant0607** [comment]
Looks reasonable to me.

**Comment by david-mcmahon** [comment]
I just noticed that `release-note-experimental` is no longer on the label list.  Probably pulled because it was not enforced yet.  We can re-add when we add enforcement of it.
