### ISSUE TITLE
SSL as a Reverse Proxy on Nginx Controller ? 

### ISSUE THREAD

**Issue by Joncak** [kubernetes/contrib#884]
Hi, i'm using the nginx and GCE official ingress controllers, but the reverse fot the backend service  is http only, it is posible a proxy pass with https support or maybe using the redirect.

` proxy_redirect      http://localhost:8080 https://secure.domain.com;`

**Comment by aledbf** [comment]
@Joncak this is being implemented in the nginx ingress controller (#1104) using the annotation
`ingress.kubernetes.io/secure-upstream: "true"` in the ingress rule. 
This assumes the service is running with `https`.
