### ISSUE TITLE
Nginx Ingress Controller - Option to disable interception of errors

### ISSUE THREAD

**Issue by databus23** [kubernetes/contrib#897]
It seems to me right now there is no way to configure the nginx ingress controller to **not** intercept errors and serve them from the default/error backend.

In our case this is problematic. Our backends serve meaningful error pages for 500 errors which contain exception ids which help us debugging problems when customers create support requests.
We also have a JSON API backend where 404 error contain additional information that help api clients to fail more gracefully.

How about adding an option to (potentially partially) disable the *error interception* ?
I can submit an initial PR of this would be considered useful.

**Comment by aledbf** [comment]
@databus23 this is the list of the intercepted errors https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx.tmpl#L129 . Just in case error 500 is not intercepted. 
You want multiple options (one per error) or a global flag?

**Comment by aledbf** [comment]
> You want multiple options (one per error) or a global flag?

I meant option in the nginx configmap

**Comment by databus23** [comment]
@aledbf Ups missed that one. Ok, so 500 errors should work, I actually never tested this. But we have had problems with 404 and 403 errors where backend developers where unhappy that there response didn't get served to the client. For a start I would like a global flag to have nginx not mingle any responses. Having this configurable per error or even per backend would be nice to have.

**Comment by aledbf** [comment]
@databus23 I will add a global option and one per intercepted error today
