### ISSUE TITLE
[submit-queue] Wrong lgtm label handling

### ISSUE THREAD

**Issue by piosz** [kubernetes/contrib#901]
Submit Queue is removing lgtm label in https://github.com/kubernetes/kubernetes/pull/24253 despite that the PR didn't change. 

From its logs it seems something is broken:

```
I0505 07:05:31.070833       1 lgtm_after_commit.go:78] PR: 24253 lgtm:2016-04-29 07:48:10 +0000 UTC  lastModified:2016-05-05 06:57:29 +0000 UTC
I0505 07:05:31.070935       1 github.go:1327] Commenting "PR changed after LGTM, removing LGTM." in 24253
I0505 07:05:31.300853       1 github.go:661] Removing label "lgtm" to PR 24253
I0505 07:05:31.754954       1 github.go:929] PR 24253 setting "Submit Queue" Github status to "Github CI tests are not green."
I0505 07:35:29.196452       1 lgtm_after_commit.go:78] PR: 24253 lgtm:2016-04-29 07:48:10 +0000 UTC  lastModified:2016-05-05 06:57:29 +0000 UTC
I0505 07:35:29.196529       1 github.go:1327] Commenting "PR changed after LGTM, removing LGTM." in 24253
I0505 07:35:29.402405       1 github.go:661] Removing label "lgtm" to PR 24253
I0505 07:35:29.800642       1 github.go:929] PR 24253 setting "Submit Queue" Github status to "PR does not have LGTM."
```

**Comment by eparis** [comment]
I've seen this bug once before. It's the reason I added the debug line on lgtm_after_commit.go:78.

**Comment by eparis** [comment]
I see that the bot is paying attention to the label on page1 (`2016-04-29 07:48:10 +0000 UTC`
https://api.github.com/repos/kubernetes/kubernetes/issues/24253/events?per_page=100&page=1
And ignoring the labels on page2
https://api.github.com/repos/kubernetes/kubernetes/issues/24253/events?per_page=100&page=2

At least something for me to poke!  I thought we fixed it last time by just restarting the bot. But that wouldn't explain why the bot was only looking at 1 page of events...

**Comment by eparis** [comment]
My best guess is that this is a github api error where we have cached in the local proxy that there is a single page of events and this is not invalidated when it grows to a second page?  I'm not sure how to debug, but might just dump in the logs the last `N` github responses every time LGTM is missed/bad like this....

**Comment by lavalamp** [comment]
ref #996 

I did some local testing - it seems the Etag doesn't change if you delete a comment. And the cache gives a false hit in that case.

However adding/removing a label does seem to change the Etag, so that doesn't seem to explain this.

**Comment by lavalamp** [comment]
I tossed my debug code into #1003

**Comment by lavalamp** [comment]
I observed that my change in #996 actually triggers. So I believe this is actually fixed. We can probably remove some of the debug messages now.

**Comment by eparis** [comment]
we never did figure out what was wrong though...  somehow we don't think there is another page, but there is...   so who is lying to us? the proxy or github? (I bet github)

**Comment by lavalamp** [comment]
Yes, my money's on github also.

**Comment by piosz** [comment]
Closing as obsolete
