### ISSUE TITLE
[ingress/controllers/nginx] per service configuration proposal

### ISSUE THREAD

**Issue by simonswine** [kubernetes/contrib#904]
I started using nginx-ingress for my private cluster a couple of days ago. I can already see the strong need to have per service configuration options. They would allow me to run only one set of nginx-ingress controllers in your cluster, but different configurations. I took a short look at the issues and I can see the need for something like this is definitely there.

I am thinking of uses cases like these:

- authentication with http auth (#877)
- custom-error pages enable/disable, range of error codes to intercept, link custom error-backend (#897)
- HSTS enable/disable 
- HTTPS enforcement (301 redirect) (#784) (#877)
- there are probably a lot more

All of these could be configured on nginx `location` - level (makes no sense for HSTS)

My plan for implementing that would be:

- create an annotation for the service object which links a configmap
- read and watch the linked config object and respect them when building the nginx.conf

How do you think about that?

I would be willing to do the implementation, but probably need some help around watching config objects.

**Comment by simonswine** [comment]
@aledbf 
@bprashanth

**Comment by bprashanth** [comment]
Your plan sounds good. We should work toward distilling common config options up into the IngressBackend section, but a config map is the way to start. My only fear is it will lead to a complicated mess. Are Service annotations insufficient?

**Comment by simonswine** [comment]
I just had in mind that we might want to have services, which you want to configure in the same way and so I thought about abstracting a bit more with a configmap. But for simplicity's sake I am gonna start with service annotations and features redirect/hsts/custom-error. Let you know as soon as I've got something to work with...

**Comment by aledbf** [comment]
@simonswine can you close this issue? (the mentioned items are implemented now)

**Comment by simonswine** [comment]
Yes all of this has been implemented
