### ISSUE TITLE
Merge bot could be more helpful when flakes require a retest

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/contrib#920]
See https://github.com/kubernetes/kubernetes/issues/25212

I hardly ever get the syntax right for the "@k8s-bot please retest this" command. It would be nice if a failed test gave me the exact command (without the actual flake issue) that I needed to get a retest.

I was also confused by the behavior from the issue linked above. My command did trigger a retest, but @k8s-merge-robot didn't agree. To further confuse me, my command to @k8s-bot was deleted.

**Comment by bprashanth** [comment]
Yeah i think it deletes comments when you use #link instead of #number too

**Comment by eparis** [comment]
@bprashanth that one was fixed. Assuming the link was reasonable.

**Comment by eparis** [comment]
so @k8s-merge-robot is what complains, but @k8s-bot is what "does" the retest. @k8s-bot has no enforcement (this was intentional).  But at this point maybe we should 'enforce' it. But just yelling at people while still letting them get work done seems like a reasonable tradeoff.
