### ISSUE TITLE
[ansible] problems with external artifacts (e.g. from github)

### ISSUE THREAD

**Issue by simonswine** [kubernetes/contrib#931]
Currently the latest ansible code fails to deploy a master on CoreOS, because there are artifacts missing, due to ongoing development on the mainline kubernetes github repo:

```
TASK [kubernetes-addons : Make sure the system services namespace exists] ******
fatal: [10.251.0.10]: FAILED! => {"changed": false, "dest": "/etc/kubernetes/addons/", "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/saltbase/salt/kube-addons/namespace.yaml"}
```

While this bug is rather easy to "fix" it shows a more general problem: We are relying on a lot of external files/resources to spin up a kubernetes with ansible.

As an intermediate fix I am gonna do the following in a follow up pull request:

Instead of using the `master` I am gonna use `v{{ kube_version }}` to get the resources for the related tag. This should solve issues like that for now and would give use more reproducible ansible results.

I think ultimately we should review our heavy reliance on external resources to configure kubernetes with ansible. I think this could create plenty of issues like:
- compatibility only with latest/master k8s release
- really hard to run k8s in private network envs (no general internet access)

I would strongly suggest we should aim to reduce the external resource (e.g. things that do not come with the ansible code) to the following:
- k8s build artifacts from `{{ kube_download_url_base }}`
- docker images of all sorts

Let me know how you think about this!

**Comment by adamschaub** [comment]
See WIP #927 to solve the immediate issue. +1 to reducing external resources to mitigate these issues in the future.

**Comment by ingvagabund** [comment]
Let's do that as part of the roles refactoring. I would like to finish https://github.com/kubernetes/contrib/pull/967 first. Together with refactoring of etcd https://github.com/kubernetes/contrib/pull/1380 and kubernetes https://github.com/kubernetes/contrib/pull/1444 roles. After that, it will be more pleasant to minimize the number of outside dependencies.

**Comment by ingvagabund** [comment]
Among others we should pick systemd unit files, config files and upstart files from corresponding roles, not downloading them.

```sh
$ grep -rn "get_url"
node/tasks/retrieve-systemd-files.yml:3:  get_url:
node/tasks/retrieve-systemd-files.yml:19:  get_url:
node/tasks/retrieve-systemd-files.yml:36:  get_url:
node/tasks/fluentd-install.yml:3:  get_url:
node/tasks/ubuntu-14.04.yml:3:  get_url:
node/tasks/ubuntu-14.04.yml:17:  get_url:
node/tasks/coreos.yml:3:  get_url:
master/tasks/retrieve-systemd-files.yml:3:  get_url:
master/tasks/retrieve-systemd-files.yml:21:  get_url:
master/tasks/retrieve-systemd-files.yml:40:  get_url:
master/tasks/ubuntu-14.04.yml:3:  get_url:
master/tasks/ubuntu-14.04.yml:18:  get_url:
master/tasks/coreos.yml:3:  get_url:
```
