### ISSUE TITLE
More configurable health checks for GCLB

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#934]
To do this we'd pipe a richer datastructure through the `Add` method: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/backends/backends.go#L140, something like:

``` go

type healthCheck {
    path string
    interval time.Duration
}

type backendInfo struct {
  nodePort int
  hc healthCheck
}
```

And then read those values from annotations here: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/controller/controller.go#L238 (similar method called ListBackendInfo) and pipe it through to https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/controller/controller.go#L271.

Essentially if any Ingress specifice `ingress.beta.kubernetes.io/health-check-path: "/foo"` and/or `ingress.beta.kubernetes.io/health-check-interval: "duraiton"`, we should program the health check appropriately.

**Comment by ajcrowe** [comment]
I've been thinking through the implications of this change. 

Currently health checks are created per backend with the name `k8s-be-<node-port>--<cluster-uid>`. These are then reused for any Ingress resources which make use of the same backend service, or more specifically `node_port`. 

With this change we'll opening the door to health checks which are unique per Ingress.

Questions

* Do we still try and dedup the healthchecks?
  * If so what naming convention would be best, so would we read all k8s healthchecks and look for a match?
* If not do we simply create per ingress health checks which can be named `k8s-be-<ing-name>-<be-name>--<cluster-uid>`

My personal thoughts are given that backends are likely not going to be reused in multiple ingress resources we move to a per ingress naming scheme.

**Comment by bprashanth** [comment]
> My personal thoughts are given that backends are likely not going to be reused in multiple ingress resources we move to a per ingress naming scheme.

Resource sharing is required for 2 things:
1. Backends: because the quota is really low (3 by default), and it's very common to have a single kube Service for, eg: login and only need a single backend for that (so all urlmaps have a /login going to a single backend).
2. Instance groups: because you can't add a single vm to > 1 loadbalanced instance group and get accurate utilization information.

So the core problem seems to be: when you crate a backend, you need to give it a  health check, but that makes the backend unusable by some other Ingress that has asked for a different health check. 

> If not do we simply create per ingress health checks which can be named k8s-be-<ing-name>-<be-name>--<cluster-uid>

If we could avoid this it would be best (because of the reason stated above), but it's software, so I'm sure we can make it work somehow if we need to :)


>Do we still try and dedup the healthchecks?
If so what naming convention would be best, so would we read all k8s healthchecks and look for a match?

Yeah I'm voting for this. You can still use a single backend in multiple url maps with a different health check. The health checks can be specific to the Ingress name/ns, I don't think we'll need multiple backends to share a health check. 

I think this also takes us one step closer to health checking straight to endpoints.
