### ISSUE TITLE
[ansible] Monitoring & logging services not started

### ISSUE THREAD

**Issue by elemoine** [kubernetes/contrib#941]
I followed the [ansible/vagrant README](https://github.com/kubernetes/contrib/blob/master/ansible/vagrant/README.md). Ansible successfully finished but the monitoring and logging services are not started:

```bash
[static-67 vagrant (master u=)]$ vagrant ssh kube-master
[vagrant@kube-master ~]$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
```

I ran `vagrant up --provider libvirt` with the default options. So CentOS7 is used in my case. I also tried to run `vagrant provision` again as indicated in the README, but that did not help.

**Comment by gouyang** [comment]
@elemoine is `kube-system` namespace created?

**Comment by elemoine** [comment]
No, the `kube-system` namespace is not created. So this issue is indeed related to https://github.com/kubernetes/contrib/issues/944.

**Comment by gouyang** [comment]
I think it is #944, you can create `kube-system` namespace manually and to see whether addons are created, maybe need to restart kube-addons service.
