### ISSUE TITLE
[ansible] namespace kube-system is not created

### ISSUE THREAD

**Issue by gouyang** [kubernetes/contrib#944]
namespace `kube-system` is not created because kube-addons.sh is expecting to find it at /opt/namespace.yaml.

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube-addons.sh#L68

**Comment by rakesh-k** [comment]
Rest of the kube-system related (add-ons) .yaml's are under /etc/kubernetes/addons. And that's where the namespace.yaml is on my system. Why would it expect the namespace.yaml in the /opt directory?

**Comment by eparis** [comment]
I believe this was resolved...

**Comment by gouyang** [comment]
The issue is gone as we're using local common/kube-addons.sh, it's using /etc/kubernetes/addons/namespace.yaml.
