### ISSUE TITLE
Change to expose hostname instead of localhost for the apiserver etc.

### ISSUE THREAD

**Issue by rakesh-k** [kubernetes/contrib#948]
The k8s cluster installation on my VMs leads to this:

```
[rakeshk@cd3labvdapp002 system]$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
Elasticsearch is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubedash is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubedash
kubernetes-dashboard is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
[rakeshk@cd3labvdapp002 system]$
```
 I would rather expose the hostname for these URLs so that it can be accessed by other hosts. What config change is needed?

**Comment by gouyang** [comment]
what's the hostname in the ansible/inventory when you run the ansible-playbook?

**Comment by rakesh-k** [comment]
It is the hostname of the nodes and the master and not localhost. The setup is for a multinode cluster so, localhost won't even work there. Wonder where/how localhost gets picked up?

**Comment by gouyang** [comment]
@rakesh-k if the hostname is dns resovlable, it should not be `localhost`.  I don't see this problem in my environment.

**Comment by rakesh-k** [comment]
Here are the outputs from ping and nslookup:

```
[rakeshk@cd3labvdapp002 ~]$ ping cd3labvdapp002
PING cd3labvdapp002 (172.27.36.101) 56(84) bytes of data.
64 bytes from cd3labvdapp002 (172.27.36.101): icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from cd3labvdapp002 (172.27.36.101): icmp_seq=2 ttl=64 time=0.029 ms
64 bytes from cd3labvdapp002 (172.27.36.101): icmp_seq=3 ttl=64 time=0.030 ms
64 bytes from cd3labvdapp002 (172.27.36.101): icmp_seq=4 ttl=64 time=0.027 ms
^C
--- cd3labvdapp002 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 2999ms
rtt min/avg/max/mdev = 0.027/0.030/0.036/0.006 ms
[rakeshk@cd3labvdapp002 ~]$ nslookup cd3labvdapp002
Server:         172.16.245.144
Address:        172.16.245.144#53

Name:   cd3labvdapp002.{snipped}.com
Address: 172.27.36.101
```
Here is the inventory file content:

```
[masters]
cd3labvdapp002

[etcd]
cd3labvdapp002

[nodes]
cd3labvdapp002
cd3labvdapp003
cd3labvdapp004
cd3labvdapp005
```

**Comment by gouyang** [comment]
I think you should put `cd3labvdapp002.{snipped}.com` in inventory.

**Comment by gouyang** [comment]
@tomsherrod `cp /etc/kubernetes/kubectl.kubeconfig /root/.kube/config` and try again.

**Comment by gouyang** [comment]
@rakesh-k Would you like to take a look at this problem again, see above comment.

If it's solved, we can close this issue.

**Comment by ingvagabund** [comment]
@rakesh-k 

deployed with vagrant [1], deployed on openstack [2]. The only difference is in ``/etc/hosts``. In the first case, there is ``127.0.0.1   localhost...``. In the second case there is ``127.0.0.1    kube-master-1...``.

At the same time all the links are proxied via the localhost as the master runs on the machine.

> I would rather expose the hostname for these URLs so that it can be accessed by other hosts. What config change is needed?

It runs on localhost so replacing/curl it with kube-master-1 or any hostname for the master should work.

> It is the hostname of the nodes and the master and not localhost in the inventory file. The setup is for a multinode cluster so, localhost won't even work there. Wonder where/how localhost gets picked up?

> Fully qualified names in inventory file, cluster-info shows localhost for me. I even change to ip address for master and remains localhost.

Check out https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/clusterinfo.go#L94. This is ansible independent.

[1] https://github.com/kubernetes/contrib/issues/1632#issuecomment-243138322
[2] https://github.com/kubernetes/contrib/issues/1632#issuecomment-243093845

----

Closing this as it is not an ansible issue.

**Comment by ingvagabund** [comment]
@tomsherrod, @rakesh-k as @gouyang commented, this is related to the kubectl configuration.

**Comment by ingvagabund** [comment]
@tomsherrod, @rakesh-k You can run either of both as well:

``kubectl --kubeconfig /etc/kubernetes/kubectl.kubeconfig cluster-info`` 
``KUBECONFIG=/etc/kubernetes/kubectl.kubeconfig kubectl cluster-info``

**Comment by DarkBlaez** [comment]
Surprised this thread did not go further than this... The above issue is repeatable using the ansible scripts.

All nodes Ubuntu 16.04

1) Inventory containing IP addresses only of each master, node
 A) run ansible, result localhost referenced as indicated in the original issue above. this should be considered a failure of the install. One would expect IPs defined to be used, not localhost

2) Inventory containing fully qualified server names
  A) ansible blows chunks when trying to reference the certs with flanneld indicating the actual IPs over fqdn. Might be a cert generation issue

Either way has anyone gone back and checked the current ansible install on fresh VMs. I've already found one issue with the current and Ubuntu 16.04

This issue should be considered still open until resolved as default behavior with FQDN or IP defined in inventory should not default to services on localhost.

DB
