### ISSUE TITLE
Perfdash Godeps are invalid

### ISSUE THREAD

**Issue by eparis** [kubernetes/contrib#949]
2cd65f7 is not a commit in kubernetes. And yet it is claimed in https://github.com/kubernetes/contrib/blob/master/perfdash/Godeps/Godeps.json#L20

This was done in https://github.com/kubernetes/contrib/pull/815 by @Random-Liu 

This is an example of why verify-godeps.sh is run in the main tree. So we don't get random non-godep-restorable cruft.

**Comment by Random-Liu** [comment]
@eparis Will fix it soon, :(
Thanks a lot!

**Comment by Random-Liu** [comment]
Close this since #955 has been merged.
