### ISSUE TITLE
ingress controllers should watch secrets

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#952]
Currently there is no code that translates secrets <-> ingress. we wait for the periodic relist, then lookup secrets and create certs. We should notice when secrets change and invoke a sync on the associated ingress.

**Comment by guybrush** [comment]
Isn't this solved with #1063 ?

**Comment by bprashanth** [comment]
I don't think the gce controller watches yet, it does the re-list thing, so leaving open
