### ISSUE TITLE
Cannot build ingress

### ISSUE THREAD

**Issue by dmitrig01** [kubernetes/contrib#957]
Hi, I am trying to make some changes to the nginx ingress, but I cannot get it to build. The steps I took are:

First, `go get github.com/kubernetes/contrib`

Then, `cd $GOPATH/src/github.com/kubernetes/contrib/ingress` (NOTE: it breaks if I do `cd $GOPATH/src/github.com/kubernetes/contrib/Ingress`)

Then, `godep restore`

It complains about `speter.net/go/exp/math/dec/inf` missing. So I did a find-and-replace replacing that with `gopkg.in/inf.v0`. Suboptimal, but it worked.

Then I tried to run `make controller` in `nginx`.

I got `controller.go:43:2: cannot find package "k8s.io/contrib/ingress/controllers/nginx/nginx" in any of: .....`

So I replaced `"k8s.io/contrib/ingress/controllers/nginx/nginx"` with `"github.com/kubernetes/contrib/ingress/controllers/nginx/nginx"`. Which seemed to fix that. Also suboptimal.

Now it finally builds.

For reference,
```
$ godep version
godep v62 (darwin/amd64/go1.6)
$ go version
go version go1.6 darwin/amd64
```

**Comment by aledbf** [comment]
@dmitrig01 you need to follow [clone-your-fork](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#clone-your-fork). This workflow also applies to contrib

**Comment by dmitrig01** [comment]
oh nice! will try and get back to you. thanks

**Comment by dmitrig01** [comment]
Still running into the issue with `speter.net/go/exp/math/dec/inf` missing. However, once I did a find-and-replace with `gopkg.in/inf.v0`, it worked.

**Comment by aledbf** [comment]
@dmitrig01 you should follow the workflow for kubernetes and run `godep restore`. That will restore the missing package.

**Comment by dmitrig01** [comment]
ahhhh

**Comment by dmitrig01** [comment]
thanks
