### ISSUE TITLE
Nginx Ingress Controller - Safari 9 craps out with http2

### ISSUE THREAD

**Issue by alanhartless** [kubernetes/contrib#960]
I've literally wasted hours upon hours tracking this down. :-)

Using the nginx controller with SSL, Safari 9 will refuse to load any site. I'm sure this is a bug on Safari's part but I finally tracked it down to http2 in the listen 443 ssl line. I had to create a custom template to remove the http2 lines in order to get Safari (mobile or mac) to load our sites. None of the other browsers including older Safari browsers had an issue. I think http2 support was added in recent Safari version on the latest OS but obviously something is not right. Unfortunately, it wasn't just my local mac safari either as we had customers all over the world complain they couldn't access the sites with safari! 

Maybe this should be a setting? Or if there's a known workaround I couldn't figure out? 

https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx.tmpl#L157

**Comment by aledbf** [comment]
@alanhartless I think this issue is related to https://forum.nginx.org/read.php?2,266525,266525#msg-266525
Can you check if the logs contains connections errors?

You are right, http2 should be optional. #962 allows this.

**Comment by aledbf** [comment]
https://trac.nginx.org/nginx/ticket/979

**Comment by alanhartless** [comment]
It sounds like it; although in our case I couldn't get any indication in the log as to what was happening.
