### ISSUE TITLE
Cannot launch keepalived (timed out)

### ISSUE THREAD

**Issue by AblionGE** [kubernetes/contrib#961]
Hello,
When I try to install keepalived, I encounter a problem which is described in the logs from Kubernetes : 

```
I0512 08:35:42.346381       1 keepalived.go:161] cleaning ipvs configuration
I0512 08:35:42.349105       1 main.go:109] starting LVS configuration
F0512 08:36:12.398938       1 controller.go:261] Error getting POD information: timed out waiting to observe own status as Running
```

I tried with the original code from the repo. Any idea on what could go wrong ? Thanks!

**Comment by kokhang** [comment]
I am also seeing this. It seems that it cannot talk to the kubernete API for POD information when using the host network (hostNetwork: true)

**Comment by aledbf** [comment]
@AblionGE which version of kubernetes are you using? Can you use `--v=10` and post the logs?

**Comment by snowhigh** [comment]
Hello, I got exactly the same message in kubernetes pod log.
I use kubernetes version 1.2.1
> Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1", GitCommit:"50809107cd47a1f62da362bccefdd9e6f7076145", GitTreeState:"clean"}
> Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1", GitCommit:"50809107cd47a1f62da362bccefdd9e6f7076145", GitTreeState:"clean"}

Here is the log of keepalived-vip pod.
> $ kubectl logs kube-keepalived-vip-z5u49 --v=10 -f
I0613 05:53:14.081159   21155 round_trippers.go:267] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.2.1 (linux/amd64) kubernetes/5080910" http://localhost:8080/api
I0613 05:53:14.081890   21155 round_trippers.go:286] GET http://localhost:8080/api 200 OK in 0 milliseconds
I0613 05:53:14.081907   21155 round_trippers.go:292] Response Headers:
I0613 05:53:14.081913   21155 round_trippers.go:295]     Content-Type: application/json
I0613 05:53:14.081919   21155 round_trippers.go:295]     Date: Mon, 13 Jun 2016 05:53:14 GMT
I0613 05:53:14.081924   21155 round_trippers.go:295]     Content-Length: 133
I0613 05:53:14.081955   21155 request.go:870] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.17.0.46:443"}]}
I0613 05:53:14.082721   21155 round_trippers.go:267] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.2.1 (linux/amd64) kubernetes/5080910" http://localhost:8080/apis
I0613 05:53:14.083088   21155 round_trippers.go:286] GET http://localhost:8080/apis 200 OK in 0 milliseconds
I0613 05:53:14.083098   21155 round_trippers.go:292] Response Headers:
I0613 05:53:14.083102   21155 round_trippers.go:295]     Content-Length: 769
I0613 05:53:14.083106   21155 round_trippers.go:295]     Content-Type: application/json
I0613 05:53:14.083110   21155 round_trippers.go:295]     Date: Mon, 13 Jun 2016 05:53:14 GMT
I0613 05:53:14.083132   21155 request.go:870] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.17.0.46:443"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.17.0.46:443"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.17.0.46:443"}]}]}
I0613 05:53:14.083405   21155 round_trippers.go:267] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.2.1 (linux/amd64) kubernetes/5080910" http://localhost:8080/api/v1/namespaces/default/pods/kube-keepalived-vip-z5u49
I0613 05:53:14.084396   21155 round_trippers.go:286] GET http://localhost:8080/api/v1/namespaces/default/pods/kube-keepalived-vip-z5u49 200 OK in 0 milliseconds
I0613 05:53:14.084407   21155 round_trippers.go:292] Response Headers:
I0613 05:53:14.084412   21155 round_trippers.go:295]     Content-Type: application/json
I0613 05:53:14.084418   21155 round_trippers.go:295]     Date: Mon, 13 Jun 2016 05:53:14 GMT
I0613 05:53:14.084445   21155 request.go:870] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"kube-keepalived-vip-z5u49","generateName":"kube-keepalived-vip-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/kube-keepalived-vip-z5u49","uid":"9f191884-312a-11e6-bc9a-00089bf10eea","resourceVersion":"49686","creationTimestamp":"2016-06-13T05:49:40Z","labels":{"name":"kube-keepalived-vip"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"DaemonSet\",\"namespace\":\"default\",\"name\":\"kube-keepalived-vip\",\"uid\":\"9f0aa30b-312a-11e6-ba12-00089bf10e32\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"49355\"}}\n"}},"spec":{"volumes":[{"name":"modules","hostPath":{"path":"/lib/modules"}},{"name":"dev","hostPath":{"path":"/dev"}},{"name":"default-token-3fvsk","secret":{"secretName":"default-token-3fvsk"}}],"containers":[{"name":"kube-keepalived-vip","image":"gcr.io/google_containers/kube-keepalived-vip:0.5","args":["--services-configmap=default/vip-configmap"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"resources":{},"volumeMounts":[{"name":"modules","readOnly":true,"mountPath":"/lib/modules"},{"name":"dev","mountPath":"/dev"},{"name":"default-token-3fvsk","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always","securityContext":{"privileged":true}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"type":"worker"},"serviceAccountName":"default","serviceAccount":"default","nodeName":"172.17.0.47","hostNetwork":true,"securityContext":{}},"status":{"phase":"Running","conditions":[{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2016-06-13T05:52:59Z"}],"hostIP":"172.17.0.47","podIP":"172.17.0.47","startTime":"2016-06-13T05:49:40Z","containerStatuses":[{"name":"kube-keepalived-vip","state":{"running":{"startedAt":"2016-06-13T05:52:59Z"}},"lastState":{"terminated":{"exitCode":255,"reason":"Error","startedAt":"2016-06-13T05:51:14Z","finishedAt":"2016-06-13T05:52:44Z","containerID":"docker://3e7f3660a4a41775ebfe88ec8bc0b17b34404951002eb1722801166daf0f3d4c"}},"ready":true,"restartCount":2,"image":"gcr.io/google_containers/kube-keepalived-vip:0.5","imageID":"docker://sha256:e40b3de2d88d04bbee89903aba8728908e446fd069f1cfee852ab2bdc601e32c","containerID":"docker://5a1f87274833a03303c454e567df7676464617c3adb7865e6b7909d195cc7c4e"}]}}
I0613 05:53:14.084925   21155 round_trippers.go:267] curl -k -v -XGET  -H "User-Agent: kubectl/v1.2.1 (linux/amd64) kubernetes/5080910" -H "Accept: application/json, */*" http://localhost:8080/api
I0613 05:53:14.085182   21155 round_trippers.go:286] GET http://localhost:8080/api 200 OK in 0 milliseconds
I0613 05:53:14.085190   21155 round_trippers.go:292] Response Headers:
I0613 05:53:14.085194   21155 round_trippers.go:295]     Content-Type: application/json
I0613 05:53:14.085197   21155 round_trippers.go:295]     Date: Mon, 13 Jun 2016 05:53:14 GMT
I0613 05:53:14.085205   21155 round_trippers.go:295]     Content-Length: 133
I0613 05:53:14.085221   21155 request.go:870] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.17.0.46:443"}]}
I0613 05:53:14.085317   21155 round_trippers.go:267] curl -k -v -XGET  -H "User-Agent: kubectl/v1.2.1 (linux/amd64) kubernetes/5080910" -H "Accept: application/json, */*" http://localhost:8080/apis
I0613 05:53:14.085575   21155 round_trippers.go:286] GET http://localhost:8080/apis 200 OK in 0 milliseconds
I0613 05:53:14.085583   21155 round_trippers.go:292] Response Headers:
I0613 05:53:14.085589   21155 round_trippers.go:295]     Content-Type: application/json
I0613 05:53:14.085593   21155 round_trippers.go:295]     Date: Mon, 13 Jun 2016 05:53:14 GMT
I0613 05:53:14.085597   21155 round_trippers.go:295]     Content-Length: 769
I0613 05:53:14.085611   21155 request.go:870] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.17.0.46:443"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.17.0.46:443"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.17.0.46:443"}]}]}
I0613 05:53:14.085837   21155 round_trippers.go:267] curl -k -v -XGET  -H "User-Agent: kubectl/v1.2.1 (linux/amd64) kubernetes/5080910" http://localhost:8080/api/v1/namespaces/default/pods/kube-keepalived-vip-z5u49/log?follow=true
I0613 05:53:14.088027   21155 round_trippers.go:286] GET http://localhost:8080/api/v1/namespaces/default/pods/kube-keepalived-vip-z5u49/log?follow=true 200 OK in 2 milliseconds
I0613 05:53:14.088040   21155 round_trippers.go:292] Response Headers:
I0613 05:53:14.088045   21155 round_trippers.go:295]     Content-Type: text/plain
I0613 05:53:14.088050   21155 round_trippers.go:295]     Date: Mon, 13 Jun 2016 05:53:14 GMT
I0613 05:52:59.666249       1 keepalived.go:161] cleaning ipvs configuration
I0613 05:52:59.666945       1 main.go:109] starting LVS configuration
F0613 05:54:29.867856       1 controller.go:261] Error getting POD information: timed out waiting to observe own status as Running

PS: I can't pull kube-keepalived-vip:0.6 image, so I changed to kube-keepalived-vip:0.5 instead.

**Comment by snowhigh** [comment]
It was because the certification file of apiserver didn't accept KUBERNETES_SERVICE_HOST ip address. After regenerating certification files, I can start keepalived without problem. :)
