### ISSUE TITLE
Issue about scale-demo, container aggregator logs"Error getting pods: empty input1.000167427s"

### ISSUE THREAD

**Issue by zzy302** [kubernetes/contrib#990]
Hello, 
I'am running the test scale-demo refer to http://blog.kubernetes.io/2016/03/1000-nodes-and-beyond-updates-to-Kubernetes-performance-and-scalability-in-12.html . But from the web page, I can only see the numbers of NGINX and VEGETA, not QPS or RESPONSE TIME, but CPU load on node is high, then I checked the logs and found the aggregator logs of error like "Error getting pods: empty input1.000167427s". 

Some screen shots are attached, 

thanks for the help.

![](http://i2.buimg.com/33e58121775b0067.png)
![](http://i2.buimg.com/94d04c892325caf7.png)
![](http://i2.buimg.com/88325bf93cb349d1.png)

**Comment by zzy302** [comment]
Resolved after updating DNS

**Comment by BertrandNOEL** [comment]
Can you tell what was the version that was failing, and the updated version? I see the same issue with kube-dns-v11
